### ISSUE TITLE
Import of semi-specific peptides with defined terminus

### ISSUE THREAD

**Issue by ulrich-eckhard** [compomics/peptide-shaker#100]
Is there a chance to include an option in the PeptideShaker Import to define the "termininus" of the unspecific cleavage? so like e.g. comet allows it: http://comet-ms.sourceforge.net/parameters/parameters_201502/num_enzyme_termini.php.

I assume it is not that easy in SearchGUI as different search engines handle that differently - or just don't have the option, but it could be rather easy for PeptideShaker to just kick the "other" ones out, like it does with the "unrecognized modifications", right?

thanks in advance and all the best
u

**Comment by mvaudel** [comment]
Hi Ulrich,

Harald has already been working in improing this in SearchGUI, we can also build in some filters in PeptideShaker. I will keep you posted on this.

Best regards,

Marc

P.S. Congratulations for opening our 100th issue!

**Comment by hbarsnes** [comment]
Hi Ulrich,

Only two of the search engines support setting if the unspecific cleavage is allowed at the n or c terminal, namely Comet and Andromeda. For all the others it is only possible to have full or semi enzymatic cleavage.

But I guess we could implement the option of kicking out the unwanted peptides when loading the data in PeptideShaker. However, note that semi-specific searches (especially for both terminals) can be very slow...

Best regards,
Harald

**Comment by ulriche** [comment]
unfortunately I know that very well (that semi-specific searches are slow), but it is what we have to do if we "N-terminomics" people want to find what we are looking for! ;-)

and yeah! topic 200 here I come! :-)

**Comment by hbarsnes** [comment]
Hi Ulrich,

It took a very long time, but we finally got around to extending the enzyme support. So take a look at the new releases when you get the chance and see what you think? If you come across any issues, please let us know and we'll reopen the issue.

Best regards,
Harald
