### ISSUE TITLE
java.io.FileNotFoundException, log7.dat not found

### ISSUE THREAD

**Issue by somakray** [compomics/peptide-shaker#101]
Hello,
While working with peptideshaker I got the follwing error:
Tue Dec 01 20:34:28 EST 2015 An exception occurred while saving the project.
java.io.FileNotFoundException: C:\Users\BLK\Desktop\sr\UMPIRE\PeptideShaker-1.1.3\resources\matches\myExp_mySamp_1_id\log\log7.dat (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.compomics.util.io.compression.TarUtils.addFile(TarUtils.java:176)

I was trying to execute the following command:

java -cp .\PeptideShaker-1.1.3\PeptideShaker-1.1.3.jar u.isas.peptideshaker.cmd.PeptideShakerCLI -experiment myExp -sample mySamp -replicate 1 -identification_files .\RAW_FILE\MGF\ALL_Q_SEARCH\  -spectrum_files .\RAW_FILE\MGF\ALL_Q\  -id_params .\DATABASE\PS_CLI.par -out .\RAW_FILE\MGF\ALL_Q_SHAKER\CEXGroup4Analysis_ALL_Q.cpsx

A cpsx file is made but much smaller than size than made in a previous session which completed without any errors

**Comment by mvaudel** [comment]
Hi and thank you for reporting this issue,

It seems that the project files were changed during saving. This can happen when different PeptideShaker processes are running simultaneously or another process interfers. Please make sure that you have only one PeptideShaker process running at a time.

If you are working in command line I would recommend using the ```-temp_folder``` option which will use a working folder for all your files (More information here http://compomics.github.io/peptide-shaker/wiki/peptideshakercli.html). This will reduce the chances of encountering such issues :) You might also want to give a look at the zip packaging option, which will make the project self contained and easy to transfer between computers.

Best regards,

Marc

**Comment by hbarsnes** [comment]
This issue should have been solved with the release of PeptideShaker v1.3.0. If this is not the case, please let us know and we'll reopen the issue.
