### ISSUE TITLE
PeptideShaker Input of MS-GF+ data: N-terminal K with two TMTs - problem

### ISSUE THREAD

**Issue by ulriche** [compomics/peptide-shaker#102]
After importing some data from MSGF+ and Comet into PeptideShaker, I realized that for MS-GF+ I didn't have any peptides with a N-terminal K possessing both a N-terminal TMT and a sidechain TMT label (note, it is a TAILS experiment using GluC for proteome digest after labeling). but interestingly I did find peptides with a N-terminal K and a TMT on its sidechain and acetyl at its N-terminus. For comet I could find both scenarios, so the comet runs are fine.

I tried to go back to the mzid from my MS-GF+ file and found the following: e.g.

-----------------------------
    </Peptide>
    <Peptide id="142SKQLAARILEAHHNVAQMPLVE">
        <PeptideSequence>KSKQLAARILEAHHNVAQMPLVE</PeptideSequence>
        <Modification monoisotopicMassDelta="229.162932" location="1">
            <cvParam accession="UNIMOD:737" cvRef="UNIMOD" name="TMT6plex"/>
        </Modification>
        <Modification monoisotopicMassDelta="229.162932" location="0">
            <cvParam accession="UNIMOD:737" cvRef="UNIMOD" name="TMT6plex"/>
        </Modification>
        <Modification monoisotopicMassDelta="229.162932" location="3">
            <cvParam accession="UNIMOD:737" cvRef="UNIMOD" name="TMT6plex"/>
        </Modification>
    </Peptide>

    <Peptide id="142YLLPSLEKELFLAEHSDLE">
        <PeptideSequence>KYLLPSLEKELFLAEHSDLE</PeptideSequence>
        <Modification monoisotopicMassDelta="229.162932" location="1">
            <cvParam accession="UNIMOD:737" cvRef="UNIMOD" name="TMT6plex"/>
        </Modification>
        <Modification monoisotopicMassDelta="229.162932" location="0">
            <cvParam accession="UNIMOD:737" cvRef="UNIMOD" name="TMT6plex"/>
        </Modification>
        <Modification monoisotopicMassDelta="229.162932" location="9">
            <cvParam accession="UNIMOD:737" cvRef="UNIMOD" name="TMT6plex"/>
        </Modification>
    </Peptide>
-----------------------------
both these peptides got imported into PeptideShaker, got validated, but both (and others) lost the N-terminal TMT label. It is maybe linked with the "142 (instead of K)" in the "peptide id" tag. 

for a acetylated peptide with N-terminal TMT-labeled K it looks like that: e.g.

-----------------------------
    </Peptide>
    <Peptide id="kTTADRAE">
        <PeptideSequence>KTTADRAE</PeptideSequence>
        <Modification monoisotopicMassDelta="229.162932" location="1">
            <cvParam accession="UNIMOD:737" cvRef="UNIMOD" name="TMT6plex"/>
        </Modification>
        <Modification monoisotopicMassDelta="42.010565" location="0">
            <cvParam accession="UNIMOD:1" cvRef="UNIMOD" name="Acetyl"/>
        </Modification>
    </Peptide>
-----------------------------
as said, the latter one got correctly imported into PeptideShaker, whereas the above ones had a mass deficit of 229 Da, and were assigned with an Isotope Number of 4 (obviously wrong but I guess everything off by more than 3 hydrogens gets assigned with that).

Importantly and as always in my searches: the TMT-label of the K is set as fixed modification, but for the N-terminus as variable.

any ideas?

**Comment by ulriche** [comment]
Sidenote: think that was also the reason why I often saw enormous ppm errors after my searches (mentioned previously when I noticed that "-1" is not reported). e.g. in the two cases above they are then 73914 and 79398 ppm (229 of approx. 3000 Da), respectively

**Comment by hbarsnes** [comment]
Hi Ulrich,

I think this could be linked to a weakness in how the modifications are annotated in mzIdentML files, especially when two modifications have the same accession number and mass. Not sure how easy it is to fix, but if you send me your data (unless I have these already..?), I'll see what we can do.

Best regards,
Harald

**Comment by ulriche** [comment]
will give my best to find them again - getting in quite a mess with my testing! ;-) It is also not many peptides that make it into PeptideShaker but loose the N-terminal tag on their way (but not sure if some of them just don't make it because of that reason). But I will try to put some "Info Sheet" together with the spurious IDs, plus provide the mgf and my SearchGUI results. Note: It is a GluC based preTAILS experiment - so we don't expect too many labeled N-termini as no enrichment was done at that point.

**Comment by ulriche** [comment]
just sent the link to the data sent by emai

**Comment by hbarsnes** [comment]
This issue has been solved with the release of PeptideShaker v1.3.0. If this is not the case, please let us know and we'll reopen the issue.

**Comment by ulriche** [comment]
finally found time to test that - definitely works in PeptideShaker 1.5.1-beta!  thanks thanks!
