### ISSUE TITLE
Exception while loading search results

### ISSUE THREAD

**Issue by thabangh** [compomics/peptide-shaker#104]
I got an exception while trying to load search results from tide-search. I suspect that my column names don't match the expected names. I will attach the various files I used, as well as the log. You can ignore the warnings in the log about repeated protein IDs.  I fixed that and re-loaded the database.

I can't upload the MGF file because it's too big.  :(

[PeptideShaker 1.2.2 log.txt](https://github.com/compomics/peptide-shaker/files/70020/PeptideShaker.1.2.2.log.txt)

[SOLUBLE_FRACTIONS.T=-6.Run1.Band16.tide-search.target.txt](https://github.com/compomics/peptide-shaker/files/70021/SOLUBLE_FRACTIONS.T.-6.Run1.Band16.tide-search.target.txt)

**Comment by mvaudel** [comment]
Hi and thank you for reporting this issue.

Are you running the import from the gui or in command line?

It seems that there is an error in the parsing of the database. May we have
more information on the protein database used for the search? Would it be
possible to share it with us?

Best regards,

Marc

2015-12-22 18:52 GMT+01:00 thabangh <notifications@github.com>:

**Comment by thabangh** [comment]
Yes, I am attaching the database.  Note that I had to rename it to a .txt file in order to upload it because github doesn't like .fasta files.

I was using the GUI.


[target+decoy.txt](https://github.com/compomics/peptide-shaker/files/70139/target.decoy.txt)

**Comment by mvaudel** [comment]
Hi again,

It seems that the database is not a valid fasta file, there are mass tags in the prote sequences as for example
```
>2879818(1),2879816(1),2876267(1),2879819(1),2879820(1),2879815(1),2879817(1)_7931
MMIIMMIIIMIILVIIVIIIVVIIVVIIIM[15.9949]G
``` 

This could explain why the tool could not parse it. May we have more input on where you obtained this file?

Best regards,

Marc

**Comment by thabangh** [comment]
Doh!  That is my fault.  Thanks for finding that. I created the file for
this particular analysis and forgot to strip out the mass tags. I'll fix
this and try again.

Bill

**Comment by mvaudel** [comment]
Hi again,

Great, if removing the mass tags does not fix the problem, feel free to contact us again and we will reopen the issue.

Best regards,

Marc
