### ISSUE TITLE
Attempting to read new line before current read operation is completed

### ISSUE THREAD

**Issue by AT52** [compomics/peptide-shaker#106]
While importing PSMs from .xml file generated by searcGUI I get the following error:
An error occurred: Attempting to read new line before current read operation is completed

Why does peptideshaker give this error and how can I solve it?

Many thanks!

**Comment by mvaudel** [comment]
Hi and thank you for reporting this issue.

Which search engine is causing the issue?

Note that there are issues with the support of mgf files in Comet, we are working on a fix together with the developers:
https://groups.google.com/forum/#!topic/comet-ms/pwNDs5JrGUg
In the meantime, you might want to skip Comet.

Hope this helps, our apologizes for the inconvenience,

Best regards,

Marc

**Comment by AT52** [comment]
Dear Marc,
Thanks for the reply; I'm using X!Tandem search on a thermo RAW file converted to mgf using msconvert. However, I'm using a relatively large FASTA file, could this be a memory issue? (during the peptideshaker procedure memory consumption goes up to about 98% before this error appears)
Beste regards,
Stijn

**Comment by hbarsnes** [comment]
Hi Stijn,

Could you send us the PeptideShaker log file? You can find it via the Welcome dialog > Settings & Help > Help > Bug Report. It should tell us where in the code the problem occurs, and hopefully allow us to fix it.

Using a large FASTA file should not result in any errors, but how large a FASTA file are we talking about? Also, please make sure that the FASTA file is located on a local disk and not on a shared drive as this can dramatically impact the performance.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
