### ISSUE TITLE
Windows high DPI displays not rescaling

### ISSUE THREAD

**Issue by im281** [compomics/peptide-shaker#107]
It appears that the UI does not scale or display properly (can barely see the icons)

**Comment by hbarsnes** [comment]
Hi.

I'm afraid that this is a general issue with Java application on some Windows 10 computers, especially the ones that have the newer very high resolution displays. (For example it resizes fine on our Windows 10 computers in the lab, but these have "normal" resolution displays. But not sure if it's the graphics card or the resolution itself.)

So far we've found no good workaround. The only option is to use the Windows Magnifier option, which is very far from optimal, but at least it allows you to see read the text etc.

I will do another search to see if there are any new solutions to this problem. But it's a bit difficult to test the suggestions has I don't have direct access to any computers with this issue. So if you come across any solutions on your side please let me know.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

Here are some more details about the underlying Java issue: https://bugs.openjdk.java.net/browse/JDK-8080153.

Apparently the problem does not occur on Java 6. Would it be possible for you to install an older Java version and see if that actually helps? You can find the old Java 6 versions here: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase6-419409.html.

Another option is to wait for Java 9, but it will not become available until early 2017 it seems... So let me know if you come across any other workarounds.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

We've found a fix for advanced Windows users: https://github.com/compomics/compomics-utilities/wiki/JavaTroubleShooting#text-and-icons-are-too-small.

But we stress that this is a fix that you use at your own risk. We're still hoping for Java to come up with a proper fix in a future release.

Best regards,
Harald

**Comment by im281** [comment]
Thanks Harold!

**Comment by hbarsnes** [comment]
No worries. Pease let us know if you test it and if it works for you or not.

Best regards,
Harald

**Comment by hbarsnes** [comment]
More tips added to https://github.com/compomics/compomics-utilities/wiki/JavaTroubleShooting#text-and-icons-are-too-small. We refer the users to this page for help and are therefore closing the issue.
