### ISSUE TITLE
Running SearchGUI from a C# application

### ISSUE THREAD

**Issue by im281** [compomics/peptide-shaker#108]
Is there a way to shell the command line application using C# for example?

Fro example,
This starts the application's GUI but does not process anything (in this example create a .par file) THis works from the command line though..

//System.Diagnostics.Process clientProcess = new Process();
            //clientProcess.StartInfo.FileName = "java.exe";
            //clientProcess.StartInfo.Arguments = "-jar" + " " + @"SearchGUI-2.3.3\SearchGUI-2.3.3.jar" + " " + "java -cp SearchGUI-2.3.3.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -db" + " " + @"fasta\myoglobin.fasta -out" + " " + @"SearchGUI-2.3.3\testparams.par";
            //clientProcess.Start();

**Comment by im281** [comment]
Oh sorry, didn't know where to post the question

**Comment by hbarsnes** [comment]
Hi,

I'm afraid I have no experience with C#. But what is your goal here? Why do you need to start SearchGUI via C# in the first place?

And why one command instead of two (if I read your code correctly)? The creation of the parameter file should be a separate command line which should create a parameter file that can be used as input to the first one (which should then be run last).

> Oh sorry, didn't know where to post the question
No worries, all the issues end up with the same developers anyway. :)

Best regards,
Harald

**Comment by im281** [comment]
So I have a web application that runs on Azure. It runs many different executables including XTandem. I thought I could simply use your SearchGUI exe and call it from my web application. The server side is written in C# (much like JAVA) so I thought I could just shell out the application. The idea is that a web interface calls the search algorithms and the data gets stored in a cloud-based database...

So, the Web API gives the paramters to the server. The server code parses the input and creates a command line to run searchGUI. The results are then uploaded to a database...

So each time a user submits a query with their specified parameters, the backend creates a CLI .par file and then launches searchGUI with that input...

is this possible?

**Comment by im281** [comment]
This should work with any .jar file and associated arguments which you document well. The problem is that when I try to start the app the GUI is started and no processing occurs...

**Comment by hbarsnes** [comment]
Yup, should be possible. We are moving towards providing SearchGUI (and PeptideShaker) in a web based settings on our side as well. So far we have focused in the Galaxy platform and made our command lines compatible with this setup. See https://usegalaxyp.org.

So all you have to do is find the correct command lines and then execute them in the correct order. I would recommend using the SearchCLI interface though (https://github.com/compomics/searchgui/wiki/SearchCLI), instead of running the SearchGUI jar file directly.

**Comment by hbarsnes** [comment]
>This should work with any .jar file and associated arguments which you document well. The problem is that when I try to start the app the GUI is started and no processing occurs...

The processing does not start if you start the GUI, to start the processing use the SearchCLI instead.

**Comment by im281** [comment]
ahh of course, let me check! Also, another question. Can you expose your algorithms through REST APIs? This would be a home run! Everyone can call them in their apps and even contribute in a 'language neutral' setting :)

**Comment by im281** [comment]
But what about the parameters. All I'm trying to do is create a.par file from the C# application. (similar to how it is done using the command line

**Comment by hbarsnes** [comment]
> Can you expose your algorithms through REST APIs?

Not sure which algorithms you refer to? Do you mean the PeptideShaker processing? As SearchGUI just runs the search engine executables.

As for PeptideShaker (i.e., the processing of the output from the search engines) I don't really see how this could be made available as a REST API? How would this work in practice?

**Comment by hbarsnes** [comment]
> But what about the parameters. All I'm trying to do is create a.par file from the C# application. (similar to how it is done using the command line.

Not sure what your question is..? The creation of the parameters is a separate command line using IdentificationParametersCLI (https://github.com/compomics/compomics-utilities/wiki/IdentificationParametersCLI). After this is been created you hand the parameter file (and the other settings) over to the SearchCLI command.

**Comment by im281** [comment]
Right, I guess where I'm stuck is using searchGUI to run all the algorithm executables in a separate application. Since it has a command line interface I thought I could just us system.diagnostics in the .NET environment to shell out the application and return the results and do other processing downstream. Right now I can just start the GUI with these lines:

  ProcessStartInfo startInfo = new ProcessStartInfo()  
  startInfo.FileName = @"SearchGUI-2.3.3\SearcCLI-2.3.3.jar";
   Process.Start(startInfo);

However, I tried this:
startInfo.Arguments = "java -cp SearchGUI-2.3.3.jar 
eu.isas.searchgui.cmd.IdentificationParametersCLI";

But that didn't work as it started the GUI so I'm not sure if I'm doing something wrong or its just not possible. Maybe I'm not thinking about this right as well as the JAVA and .NET interoperability but I just look at searchGUI as an executable that can be wrapped in any application...

**Comment by hbarsnes** [comment]
Use the following two command lines:

1) java -cp SearchGUI-2.3.3.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out "path to your output file" [add your search parameters here]

2) java -cp SearchGUI-2.3.4.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "path to your spectrum files" -output_folder "path to output folder" -id_params "the path to the parameter file created in the first command line" [add other parameters here]

**Comment by im281** [comment]
Thanks Herald,
The both work fine using the command line. The problem is wrapping it into a C# application. Only the GUI will start...

**Comment by hbarsnes** [comment]
Seems like your startInfo.FileName is incorrect and should rather refer to "java.exe"?

See the example towards the end here: http://stackoverflow.com/questions/909303/c-how-would-i-execute-this-command-line-directly-to-java-exe.

**Comment by im281** [comment]
right

**Comment by im281** [comment]
What are the other 'arguments'?
Tried this:
 startInfo.FileName = "java";
 startInfo.Arguments = "-cp" + " " + @"SearchGUI-2.3.3\SearchGUI-2.3.3.jar" + " " +
 "eu.isas.searchgui.cmd.IdentificationParametersCLI";


Seems like its trying to do something :)

**Comment by im281** [comment]
That worked! :)

**Comment by im281** [comment]
Big plans now to use you stuff :)

**Comment by im281** [comment]
Thanks Herald! I really appreciate the support. Your development program is awesome. I hope to make some contributions soon :)

**Comment by hbarsnes** [comment]
Great! Closing this issue now. But feel free to open a new one if you come across other issues or have other questions.
