### ISSUE TITLE
can't parse my sequence database

### ISSUE THREAD

**Issue by FazeH** [compomics/peptide-shaker#109]
Hi,
We have been using peptide-shaker for a proteogenomic study in which the sequence database is derived from 3-frame translation of RNA-seq data. Therefore the header in our fasta file is not standard. 
Here is an example of header that I am trying to use in peptide-shaker:

```
>generic|chr1:100672001-100672192|frame 2
DPMLERVNVPPVRSVVLSXPTEPNFWRRFSSVAMSNIEQIXTFFTLGTIKPCSVSIAIPMLXE
>generic|chr1:100672001-100672192|frame 3
IQCWKEXMFLIXDQWCXADPQSPPISGGGSVQWRCQIXSRSEHFSHXGQSNPAQYPLLSQCYEK
```

the X in the sequence represent a potential stop codon in the genome. 
What do you recommend? does X in the sequence interfere with parsing? 
Thanks and I look forward to hearing from you.
HFaz
![peptide_shaker_error](https://cloud.githubusercontent.com/assets/13034441/12209247/c545b0c8-b61f-11e5-94d3-8f45f3638f6c.PNG)

**Comment by hbarsnes** [comment]
Hi HFaz,

In the generic FASTA file format the second part (i.e. the text between the first and second '|') will be used as the accession number for the protein sequence. In your example above this will end up as "chr1:100672001-100672192" in both cases, and hence the warning about non unique accession numbers.

You therefore need to reformat your FASTA headers. From the two example sequences above all that should be needed is to remove or replace the last '|', for example:

```
>generic|chr1:100672001-100672192 frame 2
DPMLERVNVPPVRSVVLSXPTEPNFWRRFSSVAMSNIEQIXTFFTLGTIKPCSVSIAIPMLXE
>generic|chr1:100672001-100672192 frame 3
IQCWKEXMFLIXDQWCXADPQSPPISGGGSVQWRCQIXSRSEHFSHXGQSNPAQYPLLSQCYEK
```

Then "chr1:100672001-100672192 frame 2" will be used as the accession number for the first sequence and "chr1:100672001-100672192 frame 3" for the second. Hopefully this approach will work for the rest of your FASTA file as well.

>the X in the sequence represent a potential stop codon in the genome. 
 What do you recommend? does X in the sequence interfere with parsing?

The X's will be interpreted as representing any amino acid, as this is the general rule for X's in protein sequences, for example in FASTA files from UniProt. So you in your case I think I would recommend removing them before doing the search. But depends on how you want the search engine to treat the potential stop codons. But in any case the X's have a different standard interpretation.

Best regards,
Harald

**Comment by hbarsnes** [comment]
(Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.)
