### ISSUE TITLE
Peptideshaker mzid to pepxml conversion error

### ISSUE THREAD

**Issue by somakray** [compomics/peptide-shaker#110]
Hello,

 I'm having a problem while converting the Peptideshaker derived mzid file to a pepxml file using Idconvert. I get an error message " Invalid cvParam accession "1002567" ".

Can you please look into this matter.

**Comment by hbarsnes** [comment]
Hi.

Please make sure that you are using a recent version of ProteoWizard, as the support for cv terms is constantly being extended. For example converting PeptideShaker mzIdentML works fine on my side when using ProteoWizard v3.0.9134.

Please let me know if upgrading ProteoWizard solves the issue on your side as well.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Assumed fixed by updating to the latest version of ProteoWizard. If this is not the case, please let us know and we'll reopen the issue.
