### ISSUE TITLE
SearchCLI

### ISSUE THREAD

**Issue by im281** [compomics/peptide-shaker#111]
Hi Herald,
I tried this in SearchGUI 2.3.3 and got the error below. Bug?

java -cp SearchGUI-2.3.3.jar eu.isas.searchgui.cmd.SearchCLI  -id_params testparams.par -spectrum_files myo.mgf -output_folder C:\somefolder

Tue Jan 12 16:18:05 PST 2016 Validating MGF file: C:\.CompOmicsWebRole\SearchGUI-2.3.3\myo.mgf
10% 20% 30% 40% 50% 60% 70% 80% 90%

makeblastdb command:
C:\Users\im281\Documents\SearchGUI-2.3.3-windows\SearchGUI-2.3.3\resources\makeblastdb\windows\makeblastdb -in myoglobin.fasta -dbtype prot

Tue Jan 12 16:18:08 PST 2016 Formatting myoglobin.fasta for OMSSA.

Building a new DB, current time: 01/12/2016 16:18:08
New DB name:   myoglobin.fasta
New DB title:  myoglobin.fasta
Sequence type: Protein
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1073741824B
Error: NCBI C++ Exception:
    "..\..\..\..\..\src\serial\objistrasnb.cpp", line 164: Error: ncbi::CObjectIStreamAsnBinary::UnexpectedTagClassByte() - byte 0: unexpected tag class/constructed: #239, should be #160 ( at Seq-entry)

Tue Jan 12 16:18:09 PST 2016 Database Formating finished for myoglobin.fasta (138 milliseconds).

Tue Jan 12 16:18:09 PST 2016 myoglobin.fasta formatted for OMSSA.

Tue Jan 12 16:18:09 PST 2016 Andromeda configuration.

Tue Jan 12 16:18:09 PST 2016 Error: null
Tue Jan 12 16:18:09 PST 2016 An error occurred while running SearchGUI. Please contact the developers.
java.lang.NullPointerException
        at eu.isas.searchgui.processbuilders.AndromedaProcessBuilder.getDatabaseTypeAndromedaAccessionParsingRule(AndromedaProcessBuilder.java:772)
        at eu.isas.searchgui.processbuilders.AndromedaProcessBuilder.createDatabaseFile(AndromedaProcessBuilder.java:167)
        at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:1797)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Tue Jan 12 16:18:09 PST 2016 The search or processing did not finish properly!

C:\\SearchGUI-2.3.3>

**Comment by mvaudel** [comment]
Hi,

It seems that the search engines do not support your database format. Can
you provide more information on how you generated the file?

If you are using a home made database, please have a look at our help on
this:
https://github.com/compomics/searchgui/wiki/DatabaseHelp

Best regards,

Marc

2016-01-13 1:22 GMT+01:00 im281 <notifications@github.com>:

**Comment by im281** [comment]
Hi,
It is a standard .fasta file?

**Comment by im281** [comment]
one protein sequence.Seems like MSAmanda didn't like it.If I use the SearchGUI GUI and import the .par file that I created using the command line it works?

**Comment by im281** [comment]
One protein:

>sp|P68082|MYG_HORSE Myoglobin OS=Equus caballus GN=MB PE=1 SV=2
MGLSDGEWQQVLNVWGKVEADIAGHGQEVLIRLFTGHPETLEKFDKFKHLKTEAEMKASE
DLKKHGTVVLTALGGILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISDAIIHVLHSKH
PGDFGADAQGAMTKALELFRNDIAAKYKELGFQG

**Comment by mvaudel** [comment]
Hi again,

Can you make sure that there is a '>' at the start of every protein header?
If this does not work, can you make the fasta file available to us?

Best regards,

Marc

2016-01-13 17:46 GMT+01:00 im281 <notifications@github.com>:

**Comment by im281** [comment]
[myoglobin.zip](https://github.com/compomics/peptide-shaker/files/89737/myoglobin.zip)

**Comment by hbarsnes** [comment]
Hi,

It turns out that your FASTA header does not start with '>' after all but with 'ï»¿>'. Don't know where the strange characters at the start come from, but if i open the file in a text editor and replace the '>' with a regular '>' (and I cannot even see the 'ï»¿' part in the text editor), the file can be parsed without any problems. Could you check if the same is the case on your side?

Which operating system are you using btw? And how did you create the FASTA file?

Best regards,
Harald

**Comment by im281** [comment]
Hi Herald,
I'm using windows 10. Strange, the file works when I import it to the gui

**Comment by hbarsnes** [comment]
Hi again,

> the file works when I import it to the gui

So you don't have any problems with the FASTA file anymore then..?

Best regards,
Harald

**Comment by im281** [comment]
Well, it still gives me the error when I try to run searchgui cli but not
with the actual gui?

**Comment by hbarsnes** [comment]
I'd double check the FASTA file, as I cannot load it in the GUI on on my side before removing the strange characters. Could you try with this one?
[myoglobin_2.zip](https://github.com/compomics/peptide-shaker/files/90732/myoglobin_2.zip). Same file as the one sent me, just with the strange characters removed.

**Comment by im281** [comment]
sure one sec

**Comment by im281** [comment]
Ok excellent it works! My bad sorry for the error...

**Comment by hbarsnes** [comment]
Great! I'll close the issue then. But feel free to open a new one if you come across more issues.

**Comment by mvaudel** [comment]
As a last comment on this, you might want to include standard contaminants
to your sequence file in order to avoid false positives :) A list of
standards contaminants can be found on the GPM website:
www.thegpm.org/crap

2016-01-14 18:41 GMT+01:00 Harald Barsnes <notifications@github.com>:
