### ISSUE TITLE
Post processing directly after SearchGUI fails if the "Include Date in File Name" option is used

### ISSUE THREAD

**Issue by ulriche** [compomics/peptide-shaker#113]
somehow running Peptide Shaker right after SearchGUI doesn't work for me anymore. Here the report from a X!Tandem search. Note: the import workes when I start Peptide Shaker separately. Could it be that it doesn't find the zip-file as I include the Date in the File name? will try a comet run over night to rule out it is something X! Tandem specific.

---
X! TANDEM Sledgehammer (2013.09.01.1)

Loading spectra| (mgf)...................................... loaded.
Spectra matching criteria = 74516
Starting threads .|.|.|.|.|.|.|.|.|.|.|. started.
Computing models:
	Spec:trum-t:o-seque:nce ma:tching: proce:ss in p:rogre:ss | 50 ks 
	Spe:ctrum-:to-seq:uence: match:ing pr:oce
	waiting for 23456789101112 done.
	sequences modelled = 84 ks
Model refinement:
	waiting for 23456789101112 done.
Merging results:
	from 2......3......4......5......6......7......8......9......10......11......12......

Creating report:
	initial calculations  ..... done.
	sorting  ..... done.
	finding repeats ..... done.
	evaluating results ..... done.
	calculating expectations ..... done.
	writing results ..... done.

Valid models = 9586

---

Thu Jan 14 20:44:09 PST 2016        X!Tandem finished for xxx (25 minutes 23 seconds).

Thu Jan 14 20:44:09 PST 2016        Zipping output files.

Thu Jan 14 20:44:13 PST 2016        Could not find X!Tandem results.
Thu Jan 14 20:44:13 PST 2016        Processing identification files with PeptideShaker.

Thu Jan 14 20:44:13 PST 2016        PeptideShaker processing failed. See the PeptideShaker log for details.

Thu Jan 14 20:44:13 PST 2016        Search Canceled!
org.apache.commons.cli.MissingArgumentException: Missing argument for option: identification_files
	at org.apache.commons.cli.Parser.processArgs(Parser.java:343)
	at org.apache.commons.cli.Parser.processOption(Parser.java:393)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:879)
Thu Jan 14 20:44:13 PST 2016        The search or processing did not finish properly!

**Comment by ulriche** [comment]
hmmm ... comet still doesn't work with my mgf - will have to check the standalone version tomorrow.

**Comment by ulriche** [comment]
tried with two different mgf types so far ...

---
BEGIN IONS
TITLE=1502_UE_Pulp_TMT-1_TAILS_ArgC_C6_01_1119.3189.3189.2
RTINSECONDS=600.224
PEPMASS=330.70013
CHARGE=2+
110.07001	642	
116.06588	224	
120.06181	424	
126.12699	1066
128.13309	3162	

---
and

---
BEGIN IONS
TITLE=Cmpd 2234, +MS2(330.7001), 23.0-27.6eV, 10.0 min #3189
RTINSECONDS=600.224
SCANS=MS: 3188 MSMS: 3189
PEPMASS=330.70013	17736
CHARGE=2+
110.07001	642	1+
116.06588	224	
120.06181	424	1+
126.12699	1066
128.13309	3162

---
The 2nd one has quite some additional "annotation" stuff - commented out with ### e.g.:

###FS:    #m/z: 330.70013 #charge   2
###MaxRes:#m/z:  0.00000 #charge-128
###MS: 3188
###MSMS: 3189

---
maybe you spot once again the obvious ... ;-)

**Comment by ulriche** [comment]
hmmm ... in standalone the comet search started at least (so far for mgf format #2).

will keep you posted.

**Comment by hbarsnes** [comment]
> somehow running Peptide Shaker right after SearchGUI doesn't work for me anymore. Here the report from a X!Tandem search. Note: the import workes when I start Peptide Shaker separately. Could it be that it doesn't find the zip-file as I include the Date in the File name?

Works fine with the date added to the zip file name on my side. Do you make any other changes to the zip file format?

**Comment by hbarsnes** [comment]
> comet still doesn't work with my mgf 

No, I don't see anything obviously wrong with your mgf files.

> in standalone the comet search started at least (so far for mgf format #2).

Not sure how that is possible? Do you have a different Comet version than the one used in SearchGUI?

**Comment by ulriche** [comment]
hmmm ... interesting ... not to my knowledge, just downloaded the last
comet version yesterday (comet.2015024.win64), and SearchGUI also says
"Comet version "2015.02 rev. 4"

re zip files: I also use typically "One zip per algorithm", but otherwise
the default advanced settings.
thus my filename is: X!Tandem_searchgui_out_2016-01-14_20.44.09.zip

will play more in the afternoon. cheers and thanks already
u

**Comment by hbarsnes** [comment]
> re zip files: I also use typically "One zip per algorithm", but otherwise
the default advanced settings.

I was finally able to reproduce the zip file issue. The problem is that the date (or rather the time part of the date/time stamp) changes from when we create the zip file to when we check if the results files are there before loading them into PeptideShaker.

We'll try to come up with a fix and release a new version of SearchGUI. In the meantime please run without the "Include Date in File Name" option enabled as this seems to work fine.

**Comment by ulriche** [comment]
totally fine ... that's what I did so far most of the time. just wanted to
let you know.

btw. didn't have time yet to further check into the mgf issue, but hope to
do so over the weekend.

cheers, u

**Comment by ulriche** [comment]
just installed SearchGUI 2.4.0 and both my MGFs work now.
did you fix something in SearchGUI or did restarting my system do the job?
all the best
u

**Comment by hbarsnes** [comment]
> just installed SearchGUI 2.4.0 and both my MGFs work now.
 did you fix something in SearchGUI or did restarting my system do the job?

There are no changes related to this between SearchGUI 2.3.5 and SearchGUI 2.4.0. But good to hear that it now works.

**Comment by hbarsnes** [comment]
With the release of SearchGUI v2.4.1 the "Include Date in File Name" option works in combination with post-processing in PeptideShaker.
