### ISSUE TITLE
Scoring PTM probabilities of N-terminal variable modifications - needed?

### ISSUE THREAD

**Issue by ulriche** [compomics/peptide-shaker#115]
My Peptide Shaker imports typically fail (think even always) when switching off the the "Probabilistic Scoring" in the PTM Scoring module. Is that expected? The step takes really long in my hands (approx. 15 minutes for a single file) and especially for testing I would love to skip it.

all of my variable modifications besides of Met oxidation are at the N-terminus thus don't need additional scoring, no? Or an idea why it takes so long? e.g. out of my approx. 6000 PSMs only 107 have actually an oxidized Met.

Localization Confidence is only assigned for Met-Oxidation, but "probabilistic PTM score" and "D-score" are done for all N-terminal modifications. The probabilistic score seems to be always "100" thus is maybe not calculated but just assigned, but the D-score can be as low as "50" (but the majority is "90+"). I totally see the point of assessing also the N-terminal modification, but the thing is, if it is not there, then the whole PSM is wrong anyway. thus I would be tempted to just skip it, no?

what do you think?

PS: it is a bit of a follow up of our email thread with the subject: "very quick question regarding PSM probabilities (D-score and PhosphoRS)"

**Comment by mvaudel** [comment]
Hi Ulrich,

Can you confirm that it is still the case with version 1.4.0? I have tried
to fix this one and it worked on the files I had from other users having
the same issue. If it still fails on your side, can you send me the mgf,
fasta, and parameters file?

Best regards,

Marc

2016-01-19 2:53 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
ha, indeed ... that could be when it got resolved, makes sense. because the
one search was last Friday, the other ones today ... will keep an eye on it
but think you can close the issue already again.

**Comment by mvaudel** [comment]
Let's keep the issue open until more testing has been done - another user
is having similar issues :)

2016-01-19 9:58 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

> ha, indeed ... that could be when it got resolved, makes sense. because the
> one search was last Friday, the other ones today ... will keep an eye on it
> but think you can close the issue already again.

**Comment by ulriche** [comment]
will keep my eyes open ... but last runs looked good ...

(it is a bit hard for me to keep track of which SearchGUI and which
PeptideShaker I was running exactly at which time ... but guess find that
somewhere in the outputs, right (haven't looked yet)?)

**Comment by hbarsnes** [comment]
> it is a bit hard for me to keep track of which SearchGUI and which PeptideShaker I was running exactly at which time ... but guess find that somewhere in the outputs

The SearchGUI and PeptideShaker (and the search engine versions) are all listed in the html reports located in the selected output folder.

**Comment by ulriche** [comment]
then my results with the "comet n[230] are from

   - Comet version "2015.02 rev. 4"
   - SearchGUI 2.4.1 Report File
   - PeptideShaker 1.4.0 Report File

which doesn't make sense as you can't reproduce it. will ask Jimmy if he
ever even used the n[230] tag

**Comment by hbarsnes** [comment]
> will ask Jimmy if he ever even used the n[230] tag

I think he mentioned it once in an e-mail that "in the next version the terminal PTMs would be annotated like this", but I never knew if the next version meant this revision or the next proper release. And as I cannot see them on my side...

**Comment by ulriche** [comment]
wondering myself

**Comment by hbarsnes** [comment]
The issue should have been fixed with the release of SearchGUI 2.5.0 and PeptideShaker 1.5.0. If not, please let us know and we'll reopen the issue.
