### ISSUE TITLE
some Met oxidations get lost during Peptide Shaker import (coming from Comet)

### ISSUE THREAD

**Issue by ulriche** [compomics/peptide-shaker#116]
e.g. the following ones:

\<search_hit hit_rank="1" peptide="PMFIVNTNVPR" peptide_prev_aa="M" peptide_next_aa="A" protein="sp|P14174|MIF_HUMAN" num_tot_proteins="1" num_matched_ions="16" tot_num_ions="40" calc_neutral_pep_mass="1531.838374" massdiff="-0.001974" num_tol_term="1" num_missed_cleavages="0" num_matched_peptides="87966">
    \<modification_info modified_peptide="**n[230]**PM[147]FIVNTNVPR" mod_nterm_mass="230.170757">
     \<mod_aminoacid_mass position="2" mass="147.035400"/>
    \</modification_info>
    \<search_score name="xcorr" value="2.827"/>
    \<search_score name="deltacn" value="0.356"/>
    \<search_score name="deltacnstar" value="0.000"/>
    \<search_score name="spscore" value="640.9"/>
    \<search_score name="sprank" value="1"/>
    \<search_score name="expect" value="5.23E-003"/>
   \</search_hit>

or

\<search_hit hit_rank="1" peptide="VMHSVLLGGEEQR" peptide_prev_aa="M" peptide_next_aa="Y" protein="sp|Q02846|GUC2D_HUMAN" num_tot_proteins="1" num_matched_ions="13" tot_num_ions="48" calc_neutral_pep_mass="1698.892595" massdiff="-0.007314" num_tol_term="1" num_missed_cleavages="0" num_matched_peptides="86873">
    \<modification_info modified_peptide="**n[230]**VM[147]HSVLLGGEEQR" mod_nterm_mass="230.170757">
    \<mod_aminoacid_mass position="2" mass="147.035400"/>
    \</modification_info>
    \<search_score name="xcorr" value="2.386"/>
    \<search_score name="deltacn" value="0.222"/>
    \<search_score name="deltacnstar" value="0.000"/>
    \<search_score name="spscore" value="129.3"/>
    \<search_score name="sprank" value="1"/>
    \<search_score name="expect" value="3.45E-002"/>
   \</search_hit>

or

\<search_hit hit_rank="1" peptide="DIQMTQSPSSVSASVGDR" peptide_prev_aa="-" peptide_next_aa="V" protein="sp|P01611|KV119_HUMAN" num_tot_proteins="1" num_matched_ions="18" tot_num_ions="68" calc_neutral_pep_mass="2109.021103" massdiff="-0.005582" num_tol_term="2" num_missed_cleavages="0" num_matched_peptides="68432">
    \<modification_info modified_peptide="n[230]DIQM[147]TQSPSSVSASVGDR" mod_nterm_mass="230.170757">
     <mod_aminoacid_mass position="4" mass="147.035400"/>
    \</modification_info>
    \<search_score name="xcorr" value="3.078"/>
    \<search_score name="deltacn" value="0.314"/>
    \<search_score name="deltacnstar" value="0.000"/>
    \<search_score name="spscore" value="246.2"/>
    \<search_score name="sprank" value="1"/>
    \<search_score name="expect" value="6.28E-003"/>
   \</search_hit>

all three loose somehow the Met-oxidation during PS import and I get a delta mass of 16 and a precursor m/z Error [ppm] of >8000.

**Comment by ulriche** [comment]
but interestingly the following (e.g.) work:

\<search_hit hit_rank="1" peptide="FEGKDMAAVQR" peptide_prev_aa="L" peptide_next_aa="T" protein="sp|Q01995|TAGL_HUMAN" num_tot_proteins="1" num_matched_ions="14" tot_num_ions="40" calc_neutral_pep_mass="1495.765603" massdiff="-0.013263" num_tol_term="1" num_missed_cleavages="0" num_matched_peptides="73252">
    \<modification_info modified_peptide="FEGKDM[147]AAVQR">
     \<mod_aminoacid_mass position="4" mass="357.257895"/>
     \<mod_aminoacid_mass position="6" mass="147.035400"/>
    \</modification_info>
    \<search_score name="xcorr" value="2.547"/>
    \<search_score name="deltacn" value="0.215"/>
    \<search_score name="deltacnstar" value="0.000"/>
    \<search_score name="spscore" value="146.1"/>
    \<search_score name="sprank" value="1"/>
    \<search_score name="expect" value="2.44E-002"/>
   \</search_hit>

or also that one:

\<search_hit hit_rank="1" peptide="ADMQNLVER" peptide_prev_aa="M" peptide_next_aa="L" protein="sp|Q01518|CAP1_HUMAN" num_tot_proteins="2" num_matched_ions="12" tot_num_ions="16" calc_neutral_pep_mass="1132.518273" massdiff="0.000114" num_tol_term="1" num_missed_cleavages="0" num_matched_peptides="36071">
    \<modification_info modified_peptide="ADM[147]QNLVER" mod_nterm_mass="43.018390">
     <mod_aminoacid_mass position="3" mass="147.035400"/>
    \</modification_info>
    \<search_score name="xcorr" value="2.487"/>
    \<search_score name="deltacn" value="0.342"/>
    \<search_score name="deltacnstar" value="0.000"/>
    \<search_score name="spscore" value="794.5"/>
    \<search_score name="sprank" value="1"/>
    \<search_score name="expect" value="3.64E-003"/>
   \</search_hit>

**Comment by ulriche** [comment]
a difference that I see now is:

the ones from the top are all "TMT@Nter" whereas the two at the bottom are all all "acetyl@Nter"

but more interestingly I guess:

whereas for "TMT@Nter" it is:
\<modification_info modified_peptide="n[230]PM[147]FIVNTNVPR" mod_nterm_mass="230.170757"> ... so a "n[230]" in the peptide sequence

for "acetyl@Nter" this information is missing:
\<modification_info modified_peptide="ADM[147]QNLVER" mod_nterm_mass="43.018390">

for pyro-peptides the situation is rather as for the "acetylated" ones: e.g.
\<modification_info modified_peptide="E[111]KM[147]TQIM[147]FETFNVPAMYVAIQAVLSLYASGR">
\<modification_info modified_peptide="C[143]DVM[147]YGIEDTQDTVSLTVDGVVFHYR">
\<modification_info modified_peptide="Q[111]KLHELQEKLSPLGEEM[147]R">

so no "n["-tag in the sequence and thus the import seems to work properly.

could that be the reason?

**Comment by ulriche** [comment]
interestingly, when using Comet standalone (Comet version "2015.02 rev. 4"), N-terminal TMT does NOT get reported like via SearchGUI; so here there is NO "n[230]" in the <modification_info modified_peptide=

e.g.: (just took the first hit not necessarily a good one)
\<modification_info modified_peptide="SGGEGTCEASCGNSCDM" mod_nterm_mass="230.170757">

do we use different comet versions?

**Comment by hbarsnes** [comment]
I don't think that we consider the new n[230] tags, so I assume this is causing problems. I will look into it. As for differences compared against Comet standalone there should not be any as all we're doing is executing the same command line. So my guess is that your version of Comet standalone is not identical to the one in SearchGUI?

**Comment by hbarsnes** [comment]
Just did a test with the Comet version included in the current SearchGUI release and I don't get any n[230] tags. You sure you're using the latest Comet release and not some beta version Jimmy created during testing? And you are using the same settings as for the X!Tandem issues right, i.e. variable tmt on n-term and fixed tm on K etc.?

**Comment by ulriche** [comment]
don't understand. i should be using exactly the same comet, just had
downloaded the SearchGui. sure you used variable TMT@Nter? bur will triple
check when at work.

**Comment by ulriche** [comment]
double checked my SearchGUI SearchEngine Settings ...
and comet points to the SearchGUI 2.4.1 installation - so definitely no beta-version.
but will restart the system and rerun the search.

**Comment by hbarsnes** [comment]
> sure you used variable TMT@Nter?

Yup.

**Comment by ulriche** [comment]
rerunning now, and asked Jimmy if he ever used the n[230] tag

but my Report files really say:

   - Comet version "2015.02 rev. 4" (the one that comes with SearchGUI
   2.4.1)
   - SearchGUI 2.4.1
   - PeptideShaker 1.4.0

let's see if I can reproduce it - somehow hope so (feel like chasing
ghosts) and somehow not (less hassle) :-)

**Comment by hbarsnes** [comment]
The issue should have been fixed with the release of SearchGUI 2.5.0 and PeptideShaker 1.5.0. If not, please let us know and we'll reopen the issue.

**Comment by ulriche** [comment]
perfectly works for Comet and X!Tandem now - awesome! really appreciated.
(tested with PeptideShaker 1.5.1 beta)
