### ISSUE TITLE
PeptideShaker import of Comet results - peptides with "TMT @ Nter & K1" get lost

### ISSUE THREAD

**Issue by ulriche** [compomics/peptide-shaker#117]
Along the line with the Met-oxidations that get lost when identified on a peptide with an N-terminal TMT-label (both searched as variable modifications in comet), I fear we still also lose PSMs when they posses both TMT at the N-terminus and at K1. e.g. the following:

   \<search_hit hit_rank="1" peptide="KLEARLKQR" peptide_prev_aa="P" peptide_next_aa="L" protein="sp|Q4G0P3_REVERSED|HYDIN_HUMAN" num_tot_proteins="1" num_matched_ions="7" tot_num_ions="64" calc_neutral_pep_mass="1828.197921" massdiff="3.033646" num_tol_term="1" num_missed_cleavages="1" num_matched_peptides="3991">
    \<modification_info modified_peptide="n[230]KLEARLKQR" mod_nterm_mass="230.170757">
     \<mod_aminoacid_mass position="1" mass="357.257895"/>
     \<mod_aminoacid_mass position="7" mass="357.257895"/>
    \</modification_info>

Note: as nearly always in my searches: TMT@K is set as fixed modification whereas TMT@Nter is a variable one.

possible? at least none of these currently make it into PeptideShaker - but also not too sure how many of these I would really expect.

**Comment by hbarsnes** [comment]
Pretty sure this is the same issue as https://github.com/compomics/peptide-shaker/issues/116. Will look into it.

**Comment by hbarsnes** [comment]
The issue should have been fixed with the release of SearchGUI 2.5.0 and PeptideShaker 1.5.0. If not, please let us know and we'll reopen the issue.

**Comment by ulriche** [comment]
definitely fixed for X! Tandem. will check Comet in a bit.
(tested with PeptideShaker 1.5.1 beta)

**Comment by ulriche** [comment]
also perfectly works for Comet now - cool cool! appreciated.
(tested with PeptideShaker 1.5.1 beta)
