### ISSUE TITLE
An error occurring while loading the identification files

### ISSUE THREAD

**Issue by Dendrobium88** [compomics/peptide-shaker#120]
Hi!
I have a problem with loading the identified files by the Peptide-Shaker.
For a single file analysis I get an output, but when I tried with multiple files it failed. The database was the same in each case.
I was trying with 6 files analyzed first with SearchGUI with different enzyme each. Then I tried to analyze the output of the SearchGUI with the Peptide-Shaker using the “unspecific enzyme” option. It loaded all the data and started the analysis, but then it crashed showing me this messager in the run report:

Computing assumptions probabilities.
Saving assumptions probabilities.
Selecting best peptide per spectrum.
Computing PSM probabilities.
Scoring PTMs in PSMs (D-score and PhosphoRS)
Thresholding PTM localizations.
Resolving peptide inference issues.
Saving probabilities, building peptides and proteins.
Importing Data Canceled!
An error occurred while loading the identification files:
Syntax error: Encountered "subunit" at line 1, column 93.

Does anyone know how can I fix the problem?
Thanks!

**Comment by mvaudel** [comment]
Hi,

Can you try to export the PeptideShaker log via the "Export" -> "Bug Report" Menu?

It seems that an error occurred while interacting with the back-end database. Please make sure that no other instance of PeptideShaker is running. In case you are unsure whether another process is running, restarting the computer might help :)

Best regards,

Marc

**Comment by hbarsnes** [comment]
(Issue assumed fixed. If this is not the case, please let us know and we'll reopen the issue.)
