### ISSUE TITLE
Peptide Shaker 1.4.0: Import of X! Tandem results - Multiple PTMs on termini not supported

### ISSUE THREAD

**Issue by ulriche** [compomics/peptide-shaker#121]
I am having some problems when trying to load some X! Tandem files into PeptideShaker.

Search settings were:
![image](https://cloud.githubusercontent.com/assets/13509447/12519557/70ab4fd4-c0f4-11e5-9728-e2445069e95b.png)

and

![image](https://cloud.githubusercontent.com/assets/13509447/12519590/91dde0cc-c0f4-11e5-89b3-2028d4829171.png)

---
Fri Jan 22 09:58:55 PST 2016        Simplifying protein groups.
Fri Jan 22 09:58:57 PST 2016        9152 unlikely protein mappings found:
Fri Jan 22 09:58:57 PST 2016            - 1418 protein groups explained by peptides shared to less confident mappings.
Fri Jan 22 09:58:57 PST 2016            - 4 protein groups supported by peptides shared to uncharacterized proteins.
Fri Jan 22 09:58:57 PST 2016            - 8101 groups explained by a simpler group.
Fri Jan 22 09:58:57 PST 2016            Note: a group can present combinations of these criteria.
Fri Jan 22 09:58:57 PST 2016        Generating peptide map.
Fri Jan 22 09:58:59 PST 2016        Computing peptide probabilities.
Fri Jan 22 09:58:59 PST 2016        Saving peptide probabilities.
Fri Jan 22 09:59:00 PST 2016        Generating protein map.
Fri Jan 22 09:59:13 PST 2016        Resolving protein inference issues, inferring peptide and protein PI status.
Fri Jan 22 10:31:11 PST 2016        28547 conflicts resolved. 14511 protein groups remaining (30 suspicious).
Fri Jan 22 10:31:11 PST 2016        Correcting protein probabilities.
Fri Jan 22 10:31:11 PST 2016        Saving protein probabilities.
Fri Jan 22 10:31:28 PST 2016        Validating identifications at 1% FDR, quality control of matches.
Fri Jan 22 10:33:24 PST 2016        Scoring PTMs in peptides.

Fri Jan 22 10:33:28 PST 2016        Importing Data Canceled!
Fri Jan 22 10:33:28 PST 2016        An error occurred while loading the identification files:
Fri Jan 22 10:33:28 PST 2016        ***Multiple PTMs on termini not supported.***

---

I had to add Semi-GluC-(DE) to SearchGUI to do it, but think that part went fine (SearchGUI completed without throwing any flags) and the ***X! Tandem parameter*** file looked good:

\<note type="input" label="protein, cleavage site">[DE]|{P}</note>
\<note type="input" label="protein, quick acetyl">no</note>
\<note type="input" label="protein, quick pyrolidone">yes</note>

---

i guess what happens is that there are some PSMs with both e.g. acetyl and pyrrolidone or TMT and pyrrolidone at the N-terminus. but I didn't have problems with importing ArgC data so far.

---

i tried to load another file ... there I got the following error:

Fri Jan 22 10:46:39 PST 2016        Scoring PTMs in peptides.
Fri Jan 22 10:46:51 PST 2016        Importing Data Canceled!
Fri Jan 22 10:46:51 PST 2016        An error occurred while loading the identification files:
Fri Jan 22 10:46:51 PST 2016        ***More sites than PTMs on peptide MSIDKAE_15.99491461956-ATAA-1_42.0105646837-ATAA-1 for PTM of mass 15.99491461956.***

---

but maybe it will be already fixed by the changes you made for the next PS version and the X! Tandem results parsing. The interesting thing though is, that for ArgC PeptideShaker imported these PSMs but lost the Met-oxidation then, in this case (GluC) it fails at the import. But guess there is also something else different.

**Comment by hbarsnes** [comment]
Yes, at least part of these issues should be fixed in the upcoming release. But lets check when it becomes available. Just waiting for the new Comet release.

**Comment by ulriche** [comment]
should be coming today. and will test then again. just wanted to report it in case you spot something additional.

**Comment by hbarsnes** [comment]
No, I don't see anything particular. At least not without looking at it in more details. And I'd rather not debug a bug that may already be fixed. ;) 

I did just add support for "Semi-GluC-(DE)" though. :)

**Comment by ulriche** [comment]
agreed and yeah!!! :-)

**Comment by hbarsnes** [comment]
Hopefully fixed with the release of SearchGUI 2.5.0 and PeptideShaker 1.5.0. If not, please let us know and we'll reopen the issue.

**Comment by ulriche** [comment]
perfectly fixed with PeptideShaker 1.5.1 beta!!!
