### ISSUE TITLE
Feature Request -  PSM report "AAs Before" and "AAs After"

### ISSUE THREAD

**Issue by ulriche** [compomics/peptide-shaker#123]
Is there a way to get the the "AAs Before" and "AAs After" columns from the "Peptide Report also into the "PSM Report"?"

**Comment by mvaudel** [comment]
Yes, will add this.

Thanks for the suggestion,

Marc

2016-01-26 2:26 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
awesome!!!

**Comment by hbarsnes** [comment]
Added in PeptideShaker v1.6.0.

**Comment by ulriche** [comment]
is there a way for me to include it into the "Default PSM Report" or do I
have to create my own one?

and if so, do I keep these personalized reports settings with PeptideShaker
updates or do I have to create them again?

**Comment by mvaudel** [comment]
Hi again,

It is not possible to edit the default PSM report so I am afraid you would
need to create your own export. The exports are saved in your user folder
and conserved between versions :)

Best regards,

Marc

2016-01-26 23:07 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
then it is perfect - that works with me! ;-)
