### ISSUE TITLE
Minor Low Priority Export Modified PSM Report Issue

### ISSUE THREAD

**Issue by ulriche** [compomics/peptide-shaker#133]
One of the "PSM Identification Features" export options gives an error:

-> Peptide spectrum Matching Summary
-> check "show Advanced Features" and "Show Sub Features"
-> `#62:` Peptide Spectrum Matching Summary / Algorithm Score (Best score given by the identification algorithm to the hit retained by PeptideShaker independent of modification localization)

=> "An error occurred while generating the output"

not really a big thing but just wanted to let you know.

**Comment by hbarsnes** [comment]
Thanks for letting us know. There was a minor bug that has now been corrected. Will be fixed in the next release.

**Comment by ulriche** [comment]
again and again impressed by your 24/7 support!

**Comment by hbarsnes** [comment]
Fixed in PeptideShaker v1.7.4.

**Comment by ulriche** [comment]
export works great. thanks.

is it on purpose that the entry of the first search engine is "-10*log(raw score)" while the others are given as "raw score"?

e.g. 
- Algorithm Score: MS Amanda (218.245443490027), MS-GF+ (3.765923E-8), Comet (0.0334)
- Score 47.00
- Raw Score: 1.99E-05

**Comment by mvaudel** [comment]
Hi Ulrich,

The raw score of MS Amanda is 218.245443490027, it is a bit like a Mascot
score. This is why it is different from the others which return a kind of
e-value.

Best regards,

Marc

2016-02-09 1:02 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
oki ... got it ... makes perfectly sense.

but what is then the transformation from "Algorithm Score" to "Raw Score" for MS Amanda? For comet e.g. they are the same.

**Comment by mvaudel** [comment]
The raw score is always the one provided by the algorithm. However, most of
our code assumes that the score is lower for better hits, so whenever we
have a Mascot like score we transform it (10^-score) and use this value to
estimate PEPs and so. For Comet, the score is already in this form so we
keep it as it is :)

2016-02-09 19:24 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
that  makes perfectly sense - thanks for clarification!
