### ISSUE TITLE
peptide-shake command line problem

### ISSUE THREAD

**Issue by wenbostar** [compomics/peptide-shaker#134]
Hi, 
Does anyone know how to solve the following problem?

The command line:
java -Xmx8G -cp  /home/test/PeptideShaker-1.7.4/PeptideShaker-1.7.4.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment test -sample test -replicate 1 -identification_files searchgui_out.zip -out  my.cpsx -spectrum_files test.mgf -id_params search.par

The file "searchgui_out.zip" is directly from SearchGUI (version 2.6.3) and the file "search.par" is the parameter file for SearchGUI command line.

The complete error message:
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
        at eu.isas.peptideshaker.cmd.PeptideShakerCLIInputBean.isValidStartup(PeptideShakerCLIInputBean.java:463)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:890)

Best regards!
Bo

**Comment by hbarsnes** [comment]
Hi Bo,

The "-out" option requires the complete path and not just the file name. (Relative paths may also work but not sure.) 

Best regards,
Harald

**Comment by mvaudel** [comment]
Hi Bo,

It seems that one of the arguments cannot be parsed. My best guess is that -Xmx8G cannot be interpreted due to the missing space.

Best regards,

Marc

**Comment by wenbostar** [comment]
Hi Harald, Marc,

Thank you both very much. When I set all the files and directories as the complete path, it works.
Best regards!

"-Xmx8G" is OK.

Bo

**Comment by hbarsnes** [comment]
Hi Bo,

Great! And yes, "-Xmx8G" is fine.

Best regards,
Harald

**Comment by mvaudel** [comment]
OK guys you win! :)

2016-02-08 21:53 GMT+01:00 Harald Barsnes <notifications@github.com>:
