### ISSUE TITLE
About output file "*_Certificate_of_Analysis.txt" from PeptideShake

### ISSUE THREAD

**Issue by wenbostar** [compomics/peptide-shaker#135]
Hi,
Below is part content from the file "*_Certificate_of_Analysis.txt" generated by PeptideShake. Does anyone know what the meaning is for each row?

Validation Summary

1: #Validated Proteins: 2641.0
2: Protein Total: 3856.27
3Protein FDR Limit: 0.0 %
4: Protein FNR Limit: 31.53 %
5: Protein Confidence Limit: 99.48 %
6: Protein PEP Limit: 0.52 %
7: Protein Confidence Accuracy: 0.52 %
8: #Validated Peptides: 2515.0
9: #Validated Peptides: 367.0
10: #Validated Peptides: 401.0
11: #Validated Peptides: 2306.0
12: #Validated Peptides: 207.0
13: Peptide Total: 4998.61
14: Peptide Total: 960.19
15: Peptide Total: 691.38
16: Peptide Total: 4808.44
17: Peptide Total: 582.06
18: Peptide FDR Limit: 0.0 %
19: Peptide FDR Limit: 0.0 %
20: Peptide FDR Limit: 0.0 %
21: Peptide FDR Limit: 0.0 %
22: Peptide FDR Limit: 0.0 %
23: Peptide FNR Limit: 49.69 %
24: Peptide FNR Limit: 61.84 %
25: Peptide FNR Limit: 42.01 %
26: Peptide FNR Limit: 52.05 %
27: Peptide FNR Limit: 64.44 %
28: Peptide Confidence Limit: 99.96 %
29: Peptide Confidence Limit: 97.83 %
30: Peptide Confidence Limit: 99.79 %
31: Peptide Confidence Limit: 99.73 %
32: Peptide Confidence Limit: 99.64 %
33: Peptide PEP Limit: 0.04 %
34: Peptide PEP Limit: 2.17 %
35: Peptide PEP Limit: 0.21 %
36: Peptide PEP Limit: 0.27 %
37: Peptide PEP Limit: 0.36 %
38: Peptide Confidence Accuracy: 0.19 %
39: Peptide Confidence Accuracy: 1.39 %
40: Peptide Confidence Accuracy: 0.78 %
41: Peptide Confidence Accuracy: 0.36 %
42: Peptide Confidence Accuracy: 0.7 %
43: #Validated PSM: 3875.0
44: #Validated PSM: 3327.0
45: #Validated PSM: 356.0
46: PSM Total: 11437.84
47: PSM Total: 7245.82
48: PSM Total: 995.19
49: PSM FDR Limit: 0.0 %
50: PSM FDR Limit: 0.0 %
51: PSM FDR Limit: 0.0 %
52: PSM FNR Limit: 66.13 %
53: PSM FNR Limit: 54.09 %
54: PSM FNR Limit: 64.28 %
55: PSM Confidence Limit: 99.59 %
56: PSM Confidence Limit: 99.62 %
57: PSM Confidence Limit: 99.55 %
58: PSM PEP Limit: 0.41 %
59: PSM PEP Limit: 0.38 %
60: PSM PEP Limit: 0.45 %
61: PSM Confidence Accuracy: 0.14 %
62: PSM Confidence Accuracy: 0.38 %
63: PSM Confidence Accuracy: 0.45 %

Best  regards!
Bo

**Comment by hbarsnes** [comment]
Hi Bo,

It seems like we have forgotten to update the Certificate of Analysis after making changes to other parts of the code, and that there are thus important elements missing here. We'll look into it and get back to you as soon as we've had the time to update the content of the export.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Bo,

The validation part of the Certificate of Analysis has now been updated and in PeptideShaker v1.7.6 it will hopefully make a lot more sense. But if you still have questions don't hesitate to ask and we'll reopen the issue.

Best regards,
Harald
