### ISSUE TITLE
Duplicate key value issue

### ISSUE THREAD

**Issue by Tracey-Hurrell** [compomics/peptide-shaker#136]
Hi,

I received the following error resulting in cancellation of data import:

Wed Feb 10 18:46:18 CAT 2016        An error occurred: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL160210152613490' defined on 'PROTEINS'.

Would you be able to provide assistance in this regard.
Best,
Tracey

**Comment by hbarsnes** [comment]
Hi Tracy,

Thanks for telling us about this. First, please make sure that you are using the latest version of PeptideShaker, as I'm pretty sure we corrected an error very similar to this one in a recent version. If you are using the latest version, it would be great if you could send us the PeptideShaker log file. You can find it via the Welcome Dialog > Settings & Help > Help > Bug Report. The content of the log file will hopefully tell us a bit more about the source of the issue.

Best regards,
Harald

**Comment by hbarsnes** [comment]
(Issue assumed fixed as the user did not follow up on the issue. If this is not the case, please let us know and we'll reopen the issue.)
