### ISSUE TITLE
Loading results into PeptideShaker fails.

### ISSUE THREAD

**Issue by ulrich-eckhard** [compomics/peptide-shaker#138]
Hey Marc and Harald,

i somehow fail to load some data into PeptideShaker (more details below). tried PS 1.7.5 and 1.7.4, both the same result. It was a rather open search of a QC sample, so with variable dm@K and variable cm@Cys on top of all the other variable ones we typically have (dm/acet/pyro@Nter, Ox@Met). Results are from comet. I also had to add dm4 - 12C(2) 2H(4) [Unimod 199] as we used "deuterated formaldehyde" but "light" sodium cyanoborohydride, giving us +4.

can you have a quick look into that, or have a quick idea what is going wrong?
i am uploading right now the SearchGUI files to my google drive account. will send the link off-list as soon as the upload is done.

thanks already,
u

Peptide Shaker Report
===

Fri Feb 12 10:58:29 PST 2016        Importing sequences from 1512_UP_human_CanIsoCon_concatenated_target_decoy.fasta.
Fri Feb 12 10:58:32 PST 2016        FASTA file import completed.
Fri Feb 12 10:58:32 PST 2016        Importing gene mappings.
Fri Feb 12 10:58:34 PST 2016        Establishing local database connection.
Fri Feb 12 10:58:35 PST 2016        Reading identification files.
Fri Feb 12 10:58:35 PST 2016        Parsing MegaGum_preT_UE-QC1B_F12_01_4545_uncalib_4.3.110.comet.pep.xml.
Fri Feb 12 10:58:38 PST 2016        Loading spectra for MegaGum_preT_UE-QC1B_F12_01_4545_uncalib_4.3.110.comet.pep.xml.
Fri Feb 12 10:58:38 PST 2016        Importing MegaGum_preT_UE-QC1B_F12_01_4545_uncalib_4.3.110.mgf
Fri Feb 12 10:58:38 PST 2016        MegaGum_preT_UE-QC1B_F12_01_4545_uncalib_4.3.110.mgf imported.
Fri Feb 12 10:58:39 PST 2016        Collecting peptides to map.
Fri Feb 12 10:58:40 PST 2016        Mapping peptides to proteins.
Fri Feb 12 11:02:45 PST 2016        Importing PSMs from MegaGum_preT_UE-QC1B_F12_01_4545_uncalib_4.3.110.comet.pep.xml
Fri Feb 12 11:02:45 PST 2016        An error occurred: null
Fri Feb 12 11:02:45 PST 2016        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Fri Feb 12 11:02:45 PST 2016        Importing Data Canceled

Peptide Shaker Log
===
Fri Feb 12 08:58:38 PST 2016: PeptideShaker version 1.7.5.
Memory given to the Java virtual machine: 13981188096.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 131627536.
Java version: 1.8.0_71.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_71
os.name: Windows 7
memory: 46.8/163.1
processors available: 8
useCommandThread: false
java.lang.NullPointerException
	at com.compomics.util.experiment.biology.Peptide.getPotentialModificationSites(Peptide.java:898)
	at com.compomics.util.experiment.biology.PTMFactory.getExpectedPTMs(PTMFactory.java:404)
	at eu.isas.peptideshaker.fileimport.PsmImporter.importAssumptions(PsmImporter.java:580)
	at eu.isas.peptideshaker.fileimport.PsmImporter.importPsm(PsmImporter.java:416)
	at eu.isas.peptideshaker.fileimport.PsmImporter.access$000(PsmImporter.java:66)
	at eu.isas.peptideshaker.fileimport.PsmImporter$PsmImporterRunnable.run(PsmImporter.java:1459)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by hbarsnes** [comment]
Hi Ulrich,

Thanks for the data. We'll have a look at it next week and get back to you. Probably another strange PTM related issue that nobody's come across before, as you're pretty good at those. ;)

Best regards,
Harald

**Comment by ulriche** [comment]
yeah, must be my special gift - and being my own nemesis! ;-)

**Comment by ulriche** [comment]
and thanks already!

**Comment by anupshah14** [comment]
Hi Guys,

I recently had a similar issue. I search the data using SearchGUI 2.6.1. It has successfully completed search using X!Tandom and created a zip file. I got error while importing to Peptideshaker 1.7.6. 
Here are last few lines of peptideshaker report 

Fri Feb 19 18:27:02 AEST 2016        Computing assumptions probabilities.
Fri Feb 19 18:27:02 AEST 2016        Saving assumptions probabilities.
Fri Feb 19 18:27:16 AEST 2016        Selecting best peptide per spectrum.
Fri Feb 19 18:27:59 AEST 2016        Computing PSM probabilities.
Fri Feb 19 18:27:59 AEST 2016        Scoring PTMs in PSMs (D-score and A-score)
Fri Feb 19 18:27:59 AEST 2016        An error occurred: null
Fri Feb 19 18:27:59 AEST 2016        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Fri Feb 19 18:27:59 AEST 2016        Importing Data Canceled!

Not sure if I have done something wrong here. 

Thanks
Anup

**Comment by mvaudel** [comment]
Dear Anup,

Would it be possible for you to send us the log of the tool (available via the _Help_ -> _Bug Report_ menu), and eventually also the paramters file?

Apologies for the inconvenience,

Marc

**Comment by anupshah14** [comment]
Hi Marc,
I was using the option to visualise the report in Peptideshaker after search completion. 
But when I tried to open the zip file in Peptide shaker separately I would load my results. 
Still I will send you the files. 

Anup

**Comment by anupshah14** [comment]
Hi Marc,

Here are files you requested.

Anup

**Comment by mvaudel** [comment]
Hi again,

Great to read that it worked out in the end, and thanks for the log you sent. Would it be possible to send me the log of PeptideShaker as well?

Thank you,

Marc

**Comment by Nyaradzo** [comment]
Hi Marc,

I have been experiencing the same problem. 

error is below and I have attached the log. 

Tue Feb 23 14:10:55 CAT 2016        2 identified spectra (0.1%) did not present a valid peptide.
Tue Feb 23 14:10:55 CAT 2016        4 of the best scoring peptides were excluded by the import filters:
Tue Feb 23 14:10:55 CAT 2016            - 100.0% peptide mapping to both target and decoy.
Tue Feb 23 14:10:55 CAT 2016        Parsing 3B_5ul.myrimatch.mzid.
Tue Feb 23 14:11:05 CAT 2016        Loading spectra for 3B_5ul.myrimatch.mzid.
Tue Feb 23 14:11:05 CAT 2016        Importing PSMs from 3B_5ul.myrimatch.mzid
Tue Feb 23 14:14:26 CAT 2016        An error occurred: Error while loading spectrum 3B_5ul.471.471. File:"3B_5ul.raw", NativeID:"controllerType=0 controllerNumber=1 scan=471" of file 3B_5ul.mgf.
Tue Feb 23 14:14:26 CAT 2016        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Tue Feb 23 14:14:26 CAT 2016        Importing Data Canceled!





Nyari
[Importing data error2.txt](https://github.com/compomics/peptide-shaker/files/144154/Importing.data.error2.txt)

**Comment by mvaudel** [comment]
Hi Nyari,

It seems like these is a problem when reading your files. Can you send me the log of the tool? It is available under the "Help" > "Bug Report" menu which you can access at the tool startup or in the main interface.

Apologizes for the inconvenience,

Marc

**Comment by Nyaradzo** [comment]
Hi Marc,

Please find attached the log

Nyari

**Comment by Nyaradzo** [comment]
Apologies, that was the search gui log attached here is the peptide shaker one,

Nyari

**Comment by mvaudel** [comment]
Hi again and thanks for the files,

It seems that you are running into several problems here: the Comet pepXML files seem to be empty, and the tool does not find the mgf files corresponding to the identification results.

Can you make the zip file containing the identification results available to us, and make sure that the mgf files used for the search are available to the tool?

Best regards,

Marc

**Comment by Nyaradzo** [comment]
Hi,
The zip file without the MGF's is 1Gb. do we have another option?

Nyari

**Comment by mvaudel** [comment]
Hi again,

Can you try to unzip it, and send me one of the pep xml files responsible
for the error?

Best regards,

Marc

2016-02-24 13:28 GMT+01:00 Nyaradzo <notifications@github.com>:

**Comment by Nyaradzo** [comment]
Good Morning,

[8E_5ul.comet.pep.zip](https://github.com/compomics/peptide-shaker/files/146126/8E_5ul.comet.pep.zip)

**Comment by mvaudel** [comment]
Hi again and thank you for these files.

8E_5ul.comet.pep.xml is empty and seems to be the problem. Can you send
us 8E_5ul.mgf as well?

I will make sure that the tool does not break on empty files in the future.
Do you see any reason why Comet did not work on this file? Was there any
error message?

Best regards,

Marc

2016-02-25 9:29 GMT+01:00 Nyaradzo <notifications@github.com>:

**Comment by ulriche** [comment]
Hey Harald and Marc,
trying to hijack my thread again! ;-) did you have time to check my dimethyl data? provided them via my google drive account.
thanks in advance
u

**Comment by hbarsnes** [comment]
Hi Ulrich,

Yes, we think we've located the problem and are working on a fix. A new version will hopefully be out soon.

Best regards,
Harald

**Comment by ulriche** [comment]
cool cool ... thanks already

**Comment by ulriche** [comment]
Hey Harald,

finally found time to play with my duplex dimethyl data with the latest SG release. but as I wanted to have the dm0@K only with dm0@Nter and not with dm6@Nter, I hijacked SG as you suggested (https://github.com/compomics/searchgui/issues/72).

but now I can't load the X! Tandem results into PeptideShaker. The file looks good I think. but maybe you spot something obvious.

i will upload the data to my google drive and send you a link. will also put my parameter file there, so that you can see what I did.

guess you will figure it out quickly,
all the best
u

**Comment by hbarsnes** [comment]
> i will upload the data to my google drive and send you a link. will also put my parameter file there, so that you can see what I did.

I'm still waiting for that link right..?

**Comment by ulriche** [comment]
seems you are! sorry for that! :-)

**Comment by hbarsnes** [comment]
Hi Ulrich,

The new PeptideShaker version is finally out. It should fix the problem with the "Dimethylation of peptide N-term 2H(4)" and "Dimethylation of peptide N-term" modifications.

Best regards,
Harald

**Comment by ulrich-eckhard** [comment]
should find time over the weekend to give it a shot.

fingers crossed!

**Comment by hbarsnes** [comment]
(Issue assumed fixed. If this is not the case, please let us know and we'll reopen the issue.)
