### ISSUE TITLE
Support spectrum input as mzML

### ISSUE THREAD

**Issue by uhaifabioinfo** [compomics/peptide-shaker#140]
Hi,

First off, I would like to thank you guys for all the work you're putting in. SG and PS are awesome platform to work with!

I'm running lots of analyses derived from other search engines. In most cases they run mzML spectrum files and mzidml exported results. However, PS can't match the input MGF to the search results and fails. this requires re-running the search again with MGF. would it be possible to expand format compatibility, at least for PS? 
I would also think that switching to mzML allow quantification using MS1 spectra (which would be great!)

Thanks,
David.

**Comment by mvaudel** [comment]
Hi David,

This is definitely on our todo list. We already have bits of code to support mzML but never got to the point of implementing it. We certainly will and I will keep you posted on our progress.

Best regards and thank you for your feedback,

Marc

**Comment by trishorts** [comment]
is this still moving forward? I have mzml files to load.

**Comment by mvaudel** [comment]
For now the best is that you convert your files to mgf using ProteoWizard (proteowizard.sourceforge.net). If you are using SearchGUI, ProteoWizard is embedded and supports mzML, so you should be able to load your files directly. 
Things have been moving forward on this front, and we are working towards coupling our code with mzDB. This involves major back-end refactoring though so it will take time. If you are interested in contributing we welcome help :)

**Comment by trishorts** [comment]
ok. we have created an excellent library of mass spec tools as a nuget package mzlib (https://github.com/smith-chem-wisc/mzLib). Don't know anything about java so I'm not sure how you'd access it. Bummer because it has tons of functionality and it is very well tested. Maybe we'll add an mgf writer?

**Comment by mvaudel** [comment]
It should be quite simple to export mgf if you already have the data structure indeed, and then you will be able to run more tools on your data :)

**Comment by hbarsnes** [comment]
It took a very long time for us to get around to it, but mzML is now finally supported as an alternative spectrum file format in the latest releases. If it does not work as wanted, please let us know by opening a new issue.
