### ISSUE TITLE
MSGF+ import

### ISSUE THREAD

**Issue by cdlawless** [compomics/peptide-shaker#141]
Hi Marc/Harald

Not really an issue, more of a question. When importing MSGF+ search results to PeptideShaker, do you use the MSGF RawScore or the SpecEValue for calculating the PEP/confidence? 

Thanks

Craig

**Comment by mvaudel** [comment]
Hi Craig,

We use the spectral E-value MS:1002052, if I remember correctly this was approved by the developer.

Best regards,

Marc

**Comment by cdlawless** [comment]
Brilliant. Thanks for the quick response. 
Could I ask what the scores from the other search engines you use?

Thanks again

Craig

**Comment by mvaudel** [comment]
Sure! Note that you will see two scores in PeptideShaker, the raw score as given by the search engine, and the score we use, which can be transformed to have low scores corresponding to high confidence. The list for the different software we support is below, for mzid files I put the CV term ID (see www.ebi.ac.uk/ontology-lookup). When multiple cv terms are possible, the first following the order in the list is selected.

Feel free to ask again if anything is unclear.

Best regards,

Marc



1. Andromeda:
    Raw score: value in the second column of the .res file, MS:1002338 in mzIdentML
    Score used: 10^-rawScore

2. DirecTag:
    Score used: value of the _Total_ column

3. MS Amanda:
    Raw score: Amanda Score in native format, MS:1002319 in mzIdentML
    Score used: _Weighted Probability_ or 10^-rawScore) if not present, both in native format, 10^-MS:1002319 in mzIdentML 
    
4. Novor:
    Score used: _score_

5. pnovo:
    Score used: value of the third column

6. pepnovo:
    Score used: value of the third column

7. Comet:
    Raw score: _expect_ in pepXML, MS:1002255, MS:1002252, MS:1002053, MS:1002055, MS:1002054, MS:1002049 in mzIdentML
    Score used: respectively _expect_ in pepXML, MS:1002255, 10^-MS:1002252, MS:1002053, MS:1002055, MS:1002054, MS:1002049

8. Tide:
    Raw score: _exact p-value_ if present, _xcorr score_ otherwise
    Score used: _exact p-value_ if present, 10^-_xcorr score_ otherwise

9. OMSSA:
    Score used: _e-value_ in native format, MS:1001328, MS:1001329 in mzIdentML

10. Scaffold:
    Score used: MS:1001568

11. X!Tandem:
    Score used: _e-value_ in native format, MS:1001330, MS:1001331 in mzIdentML

12. MS-GF+:
    Score used: MS:1002052

13. Byonic:
    Raw score: MS:1002262, MS:1002311, MS:1002265, MS:1002309, MS:1002266
    Score used: respectively 10^-MS:1002262, 10^-MS:1002311, MS:1002265, 10^-MS:1002309, 10^-MS:1002266

14. MS Fit:
    Score used: MS:1001501

15. Mascot:
    Raw score: _Mascot Score_ in native format, MS:1001172, MS:1001171 in mzIDentML
    Score used: _e-value_ in native format, MS:1001172, 10^-MS:1001171 in mzIdentML, respectively

16. Myrimatch:
    Raw score: MS:1001589, MS:1001590
    Score used: e^-MS:1001589, e^-MS:1001590

17. Peaks:
    Raw score: MS:1002448, MS:1001950
    Score used: respectively MS:1002448, 10^-MS:1001950

18. Phenyx:
    Raw score: MS:1001396, MS:1001395
    Score used: respectively MS:1001396, 2^-MS:1001395

19. Profound:
    Raw score: MS:1001499, MS:1001498
    Score used: respectively 10^-MS:1001499, 2^-MS:1001498

20. ProteinLynx:
    Raw score: MS:1001570, MS:1001569
    Score used: respectively 10^-MS:1001570, 10^-MS:1001569

21. ProteinProspector:
    Raw score: MS:1002045, MS:1002044
    Score used: respectively MS:1002045, 10^-MS:1002044

22. ProteinScape:
    Raw score: MS:1001503, MS:1001504
    Score used: respectively MS:1001503, 10^-MS:1001504

23. SEQUEST:
    Raw score: MS:1001154, MS:1001155, MS:1001215, MS:1002248
    Score used: respectively MS:1001154, 10^-MS:1001155, MS:1001215, 10^-MS:1002248

24. SQID:
    Raw score: MS:1001887
    Score used: 10^-MS:1001887

25. Sonar:
    Raw score: MS:1001502
    Score used: 10^-MS:1001502

26. SpectraST:
    Raw score: MS:1001417
    Score used: 10^-MS:1001417

27. SpectrumMill:
    Raw score: MS:1001572
    Score used: 10^-MS:1001572

28. ZCore:
    Score used: MS:1001952

29. Percolator:
    Raw score: MS:1001491, MS:1001493, MS:1001492
    Score used: respectively MS:1001491, MS:1001493, 10^-MS:1001492

Others:
    Raw score: MS:1002353, MS:1002354, MS:1002357, MS:1002352
    Score used: respectively MS:1002353, MS:1002354, 1-MS:1002357, 1-MS:1002352

**Comment by cdlawless** [comment]
Thanks for this Marc, this helps a lot.

Craig
