### ISSUE TITLE
PeptideShaker Startup Error

### ISSUE THREAD

**Issue by ulrich-eckhard** [compomics/peptide-shaker#142]
Hey guys,

somehow I am getting recently quite often the following error:
![image](https://cloud.githubusercontent.com/assets/13509447/13643727/061c5bf6-e5d7-11e5-9e64-35dad7fefe36.png)
but didn't find the respective folder - an idea/hint?

the interesting thing is though, that it happens while I am within PeptideShaker and when the program stalls (but maybe I am just not waiting long enough for it to recover). 

![image](https://cloud.githubusercontent.com/assets/13509447/13644064/b06da9d8-e5d8-11e5-8de9-5341f0c739c2.png)

My PS projects are are rather big, already (>5GB), and will be soon even bigger I fear. I have roughly 30GB of memory allocated to PS - an idea when I will hit the sealing here? so is there something like a "minimum" ratio of PS project size and memory? or will it just be slower?

**Comment by hbarsnes** [comment]
Hi Ulrich, 

> but didn't find the respective folder - an idea/hint?

You'll find the startup log file here: PeptideShaker-1.8.1\resources\conf\startup.log. You don't see it?

If the error occurs after the tool as started it might also help to check the normal log file. Usually it means that an error occurred that is not picked up properly.

> My PS projects are rather big, already (>5GB), and will be soon even bigger I fear. I have roughly 30GB of memory allocated to PS - an idea when I will hit the sealing here? so is there something like a "minimum" ratio of PS project size and memory? or will it just be slower?

There is no ceiling really, it will just take more time. But of course if it takes way too long than that could be considered as a ceiling as well of course. We are however always looking into ways of speeding up the processing and reducing the memory consumption, and the current versions is a lot better in both respects compared to older versions. Recently we've also made some speed ups to the PTM scoring that will be included in the next release.

Generally, the best way of speeding up the processing is to optimize the input, in terms of the spectra, the search settings and the FASTA file used.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Ulrich, 

Did you make any progress on this one? Did you find the startup log file? Or see anything in the normal log file?

Best regards,
Harald

**Comment by ulriche** [comment]
since the new PS all looks good so far. but will keep an eye on it.

**Comment by ulriche** [comment]
here the startup log: (had the error again after PS died while saving my results)
---
Memory settings read from the user preferences: 30720
args: 
original java.home: C:\Program Files\Java\jre1.8.0_72\bin\
new java.home: C:\Program Files\Java\jre1.8.0_72\bin\

Command line: 
"C:\Program Files\Java\jre1.8.0_72\bin\java" -splash:resources\conf\peptide-shaker-splash.png -Xms128M -Xmx30720M -cp "C:\Users\Overall Lab\Desktop\55_TopHeart-NEW\03 PeptideShaker\PeptideShaker-1.9.0\PeptideShaker-1.9.0.jar" eu.isas.peptideshaker.gui.PeptideShakerGUI 
Process exitValue: 1

**Comment by hbarsnes** [comment]
> here the startup log: (had the error again after PS died while saving my results)

Don't see any problems there. Anything in the normal log file?

**Comment by ulriche** [comment]
no ... nothing ... but will keep an eye on it ...
