### ISSUE TITLE
Custom reports in PeptideShakerCLI

### ISSUE THREAD

**Issue by cdlawless** [compomics/peptide-shaker#143]
Hi

How can you create custom reports to use with the PeptideShakerCLI and then specify to use them?

Thanks

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

You will have to set up the custom reports via the graphical user interface as there is no support for doing this via the command line. Custom reports made via the graphical user interface are however available for use on the command line as well. 

If you use `java -cp PeptideShaker-X.Y.Z.jar eu.isas.peptideshaker.cmd.ReportCLI` you will see the index to use for your custom reports. Then use [ReportCLI](https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI#b---reportcli) to create the export. Or you can add "-reports" to the normal PeptideShaker command line.

Best regards,
Harald

**Comment by cdlawless** [comment]
Hi Harald

The only problem with that is that I run PeptideShaker on our HPC, so cannot use the GUI. I did try a workaround, by creating the report in the PeptideShaker GUI and then copying across the exportFactory.cus that was created. 

I then set the Paths by calling:
java -Xms1024m -Xmx262144m -cp /scratch/mjfidcl2/PeptideShaker-1.8.1/PeptideShaker-1.8.1.jar eu.isas.peptideshaker.cmd.PathSettingsCLI -peptideshaker_exports "/scratch/mjfidcl2/DDIP/"

but when I run: 
ava -Xms1024m -Xmx262144m -cp /scratch/mjfidcl2/PeptideShaker-1.8.1/PeptideShaker-1.8.1.jar  eu.isas.peptideshaker.cmd.ReportCLI -in "/scratch/mjfidcl2/DDIP/Vanilla_MSGF_5.cpsx" -out_reports "/scratch/mjfidcl2/DDIP/" -reports "9, 10, 11"

I get the error: 
An error occurred when setting path configurations. Default paths will be used.

In addition, because I export a zip file from SearchGUI (and also export as zip from PeptideShaker). I'm getting issues relating to protein indexes:
java.io.FileNotFoundException: File /mnt/fls01-home01/mjfidcl2/.compomics/proteins/indexes/ not found.

Is it possible to provide the PeptideShaker project zip file to the reports or do I have to unzip manually?

If so, I will still get the errors associated with the PathSettings I get above?

Thank you 

Craig

**Comment by hbarsnes** [comment]
> The only problem with that is that I run PeptideShaker on our HPC, so cannot use the GUI. I did try a workaround, by creating the report in the PeptideShaker GUI and then copying across the exportFactory.cus that was created. 

Ah, yes, but I think copying the exportFactory.cus file ought to work. But never tested this myself.

> An error occurred when setting path configurations. Default paths will be used.

And there is no more information about the error? If not, it seems like the tool is failing to extract the folders it fails to write to. Will add a better error message in the next version. Have you tried using "-temp_folder" instead of just "-peptideshaker_exports"?

> Is it possible to provide the PeptideShaker project zip file to the reports or do I have to unzip manually?

To avoid having to unzip to export the reports, I would recommend to do add the report options to the initial PeptideShaker command line. In other words add " -out_reports "/scratch/mjfidcl2/DDIP/" -reports "9, 10, 11" to the end of your PeptideShakerCLI command line.

**Comment by cdlawless** [comment]
Hi Harald

I copied over the exportFactory.cus and set -temp_folder in PathSettingsCLI and it works. 

Thank you

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

Great! I'll close the issue then. Let us know if you come across other issues with using the reports on the command line, as this is not the most heavily tested part of our code. :)

Best regards,
Harald
