### ISSUE TITLE
Protein not found

### ISSUE THREAD

**Issue by norazrin** [compomics/peptide-shaker#144]
Hi, 

I run the Peptideshaker -1.8.1 and there was this error:

> java.lang.IllegalArgumentException:

 Protein not found: ENSGALP00000036979 pep:known chromosome:WASHUC2:Z:53399698:53408329:-1 gene:ENSGALG00000015425 transcript:ENSGALT00000037774_REVERSED.

i have checked the mentioned protein in the database that i used, and the protein is there and listed with the same protein, gene and transcript id.

can you please explain on how to overcome this problem?

best,
Azrin

**Comment by mvaudel** [comment]
Hi Azrin,

it seems to be a problem with the parsing of your fasta file. Is this a standard Ensembl file?
If you are using a home made database, it can be that it is not recognized by some search engines or PeptideShaker, then we recommend to use the generic fasta format described here: https://github.com/compomics/searchgui/wiki/DatabaseHelp#non-standard-fasta

Hope this helps,

Marc

**Comment by norazrin** [comment]
thanks!
