### ISSUE TITLE
Asterisk as the stop codon in Peptideshaker

### ISSUE THREAD

**Issue by norazrin** [compomics/peptide-shaker#148]
Hi ,

I came accross some asterisk in the peptide sequence database and  the problem is that the peptideshaker failed to run as normal as it cant identified the amino acid as indicated as in the asterisk symbol. For my cases most of the "*" are the stop codon as it appears at the end of the sequence. 

Peptideshaker worked perfectly fine after i did some modification on the databasesbut it would be awesome if peptideshaker could recognize some stop codon and run automatically wiothout producing error ;)

thanks

**Comment by mvaudel** [comment]
Hi Azrin,

Thank you for this suggestion, we will work on it :)

Best regards,

Marc

**Comment by norazrin** [comment]
Cool! thanks a lot!

**Comment by mvaudel** [comment]
Hi Azrin,

The new release should now escape asterisks in protein sequences. If the problem is not fixed please contact us again and we will reopen the issue.

Best regards,

Marc
