### ISSUE TITLE
Unable to save PeptideShaker report

### ISSUE THREAD

**Issue by muizzulkapli** [compomics/peptide-shaker#150]
Hi,
I'm currently working with PeptideShaker and suddenly i am not able to save the report.
Here is the error appeared:
 
"Caused by: ERROR 23505: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL160405123758550' defined on 'PROTEINS'.

Thank you in advanced for your help.
-muiz

**Comment by mvaudel** [comment]
Hi Muiz and thank you for reporting this issue.

Can it be that you have multiple projects open simultaneously, or another instance of PeptideShaker not properly closed? You will see other instances in the task manager.

If so please try to close all other instances running - to be sure you can also restart your computer - and then try to export it again.

If the error persists, please send us the log of the tool, you will find it under the Help -> Bug Reports menu.

Apologies for the inconvenience,

Marc

**Comment by hbarsnes** [comment]
(Issue assumed solved by the user. If this is not the case, please let us know and we'll reopen the issue.)
