### ISSUE TITLE
PSM import timed out

### ISSUE THREAD

**Issue by vladie0** [compomics/peptide-shaker#151]
Dear developers, 

While using PeptideShaker I've encoutered the following error:

java.lang.InterruptedException: PSM import timed out. Please contact the developers.
        at eu.isas.peptideshaker.fileimport.PsmImporter.importPsmsMultipleThreads(PsmImporter.java:295)
        at eu.isas.peptideshaker.fileimport.PsmImporter.importPsms(PsmImporter.java:257)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importPsms(FileImporter.java:778)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:482)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:696)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:205)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:908)

The error is generated after importing PSM for 24hours, a limit enforced by you (PsmImporter module line 295). The cause of this error is probably the size and amount of files i'm working with, meaning that a limit of 1 day is insufficient to import all PSM files. I've attempted to fork PeptideShaker and adjust this limit ( to 3 days), however I do not know hot to convert the github java files into a .jar file. 

Is it possible to either adjust this variable, or guide me trough the process on how to create a .jar file from your mirrored github repository ? 

thanks in advance, 
Volodimir olexiouk

**Comment by hbarsnes** [comment]
Hi Volodimir,

Thanks for telling us about this. If the importing of the PSMs times out it is usually an indication that either something is not optimal with the setup of the environment used to process the data or an indication of a possible bug in our code.

So before you go ahead and build your own PeptideShaker version perhaps you could tell us a bit more about the machine you are using to process your data? Mainly how much memory you are giving PeptideShaker and where the files you are processing are being stored?

It is recommended to give PeptideShaker as much memory as possible. When using the command line (as I assume you are doing from the example above) this is set via the normal -Xmx Java option. Regarding the storage of the files to process we recommend keeping them all on the same drive as the one running PeptideShaker, as this speeds up the processing and reduces the chance of network issues. We also recommend SDD disks if possible.

Finally, how big are the files you are trying to process, and from which search engine? Do you have the same problem for all the search engines?

Best regards,
Harald

**Comment by vladie0** [comment]
Hi Harald,
+-50 mgf files of size 500mb-2gb were processed using SearchGUI using X!tandem, MSGF+ and OMSSA (no error occured), on a Linux machine with 64 cores and 315gb memory. All files are being stored in the same directory, I've used peptideshaker/searchGUI on many tasks without problems so I doubt the error/bug is machine related.

I will now re-run peptideshaker with increased memory as well reprocess the data with searchGUI with only 1 engine related to detect engine errors.

I will let you know the outcome,
Best Regards, 
Volodimir Olexiouk

**Comment by hbarsnes** [comment]
Hi Volodimir,

Given that we didn't hear back from you regarding this issue can we assume that you managed to resolve it? If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by vladie0** [comment]
Dear Harald, 

My apologies for not replying on this thread, it seems i've lost track of it.
The issue was solved following your suggested solution.

Thank you for your support,
Volodimir
