### ISSUE TITLE
Minor Feature Request: aa-position of matched peptide plus column with preceding aminoacids

### ISSUE THREAD

**Issue by ulrich-eckhard** [compomics/peptide-shaker#155]
Hey Marc & Harald,
finally back to playing with PS a bit. Maybe I missed it, but is there a way to get the aminoacid-position of my PSM within the matched protein, and e.g. an extended sequence column for the preceding aminoacids. I would be great for me if I could export a column with the "Start Position" of the matched peptide, plus two extra columns of 10aa before the identified peptide, and 10aa after the starting position (but the latter would be less important as I have the matched sequence but would be great for consistency). Then I could do some of my N-terminomics downstream analysis right away with the PS output. any chance of implementing that as extra export options? that would be great!!!
all the best from Vancouver
u

**Comment by mvaudel** [comment]
Hi Ulrich!

You can export these for the peptides but at the moment the position on the protein sequence is not available for the PSMs. If needed it is not much work to add them!

Best regards,

Marc

**Comment by ulrich-eckhard** [comment]
hmmm ... if possible I would love to heave it at the PSM level already. but
will definitely check the peptide export a bit more, but so far I somewhat
always prefered the PSM one - but don't ask me why, wouldn't remember right
now! :-)

**Comment by hbarsnes** [comment]
Note that you can change the number of amino acids shown before/after the peptide sequence in both the GUI and the exports via Edit > Project Settings > Display Settings. We will most likely rename the "Project Settings" option in the next version though, as I just noticed that we an option with the same name on the File menu... ;-)

**Comment by ulrich-eckhard** [comment]
that's great - didn't know - will give that a shot definitely.
cheers
u

**Comment by ulrich-eckhard** [comment]
i must look at the wrong spots - don't find it ... where do I find this option?

![image](https://cloud.githubusercontent.com/assets/13509447/14758956/0d28ab2c-08c6-11e6-82bb-2bdb08c4dba0.png)

**Comment by mvaudel** [comment]
Hi Ulrich,

Sorry, minor typo, Project Settings is in the File menu :)

Best regards,

Marc

2016-04-23 5:09 GMT+02:00 Ulrich Eckhard <notifications@github.com>:

**Comment by hbarsnes** [comment]
Hi Ulrich,

> i must look at the wrong spots - don't find it ... where do I find this option?

As mentioned above: "We will most likely rename the "Project Settings" option in the next version though". :)

Try: Edit > Project Preferences > Display Settings.

Best regards,
Harald

**Comment by ulrich-eckhard** [comment]
thanks ... i was even looking there but didn't realize that I just had to
click on the
"Edit" button next to the Display thingy ...

**Comment by hbarsnes** [comment]
Hi Ulrich,

Here's a beta version that includes the position(s) of the peptide in the protein sequence(s) and the amino acids before/after the peptide in the default PSM report: https://www.dropbox.com/s/27iy1saunnmursh/PeptideShaker-1.11.1-beta.zip?dl=0

Please check if you now have what you need?

All of it as actually already available, except for the position in the PSM report, but now the information is included in the default exports and should thus be more easily available.

Best regards,
Harald

**Comment by ulrich-eckhard** [comment]
I am out of tow this weekend but will test it on Monday right away ...

**Comment by ulrich-eckhard** [comment]
worked like a charm!!! big big thanks!!!

**Comment by hbarsnes** [comment]
Ho Ulrich,

PeptideShaker v1.12.0 has now been released which adds the requested export details.

Best regards,
Harald

**Comment by ulrich-eckhard** [comment]
Hey Mark and Harald,
any reason why the "number of amino acids shown before/after the peptide sequence" is limited to 5? if you increase it to 6 or better 10, I could directly use it for future PICS data analysis.
cheers and thanks
u
PS: it is no real rush, but i guess it is an easy fix. but if not, it is not that important - 5 can be good enough in many cases. :-)

**Comment by hbarsnes** [comment]
Hi Ulrich,

No reason that I can remember. I guess we just didn't think that people would need more than 5. :)

Will remove the limitation in the next release. I just tested with 10 and it all seemed to work fine.

Best regards,
Harald

**Comment by ulrich-eckhard** [comment]
coolio ... :-)
