### ISSUE TITLE
Errors when loading identification/database files

### ISSUE THREAD

**Issue by LZwart** [compomics/peptide-shaker#156]
Hi!

I've been trying to analyse results from three search engines (MyriMatch, MS-GF+ and X!TANDEM, 
generated with SearchGUI-2.8.2 on Windows 8 - these are the only ones that work for some reason) 
with PeptideShaker-1.9.3. The computer that I used to generate these results gave an error when I 
tried to analyse them with PeptideShaker, stating that certain database "entries were not found 
in the cache when saving." 

I decided to try and analyse these results on our server as well (Linux; it can't do the MyriMatch search in SearchGUI for some reason, only MS-GF+ and X!TANDEM, otherwise I would do everything on the server). 

Unfortunately, it doesn't work with the GUI or CLI of PeptideShaker on the server. I used 
unchanged copies of the input files, and used SearchGUI on Linux to edit the .par file (only 
changed database and spectrum file locations). I am using a custom database, but I'm not sure if 
that's causing the problem. I also noticed that the PC and server have different versions of Java installed...

When I try the searches with each identification file individually, I get the same error message 
for MS-GF+ and X!TANDEM results (Index out of bounds), but I've seen two different messages with 
the MyriMatch results ("Failed to start database", "Another instance of Derby may have already 
booted the database", "Database could not be accessed, make sure that the file is not used by another program and that you have not run out of diskspace", something about the protein tree; and something about Index out of bounds again, but this time Index and Size have the same value, "Cannot create log file at directory"). The full reports are attached.

I have used these .mgf and .fasta input files successfully in the past. I could do the entire 
analysis on the PC with single search engine results, and on the server with combined MS-GF+ and 
X!TANDEM results, as long as everything was done on the same system.

I would appreciate any suggestions!

Regards
Lizahn Zwart

[2016-04-14_MyiMatch_only_db_fail.txt](https://github.com/compomics/peptide-shaker/files/220734/2016-04-14_MyiMatch_only_db_fail.txt)
[2016-04-14_MyiMatch_only_db_fail2.txt](https://github.com/compomics/peptide-shaker/files/220737/2016-04-14_MyiMatch_only_db_fail2.txt)
[PeptideShaker 1.9.3 log Linux.txt](https://github.com/compomics/peptide-shaker/files/220741/PeptideShaker.1.9.3.log.Linux.txt)
[PeptideShaker 1.9.3 log PC.txt](https://github.com/compomics/peptide-shaker/files/220751/PeptideShaker.1.9.3.log.PC.txt)
[PS failed PC.txt](https://github.com/compomics/peptide-shaker/files/220746/PS.failed.PC.txt)
[PS_error_Linux.txt](https://github.com/compomics/peptide-shaker/files/220749/PS_error_Linux.txt)

**Comment by hbarsnes** [comment]
Hi Lizahn,

Thanks for telling us about this. Before going into the issues with the loading of the data in PeptideShaker it would be nice to know why only three of the search engines worked? Could be something special with your input or setup that could be fixed? Did you get any meaningful error messages for the search engines that failed? And could you send us the SearchGUI log file as well?

Regarding MyriMatch on Linux, did you check the SearchGUI [troubleshooting](http://compomics.github.io/projects/searchgui.html#troubleshooting) section? As there is a tip on MyriMatch on Linux there that could help?

 > I am using a custom database, but I'm not sure if that's causing the problem.

Could be the cause. But if the fasta file has worked before I don't really see why it should stop working.

Have you used [PathSettingsCLI ](http://compomics.github.io/peptide-shaker/wiki/peptideshakercli.html#e---pathsettingscli) to set the temporary paths to folders you have write access to? Path related issues seems to be a common theme to many of your error messages.

Also, make sure that only one version of PeptideShaker is running at the same time.

Best regards,
Harald

**Comment by LZwart** [comment]
Hi, Harald.

Thanks a lot for your advice and time!

The searches that failed gave a variety of error messages. I've attached these. I forgot to mention that Andromeda worked, but I decided not to use it for my analysis as discussed in a previous issue here. MS Amanda is also working on PC now (I must have done something wrong last time, was also with an older version). Sorry about the confusion! This leaves OMSSA, Comet and Tide that do not work on the PC, and MyriMatch, OMSSA, Comet and Tide on Linux (I haven't tested MS Amanda on Linux yet, will do so when I can).

On Windows:
The links on the SearchGUI troubleshooting page under "OMSSA for Windows" don't seem to lead to the right place anymore. They lead to the Microsoft "Top Download Categories" page. Or am I missing something?

While running OMSSA through SearchGUI, I noticed that "omssacl.exe (32 bit)" was running in Task Manager. Is this normal? Shouldn't it be 64-bit?

I did a quick test to see if the database format could be the problem by repeating the identical search with the UniProt database using OMSSA. The same error resulted as with my custom database, so it seems unlikely that my database is the (only) problem, at least with OMSSA.

I noticed that one error in Tide states "Load spectra:Error in MGF file: bad m/z or intensity value." Could the problem be in the MGF file?

When I run the search engines in command line, all eight seem to work (returns usage instructions). I used the 64-bit Windows executables where applicable.

On Linux:

I've tried adding the PathSettingsCLI commands with paths to new folders in my user directory: java -cp PeptideShaker-1.9.3.jar eu.isas.peptideshaker.cmd.PathSettingsCLI 
-temp_folder 
-log 
-peptideshaker_matches_directory 
-fasta_indexes 

These directories were used instead, but the analysis failed with the same errors. 

Unfortunately, there is an issue with our servers, so I can't change anything else about that analysis at the moment. I'll try your other suggestions as soon as possible. I didn't see the "locale::facet..." error with the MyriMatch search on Linux, but I'll try everything and see what happens.

I would really appreciate it if you can find the time to have a look at this.

Regards
Lizahn

[2016-04-07 OMSSA failed PC custom db.txt](https://github.com/compomics/peptide-shaker/files/225338/2016-04-07.OMSSA.failed.PC.custom.db.txt)
[2016-04-08 Comet PC failed.txt](https://github.com/compomics/peptide-shaker/files/225339/2016-04-08.Comet.PC.failed.txt)
[2016-04-18 OMSSA uniprot failed PC.txt](https://
github.com/compomics/peptide-shaker/files/225340/2016-04-18.OMSSA.uniprot.failed.PC.txt)
[Tide report PC.txt](https://github.com/compomics/peptide-shaker/files/225370/Tide.report.PC.txt)
[Tide SearchGUI 2.8.2 log.txt](https://github.com/compomics/peptide-shaker/files/225368/Tide.SearchGUI.2.8.2.log.txt)
[2016-04-06_MSGF_Myri_XTANDEM_OMSSA_Linux.txt](https://github.com/compomics/peptide-shaker/files/225342/2016-04-06_MSGF_Myri_XTANDEM_OMSSA_Linux.txt)
[2016-04-07_SearchGUI_Linux_comet_tide_failed_Linux.txt](https://github.com/compomics/peptide-shaker/files/225343/2016-04-07_SearchGUI_Linux_comet_tide_failed_Linux.txt)

**Comment by hbarsnes** [comment]
Hi Lizahn,

> The links on the SearchGUI troubleshooting page under "OMSSA for Windows" don't seem to lead to the right place anymore. They lead to the Microsoft "Top Download Categories" page. Or am I missing something?

No, the links seems to no longer be available. Not sure if the patches are even available anymore. But before searching for them see the next point.

> While running OMSSA through SearchGUI, I noticed that "omssacl.exe (32 bit)" was running in Task Manager. Is this normal? Shouldn't it be 64-bit?

Nope, OMSSA is pretty old and I don't think 64 bit was around when it was created. And given that the development and maintenance of OMSSA has since been discontinued there will not be a 64 bit. Additionally, OMSSA is struggling with big (normal?) size current mgf files. So if OMSSA does not work for your data I would recommend just leaving it out of your processing pipeline.

> I noticed that one error in Tide states "Load spectra:Error in MGF file: bad m/z or intensity value." Could the problem be in the MGF file?

Yup. I think you mean Comet and not Tide though? Could you send me one of these mgf files? Then I can discuss with the Comet developers? Or maybe find a simpler fix.

General comments:
- OMSSA seems to have memory issues. Most likely the mgf file is too big for 32 bit.
- For Tide make sure that you are using the 64 bit version. Also, make sure that you have write access in the folder where Tide puts its FASTA file index. Should be in the same folder as the Tide executable.
- The Comet error file above is actually not from Comet but from Tide.
- MyriMatch does not seem to even start? Done after 203 milliseconds? No idea why...

So to conclude, stick with the search engines you get to work. Generally the gain is not very high after adding 2-3 search engines anyway. Depending on the search engines added of course. But with X! Tandem and MS-GF+ your should be ok.

Best regards,
Harald

**Comment by LZwart** [comment]
Hi, Harald.

Thanks again for your quick response!

I don't particularly need to use OMSSA, Comet or Tide, so it should be fine
to leave them out. I'm also expecting to have results from Mascot to add
soon. I just thought it would be interesting to compare the results from
all the search engines.

Tide seemed to be using the correct exe file during the search. So did
Comet. Sorry about sending the wrong Comet report file. The Comet search
stays at "Load spectra" for many hours until I cancel it. I checked the
folders for the Tide search, and I couldn't find anything strange about the
writing permissions. I can send you a link to the mgf file if you think it
might help/if you have time. Would it be possible to email the link
directly to you?

I'll give feedback about the analysis on Linux as soon as possible.


Returning to the issues with PeptideShaker. On PC, I got a message about
certain proteins not being in the cache when I tried to combine results
from more than one search engine. This happens at/after "Saving
probabilities, building peptides and proteins." Could this mean that the
computer has insufficient memory for the analysis? And what does "_cus_"
mean between the names?

java.lang.IllegalArgumentException: Object
Eucgr.B00145.1.p|pacid:32059618_cus_Eucgr.B00145.2.p|pacid:32059619_cus_Eucgr.B00145.3.p|pacid:32059620_cus_Eucgr.B00145.4.p|pacid:32059621_cus_Eucgr.B00145.5.p|pacid:32059622_cus_Eucgr.B01243.1.p|pacid:32062111_cus_Eucgr.B01246.1.p|pacid:32059584_cus_Eucgr.B01253.1.p|pacid:32058563_cus_Eucgr.B01777.1.p|pacid:32060435_cus_Eucgr.B01777.2.p|pacid:32060436_cus_Eucgr.B01777.3.p|pacid:32060437_cus_Eucgr.B01777.4.p|pacid:32060438_cus_Eucgr.B01777.5.p|pacid:32060439_cus_Eucgr.E00336.1.p|pacid:32028975_cus_Eucgr.E00336.2.p|pacid:32028976_cus_Eucgr.E00336.3.p|pacid:32028977_cus_Eucgr.E00336.4.p|pacid:32028978_cus_Eucgr.E00337.1.p|pacid:32031595_cus_Eucgr.E00337.2.p|pacid:32031596_cus_Eucgr.E00337.3.p|pacid:32031597_cus_Eucgr.E00343.1.p|pacid:32028700_cus_Eucgr.E00344.1.p|pacid:32029644_cus_Eucgr.E00346.1.p|pacid:32031374_cus_Eucgr.F01584.1.p|pacid:32053086_cus_Eucgr.F01584.2.p|pacid:32053087_cus_Eucgr.F01584.3.p|pacid:32053088_cus_Eucgr.L02476.1.p|pacid:32032042_cus_Eucgr.L03227.1.p|pacid:32062433
corresponding to entry
2016-04-13_Zips_TAG5_0_id_ccs_proteins_ccs_Eucgr.B00145.1.p|pacid:32059618_cus_Eucgr.B00145.2.p|pacid:32059619_cus_Eucgr.B00145.3.p|pacid:32059620_cus_Eucgr.B00145.4.p|pacid:32059621_cus_Eucgr.B00145.5.p|pacid:32059622_cus_Eucgr.B01243.1.p|pacid:32062111_cus_Eucgr.B01246.1.p|pacid:32059584_cus_Eucgr.B01253.1.p|pacid:32058563_cus_Eucgr.B01777.1.p|pacid:32060435_cus_Eucgr.B01777.2.p|pacid:32060436_cus_Eucgr.B01777.3.p|pacid:32060437_cus_Eucgr.B01777.4.p|pacid:32060438_cus_Eucgr.B01777.5.p|pacid:32060439_cus_Eucgr.E00336.1.p|pacid:32028975_cus_Eucgr.E00336.2.p|pacid:32028976_cus_Eucgr.E00336.3.p|pacid:32028977_cus_Eucgr.E00336.4.p|pacid:32028978_cus_Eucgr.E00337.1.p|pacid:32031595_cus_Eucgr.E00337.2.p|pacid:32031596_cus_Eucgr.E00337.3.p|pacid:32031597_cus_Eucgr.E00343.1.p|pacid:32028700_cus_Eucgr.E00344.1.p|pacid:32029644_cus_Eucgr.E00346.1.p|pacid:32031374_cus_Eucgr.F01584.1.p|pacid:32053086_cus_Eucgr.F01584.2.p|pacid:32053087_cus_Eucgr.F01584.3.p|pacid:32053088_cus_Eucgr.L02476.1.p|pacid:32032042_cus_Eucgr.L03227.1.p|pacid:32062433
not found in cache when saving.
at com.compomics.util.db.ObjectsCache.saveObjects(ObjectsCache.java:370)
at com.compomics.util.db.ObjectsCache.saveObjects(ObjectsCache.java:318)
at com.compomics.util.db.ObjectsCache.updateCache(ObjectsCache.java:522)
at com.compomics.util.db.ObjectsCache.addObject(ObjectsCache.java:293)
at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:639)
at
com.compomics.util.experiment.identification.IdentificationDB.loadSpectrumMatches(IdentificationDB.java:841)
at
com.compomics.util.experiment.identification.Identification.loadSpectrumMatches(Identification.java:241)
at
com.compomics.util.experiment.identification.matches_iterators.PsmIterator.checkBuffer(PsmIterator.java:267)
at
com.compomics.util.experiment.identification.matches_iterators.PsmIterator.next(PsmIterator.java:236)
at
eu.isas.peptideshaker.PeptideShaker.attachSpectrumProbabilitiesAndBuildPeptidesAndProteins(PeptideShaker.java:828)
at
eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:400)
at
eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:553)
at
eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:438)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Free memory: 2341647600

All the best
Lizahn

On 19 April 2016 at 10:47, Harald Barsnes <notifications@github.com> wrote:

> Hi Lizahn,
>
> The links on the SearchGUI troubleshooting page under "OMSSA for Windows"
> don't seem to lead to the right place anymore. They lead to the Microsoft
> "Top Download Categories" page. Or am I missing something?
>
> No, the links seems to no longer be available. Not sure if the patches are
> even available anymore. But before searching for them see the next point.
>
> While running OMSSA through SearchGUI, I noticed that "omssacl.exe (32
> bit)" was running in Task Manager. Is this normal? Shouldn't it be 64-bit?
>
> Nope, OMSSA is pretty old and I don't think 64 bit was around when it was
> created. And given that the development and maintenance of OMSSA has since
> been discontinued there will not be a 64 bit. Additionally, OMSSA is
> struggling with big (normal?) size current mgf files. So if OMSSA does not
> work for your data I would recommend just leaving it out of your processing
> pipeline.
>
> I noticed that one error in Tide states "Load spectra:Error in MGF file:
> bad m/z or intensity value." Could the problem be in the MGF file?
>
> Yup. I think you mean Comet and not Tide though? Could you send me one of
> these mgf files? Then I can discuss with the Comet developers? Or maybe
> find a simpler fix.
>
> General comments:
>
>    - OMSSA seems to have memory issues. Most likely the mgf file is too
>    big for 32 bit.
>    - For Tide make sure that you are using the 64 bit version. Also, make
>    sure that you have write access in the folder where Tide puts its FASTA
>    file index. Should be in the same folder as the Tide executable.
>    - The Comet error file above is actually not from Comet but from Tide.
>    - MyriMatch does not seem to even start? Done after 203 milliseconds?
>    No idea why...
>
> So to conclude, stick with the search engines you get to work. Generally
> the gain is not very high after adding 2-3 search engines anyway. Depending
> on the search engines added of course. But with X! Tandem and MS-GF+ your
> should be ok.
>
> Best regards,
> Harald
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/compomics/peptide-shaker/issues/156#issuecomment-211804936>
>

-- 
This message and attachments are subject to a disclaimer. Please refer to 
http://www.it.up.ac.za/documentation/governance/disclaimer/ for full 
details.

**Comment by hbarsnes** [comment]
> The Comet search stays at "Load spectra" for many hours until I cancel it. I checked the folders for the Tide search, and I couldn't find anything strange about the writing permissions. I can send you a link to the mgf file if you think it might help/if you have time. Would it be possible to email the link directly to you?

Perhaps it would better if you contacted the Tide and/or Comet developers directly? As there is not much we can do on our end if these search engines have problems with your mgf file. For Comet use https://groups.google.com/forum/#!forum/comet-ms, and Tide use https://groups.google.com/forum/#!forum/crux-users.

> Returning to the issues with PeptideShaker. On PC, I got a message about certain proteins not being in the cache when I tried to combine results from more than one search engine. This happens at/after "Saving probabilities, building peptides and proteins." Could this mean that the computer has insufficient memory for the analysis? 

This should work independent of the available memory, and the error message does not seem to indicate that you are running out of memory. Rather that the object is not in the cache where it ought to be. I will need to look more into this one and get back to you. Never seen this particular error before I think.

> And what does "_cus_" mean between the names?

It is just our way of separating the individual protein identifiers.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Lizahn,

As I didn't hear back from you in a while I will assume that you managed to solve the above issues? If this is not the case please let us know by opening a new issue describing the remaining problems.

Best regards,
Harald
