### ISSUE TITLE
IdentificationParametersInputBean.java  -ptm_score  option 

### ISSUE THREAD

**Issue by jj-umn** [compomics/peptide-shaker#159]
Should -ptm_score be setting PTMScoringPreferences selectedProbabilisticScore
rather than SequenceMatchingPreferences sequenceMatchingType

diff --git a/src/main/java/com/compomics/util/experiment/identification/parameters_cli/IdentificationParametersInputBean.java b/src/main/java/com/compomics/util/experiment/identification/parameters_cli/IdentificationParametersInputBean.java
index 7ba8ea1..85a1381 100644
--- a/src/main/java/com/compomics/util/experiment/identification/parameters_cli/IdentificationParametersInputBean.java
+++ b/src/main/java/com/compomics/util/experiment/identification/parameters_cli/IdentificationParametersInputBean.java
@@ -1535,8 +1535,7 @@ public class IdentificationParametersInputBean {
         if (commandLine.hasOption(IdentificationParametersCLIParams.PTM_SCORE.id)) {
             String arg = commandLine.getOptionValue(IdentificationParametersCLIParams.PTM_SCORE.id);
             Integer intValue = new Integer(arg);
-            SequenceMatchingPreferences.MatchingType value = SequenceMatchingPreferences.MatchingType.getMatchingType(intValue);
-            sequenceMatchingPreferences.setSequenceMatchingType(value);
+            ptmScoringPreferences.setSelectedProbabilisticScore(PtmScore.getScore(intValue));^M
         }
         if (commandLine.hasOption(IdentificationParametersCLIParams.PTM_THRESHOLD.id)) {
             String arg = commandLine.getOptionValue(IdentificationParametersCLIParams.PTM_THRESHOLD.id);

**Comment by mvaudel** [comment]
Dear JJ,

You are correct again, sorry that you are encountering so many issues. Do you agree with the following fix?
https://github.com/compomics/compomics-utilities/commit/82677e98ccd2eead92d0095ca6bb7072da621f0b

Running some tests now and hopefully it will make it to the release later today.

Best regards and sorry again for these,

Marc

**Comment by jj-umn** [comment]
Looks good.  Thanks.

**Comment by mvaudel** [comment]
Works on my side and should make it to the new release tonight :)

**Comment by hbarsnes** [comment]
Made it into the new release, hence the closing of the issue. :)
