### ISSUE TITLE
TCGA protein accessions can result in mzIdentML being invalid XML

### ISSUE THREAD

**Issue by jj-umn** [compomics/peptide-shaker#161]
The TCGA cancer archive site has protein accessions in the fasta IDs that specify the nucleotide variant:
For example:
>NP_008982_959:G>GT |NM_007051|FAF1|FAS-associated factor 1|

**Comment by jj-umn** [comment]
The TCGA cancer archive site has protein accessions in the fasta IDs that specify the nucleotide variant:
For example:
   > NP_008982_959:G>GT |NM_007051|FAF1|FAS-associated factor 1|

Which we converted for Search GUI:
  >generic|NP_008982_959:G>GT|NM_007051|FAF1|FAS-associated factor 1|

The resulting PeptideShaker mzIdentML is invalid XML containing elements:
  <DBSequence id="NP_008982_959:G>GT" accession="NP_008982_959:G>GT" searchDatabase_ref="SearchDB_1" >
  <DBSequence id="NP_008982_959:G>GT_REVERSED" accession="NP_008982_959:G>GT_REVERSED" searchDatabase_ref="SearchDB_1" >

The valid XML should be:

    <DBSequence id="NP_008982_959:G&gt;GT" accession="NP_008982_959:G&gt;GT" searchDatabase_ref="SearchDB_1" >
    <DBSequence id="NP_008982_959:G&gt;GT_REVERSED" accession="NP_008982_959:G&gt;GT_REVERSED" searchDatabase_ref="SearchDB_1" > 

We are currently altering the accessions replacing '>' with '_', but that makes subsequent processing difficult.

**Comment by hbarsnes** [comment]
Thanks for reporting this. Fix pushed. We'll release a new version as soon as possible.

**Comment by hbarsnes** [comment]
A new version has just been released which should fix the problem. If this is not the case, please let us know and we'll reopen the issue.
