### ISSUE TITLE
Certificate of Analysis Report  "Number of Missed Cleavages: Not implemented"

### ISSUE THREAD

**Issue by jj-umn** [compomics/peptide-shaker#162]
User assumed that the -mc parameter was not used during search.
Should the   Certificate of Analysis Report print the parameter setting?

$ git diff src/main/java/eu/isas/peptideshaker/export/sections/PsSearchParametersSection.java
diff --git a/src/main/java/eu/isas/peptideshaker/export/sections/PsSearchParametersSection.java b/src/main/java/eu/isas/peptideshaker/export/sections/PsSearchParametersSection.java
index 8ae4e24..89c602a 100644
--- a/src/main/java/eu/isas/peptideshaker/export/sections/PsSearchParametersSection.java
+++ b/src/main/java/eu/isas/peptideshaker/export/sections/PsSearchParametersSection.java
@@ -160,6 +160,9 @@ public class PsSearchParametersSection {
                     ionName = PeptideFragmentIon.getSubTypeAsString(searchParameters.getIonSearched2());
                     writer.write(ionName);
                     break;
+                case mc:^M
+                    writer.write(searchParameters.getnMissedCleavages().toString());^M
+                    break;^M
                 default:
                     writer.write("Not implemented");
             }

**Comment by hbarsnes** [comment]
Thanks again. Will be included in the next release. Should be available tomorrow.

**Comment by hbarsnes** [comment]
A new version with the maximum missed cleavages added to the certificate of analysis has just been released.
