### ISSUE TITLE
Search GUI and Peptide Shaker option

### ISSUE THREAD

**Issue by im281** [compomics/peptide-shaker#166]
Can you run Search GUI using the command line and give it an option to create the Peptide Shaker file as you can when you run SearchGUI using the GUI?

**Comment by mvaudel** [comment]
Hi,

Yes, you can run SearchGUI in command line, but then you have to run another command line for PeptideShaker. We did our best to make the PeptideShaker command line on SearchGUI results as simple as possible. To streamline the process we recommend to use the -zip packaging option and the -temp_folder to handle the temporary files. All command line options are documented in our wikis:
https://github.com/compomics/searchgui/wiki/SearchCLI
https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI

Hope this helps, don't hesitate to contact us again if you encounter problems with the setting up of command lines.

Marc

**Comment by im281** [comment]
Thank you ! This is excellent!

**Comment by mvaudel** [comment]
Great to read that it helped, if you agree I will close the issue, don't hesitate to contact us if you encounter any other problem.

Marc
