### ISSUE TITLE
Peptide shaker file missing. Help Needed!!

### ISSUE THREAD

**Issue by rlshah** [compomics/peptide-shaker#167]
Hello,
I have tried running on search GUI first the files from Bruker using the file converter. The output file for peptide shaker doe not open automatically in peptide shaker interface. Can anyone help me in solving this problem.
Error message : peptide shaker .cpsx file missing 
![1](https://cloud.githubusercontent.com/assets/19322815/15208720/6996fbd6-182d-11e6-90e9-15166197e0b5.JPG)

**Comment by hbarsnes** [comment]
Hi,

Thanks for telling us about this. How did you load the data in PeptideShaker? You have to use the "New Project" option in the PeptideShaker Welcome Dialog when loading data from SearchGUI. Your error seems to indicate that you used the "Open Project" option instead?

Best regards,
Harald

**Comment by rlshah** [comment]
Dear Herald,
Thank you very much for the suggestion. I was trying with open project, but now according to your suggestion started with new project option and that worked out.

2. Can we use this software for label free quantitation or absolute quantitation via AQUA peptide


Regards,

Rohan Shah

PhD Student
Prof.Dr. Nikolai Kuhnert work Group.
Jacobs University Bremen gGmbH
Department of Life science and Chemistry.
Campus Ring 1 | 28759 Bremen | Germany
Phone: +49 421 200 3680.



________________________________________

**Comment by rlshah** [comment]
Dear Herald,
Thank you very much for the suggestion. I was trying with open project, but now according to your suggestion started with new project option and that worked out.

2. Can we use this software for label free quantitation or absolute quantitation via AQUA peptide

**Comment by hbarsnes** [comment]
Hi, 

> Can we use this software for label free quantitation or absolute quantitation via AQUA peptide

No, I'm afraid not. For label free quantification I'd recommend MaxQuant. I have no experience with absolute quantitation via AQUA so I cannot recommend any software there.

I'm now closing this issue, but please feel free to open a new one if you have other questions.

Best regards,
Harald
