### ISSUE TITLE
Error when unzipping SearchGUI results zip file

### ISSUE THREAD

**Issue by cdlawless** [compomics/peptide-shaker#168]
Hi Guys

Just started to get this error when running PeptideShaker-1.10.2, though get the same with 1.9.0 and 1.8.1. 
java.util.zip.ZipException: invalid entry size (expected 2251885780355920 but got 5443011737 bytes)
    at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:384)
    at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
    at com.compomics.util.io.compression.ZipUtils.unzip(ZipUtils.java:280)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:537)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:205)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:908)
java.lang.NullPointerException
    at eu.isas.peptideshaker.utils.CpsParent.saveProject(CpsParent.java:311)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:229)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:908)
java.lang.NullPointerException
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:361)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:908)

Command is:
java -Xms1024m -Xmx262144m -cp /mnt/lustre/mjfidcl2/PeptideShaker-1.10.2/PeptideShaker-1.10.2.jar  eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment MDV3_MSGF_5 -sample MDV3_MSGF_5_sample -replicate
 1 -identification_files "/mnt/lustre/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/searchGUI_zips/searchgui_MSGF_5ppm_MDV3.zip" -out "/mnt/lustre/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/PS_Projects/MDV3_MSGF_5.
cpsx" -ptm_score 1 -zip "/mnt/lustre/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/PS_zips/MDV3_MSGF_5.zip" -temp_folder "/mnt/lustre/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/temp"

The searchGUI zip file was produced using searchGUI 2.8.6 with the command:
java -Xms4096M -Xmx131072M -cp /mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.8.6/SearchGUI-2.8.6.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "/mnt/lustre/scratch/mjfidcl2/DDIP/FDR_Comp
arison/Qex_merged.mgf" -output_folder /mnt/lustre/scratch/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/temp_10_msgf/ -id_params /mnt/lustre/scratch/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/Qex_merged_MDV3_msgf_1
0.par -output_option 0 -output_data 1 -mgf_splitting 2000 -temp_folder /mnt/lustre/scratch/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/temp_10_msgf/ -xtandem 0 -msgf 1 -omssa 0 -myrimatch 0 -comet 0 -tide 0 -
ms_amanda 0 -andromeda 0 -msgf_folder /mnt/lustre/scratch/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/temp_10_msgf/

Tried re-running everything again and get the same error.

Thanks

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

That is very strange. It seems like PeptideShaker does not manage to unzip "searchgui_MSGF_5ppm_MDV3.zip". Could you try unzipping the file manually to ensure that the zip file is not corrupt? If the file is not corrupt it would be great if you could make the zip file available to use so that we can try to reproduce the problem on our side?

Best regards,
Harald

**Comment by cdlawless** [comment]
Hi Harald

Just checked, it unzips fine. Here is a link to the search zip file:
https://www.dropbox.com/s/147kjwr6i73mw27/searchgui_MSGF_5ppm_MDV3.zip?dl=0

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

Thanks for the file. We'll see what we can find out. Part of the unzipping code is using a separate standard library though, so not sure how easy it will be to solve. Does it only happen with this specific input btw? As we've not seen this problem for other zip files.

Best regards,
Harald

**Comment by cdlawless** [comment]
Yes, it happens to this one and another one run at 10ppm precursor 
error. If run with COMET alone it works fine, so unsure why it happens 
to this one.

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

How did you manually unzip the file? If I try with 7zip I get an error saying that the msgf+ mzid file is corrupt.

It could be a size issue somehow? Is the other file where this also happens quite big as well?

Best regards,
Harald

**Comment by cdlawless** [comment]
Hi Harald (apologies, I've been away)

I just used the zip program available on linux distributions, i.e unzip <filename>. 

I submitted it as a job on our HPC setup. The other file is pretty big also.

Regards

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

And there were no issues or error messages when zipping I assume?

I guess it could be related to the size of the identification file, perhaps we need to move to gzip instead of zip. However, an error ought to be thrown when creating the zip file if this was the case?

Another option is that it's a 32 bit vs. 64 bit issue. But I assume you're using 64 bit on your HCP setup?

And sorry if I asked this already, but does the same happen if you redo the PeptideShaker command line? I.e. does it always happen or is it random (for the same input)?

Best regards,
Harald

**Comment by cdlawless** [comment]
Hi Harald

I've tried unzipping and no errors occur during unzipping, however, when 
I try running PeptideShaker on the manually unzipped file, I get errors 
saying cannot create peptide shaker project.

I have run SearchGUI with output option 3 (no zipping) and PeptideShaker 
runs fine on that output. However, this means I have to run SearchGUI & 
PeptideShaker on the same HPC (which I have not been doing in the past). 
Everything is 64bit.

The zipping problem only occurs with MSGF against this fasta database 
for spectra acquired here. If I run COMET with the same parameters, I 
get no errors.

Regards

Craig

On 19/05/2016 12:54, Harald Barsnes wrote:
>
> Hi Craig,
>
> And there were no issues or error messages when zipping I assume?
>
> I guess it could be related to the size of the identification file, 
> perhaps we need to move to gzip instead of zip. However, an error 
> ought to be thrown when creating the zip file if this was the case?
>
> Another option is that it's a 32 bit vs. 64 bit issue. But I assume 
> you're using 64 bit on your HCP setup?
>
> And sorry if I asked this already, but does the same happen if you 
> redo the PeptideShaker command line? I.e. does it always happen or is 
> it random (for the same input)?
>
> Best regards,
> Harald
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/compomics/peptide-shaker/issues/168#issuecomment-220302734>
>

-- 
Craig Lawless
--------------------------------------------
Post-Doctoral Research Associate
Faculty of Life Sciences
University of Manchester
Manchester
M13 9PT

**Comment by hbarsnes** [comment]
Hi Craig,

> I've tried unzipping and no errors occur during unzipping, however, when I try running PeptideShaker on the manually unzipped file, I get errors saying cannot create peptide shaker project.

What sort of errors? Is it complaining about the MSGF+ file? If so, it could be that the file is still corrupt even though the unzipping software does not tell you. On my side I only got the error after the unzipping was done and all the files seemed to be unzipped.

> The zipping problem only occurs with MSGF against this fasta database for spectra acquired here. If I run COMET with the same parameters, I get no errors.

Yes, but the Comet output is (much) smaller right? I'm still leaning towards a zip file issue here. Will investigate more and get back to you.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
