### ISSUE TITLE
mzIdentML Peptide element missing

### ISSUE THREAD

**Issue by jj-umn** [compomics/peptide-shaker#172]
I can attempt to either find the problem or I provide the data to reproduce the issue, but here's the quick synopsis:

I ran across this issue reading the PeptideShaker (v1.10.2) mzIdentML with uk.ac.ebi.JmzIdentMLParser:

2016-05-17 16:22:38,890 ERROR RawXMLListener - Error trying to instantiate
reference resolver:
uk.ac.ebi.jmzidml.xml.jaxb.resolver.SpectrumIdentificationItemRefResolver
java.lang.IllegalStateException: Could not unmarshall refId:
IMGIPEDEQMGIIR_15.99491461956-ATAA-2 for element type: class
uk.ac.ebi.jmzidml.model.mzidml.Peptide
at
uk.ac.ebi.jmzidml.xml.jaxb.resolver.AbstractReferenceResolver.unmarshal(AbstractReferenceResolver.java:106)

A quick check of the file mzid file indicates that there isn't a Peptide element for the single modification: 
"IMGIPEDEQMGIIR_15.99491461956-ATAA-2"  

grep -n 'IMGIPEDEQMGIIR' peptideAhaker.mzid
835287:         <Peptide id="IMGIPEDEQMGIIR_15.99491461956">
1283658:                <Peptide id="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2">
1606322:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_199554" />
1608661:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956" dBSequence_ref="Q8VDD5" id="PepEv_201893" />
1613393:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_206625" />
1616829:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_210061" />
1625048:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_218280" />
5753689:                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" calculatedMassToCharge="889.450872015192" experimentalMassToCharge="889.452576" chargeState="2" id="SII_60397_1">
5798433:                                        <SpectrumIdentificationItem passThreshold="false" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956" calculatedMassToCharge="587.9713686258787" experimentalMassToCharge="587.97229" chargeState="3" id="SII_61181_1">
5895010:                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" calculatedMassToCharge="889.450872015192" experimentalMassToCharge="889.45282" chargeState="2" id="SII_62886_1">
5958747:                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" calculatedMassToCharge="593.3030068323986" experimentalMassToCharge="593.303955" chargeState="3" id="SII_64014_1">
6112333:                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-2" calculatedMassToCharge="881.453414705412" experimentalMassToCharge="881.4552" chargeState="2" id="SII_66756_1">

**Comment by jj-umn** [comment]
Here is the result of grep:
% grep  'IMGIPEDEQMGIIR' peptideAhaker.mzid      
          <Peptide id="IMGIPEDEQMGIIR_15.99491461956">
                <Peptide id="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2">
                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_199554" />
                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956" dBSequence_ref="Q8VDD5" id="PepEv_201893" />
                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_206625" />
                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_210061" />
                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_218280" />
                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" calculatedMassToCharge="889.450872015192" experimentalMassToCharge="889.452576" chargeState="2" id="SII_60397_1">
                                        <SpectrumIdentificationItem passThreshold="false" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956" calculatedMassToCharge="587.9713686258787" experimentalMassToCharge="587.97229" chargeState="3" id="SII_61181_1">
                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" calculatedMassToCharge="889.450872015192" experimentalMassToCharge="889.45282" chargeState="2" id="SII_62886_1">
                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" calculatedMassToCharge="593.3030068323986" experimentalMassToCharge="593.303955" chargeState="3" id="SII_64014_1">
                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-2" calculatedMassToCharge="881.453414705412" experimentalMassToCharge="881.4552" chargeState="2" id="SII_66756_1">

**Comment by jj-umn** [comment]
`835287:         <Peptide id="IMGIPEDEQMGIIR_15.99491461956">
1283658:                <Peptide id="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2">
1606322:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_199554" />
1608661:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956" dBSequence_ref="Q8VDD5" id="PepEv_201893" />
1613393:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_206625" />
1616829:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_210061" />
1625048:                <PeptideEvidence isDecoy="false" pre="R" post="V" start="328" end="341" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-2" dBSequence_ref="Q8VDD5" id="PepEv_218280" />
5753689:                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" calculatedMassToCharge="889.450872015192" experimentalMassToCharge="889.452576" chargeState="2" id="SII_60397_1">
5798433:                                        <SpectrumIdentificationItem passThreshold="false" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956" calculatedMassToCharge="587.9713686258787" experimentalMassToCharge="587.97229" chargeState="3" id="SII_61181_1">
5895010:                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" calculatedMassToCharge="889.450872015192" experimentalMassToCharge="889.45282" chargeState="2" id="SII_62886_1">
5958747:                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-10_15.99491461956-ATAA-2" calculatedMassToCharge="593.3030068323986" experimentalMassToCharge="593.303955" chargeState="3" id="SII_64014_1">
6112333:                                        <SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="IMGIPEDEQMGIIR_15.99491461956-ATAA-2" calculatedMassToCharge="881.453414705412" experimentalMassToCharge="881.4552" chargeState="2" id="SII_66756_1">
`

**Comment by jj-umn** [comment]
Link to PeptideShaker.mzid:
https://drive.google.com/file/d/0B5gotQcSckTmVlVvWFpBTlNqZXM/view?usp=sharing
Link to Galaxy PeptideShaker command script:
https://drive.google.com/file/d/0B5gotQcSckTma195VzZuRXl0cm8/view?usp=sharing
Link to SearchGUI archive:
https://drive.google.com/file/d/0B5gotQcSckTmOWlfZU5fY2Jha0E/view?usp=sharing

**Comment by hbarsnes** [comment]
Thanks for telling us about this. Could you also share the zipped PeptideShaker project?

**Comment by jj-umn** [comment]
Sure.  I'll have to rerun to save the PeptideShaker zip so will probably be a few hours.

**Comment by jj-umn** [comment]
Link to PeptideShaker zip
https://drive.google.com/file/d/0B5gotQcSckTmajZEX0NZbkdGa00/view?usp=sharing

**Comment by hbarsnes** [comment]
Thanks for the PeptideShaker zip. It turns out that we have an issue with the peptide keys due to the modification location confidence.

In your example the peptide IMGIPEDEQMGIIR is found twice carrying a single oxidation (i.e. two separate PSMs), once with a confidently assigned location and once with a not confidently assigned location. And in the end the peptide retained is the one with the not confidently assigned location. Which means that the peptide key will be IMGIPEDEQMGIIR_15.99491461956 and not IMGIPEDEQMGIIR_15.99491461956-ATAA-2 (the last part indicating the location of the PTM). Thus the mapping breaks when we try to map the PSM with the confidently assigned location, as it assumes that the peptide key IMGIPEDEQMGIIR_15.99491461956-ATAA-2 exists.

We'll try to come up with a fix and release a new version as soon as possible.

**Comment by jj-umn** [comment]
Thanks.  That's what I suspected.

**Comment by hbarsnes** [comment]
Here's a beta version of PeptideShaker that should solve the problem: https://www.dropbox.com/s/6xcc81dk9hw7rh0/PeptideShaker-1.10.4-beta.zip?dl=0

Let us know if you still experience any issues.

We'll most likely release the proper new version next week. Just have some other issues to finish up first.

**Comment by hbarsnes** [comment]
Issue should be fixed in the just released PeptideShaker v1.11.0. If this is not the case, please let us know and we'll reopen the issue.
