### ISSUE TITLE
Comparison of triplicate samples

### ISSUE THREAD

**Issue by uhaifabioinfo** [compomics/peptide-shaker#173]
Hi - 
I'm trying to look at triplicate samples, especially to use only proteins observable in all 3 samples. Is there a way to view protein ID's for each sample separately - allowing for different columns for each sample (like they do in ProteomeDiscoverer)? I'm mainly insterested in PSMs, unique peptides and quantitative values, which seem to be summed.

Thanks!
David.

**Comment by hbarsnes** [comment]
Hi David,

At the moment this is not supported in PeptideShaker. We are working towards this though, but it will take some time. For the time being your best option is to process the samples separately, export the wanted data and then do the follow up analysis outside of PeptideShaker.

Best regards,
Harald

**Comment by uhaifabioinfo** [comment]
Thanks!

**Comment by hbarsnes** [comment]
Merged into https://github.com/compomics/peptide-shaker/issues/139.
