### ISSUE TITLE
Error importing gene mappings

### ISSUE THREAD

**Issue by cdlawless** [compomics/peptide-shaker#177]
Hi, 

Getting another error now when running PeptideShaker 1.10.3. 

Runnning myrimatch only through SearchGUI:

java -Xms1024M -Xmx4096M -cp /mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.8.6/SearchGUI-2.8.6.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out /mnt/fls01-home01/mjfidcl2/scratch/DDI
P/FDR_Comparison/SearchGUI/Searches/Qex_merged_MDV3_myrimatch_10.par -fixed_mods "Carbamidomethylation of C" -variable_mods "Oxidation of M, Acetylation of protein N-term" -db /mnt/fls01-home01/mjfidcl2/
scratch/DDIP/FDR_Comparison/SearchGUI/Searches/slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta -prec_tol 10 -frag_tol 0.5 -enzyme "Trypsin" -mc 2 

java -Xms4096M -Xmx131072M -cp /mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.8.6/SearchGUI-2.8.6.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "/mnt/fls01-home01/mjfidcl2/scratch/DDIP/FD
R_Comparison/SearchGUI/Searches/Qex_merged.mgf" -output_folder /mnt/fls01-home01/mjfidcl2/scratch/DDIP/FDR_Comparison/SearchGUI/Searches/temp_10_myrimatch_MDV3/ -id_params /mnt/fls01-home01/mjfidcl2/scra
tch/DDIP/FDR_Comparison/SearchGUI/Searches/Qex_merged_MDV3_myrimatch_10.par -output_option 3 -mgf_splitting 2000 -temp_folder /mnt/fls01-home01/mjfidcl2/scratch/DDIP/FDR_Comparison/SearchGUI/Searches/tem
p_10_myrimatch_MDV3/ -xtandem 0 -msgf 0 -omssa 0 -myrimatch 1 -comet 0 -tide 0 -ms_amanda 0 -andromeda 0 -myrimatch_folder /mnt/fls01-home01/mjfidcl2/scratch/DDIP/FDR_Comparison/SearchGUI/Searches/temp_1
0_myrimatch_MDV3/ 

then PeptideShaker:
java -Xms1024m -Xmx262144m -cp /mnt/lustre/mjfidcl2/PeptideShaker-1.10.2/PeptideShaker-1.10.2.jar  eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment MDV3_Myrimatch_10_nozip -sample MDV3_Myrimatch_10
nozip_sample -replicate 1 -identification_files "/mnt/fls01-home01/mjfidcl2/scratch/DDIP/FDR_Comparison/SearchGUI/Searches/temp_10_myrimatch_MDV3/Qex_merged.myrimatch.mzid" -out "/mnt/fls01-home01/mjfidc
l2/scratch/DDIP/FDR_Comparison/SearchGUI/PS_Projects/MDV3_Myrimatch_10_nozip.cpsx" -spectrum_files "/mnt/fls01-home01/mjfidcl2/scratch/DDIP/FDR_Comparison/SearchGUI/Searches/Qex_merged.mgf" -id_params "/
mnt/fls01-home01/mjfidcl2/scratch/DDIP/FDR_Comparison/SearchGUI/Searches/Qex_merged_MDV3_myrimatch_10.par" -ptm_score 1 -zip "/mnt/lustre/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/PS_zips/MDV3_Myrimatch_10_
nozip.zip" -temp_folder "/mnt/lustre/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/temp"

I get the output:
Path configuration completed.
Fri Jun 03 15:43:12 BST 2016 Import process for MDV3_Myrimatch_10_nozip (Sample: MDV3_Myrimatch_10nozip_sample, Replicate: 1)

Fri Jun 03 15:43:12 BST 2016 Importing sequences from slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta.
Fri Jun 03 15:43:15 BST 2016 Estimated import time: 12 minutes.
Fri Jun 03 15:43:15 BST 2016     See http://compomics.github.io/compomics-utilities/wiki/proteininference.html.
10% 20% 30% 40% 50% 60% 70% 80%
Fri Jun 03 15:55:54 BST 2016 FASTA file import completed.
Fri Jun 03 15:55:54 BST 2016 Importing gene mappings.
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
Fri Jun 03 15:55:54 BST 2016 An error occurred while loading the identification files.
Fri Jun 03 15:55:54 BST 2016 Please see the error log (Help Menu > Bug Report) for details.
Fri Jun 03 15:55:54 BST 2016 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>
 
and error:
java.lang.NullPointerException
	at java.util.HashMap.<init>(HashMap.java:294)
	at com.compomics.util.experiment.biology.genes.GeneFactory.getGeneMaps(GeneFactory.java:214)
	at eu.isas.peptideshaker.fileimport.FileImporter.importGenes(FileImporter.java:277)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:458)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:156)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:696)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:205)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:908)

I can provide the files if needed.

**Comment by hbarsnes** [comment]
Hi Craig,

Could you rerun the PeptideShaker command line with this new beta version? https://www.dropbox.com/s/6xcc81dk9hw7rh0/PeptideShaker-1.10.4-beta.zip?dl=0

As we've made some minor changes resulting in the line numbers not being the same in our code as in the exception above. Which makes it a bit hard to debug. ;)

Best regards,
Harald

**Comment by cdlawless** [comment]
Hi Harald

I don't get the error with the 1.10.4-beta version. I tried again with 
the 1.10.3 and still got the same errors I did last time, so it appears 
it has been fixed in this version.

Regards

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

If only all bugs were that easy to fix. ;)

We'll release the new version later this week. Hopefully it will not reappear in the proper release.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Craig,

Just released PeptideShaker v.1.11.0 which should then hopefully then fix the problem. Let me know if it reappears and then we'll reopen the issue.

Best regards,
Harald
