### ISSUE TITLE
Duplicate fragment ion lines in reports

### ISSUE THREAD

**Issue by kverhegg** [compomics/peptide-shaker#180]
When exporting fragment ion identification features, such as the peak annotation / peak intensity etc, the lines appear duplicated in the report (ergo, every spectrum has the same fragment ion annotation). Aside from that, there is a lineseparator missing when using multiple sections.

I've added my user preferences in attachment !

Cheers,

Kenneth

**Comment by kverhegg** [comment]
Actually, it won't let me upload them as zip...I can provide them though :)

**Comment by mvaudel** [comment]
Hi Kenneth,

Thank you for reporting this. Can you send me the specifications of the report you are creating so that I can reproduce the bug?

When I export the fragment ions for every PSM things seem to work fine, this is what I get:

```
	Protein(s)	Sequence	Spectrum Title
1	O95456	AATFFGEVVK	qExactive01819.10418.10418.2 File:"qExactive01819.raw", NativeID:"controllerType=0 controllerNumber=1 scan=10418"
	Peak Annotation	Type	Subtype	Number	m/z	Intensity
1.1	iF	Immonium ion	Immonium F		120.0808411	14483.125	
1.2	y1	Peptide fragment ion	y	1	147.1127625	5991.3251953125	
1.3	b2	Peptide fragment ion	b	2	185.0919952	9834.7421875	
1.4	y2	Peptide fragment ion	y	2	246.1810608	5155.31640625	
1.5	b3-H2O	Peptide fragment ion	b	3	268.1288147	12310.8095703125	
1.6	b3	Peptide fragment ion	b	3	286.1390686	8135.5971679688	
1.7	b4-H2O	Peptide fragment ion	b	4	415.1979675	5884.296875	
1.8	b4	Peptide fragment ion	b	4	433.2084351	6020.33203125	
1.9	y5	Peptide fragment ion	y	5	531.3149414	11122.650390625	
1.10	y6	Peptide fragment ion	y	6	678.3822021	19193.193359375	
1.11	y7	Peptide fragment ion	y	7	825.4490356	12635.595703125	
1.12	y8	Peptide fragment ion	y	8	926.4985352	3338.2199707031	
```

and I see no duplication between spectra?

Thanks for your help,

Marc

**Comment by hbarsnes** [comment]
(Fixed in a previous release, we just forgot to close the issue.)
