### ISSUE TITLE
Custom exports: Typo in the documentation for the Validation terms at the peptide and PSM level

### ISSUE THREAD

**Issue by cdlawless** [compomics/peptide-shaker#181]
Hi Guys, 

Just a quick suggestion (unless it's already there and I have missed it). When you create a custom (psm or peptide) report, there is no column available to say whether the psm (or peptide) is validated/doubtful/not validated. There is only a column for displaying whether the protein group is validated. Is there a way to do this already?

Kind Regards

Craig

**Comment by hbarsnes** [comment]
H Craig,

Seems to be a copy-paste error in the documentation. The 'Peptide Identification Summary' term 'Validation' **does** refer to the peptide validation and **not** the protein validation. And the same for the related PSM term.

So if you just ignore the documentation and use the Validation terms at the right level you will get the correct validation information. :)

We'll correct it in the next release.

Best regards,
Harald

**Comment by cdlawless** [comment]
I thought this might be the case :)

Thank you


Craig Lawless
---------------------------------------
Postdoctoral Research Associate
Faculty of Life Sciences
Rm B.1071 Michael-Smith
Oxford Road
Manchester
M13 9PT
TEL:(+44)0161 275 1680
--------------------------------------

________________________________

**Comment by hbarsnes** [comment]
Ho Craig,

PeptideShaker v1.12.0 has now been released where the export documentation has been corrected.

Best regards,
Harald
