### ISSUE TITLE
Database, or other problem?

### ISSUE THREAD

**Issue by helenbayram** [compomics/peptide-shaker#183]
Hello,

I am trying to run searchGUI using an in house produced database for a non-model organism. It is formatted as recommended within the "database help" page. Whenever I run the search it fails as soon as the results are being imported into peptide shaker. Previously the searches and peptide shaker have worked fine using a standard Uniprot database for a closely related species. So I tried the search with the uniprot database again, and am having the same problems.  The peptide shaker report gives the following:

Mon Jun 13 12:35:28 CEST 2016        Unzipping searchgui_out.zip.
Mon Jun 13 12:35:30 CEST 2016        Import process for test4 (Sample: 28, Replicate: 0)

Mon Jun 13 12:35:30 CEST 2016        Importing sequences from uniprot-proteome%3AUP000007266_concatenated_target_decoy.fasta.
Mon Jun 13 12:35:49 CEST 2016        FASTA file import completed.
Mon Jun 13 12:35:49 CEST 2016        Importing gene mappings.
Mon Jun 13 12:35:50 CEST 2016        Establishing local database connection.
Mon Jun 13 12:35:54 CEST 2016        Reading identification files.
Mon Jun 13 12:35:54 CEST 2016        Parsing MS-15-051c-28.msgf.mzid.
Mon Jun 13 12:36:02 CEST 2016        Loading spectra for MS-15-051c-28.msgf.mzid.
Mon Jun 13 12:36:02 CEST 2016        Importing MS-15-051c-28.mgf
Mon Jun 13 12:36:02 CEST 2016        MS-15-051c-28.mgf imported.
Mon Jun 13 12:36:02 CEST 2016        Collecting peptides to map.
Mon Jun 13 12:36:02 CEST 2016        Mapping peptides to proteins.
Mon Jun 13 12:36:02 CEST 2016        An error occurred: PeptideShaker could not access the FASTA index databse. Please make sure that no other instance of PeptideShaker is running. If the problem persists, restart your computer.

Mon Jun 13 12:36:02 CEST 2016        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).
Mon Jun 13 12:36:02 CEST 2016        Importing PSMs from MS-15-051c-28.msgf.mzid
Mon Jun 13 12:36:02 CEST 2016        An error occurred: No current connection.
Mon Jun 13 12:36:02 CEST 2016        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Mon Jun 13 12:36:02 CEST 2016        Importing Data Canceled!

Is there something simple I am doing wrong? (there are no other instances of PeptideShaker running, I have tried the restart)

Many thanks,
Helen

**Comment by hbarsnes** [comment]
Hi Helen,

Thanks for telling us about this. Could you send us your PeptideShaker log file? You can find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report. It should tell us a bit more about what is going on.

Best regards,
Harald

**Comment by helenbayram** [comment]
Hi Harald,

Yes of course. Is this it?

[PeptideShaker 1.11.0 log.txt](https://github.com/compomics/peptide-shaker/files/311667/PeptideShaker.1.11.0.log.txt)

Many thanks, 
Helen

**Comment by mvaudel** [comment]
Hi Helen,

Many thanks for the log. It seems that the tool cannot access the index of the database. If PeptideShaker (eventually an earlier version) was working on this computer before can you try to restart the computer? 

Also, is there anything special with this computer in terms of installation, disc mapping, or user restrictions? If yes, please click _Settings & Help_ at tool startup, then _Settings_ and _Resource Settings_. In this table make sure that all files are located in folders where you have read and write permissions, preferentially on quick discs like SSD, and not mapped to a network drive. If this is not the case, you can move all these files to a single folder by right-clicking the table and then _Set Default Path_ to a path of your choice.

Finally, when creating the project, please click _Edit_ in front of _Identification_ in the _Project Settings_ panel. Then, click _Show Advanced Settings_, and under _Sequence Matching_ select _**FM-Index**_ as _Index type_. That should get around the problem and be much faster.

Hope this helps,

Marc

**Comment by helenbayram** [comment]
Hi, 

That was all really helpful thank you! Changing Index type to FM-Index did the trick for the Uniprot database. I'm still having problems with the in house database searching though. I think it is set up inline with the suggestions on the SearchGUI readme documentation (although this link isn't currently working). It seems like the search completes and then it fails when importing to peptide shaker. I've attached the log and the first few seq's of the database. If you have time to see if there's anything obviously wrong then that'd be really helpful! (NB: Only .txt here as can't upload .fasta)

[CmacTest.txt](https://github.com/compomics/peptide-shaker/files/313706/CmacTest.txt)

[PeptideShaker 1.11.0 log2.txt](https://github.com/compomics/peptide-shaker/files/313700/PeptideShaker.1.11.0.log2.txt)

Many thanks,
Helen

**Comment by ulrich-eckhard** [comment]
did you check the decoydatabase (fasta-file) created by SearchGUI in a text
editor?

i had recently a problem where the header of one or more of my entries got
translated the wrong way somehow. SearchGUI still finished without
problems, but PeptideShaker had problems with the import (but completely
different Error messages though). Maybe worth a check and something obvious
is going wrong. something obvious to Marc and Harald, not necessarily me!
:-)

**Comment by helenbayram** [comment]
Thanks for your suggestion! I can't see any problems with the headers in the decoy database file, so probably something else in this instance...

**Comment by ulrich-eckhard** [comment]
in my case it was something totally odd - but don't fully recall anymore.
but just one of the REVERSE tags or so got missplaced I think. After fixing
that, it worked.

will try to figure out what I changed (but I tried to mimic UniProt format
though).

**Comment by hbarsnes** [comment]
Hi Helen,

Please remove the * at the end of your sequences. I think that should solve the problem.

Best regards,
Harald

**Comment by helenbayram** [comment]
Hi Harald,

I think this has solved it! Great!! Thank you so much,

Best wishes,
Helen

**Comment by hbarsnes** [comment]
Hi Helen,

Great! Don't hesitate to open a new issue if you come across other problems. :)

Best regards,
Harald
