### ISSUE TITLE
Some IdentificationParmetersCLI parameters and expected options are different from documentation

### ISSUE THREAD

**Issue by Thys3Potgieter** [compomics/peptide-shaker#186]
Hi Guys, im sure that this rather a documentation issue and not a bug.

$ java -cp PeptideShaker-1.11.0.jar eu.isas.peptideshaker.cmd.IdentificationParametersCLI 
-sequence_matching_type '2'  -out /home/user/example

Gives:
Error parsing the sequence_matching_type option: Found 2. Supported input: [Protein, Peptide, Spectrum, Ion, PTM].
Run -usage to see the list of supported options and their input.

But the documentatation (http://compomics.github.io/compomics-utilities/wiki/identificationparameterscli.html):

-sequence_matching_type   The peptide to protein sequence matching type. Default is 2.
                          0: Character Sequence
                          1: Amino Acids
                          2: Indistinguishable Amino Acids

Simarly, the "-usage" command also states that a number between 0-2 is expected.

The new and old parameters also seem very different,

Kind regards

Thys

**Comment by Thys3Potgieter** [comment]
Another one:

"Error parsing the ptm_sequence_matching_type option: Found 1. Supported input: [Protein, Peptide, Spectrum, Ion, PTM]."

**Comment by Thys3Potgieter** [comment]
And this one (I am testing them all because I am writing a bash config file for a linux cluster...and mostly jsut passing the default settings):

java -cp /home/ptgmat003/PeptideShaker-1.11.0/PeptideShaker-1.11.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -xtandem_output_results 'all' -out '/home/user/test'

java.lang.NumberFormatException: For input string: "all"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1241)
cjava -cat java.lang.Double.valueOf(Double.java:504)2.9.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -xtandem_output_results ionParametersCli.java:92)
        at java.lang.Double.<init>(Double.java:597)metersCLI.<init>ejava -cp /home/ptgmat003/SearchGUI-2.9.0/SearchGUI-2.9.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -xtandem_output_results '
        at com.compomics.util.experiment.identification.parameters_cli.IdentificationParametersInputBean.updateIdentificationParameters(IdentificationParametersInputBean.java:549)
'all' -oat com.compomics.util.experiment.identification.parameters_cli.IdentificationParametersInputBean.<init>(IdentificationParametersInputBean.java:118)
        at com.compomics.util.experiment.identification.parameters_cli.AbstractIdentificationParametersCli.initiate(AbstractIdentificationParametersCli.java:92)
        at eu.isas.searchgui.cmd.IdentificationParametersCLI.<init>(IdentificationParametersCLI.java:25)
        at eu.isas.searchgui.cmd.IdentificationParametersCLI.main(IdentificationParametersCLI.java:36)

Docs:
-xtandem_output_results   X!Tandem 'output, results' option (all|valid|stochastic), default is 'all'.

**Comment by Thys3Potgieter** [comment]
java -cp /home/ptgmat003/SearchGUI-2.9.0/SearchGUI-2.9.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -myrimatch_isotope_low '-1' -out '/home/test/user'

Unrecognized option -myrimatch_isotope_low.

Run -usage to see the list of supported options and their input.

Docs:
-myrimatch_isotope_low    MyriMatch lower isotope error range, default is '-1'.

**Comment by Thys3Potgieter** [comment]
Unrecognized option -myrimatch_isotope_high.

Run -usage to see the list of supported options and their input.

Unrecognized option -msgf_isotope_low.

Run -usage to see the list of supported options and their input.

Unrecognized option -omssa_isotopes.

**Comment by Thys3Potgieter** [comment]
java -cp /home/ptgmat003/SearchGUI-2.9.0/SearchGUI-2.9.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -msgf_isotope_high '1' -out '/home/test/user'

Unrecognized option -msgf_isotope_high.

Run -usage to see the list of supported options and their input.

Docs:
-msgf_isotope_high        MS-GF+ upper isotope error range, default is '1'.

**Comment by Thys3Potgieter** [comment]
And this one:

"Unrecognized option -tide_decoy_seed"

**Comment by Thys3Potgieter** [comment]
Last one:
Command:
java -cp /home/ptgmat003/SearchGUI-2.9.0/SearchGUI-2.9.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -omssa_it_replace_evalue '0.0' -out '/home/test/user'

Output:
"Error parsing the omssa_it_replace_evalue option: Negative or zero value found.
Run -usage to see the list of supported options and their input."

Docs:
-omssa_it_replace_evalue  OMSSA e-value cutoff to replace a hit in the iterative search 0.0 means keep best. Default is '0.0'.

**Comment by hbarsnes** [comment]
Hi Thys,

Thanks for pointing these out. 

The "sequence_matching_type" and "ptm_sequence_matching_type" were both due to the same bug in which two parameters had gotten mixed up in the parameter check.

The same was the case for "xtandem_output_results".

The search engine specific isotope options you refer to have all been replaced by the generic options "min_isotope" and "max_isotope" which controls the isotope range across the search engines.

Finally, the "omssa_it_replace_evalue" issue was due to the code not allowing zero values. Which is a bit stupid when the default value is 0.0. ;)

All now fixed and new versions of both SearchGUI and PeptideShaker have been released.

I'm closing this issue, but please don't hesitate to open a new one if you find other errors in the command line documentation.

Best regards,
Harald

**Comment by Thys3Potgieter** [comment]
Thanks so much for a speedy reply! I will download the latest version :)
