### ISSUE TITLE
Peptide to protein mapping bug in the FM index?

### ISSUE THREAD

**Issue by jflucier** [compomics/peptide-shaker#188]
Hello again,

i am currently upgrading my installation of searchgui and peptideshaker installation to the latest version on CentOS6. I am stuck with a bug with latest version of peptideshaker (1.11). When I execute peptideshaker, I get this error message:

Thu Jun 30 13:30:38 EDT 2016 Importing sequences from searchgui_db_concatenated_target_decoy.fasta.
0%
10% 20% 30% 40% 50%PeptideShaker processing failed. See the PeptideShaker log for details.

Thu Jun 30 13:31:47 EDT 2016 An error occurred while loading the identification files:
Thu Jun 30 13:31:47 EDT 2016 820140
java.lang.ArrayIndexOutOfBoundsException: 820140
at com.compomics.util.experiment.identification.protein_inference.fm_index.Rank.getRank(Rank.java:83)
at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:327)
at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:330)
at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRank(WaveletTree.java:305)
at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.createLessTable(WaveletTree.java:289)
at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.(FMIndex.java:669)
at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1383)
at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1317)
at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:213)
at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:450)
at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:157)
at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:695)
at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:204)
at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:907)
Free memory: 7928043856
Thu Jun 30 13:31:47 EDT 2016 PeptideShaker Processing Canceled.
PeptideShaker processing canceled. See the PeptideShaker log for details.

My database has 466 606 entries. Can you guide me on how to resolve this bug.

tks again for your help,

JF

**Comment by jflucier** [comment]
ok some more notes about the analysis:

peptideshaker bug seems to be linked to datasets from SILAC experiments only. This bug is also present in version 1.1.0 of peptideshaker.

tks again for your help.

**Comment by dominik-kopczynski** [comment]
Hi jflucier,

Thank you for reporting this bug. Spontaneously, I have one or two ideas why this error is raised. Can you please tell me how big your main memory and your database (fasta) file is. It seems that your memory got full. During the creation of the index, the auxiliary data structure needs about 5 times the fasta file size. It would be also great if you could somehow place your database at our disposal, so may be we can find the error faster.

Cheers, Dominik

**Comment by jflucier** [comment]
Hey Dominick, 

seems that Marc suggestion to add -sequence_index_type 1 to my command solved the problem. 

thanks again you guys for all your help. Will now try tu rerun the whole pipeline once more to make sure everything is ok.

tks

**Comment by mvaudel** [comment]
Hi JF,

Adding `-sequence_index_type 1` is just a temporary fix to circumvent the problem. The results are exactly the same but we would like to migrate all the projects to `-sequence_index_type 0`. It seems that your database is not supported by this (new) option and it would be really nice if you could share it with us so that we can improve our code :)

Many thanks for your help,

Marc

**Comment by jflucier** [comment]
ok. no problem. Will give it to you tommorrow.

JF

**Comment by jflucier** [comment]
Hi everyone, 

you can download the database using this url:
https://drive.google.com/open?id=0B-d3q8QV4q3oN2FXUGxybkZmdmM

please tell me when the upload is completed. Thanks again for your help.

JF

**Comment by jflucier** [comment]
This database is the 201606 release of uniprot + some ensembl ORF not found in uniprot + all our out-of-frame prediction for the human genome. Thanks so much for all your help.

**Comment by jflucier** [comment]
Hello,

I would like to know if the database was downloaded so i can remove it form my gdrive.

tks

**Comment by dominik-kopczynski** [comment]
Hi JF,

thank you, I downloaded the file. The first error I met was that the database contains * instead of X for unknown amino acids. After exchanging them into X, everything went fine for me. Can you please try it and check if this suggestion helped?

Cheers, Dominik

**Comment by jflucier** [comment]
yup noticed that also.... weirdly Ensembl includes these type of
translations in there protein database. Will try it out and get back to you.

tks

**Comment by jflucier** [comment]
removing the * from the database seem to have solved the problem. I rerun
the test sample analysis without the sequence_index option and everything
worked A1. tks alot for all your help.

JF

**Comment by hbarsnes** [comment]
> removing the * from the database seem to have solved the problem. I rerun the test sample analysis without the sequence_index option and everything worked A1. tks alot for all your help.

I closed the issue as it seems to be fixed, but if I can just add a comment on the interpretation of the stars. I'm not sure if Dominik's assumption that * is the same as X, i.e. representing any amino acid, is correct. Usually the stars are added to represent stop codons when translating gene sequences to amino acid sequences.

So while removing them solves the problem of indexing the FASTA file and will allow you to load the data in PeptideShaker, I'm not sure if the remaining amino acid sequences are a valid protein sequences or not?

Is there no way in which you can control the output from Ensembl in terms of how to treat stop codons?

Best regards,
Harald
