### ISSUE TITLE
peptideshakercli error on centos6

### ISSUE THREAD

**Issue by jflucier** [compomics/peptide-shaker#191]
Hello,

we recently executed the analysis of 498 samples on our HPC clusters. Most peptideshaker analysis went all ok except 9 of them fail with the following error:

`
Path configuration completed.
Tue Jul 19 00:57:31 EDT 2016 Unzipping searchgui_out.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Tue Jul 19 00:57:40 EDT 2016 Import process for GM18516_MSB13307_07 (Sample: sample, Replicate: 1)

Tue Jul 19 00:57:40 EDT 2016 Importing sequences from searchgui_db_concatenated_target_decoy.fasta.
 0%
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tue Jul 19 01:00:13 EDT 2016 FASTA file import completed.
Tue Jul 19 01:00:13 EDT 2016 Importing gene mappings.
Tue Jul 19 01:00:13 EDT 2016     Downloading GO and gene mappings for species Homo sapiens.
Tue Jul 19 01:00:14 EDT 2016 Downloading GO Mappings. Please Wait...
Tue Jul 19 01:00:14 EDT 2016     GO mappings downloaded.
Tue Jul 19 01:00:14 EDT 2016 Downloading Gene Mappings. Please Wait...
Tue Jul 19 01:00:14 EDT 2016     Gene mappings downloaded.
Tue Jul 19 01:00:26 EDT 2016 Establishing local database connection.
Tue Jul 19 01:00:31 EDT 2016 Reading identification files.
Tue Jul 19 01:00:31 EDT 2016 Parsing GM18516_MSB13307_07.comet.pep.xml.
Tue Jul 19 01:00:34 EDT 2016 Loading spectra for GM18516_MSB13307_07.comet.pep.xml.
Tue Jul 19 01:00:34 EDT 2016 Importing GM18516_MSB13307_07.mgf
Tue Jul 19 01:00:35 EDT 2016 GM18516_MSB13307_07.mgf imported.
10% 20% 30% 40% 50% 60% 70% 80% 90%
.....
Tue Jul 19 01:02:31 EDT 2016 1497 conflicts resolved. 1438 protein groups remaining (301 suspicious).
Tue Jul 19 01:02:31 EDT 2016 Correcting protein probabilities.
Tue Jul 19 01:02:31 EDT 2016 Estimating Probabilities. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tue Jul 19 01:02:31 EDT 2016 Saving protein probabilities.
Tue Jul 19 01:02:31 EDT 2016 Attaching Protein Probabilities. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%
Tue Jul 19 01:02:32 EDT 2016 Validating identifications, quality control of matches.
Tue Jul 19 01:02:32 EDT 2016 Finding FDR Thresholds. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 110% 120% 130% 140% 150%
Tue Jul 19 01:02:32 EDT 2016 Match Validation and Quality Control. Please Wait...
java.lang.IllegalArgumentException: fromIndex(1836) > toIndex(1768)
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:964)
        at java.util.ArrayList.subList(ArrayList.java:954)
        at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.checkBuffer(PsmIterator.java:266)
        at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.next(PsmIterator.java:236)
        at eu.isas.peptideshaker.validation.MatchesValidator$PsmValidatorRunnable.run(MatchesValidator.java:1492)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Tue Jul 19 01:02:32 EDT 2016 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>
`

Here is the link to download everything linked to one of this analysis:
https://drive.google.com/folderview?id=0B-d3q8QV4q3obHdPMUZ4Y1lmNUU&usp=sharing

pshaker_error.tar.gz: the database, the mzXML file + all the logs + searchgui_out.zip
ms_analysis_pipeline.sh: the pipeline executed on the HPC cluster
parameters.txt: the initialisation parameters passed to the ms_analysis_pipeline.sh script

The dataset analysed where taken from this public study:
Battle, A., Khan, Z., Wang, S. H., Mitrano, A., Ford, M. J., Pritchard, J. K., & Gilad, Y. (2014). Impact of regulatory variation from RNA to protein. Science, 347(6222)
ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2014/12/PXD001406

If you require additionnal information, do not hesitate to contact me.

tks so much again for your help.

JF

**Comment by mvaudel** [comment]
Hi JF,

Sorry to read that some of the runs did not complete properly. My best guess is that it is a threading issue. I will look into it, hopefully in the coming weeks. It would help if you could check whether the error is reproducible when restarting the script on these particular projects.

Apologies for the inconvenience!

Marc

**Comment by jflucier** [comment]
will do and get back to you as soon as possible.

tks
JF

**Comment by max-l** [comment]
@mvaudel  we just reran peptide-shaker with the same input, and did not get the bug,
and the result is correct.

It does look like a threading issue...

**Comment by max-l** [comment]
we have had 8 similar crashes, I will also rerun them and let you know how that goes

**Comment by mvaudel** [comment]
Great, thanks for the heads up! Will look into the threading issue in the coming weeks and fix the exit code :)

**Comment by max-l** [comment]
just to give some update, this failure occurs in aprox  5% of our peptide-shaker runs,
we can reproduce it pretty consistently, so if there is a verbose or debug flag that can be set
that would give some insight, we can certainly do that.

**Comment by max-l** [comment]
actually perhaps I should not say consistently, random would be a better choice of word...

**Comment by mvaudel** [comment]
Hi JF, hi Max,

Can you try the beta version at the link below? It should solve the problem and return correct exit codes. We have also improved the performance of the tool. It would be great if you could check that it works on your side as well. If it does please also give an eye at the speed compared to previous versions, and if it does not, can you see whether the exit code is correct?

Many thanks,

Marc

http://vedlegg.uib.no/?id=061909210aa9cdb644241fc0e7327d3e

**Comment by jflucier** [comment]
hi marc,

on vacation currently. Will test it when i return after august 22nd. Thank
you for making this release.

JF

**Comment by mvaudel** [comment]
Hi JF,

Perfect, that will give us time to polish this version!

Enjoy your holiday, hope you are having a better weather than we currently do on the Norwegian west coast...

Marc

**Comment by hbarsnes** [comment]
Hi JF, hi Max,

PeptideShaker v1.13.0 has just been released which hopefully fixes the threading issue. If this is not the case please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by jflucier** [comment]
Hi Harald, Marc,

i have just tried release SearchGUI-3.1.0 and PeptideShaker-1.13.1 on our HPC cluster. Serachgui works well as before. However peptideshaker returns the following error:

[jflucier@ip32 20140707_QEp1_LC5_PhGe_SA_4_19_g1_20min]$ java -Xmx30G -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.PeptideShakerCLI \
> -temp_folder $TEMPDIR/PeptideShaker_temp \
> -experiment $__IN_DATASET_NAME  -sample sample -replicate 1 \
> -id_params $TEMPDIR/searchgui.parameters.par \
> -identification_files "$TEMPDIR/search_results/searchgui_out.zip" \
> -spectrum_files "$TEMPDIR/${__IN_DATASET_NAME}.mgf" \
> -out "$TEMPDIR/shaker_results/${__IN_DATASET_NAME}.cpsx"
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:419)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:939)


this error happens almost instantly. Please note that I use de same test suite (same mgf files) as other searchgui and peptideshaker releases have been tested with.

Tks again for help.

**Comment by hbarsnes** [comment]
Hi JF,

This is very strange. As the error seems to occur at a place in the code that should not be possible. At least not from looking at the code. Maybe something crashed earlier than we think.

I'm not able to reproduce the issue on my side, so here's a beta version which should at least print a better stack trace: https://www.dropbox.com/s/t7jg1xzhvkx9mgz/PeptideShaker-1.13.2-beta.zip?dl=0

Give it a go and send us the new error, and then hopefully we'll figure it out.

Best regards,
Harald

**Comment by jflucier** [comment]
Hi Harald,

here is the execution log:

`

[jflucier@ip32 20140707_QEp1_LC5_PhGe_SA_4_19_g1_20min]$ echo $SHAKER_JAR_PATH
/home/xroucou_group/apps/compomics/PeptideShaker-1.13.2-beta/PeptideShaker-1.13.2-beta.jar
[jflucier@ip32 20140707_QEp1_LC5_PhGe_SA_4_19_g1_20min]$ java -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.PathSettingsCLI -temp_folder $TEMPDIR/ 
Path configuration completed.
[jflucier@ip32 20140707_QEp1_LC5_PhGe_SA_4_19_g1_20min]$ 
[jflucier@ip32 20140707_QEp1_LC5_PhGe_SA_4_19_g1_20min]$ # run peptide shaker
[jflucier@ip32 20140707_QEp1_LC5_PhGe_SA_4_19_g1_20min]$ java -Xmx30G -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.PeptideShakerCLI \
> -temp_folder $TEMPDIR/PeptideShaker_temp \
> -experiment $__IN_DATASET_NAME  -sample sample -replicate 1 \
> -id_params $TEMPDIR/searchgui.parameters.par \
> -identification_files "$TEMPDIR/search_results/searchgui_out.zip" \
> -spectrum_files "$TEMPDIR/${__IN_DATASET_NAME}.mgf" \
> -out "$TEMPDIR/shaker_results/${__IN_DATASET_NAME}.cpsx"
java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.PathSettingsCLI.setPathSettings(PathSettingsCLI.java:105)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:121)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:940)
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:420)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:940)

`

tks again for your help,

JF

**Comment by hbarsnes** [comment]
Hi JF,

Ok, I see the problem now. Will correct it and release a new version later today or tomorrow.

Best regards.
Harald

**Comment by jflucier** [comment]
keep me posted please when you release the patch.

tks Harald.

**Comment by hbarsnes** [comment]
Hi JF,

Here's a beta version that should fix the problem: https://www.dropbox.com/s/63h8xqbioa8yrox/PeptideShaker-1.13.2-beta.zip?dl=0.

Please let me know if it works for you as well. If it does I'll release it properly tomorrow.

Best regards,
Harald

**Comment by jflucier** [comment]
ok problem is solved. 4 / 5 dataset in our test set have passed. The other is still running. Please tell me when you make this code available in an official release please.

Thanks Harald for your excellent support.

JF

**Comment by jflucier** [comment]
could not test threading problem thoroughly yet. We will need to send multiple datasets to our HPC system. Will get back to you about this when we analyse these studies. Should be soon.

**Comment by hbarsnes** [comment]
Hi JF, 

> ok problem is solved. 4 / 5 dataset in our test set have passed. The other is still running. Please tell me when you make this code available in an official release please.

Great! I will let you know when the new version is available. It will most likely not be until the middle of next week though as we need access to the EBI code repositories which are down for maintenance until Tuesday.

Best regards,
Harald

**Comment by jflucier** [comment]
no problem Harald. Just tell me when release is available. Tks so much.

JF

**Comment by hbarsnes** [comment]
Hi JF,

The EBI repositories finally came back online and the new PeptideShaker version (v1.13.3) has just been released.

Best regards,
Harald

**Comment by jflucier** [comment]
Yes! Thanks so much. I will test this on our HPC in the following hours.
Tks again for your excellent support.

JF
