### ISSUE TITLE
PeptideShaker process returns 0 on failure 

### ISSUE THREAD

**Issue by max-l** [compomics/peptide-shaker#193]
When the peptide shaker process fails, it still returns 0,
(wich means success in unix convention) not sure this is the case for all failures, 
but on this particular failure : 

   https://github.com/compomics/peptide-shaker/issues/191

the process returned 0. We use peptide shaker in a pipeline (in a high throughput setup),
so the debugging is easier when we can track exactly which process failed.
Otherwise, it is the next process in the chain that will fail.

It would be nice if peptide-shaker followed the unix convention : 

  http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by mvaudel** [comment]
Good point! Will work on it

**Comment by hbarsnes** [comment]
Hi,

PeptideShaker v1.13.0 has just been released which should now use the correct exit codes. If there are any cases we missed please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by max-l** [comment]
Found cases of zero exit and submited pull request  #207
