### ISSUE TITLE
Supporting ProteinPilot mzid files

### ISSUE THREAD

**Issue by jamesbroadbent** [compomics/peptide-shaker#195]
Hi Peptide Shaker team!

I've found that the mzid format from ProteinPIlot uses the *paragon:confidence* MS:1001167 flag rather than the general *PSM-level search engine specific statistic* MS:1001143 flag. I can replace the paragon:confidence flags manually and get it lo load but could you enable PeptideShaker to read these files in directly please?

Kind regards,

James

**Comment by hbarsnes** [comment]
Hi James,

Thanks for telling us about this. We will look into adding support for parsing ProteinPilot mzid files. Hopefully being able to extract the correct score will be all that is required.

It would be great if you could share with us a ProteinPilot mzid example file (plus the mgf and FASTA files used) that we could use for testing our parsing?

Best regards,
Harald

**Comment by jamesbroadbent** [comment]
Hi Harald,

Thanks for your email and my apologies for the delay; I was travelling for
the second half of last week.

I'll try to get you some data by the end of the week - I just need to check
with the data owner if thy are happy for me to pass it on to you..

Kind regards,

James

**Comment by jamesbroadbent** [comment]
​
 for Harald ProteinPilot PeptideShaker.zip
<https://drive.google.com/file/d/0B1hTLgsvFnjldFJfaVlNSVBzaTQ/view?usp=drive_web>
​Hi Harald,

The attached files should be all you need. I'm not completely sure about
the database - whether it has correctly formatted reversed sequences - but
you should still be able to test the PS import regardless. Let me know if I
can help further.

Kind regards,

James

**Comment by hbarsnes** [comment]
Hi James,

Thanks for the file. I will update our code to parse the correct PSM scores and get back to you.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi James,

PeptideShaker v1.13.1 has just been released supporting the loading of mzid files from ProteinPilot. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
