### ISSUE TITLE
Object not found in cache when saving

### ISSUE THREAD

**Issue by QiyuWang** [compomics/peptide-shaker#202]
When using peptideshaker, there was a but report
[bug report.txt](https://github.com/compomics/peptide-shaker/files/455892/bug.report.txt)

I am sure the database could word well in peptishaker. and this bug report is only for this dataset. 

Thanks for your help

**Comment by mvaudel** [comment]
Hi and thank you for reporting this issue. I will look at your files in the shortest delays.

**Comment by QiyuWang** [comment]
Hi
I tried to load the mzml files and mgf files to google dirve, it is too large about 8G,  It cost much time, How could i do?

Thanks

**Comment by mvaudel** [comment]
Hi again,

Can you try to compress the files? [7zip](http://www.7-zip.org/download.html) should be able to do this. If you can send us the mgf, fasta, and identification results files that should be enough - no need to include mzML.

Best regards,

Marc

**Comment by QiyuWang** [comment]
Hi

I have already loaded the files to you

Thanks

**Comment by mvaudel** [comment]
Hi again,

Thanks for uploading the files. I don't seem to have received the link to the files - can you send it to me, e.g. per email?

Many thanks,

Marc

**Comment by QiyuWang** [comment]
Hi,
   I have already emaied to you per your email, please check it.
Thanks
Qiyu

**Comment by QiyuWang** [comment]
Hi Marc
How about the problem solved?
Thank you
Qiyu

**Comment by mvaudel** [comment]
Hi Qiyu,
I did not find any simple fix yet and need to work more on it. Sorry about the delay, I will keep you updated with my progress!
Marc

**Comment by QiyuWang** [comment]
Hi Marc，
    How about the process?
Thanks
Qiyu

**Comment by mvaudel** [comment]
Hi again,

Really sorry but I have been kept busy by other duties. I am not sure when I will be able to look into this but I did not forget!

Sincere apologies,

Marc

**Comment by hbarsnes** [comment]
Hi Qiyu,

As this issue is the same as https://github.com/compomics/peptide-shaker/issues/235 we will assume that it is solved for your dataset as well. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
