### ISSUE TITLE
Include protein sequence in exported mzIdentML file?

### ISSUE THREAD

**Issue by AnotherKiwi** [compomics/peptide-shaker#204]
We use Bruker ProteinScape to run Mascot searches and manage our MS/MS data. The latest version of ProteinScape has the ability to import mzIdentML files and merge external search results with its own searches. What I'd like to do is use PeptideShaker to combine searches performed using SearchGUI, and then import the results into ProteinScape. Unfortunately the mzIdentML files I've exported from PeptideShaker don't include the protein sequences, as required by ProteinScape.

Is there a setting I've missed that would allow the inclusion of the protein sequeneces in <Seq> tags under each <DBSequence> tag of the mzIdentML files? Or, if not, would it be possible for the ability to include protein sequences to be added as an export option?

Thanks in advance
Stephen

**Comment by hbarsnes** [comment]
Hi Stephen,

We previously included the sequences in the mzid export but decided to remove them as they were not mandatory and only increased the size of the mzid files. Also, if I remember correctly, there were some tools that had problems parsing the resulting files if the sequences were included.

However, it is just a matter of re-adding one line of code to get the sequences included again. I will look into how easy it is to make the inclusion of the sequences an option when exporting and get back to you.

Best regards,
Harald

**Comment by AnotherKiwi** [comment]
Thanks Harald
That sounds great.
Kind regards
Stephen

**Comment by hbarsnes** [comment]
Hi Stephen,

We've just released PeptideShaker v1.13.4 which now allows you to decide if the protein sequences are to be included in your mzid export or not. This should solve your problem with opening the PeptideShaker mzid files in ProteinScape? If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by AnotherKiwi** [comment]
Hi Harald

Thanks very much for addressing this so quickly. I'll give it a try and let you know if the mzids are still not accepted by ProteinScape.

Kind regards
Stephen
