### ISSUE TITLE
Error matching variable mods to ms/ms spectra

### ISSUE THREAD

**Issue by hale94** [compomics/peptide-shaker#209]
I have noticed a problem beginning with version 13.  When the ms/ms is displayed for peptides with a variable modification (user defined in my case) the spectra do not match.  When I open the same searchgui file with version 1-12-3, the ms ms match is very good.  I have attached a screenshot for the same peptide from the same searchgui run for a representative peptide.  This problem is not present with unmodified peptides or for fixed mods.
![1-12-3](https://cloud.githubusercontent.com/assets/18413181/19204692/267c7710-8c93-11e6-94c5-d1ae42bcf9a2.png)
![1-13-5](https://cloud.githubusercontent.com/assets/18413181/19204693/267e5986-8c93-11e6-8643-24a5430e41f6.png)

This error is present in all version 13 releases.  I am using X! tandem, MSGF, Omssa, Comet and MSAmanda.

Thanks,

John

**Comment by hbarsnes** [comment]
Hi John,

Thanks for telling us about this. Would it be possible for you to share the data with us so that we can try to reproduce the issue on our side?

Best regards,
Harald

**Comment by hale94** [comment]
Harald,

 

What files will you need to reproduce it?

 

John

**Comment by hbarsnes** [comment]
Hi John,

> What files will you need to reproduce it?

We would need the SearchGUI output zip file plus the mgf and FASTA files. In other words, the files you're loading in PeptideShaker.

Best regards,
Harald

**Comment by hale94** [comment]
Harald,

The zipped searchgui folder has results from 36 individual mgfs.  I only
placed 1 mgf file in the google drive, so you can manually extract the out
folder and just use the results for the corresponding mgf.

John​
 remicade_ritux_TNF_cRAP.fasta
<https://drive.google.com/file/d/0B4bVINgeHUzzb0ZvdXcxN1NOOFE/view?usp=drive_web>
​​
 160919--RituxTNF_1to8_3.mgf
<https://drive.google.com/file/d/0B4bVINgeHUzzRGpTb1NFaGRoQlE/view?usp=drive_web>
​​
 searchgui_out.zip
<https://drive.google.com/file/d/0B4bVINgeHUzzZXc0dEI2N2VfMzA/view?usp=drive_web>
​

**Comment by hbarsnes** [comment]
Hi John,

The SearchGUI zip file contains results for the following mgf files:
160919--InflixB2M_1to0-5_1.mgf
160919--InflixB2M_1to0-5_2.mgf
160919--InflixTNF_1to0-5_2.mgf
160919--InflixTNF_1to0-5_3.mgf

But you only sent me the mgf file called 160919--RituxTNF_1to8_3.mgf?

Best regards,
Harald

**Comment by hale94** [comment]
Sorry Harald, I loaded the wrong folder.  This should have the right files.

John​
 searchgui
<https://docs.google.com/folderview?id=0B4bVINgeHUzzQ0w1dW5Uc2VZdVE&usp=drive_web>
​

**Comment by hbarsnes** [comment]
Hi John,

Thanks for the files. I can confirm that I see the same on my side. Not sure what the problem is yet, but seems to be something with the spectrum mapping. If you look closely at the two screenshots above you will notice that the spectra are not identical. One of the most obvious being the tall peak around 1600 on the x-axis.

The error only seems to affect the visual display of the PSMs though, as the rest of the results are identical as far as I can tell. 

We'll try to fix the problem and release a new version as soon as possible. 

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi John,

We've just released PeptideShaker v1.13.6 which should fix the problem with the annotation. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by hale94** [comment]
Thanks Harald, that seems to have fixed the error.

 

John
