### ISSUE TITLE
mzid import issue into Sciex SWATH micro app

### ISSUE THREAD

**Issue by 1Moe** [compomics/peptide-shaker#210]
Hi Marc and Harald,

I contacted Sciex to help me with an issue during import of a peptideshaker generated mzid file into the SWATH micro app.

The Sciex support said the following:

> "I’ve had a chance to investigate the peptide shaker *.mzid and can see that the file is not properly formed. Specifically, the file looks fine and then it just stops, right in the middle of a block of text within the spectrum identification list and is therefore missing the entire ProteinDetectionlist information.
> 
> This being the case, I would get in touch with the PeptideShaker developers. They helped me with getting proteinPilot MzID files into Peptideshaker a couple of months ago and were really quick to help me out.
> 
> I would make the files you sent me available to them and indicate that the mzID is truncated."

The mzid files in question can be downloaded here: 
https://drive.google.com/drive/folders/0BybCLLWRgDsUX2VTc0F1ZlpCMnM

I would appreciate it a lot if you could have a look into this.
Many thanks for your help,

Moe

**Comment by hbarsnes** [comment]
Hi Moe,

I'm a bit confused, as both the mzid files available at the link above seem fine to me. Both are complete mzid files (i.e. they do not stop in the middle of the file resulting in invalid xml) and both contain the ProteinDetectionList information.

Perhaps something went wrong when the Sciex support downloaded your file(s)? Or did you share the wrong files with us?

Best regards,
Harald

**Comment by 1Moe** [comment]
Thanks Harald,

I will copy the Sciex support into this thread.
I don't know the ins and outs of the sciex SWATH software.

I also tested the above mzid files with skyline which imported them fine.

Regards
Moritz

**Comment by jamesbroadbent** [comment]
Hi Harald,

You were right - the download had been truncated, causing a truncated file. Still when I try to load the file I get an error saying "The given key was not present in the dictionary"

Any ideas what this could mean? If not, I will send it on the my SWATH 2.0 developer colleagues.

Cheers,

James

**Comment by hbarsnes** [comment]
Hi James,

> You were right - the download had been truncated, causing a truncated file. Still when I try to load the file I get an error saying "The given key was not present in the dictionary". Any ideas what this could mean? If not, I will send it on the my SWATH 2.0 developer colleagues.

Does it tell you which key and in which dictionary? Usually this indicates that a CV term is not included in the supported list of CV terms in the tool loading the data. We've had similar cases in the past with the PeptideShaker scores for example. I'd recommend checking with the developers.

Best regards,
Harald

**Comment by 1Moe** [comment]
Thanks for working on this, James and thanks for your answer, Harald.
Would be great to have compatibility between peptideshaker mzid and SWATH 2.0 from Sciex. 

Regards
Moe

**Comment by hbarsnes** [comment]
Hi all,

Any progress on this one? Can we close the issue?

Best regards,
Harald

**Comment by jamesbroadbent** [comment]
Hi Harald,

The US SCIEX team indicated that they only offer full support for Mascot
and ProteinPilot at this stage. Hopefully this is something that will
change in the future.

Cheers,

James

**Comment by hbarsnes** [comment]
Hi James,

In that case I think we'll close this as a PeptideShaker issue as it's more of a ProteinPilot issue/limitation. But do feel free to reopen the issue if ProteinPilot decides to expand their mzIdentML support and it still does not work.

Best regards,
Harald
