### ISSUE TITLE
PeptideShaker fails when searched against a large database within Galaxy-P

### ISSUE THREAD

**Issue by PratikDJagtap** [compomics/peptide-shaker#216]
Hello Marc and Harald,

While searching a metaproteomics dataset against a large database (8,829,066 sequences with multiple microbial proteomes) the SearchGUI works but PeptideShaker fails. (See attached screenshot).

Can you suggest a way forward for database search using large databases?

Regards,
Pratik

On Mon, Aug 29, 2016 at 7:14 AM, Jim Johnson johns198@umn.edu wrote:
This is from the PBS stdout from the job:
galaxyp2014@galaxyp2014 [/home/mscls/apps/galaxyp2014/job_working_directory/000/121/121280] % cat galaxy_121280.o
Path configuration completed.
Fri Aug 26 15:47:43 CDT 2016 Unzipping searchgui_input.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Fri Aug 26 15:53:09 CDT 2016 Import process for Galaxy_Experiment_2016082615471472244434 (Sample: Sample_2016082615471472244434, Replicate: 1)

Fri Aug 26 15:53:09 CDT 2016 Importing sequences from input_database.fasta.
Reindexing: input_database.fasta.
10% 20% 30% 40% 50% 60% 70% 80% 90% 0%

Not too helpful.   I'll probably need to try running this via command line to see if I can determine the problem.

JJ

On 8/28/16 10:48 PM, Pratik Jagtap wrote:
It failed again with the error: The cluster DRM system terminated this job

https://galaxyp.msi.umn.edu/u/pjagtap/h/peter-mcqueen-searchgui-peptideshaker-workflow-for-metaproteomics

On Fri, Aug 26, 2016 at 3:47 PM, Pratik Jagtap pjagtap@umn.edu wrote:
Thanks - retrying now. Fingers crossed!
![screen shot 2016-10-25 at 10 38 14 am](https://cloud.githubusercontent.com/assets/10679354/19693213/59d89fce-9aa0-11e6-96db-94c4aea13a85.png)

On Fri, Aug 26, 2016 at 2:15 PM, Jim Johnson johns198@umn.edu wrote:
It ran out of memory:
Path configuration completed.
Sat Aug 20 07:24:38 CDT 2016 Unzipping searchgui_input.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Sat Aug 20 07:30:02 CDT 2016 Import process for Galaxy_Experiment_2016082007241471695858 (Sample: Sample_2016082007241471695858, Replicate: 1)

Sat Aug 20 07:30:02 CDT 2016 Importing sequences from input_database.fasta.
Reindexing: input_database.fasta.
10% 20% 30% 40% 50% 60% 70% 80% 90% 0%PeptideShaker ran out of memory! See the PeptideShaker log for details.

Sat Aug 20 08:20:16 CDT 2016 Ran out of memory!
Sat Aug 20 08:20:17 CDT 2016 PeptideShaker Processing Canceled.

I doubled the memory allocation,  can you try rerunning that job?

JJ

On 8/26/16 1:44 PM, Pratik Jagtap wrote:
Hello JJ,

Here is the SearchGUI-PeptideShaker history that generated empty PeptideShaker outputs.

https://galaxyp.msi.umn.edu/u/pjagtap/h/peter-mcqueen-searchgui-peptideshaker-workflow-for-metaproteomics

Please let me know if there are any suggestions.

Thanks,
Pratik

**Comment by mvaudel** [comment]
Hi Pratik,

What version of the software was used for this run? Can you make sure that the _-sequence_index_type_ is set to _0_?

Best regards,

Marc

**Comment by PratikDJagtap** [comment]
Hello Marc,

Thanks for your prompt reply. I believe the PeptideShaker version was 1.10.0

I have copied JJ to comment whether the  *-sequence_index_type* is set to
*0.*

Thanks,
Pratik

Pratik Jagtap,

Research Assistant Professor, Department of Biochemistry, Molecular Biology
and Biophysics,

University of Minnesota.

*Address: 7-166 MCB, 420 Washington Ave SE, Minneapolis, MN 55455*

*Phone: 612-624-0381 <http://612-624-0381/>    Email: pjagtap@umn.edu
<pjagtap@umn.edu>   *

*Twitter: twitter.com/pratikomics <http://twitter.com/pratikomics>
 Google Scholar: z.umn.edu/pjgs <http://z.umn.edu/pjgs> *

**Comment by mvaudel** [comment]
Hi Pratik,

If I am not mistaking 1.10.0 does not have this option, that might explain the memory issue. In short, we have changed the way we index fasta files to support larger sequence databases with eventual ambiguous amino acids like _X_. You will find more details at the link below. As you will see this is particularly interesting for metaproteomics databases that are very large and contain a lot of Xs.
https://github.com/compomics/compomics-utilities/wiki/PeptideMapper

So hopefully you just need to update the software to the latest version, the memory consumption will be dramatically reduced and the tool much faster :) I will come back to you soon with new features we have developed for galaxy, allowing the creation of user defined enzymes and PTMs in command line for our software.

Best regards,

Marc

**Comment by PratikDJagtap** [comment]
Thanks Marc,

This is great news. We will test this again after upgrading it to new
version. I also see that there are a few De novo tools as well.

Thanks again,

Pratik

Pratik Jagtap,

Research Assistant Professor, Department of Biochemistry, Molecular Biology
and Biophysics,

University of Minnesota.

*Address: 7-166 MCB, 420 Washington Ave SE, Minneapolis, MN 55455*

*Phone: 612-624-0381 <http://612-624-0381/>    Email: pjagtap@umn.edu
<pjagtap@umn.edu>   *

*Twitter: twitter.com/pratikomics <http://twitter.com/pratikomics>
 Google Scholar: z.umn.edu/pjgs <http://z.umn.edu/pjgs> *

**Comment by mvaudel** [comment]
Hi Pratik,

Yes, we added the de novo tools in SearchGUI so that people don't have to run DenovoGUI in parallel. However, the integration in PeptideShaker is not optimal yet and using de novo tools yields more false positives than search engines as far as we tested...

Will keep you posted on our progress on this front as well!

Marc

**Comment by hbarsnes** [comment]
As the issue should be solved by updating to the latest PeptideShaker version we will now close the issue. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
