### ISSUE TITLE
Can't export Mzid using MzidCLI because of a fasta error

### ISSUE THREAD

**Issue by videlc** [compomics/peptide-shaker#217]
Hey, 

I'm currently having some troubles exporting mzid files from cpsx using  MzidCLI.

When entering this command : 
`java -cp /path_to/compomics/PeptideShaker-1.13.4/PeptideShaker-1.13.4.jar eu.isas.peptideshaker.cmd.MzidCLI -in mycpsx.cpsx -contact_first_name test -contact_last_name  test -contact_email test -contact_address test -organization_name test -organization_email  test -organization_address  test -temp_folder /path_to/tempdir/ -output_file /out_path/mycpsx.mzid
`
returns me this error message : 
`Path configuration completed.
10% 20% 80% 90%
Wed Oct 26 13:32:38 EDT 2016 The FASTA file was not found. Please provide its location in the command line parameters.
`

Could not figure out how to enter FASTA location in cmds...

note : FASTA file is in the same directory as cpsx and mgf files. Testing with the GUI with similar conditions (cpsx + mgf + fasta at the same place) worked
note 2 : cpsx and mgf have been moved since they have been generated

Thanks by advance,
Vivian

**Comment by hbarsnes** [comment]
Hi Vivian,

At the moment you cannot change the FASTA file as part of the MzidCLI command line (even though the error message seems to indicate otherwise). 

To avoid such problems we recommend that you use the -zip option when generating the PeptideShaker project. That way a zip file which also includes the mgf and FASTA files is created and can then be used as input to the MzidCLI command line (and ensures that the project can be opened on any computer by transferring a single file).

However, this is most likely a bit too late for this particular project, but if you put the FASTA file in the same folder as the cpsx file (or in a subfolder called "data") this should work. At least this works fine on my side and is our general fix in cases like this.

Could you try using the complete path to the mzid file instead of just "mycpsx.cpsx"?

Best regards,
Harald

**Comment by videlc** [comment]
Thanks Harald for such a quick answer,

Placing FASTA into /mypath/data/ and placing /mypath/mycpsx.cpsx into the command  fixed the issue I had.
However, I now get another error which is the following : 
`
Path configuration completed.
10% 20% 80% 90%Reindexing: searchgui_db_concatenated_target_decoy.fasta.

10% 20% 30% 40% 50% 60% 70% 80% 90%
Wed Oct 26 18:51:55 EDT 2016 Protein database searchgui_db_concatenated_target_decoy.fasta.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Wed Oct 26 18:51:58 EDT 2016 An error occurred while generating the mzid file.
java.io.FileNotFoundException: /mypath_to/mycpsx.mzid (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at eu.isas.peptideshaker.export.MzIdentMLExport.<init>(MzIdentMLExport.java:270)
	at eu.isas.peptideshaker.export.MzIdentMLExport.<init>(MzIdentMLExport.java:221)
	at eu.isas.peptideshaker.cmd.CLIMethods.exportMzId(CLIMethods.java:359)
	at eu.isas.peptideshaker.cmd.MzidCLI.call(MzidCLI.java:215)
	at eu.isas.peptideshaker.cmd.MzidCLI.main(MzidCLI.java:352)
`

**Comment by hbarsnes** [comment]
Hi Vivian,

Does all the folders in the path "/mypath_to/" exist? As parent folders will not be created as part of the -output_file option, only the mzid file itself.

Best regards,
Harald

**Comment by videlc** [comment]
Hey Harald,

Thank to your last comment, I changed my command to : 
` java -cp /mypath/compomics/PeptideShaker-1.13.4/PeptideShaker-1.13.4.jar eu.isas.peptideshaker.cmd.MzidCLI -in /mypath/analysispath/myfile.cpsx -contact_first_name test -contact_last_name test -contact_email test -contact_address test -organization_name test -organization_email  test -organization_address  test -temp_folder /mypath/analysispath/tempdir/ -output_file test2.mzid`

which gives me the following : 
` 
Path configuration completed.
10% 20% 80% 90%
Wed Oct 26 19:28:06 EDT 2016 Protein database searchgui_db_concatenated_target_decoy.fasta.
Reindexing: searchgui_db_concatenated_target_decoy.fasta.
Wed Oct 26 19:28:57 EDT 2016 An error occurred while generating the mzid file.
java.lang.IllegalArgumentException: Protein not found: HDHD2.
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getProteinSynchronized(SequenceFactory.java:321)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getProtein(SequenceFactory.java:223)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getProteinSynchronized(SequenceFactory.java:319)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getProtein(SequenceFactory.java:223)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getProtein(SequenceFactory.java:189)
	at eu.isas.peptideshaker.export.MzIdentMLExport.writeSequenceCollection(MzIdentMLExport.java:634)
	at eu.isas.peptideshaker.export.MzIdentMLExport.createMzIdentMLFile(MzIdentMLExport.java:323)
	at eu.isas.peptideshaker.cmd.CLIMethods.exportMzId(CLIMethods.java:360)
	at eu.isas.peptideshaker.cmd.MzidCLI.call(MzidCLI.java:215)
	at eu.isas.peptideshaker.cmd.MzidCLI.main(MzidCLI.java:352)
`

However, a "test2.mzid" file is created but I think last error would suggest it might be unusable ?

Regards,
Vivian

**Comment by hbarsnes** [comment]
Hi Vivian,

And you are sure that you are using the correct FASTA file and that this file contains a protein with the accession number "HDHD2"? Where does this FASTA file come from? As these do not seem to be standard FASTA accession numbers? Could indicate an issue with the parsing of the FASTA headers.

Best regards,
Harald

**Comment by videlc** [comment]
Hey Harald,

Indeed, the FASTA was problematic. It is a FASTA we generated with non canonical portein sequences and the one I used in last commands was not the version we used to generate the cpsx file (and indeed, HDHD2 protein was missing). Retrieving that particular FASTA and re-running the command : 
`java -cp /mypath/compomics/PeptideShaker-1.13.4/PeptideShaker-1.13.4.jar eu.isas.peptideshaker.cmd.MzidCLI -in /mypath/myfile.cpsx -contact_first_name test -contact_last_name test -contact_email test -contact_address test -organization_name test -organization_email  test -organization_address  test -temp_folder /mypath/tempdir/ -output_file test4.mzid`

returned me : 
`Path configuration completed.
10% 20% 80% 90%Reindexing: searchgui_db_concatenated_target_decoy.fasta.

10% 20% 30% 40% 50% 60% 70% 80% 90%
Thu Oct 27 09:10:32 EDT 2016 Protein database searchgui_db_concatenated_target_decoy.fasta.
Thu Oct 27 09:11:36 EDT 2016 MzIdentML export completed.
`

Thank you a lot for fast support !
Vivian

**Comment by hbarsnes** [comment]
Hi Vivian,

Great! Always happy to help. :)

I will now close this issue, but don't hesitate to create a new one if you come across other problems.

Best regards,
Harald
