### ISSUE TITLE
Exporting non-validated spectra as mgf

### ISSUE THREAD

**Issue by akwalker** [compomics/peptide-shaker#218]
I start with a 100Mb mgf file and about 15% are identified confidently. After I export the non-validated PSMs, the mgf is only about 2.5 Mb so I definitely am not getting what I expected, or at least what I need. 

It seems that this only exports PSMs that were "identified" but without enough evidence to have a high score or validation. I would like the option to export all spectra that weren't positively identified for the purpose of iterative searches (for additional modifications, for example).

**Comment by akwalker** [comment]
To clarify, if I have several different modifications that I need to look for and would rather search iteratively than put 6 or more into one search. I would like to do a search with one or two modifications such as oxidation of methionine and identify a few thousand PSMs. I would like to essentially remove those spectra (including confident unmodified peptides) from the mgf file and then search what is left with additional modifications.

**Comment by mvaudel** [comment]
Hi and thank you for reporting this issue. This looks peculiar, are you operating from the GUI or in command line? What is the option selected, _Spectra of Non-Validated PSMs_?

Best regards,

Marc

**Comment by akwalker** [comment]
Always in the GUI :-) And yes, that is the option I selected. Based on the sized of the export, it must be exporting the PSMs that were "identified" but not validated, which is exactly what the option says. However, I guess I don't want just PSMs, but rather unidentified spectra AND non validated PSMs.

**Comment by mvaudel** [comment]
Hi again,

Indeed, the problem was that we were iterating the identified spectra instead of all spectra. Very nice catch. Apologies for this error on our side, we will release new versions with a fix very soon.

Please keep this issue open until the fix is released in case other users encounter the same problem :)

Best regards and thanks for your contribution,

Marc

**Comment by hbarsnes** [comment]
Hi,

We've now released PeptideShaker v1.14.0 which should fix this issue. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
