### ISSUE TITLE
Entry not found in cache when saving

### ISSUE THREAD

**Issue by talpa25** [compomics/peptide-shaker#220]
Hey Folks,

i have problems with peptideshaker importing the data from the search gui.

Thu Nov 10 13:21:02 CET 2016        Importing Data Canceled!
Thu Nov 10 13:21:02 CET 2016        An error occurred while loading the identification files:
Thu Nov 10 13:21:02 CET 2016        Object 2016_10_21_iG_C1.mgf_cus_2016_10_21_iG_C1.10942.10942.3 corresponding to entry CR_CR1_0_id_ccs_"2016_10_21_iG_C1.mgf_raw_assumptions"_ccs_2016_10_21_iG_C1.mgf_cus_2016_10_21_iG_C1.10942.10942.3 not found in cache when saving.

here is the complete log: 
[20161110 loading new project peptide shaker log.txt](https://github.com/compomics/peptide-shaker/files/583751/20161110.loading.new.project.peptide.shaker.log.txt)
[20161110 searchgui log.txt](https://github.com/compomics/peptide-shaker/files/583752/20161110.searchgui.log.txt)
[PeptideShaker 1.13.6 log.txt](https://github.com/compomics/peptide-shaker/files/583787/PeptideShaker.1.13.6.log.txt)

i loaded 3 spectra files in the searchgui (CR1...CR3)

Do you know what is the problem?

**Comment by hbarsnes** [comment]
Hi,

Thanks for telling us about this. The same issue has also been reported by others (for example: https://github.com/compomics/peptide-shaker/issues/202) and we are working on trying to fix the problem. It seems to be more complicated than we hoped though, so I'm afraid it will still take a bit more time. We will let you know as soon as we've located and fixed the issue.

Best regards,
Harald

**Comment by talpa25** [comment]
Surpringsingly i "solved" the problem. I increased the java memory up to 8 GB. I guess its an memory / cache overflow issue...

**Comment by talpa25** [comment]
Update:
Unfortunately this does only work for some files. With others i still cannot load the searchgui results in peptideshaker.
[faillog.txt](https://github.com/compomics/peptide-shaker/files/587187/faillog.txt)
[PeptideShaker 1.13.6 log.txt](https://github.com/compomics/peptide-shaker/files/587188/PeptideShaker.1.13.6.log.txt)
[SearchGUI 3.1.4 log.txt](https://github.com/compomics/peptide-shaker/files/587189/SearchGUI.3.1.4.log.txt)

**Comment by hbarsnes** [comment]
Hi again,

Yes, I'm afraid that the problem can reoccur in cases where the dataset is too big to keep in memory. The issue does not happen very frequently even in these situations though, which is why it is so hard to locate and fix the error.

Best regards,
Harald

**Comment by talpa25** [comment]
i'm running this on 64 bit windows 10, 8gb RAM, i7-3667U, and it makes no difference whether i run a single raw file or even e.g. four in one searchgui run.

**Comment by hbarsnes** [comment]
If you can consistently reproduce the error on a small dataset it would be great if you could share the data with us so that we can use it for testing on our side? As the other datasets we've had reported with this error are all quite big.

**Comment by talpa25** [comment]
Ican reproduce the error with the following dataset:
https://drive.google.com/open?id=0B0VKdZCKDItLUUxhZUwxeVNBVDA mgf File
with this FASTA DB (TrEMBL) it works: 
[uniprot-pisum+sativum_TrEMBL_2202-Kopie.txt](https://github.com/compomics/peptide-shaker/files/603334/uniprot-pisum.sativum_TrEMBL_2202-Kopie.txt)

with this  it does'nt (uniprot curated):
[uniprot-Pisum+sativum_1661-Kopie.txt](https://github.com/compomics/peptide-shaker/files/603335/uniprot-Pisum.sativum_1661-Kopie.txt)

it looks like that certain sequences or sequence complexities aren't that helpful

**Comment by hbarsnes** [comment]
Hi,

> I can reproduce the error with the following dataset [...] (i hope the dataset is'nt too big)

Thanks for the files. Perfect size for testing. However, in order to reproduce the error we also need your search settings, or even better your SearchGUI output. Then we can directly try to load the data in PeptideShaker and see of we get the same error.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

Did you manage to solve the problem on your own? As we're still waiting for your SearchGUI output or search settings in order to be able to try to reproduce the error on our side?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi,

As this issue is the same as https://github.com/compomics/peptide-shaker/issues/235 we will assume that it is solved for your dataset as well. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
