### ISSUE TITLE
Annotation level slider Bug

### ISSUE THREAD

**Issue by KenWifi** [compomics/peptide-shaker#224]
Hi, 
When I move the annotation slider in Spectrum&Fragment Ions panel to the maximum value, Peptide-Shaker will has no response about one minute. And then it return to the default value.
Is it a bug? Or can you help me to fix it.
Thanks!

**Comment by hbarsnes** [comment]
Hi,

I think it's just a matter of the slider getting stuck from some unknown reason. Are you using the mouse wheel to move the slider? If so, try using the left mouse button to drag the slider instead, this should solve the problem.

Best regards,
Harald

**Comment by KenWifi** [comment]
Hi,

You are right, it only have problem when I use mouse wheel. And I hope you can fix this bug! 

Thank you very much!
Best regards!
Kai

**Comment by hbarsnes** [comment]
Hi Kai,

I finally managed to locate the problem with the slider. Will be fixed in the next release. :)

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Kai,

PeptideShaker v1.14.3 has just been released which should fix the problem with the slider getting stuck. If you still experience issues, please let us know and we'll reopen the issue.

Best regards,
Harald
