### ISSUE TITLE
Issue of SVG export 

### ISSUE THREAD

**Issue by KenWifi** [compomics/peptide-shaker#225]
Hi,
I try export the spectrum as SVG, but when I get it, I found it doesn't look like the spectrum in Spectrum&Fragment Ions panel. There are some problems in the SVG picture. 

1. The other panel's table title paint in the picture sometimes.

2. The number's size in SVG is more bigger and effect the observation of spectrum.

But the picture in PDF is normal. When I read the code in Utilities jar package, I found the PDF is transformed from SVG. So, do you have any idea about this issue?
Best regards!

**Comment by hbarsnes** [comment]
Hi,

Are you opening the SVG file in a proper SVG editor? Opening it in your browser will in most cases not display the image properly. Also, if you get the panel's table title included (or other elements) simply re-export the image. This usually solves the problem. And unless you're going to alter the image the PDF export is usually good enough quality?

Best regards,
Harald

**Comment by KenWifi** [comment]
Hi

Thanks for your reply. Yes, you are right, I opened them in IE browse and it looks much better when using SVG editor.  And when I reexport the image, the other elements are gone. But I cannot export image twice times every time, so do you have any idea to resolve this problem? 

Best regards!
Kai

**Comment by hbarsnes** [comment]
Hi Kai,

> But I cannot export image twice times every time, so do you have any idea to resolve this problem? 

I'm afraid there is not much we can do about this. At least I have not been able to figure out why this sometimes happens. As far as I know it does not always happen though, often it also works on the first attempt. But feel free to have a closer look at the code to see if you have better luck with locate the problem?

May I ask why you would need to export the spectra frequently as SVG files? Is there a particular use case where this is required? We assumed that this was only required when wanting to put a specific spectrum on a poster or similar and the image had to be edited in high resolution? And in that case, having to sometimes export twice is not a big issue?

Best regards,
Harald

**Comment by KenWifi** [comment]
Hi,

Thanks for your answer. I just use SVG sometimes and find this issue. That's all right, it's not a big problem!

Thank you again!
Best regards!
Kai

**Comment by hbarsnes** [comment]
Hi Kai,

> The other panel's table title paint in the picture sometimes.

I've looked into this issue now, and from what I can tell it is quite rare. I've only seen it once in 30+ image exports. So it seems to be a random event outside of our control. And given that it is easily fixed by simply exporting the image once more I will therefore close the issue. But do feel free to open a new issue if you come across other problems.

Best regards,
Harald
