### ISSUE TITLE
Maximal size of the database for FM index

### ISSUE THREAD

**Issue by dblyon** [compomics/peptide-shaker#229]
Dear Compomics-team,

I'm encountering errors when trying to process comet.pep.xml files with peptideShaker ("""An error occurred while loading the identification files"""). I've got 54 files, but for the sake of trying to figure out the error, I've been trying to process only a single file (tried different files, always the same error). Please find the error log below. 
**General infos about my data:**
Thermo Raw files from Q-exactive
converted to MGF using MS-convert with the following settings:
###
mgf=true
zlib=true
filter="peakPicking true [2,3]"
filter="titleMaker <RunId>.<ScanNumber>.<ScanNumber>.<ChargeState> File:"<SourcePath>", NativeID:"<Id>""
###
running on CentOS7 using current release of searchGUI and peptideShaker.

**How can I resolve this issue?? Any suggestions would be greatly appreciated!**

Best regards,
David

########################################################################
Tue Nov 22 10:05:12 CET 2016: PeptideShaker version 1.13.6.
Memory given to the Java virtual machine: 28631367680.
Total amount of memory in the Java virtual machine: 2024275968.
Free memory: 1950288344.
Java version: 1.8.0_102.
java.lang.NegativeArraySizeException
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:690)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1434)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1368)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:216)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:453)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:234)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:732)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:220)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:945)
Free memory: 5096832872
########################################################################

########################################################################
java -cp /home/projects/cu_10029/apps/PeptideShaker-1.13.6/PeptideShaker-1.13.6.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment "AnnaF_HOMD_SP_Vir_UPstyle_201607" -sample "HOMD_SP_Vir_UPstyle_201607" -replicate 1 -identification_files "/home/projects/cu_10029/data/ms/AnnaF/zippy/20160513_QE3_nLC5_RJC_COLLAB_GeoG_948_01.comet.pep.xml" -out "/home/projects/cu_10029/data/ms/AnnaF/pS_AnnaF_HOMD_SP_Vir_UPstyle_201607.cpsx" -spectrum_files "/home/projects/cu_10029/data/ms/AnnaF" -id_params "/home/projects/cu_10029/data/ms/AnnaF/zippy/param.par" -log "peptideShakerLog"
Tue Nov 22 10:37:26 CET 2016 Import process for AnnaF_HOMD_SP_Vir_UPstyle_201607 (Sample: HOMD_SP_Vir_UPstyle_201607, Replicate: 1)

Tue Nov 22 10:37:26 CET 2016 Importing sequences from HOMD_SP_Vir_UPstyle_201607_searchGUI_concatenated_target_decoy.fasta.
 0%
10%<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>

Tue Nov 22 10:38:18 CET 2016 An error occurred while loading the identification files:
Tue Nov 22 10:38:18 CET 2016 null
Tue Nov 22 10:38:18 CET 2016 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>
########################################################################

**Comment by mvaudel** [comment]
Dear David,

Many thanks for reporting this issue. It seems that the software has trouble indexing your sequence database. Is there anything special with this file? Would it be possible to share it with us?

Best regards,

Marc

**Comment by dblyon** [comment]
Dear Marc,

I can gladly share the fasta. It's a mix of UniProt entries from various species and entries from HOMD (Human Oral Microbiome Database). I've created custom headers a la searchGUI style (e.g. ">generic|001R_FRG3G") since they were not uniform. There are some redundant amino acid sequences in the fasta, but unique accession numbers. The file is 1.3 GB in size. I can send you a "wetransfer" unless you have a better way!?

I've also been having trouble with searchGUI (which might be due to the file storage solution on the server), but I double checked and used an mgf / comet.pep.xml file that had no issues completing.

Thank you for your support!!

Best,
David

**Comment by mvaudel** [comment]
Dear David,

Well, with a 1.3 GB fasta file, algorithms are not really operating in their comfort zone :) Any kind of transfer is fine by me, just don't forget to compress the file beforehand!

Best regards,

Marc

**Comment by dblyon** [comment]
Dear Marc,
I've sent you the files via "wetransfer" using this "marc.vaudel@biomed.uib.no" email. Did you get the email with the link? Should I send it to a different address? 

I'm trying to find a solution myself, but have been unsuccessful. I've repeated the steps of appending the decoy sequences and reindexing the fasta, and then tried to run peptideShaker with a .comet.pep.xml file (that didn't have any issues), but run into the same problems/error messages. I've done this independently on CentOS7 and Windows7. 

Best,
David

**Comment by mvaudel** [comment]
Hi David,

Thanks for the reminder. The notification landed in my spam folder. Will look at the database later today :)

Best regards,

Marc

**Comment by mvaudel** [comment]
Hi David,

Somehow there is a limit in our code that you cannot have more than approximately 2 billion amino acids. Your database contains 2,568,043,213 for 8,365,860 proteins. We can try to look into supporting larger databases but does it make sense? Do you really need that many sequences - and if yes, will the results make any sense at all? Would be much easier if you could manage to trim this database :-)

Best regards,

Marc

**Comment by dblyon** [comment]
Hi Marc,

**thank you for looking into this!!** 

Yes, I think this makes sense in specific scenarios. 
First, some sequences are redundant, which means that for these sequences only the fasta will be "big" but the search space will remain unaffected, only the protein-groups will be "larger". I can create a non-redundant fasta, but that will only affect a very small proportion of the sequences (since lots of them are similar but not identical in sequence and length). Something like UniRef90 would most probably dramatically reduce the size. There are non-UniProt sequences I have to include, and wouldn't I loose sequence variants when using UniRef90 or 50? I could run with an analogue of UniRef50, identify taxa, reduce the original search space and run the search again. But that is computationally expensive and might even lead to false assumptions.
**I agree that having a custom search space for a given sample would be preferable.** I'm already trying to do that with the fasta I'm using. The largest part of the fasta is composed of bacterial sequences from HOMD (Human Oral Microbiome Database) many of which could potentially be in there. 
I'm working on a bioinformatics solution to make sense of such data (metaproteomics data run against a "large" search space). **It would be extremely helpful if you could fix this peptideShaker restriction.** Other software packages/pipelines such as e.g. MaxQuant or ProteomeDiscoverer accept such fastas, but **I can't run them on a linux cluster and they don't come with some of the very nice features of searchGUI/peptideShaker.**

Best regards,
David

**Comment by mvaudel** [comment]
Hi David,

We will look into it but I cannot give you any timeline :)

In the meantime, there is something you can try: edit the _Identification Settings_, click on _Show Advanced Settings_, _Sequence Matching_, and select _Tree_ as index type. This index will take much more memory and is much slower, so not sure whether it will work, but it is worth a shot :)

Hope this helps,

Marc

**Comment by dblyon** [comment]
Hi Marc,

**## thank you for looking into it!!** 

I'm trying your suggestion, so far it hasn't run into errors ("estimated import time 54hours", so I'll update you when I have any news). 

I don't want to be rude, but I would like to suggest adding a warning message/test to searchGUI when utilising a "too large fasta". 

Best regards,
David

**Comment by dblyon** [comment]
Hi Marc,

I've tried your suggestion independently on a Windows 7 system (with 64GB RAM and 22 threads) and CentOS7 Linux (with 1TB RAM and 32 threads). It crashed on Windows and didn't complete on Linux after more than 12 days. 
Seems like this will not work for my data.

Best,
David

**Comment by mvaudel** [comment]
Hi David,

Really sorry to hear that this did not fix the issue. We will extend our index so that it can operate on such large databases but this is really not something trivial we can get done within a few weeks. We will come back to you when I have a time estimate. In the meantime, do you think it would be possible to use a simpler database?

Apologies for the inconvenience,

Marc

**Comment by hbarsnes** [comment]
Hi David,

We just released PeptideShaker v1.15.0 which should be able to support bigger FASTA files. Would be great if you could test the new version on your database and let us know?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.

**Comment by dblyon** [comment]
Hi Marc & Harald,

please excuse the late reply! 

# It works!! :)

I've used peptideShaker v.1.16.0. with the (previously described) large fasta and processed a single comet.pep.xml file. In short cpsx file generation (and report generation) works. 
Thank you for fixing the issue!!

Best regards,
David
