### ISSUE TITLE
Validating and exporting PSM from Mascot dat at 1% FDR

### ISSUE THREAD

**Issue by Fiona-dym** [compomics/peptide-shaker#230]
Dear Marc,

I made a database search on nearly totally 2000 spectra (I selected them on purpose) using Mascot, then used peptide-shaker to validate the PSM result at 1% FDR. 1846 of these spectra have one or more peptide matches in Mascot dat file. Some PSMs have a very high ion score and a very good e-value. But none of them were validated by peptide-shaker. The final PSM summary file is empty, only have the title line. while in the peptide summary file, some validated peptides' information presented.

So why those PSM with high ion score and good e-value are not validated by peptide-shaker? 

Best regards,
Aimee

**Comment by mvaudel** [comment]
Hi Aimee,

Can you provide more information on the database you use, does it contain decoy proteins? Also, did you have the "decoy" option of Mascot turned off?

You will find more input on compatibility with Mascot at the link below.
http://compomics.github.io/projects/peptide-shaker.html#mascot-support

Best regards,

Marc

**Comment by Fiona-dym** [comment]
Marc, 
I used search-gui to build up a new database containing decoy protein, and turned off the decoy option in Mascot parameter setting. 
Hope you can have a check on the files attached bellow for me. Thank you very much!

Aimee
[test.zip](https://github.com/compomics/peptide-shaker/files/623461/test.zip)

**Comment by hbarsnes** [comment]
Issue assume resolved in newer versions of PeptideShaker. If this is not the case, please let us know and we'll reopen the issue.
