### ISSUE TITLE
export to mzml stuck

### ISSUE THREAD

**Issue by u-n-i-c-s** [compomics/peptide-shaker#233]
Hi Marc,

I just repost my issue here (formerly in the google group).
UPDATE: I tried again to export to a mzid file but the process got stuck agian.
Here would be the bug report.
[PeptideShaker 1.13.6 log_Reinhard.txt](https://github.com/compomics/peptide-shaker/files/628788/PeptideShaker.1.13.6.log_Reinhard.txt)

I try to set the java settings now according to your recommendations:
maximum RAM available and on 64 bit.
Though, I have 16GB RAM, by default peptide shaker takes about 4.
____________________________

I searched a rather small dataset of 24 samples measured with an orbitrap XL and opened it in peptide shaker.
I ran into problems during several processes:
1. The dataset was processed, but the search gui output .zip would not open in peptide shaker. It said something like "annotation problems". Sorry that I do not have the report saved.
2. When exporting to PRIDE (into mzident), it got s
tuck at 86%. I waited now for almost an hour for the process to continue. I attached the screen shot, however, it is probably not very meaningful.

Is it due to the "big dataset"?
Should I split big datasets to several processes? Can I then submit it to PRIDE as one project?

Thank you for your answer.
Reinhard

**Comment by u-n-i-c-s** [comment]
Super! I changed the Java settings (-> 8GB RAM) in peptide shaker and the export worked now.
Thanks for that tipp.

**Comment by mvaudel** [comment]
Hi Reinhard,

From your log I see nothing wrong so I must say I have no clue what went wrong! But if increasing the memory given to the tool fixes the issue it is great. We cannot know how much memory is available on a given computer, that is why we default to 4. If you can use up to 16, the tool will be much faster :)

I will close this issue, should you encounter any problem don't hesitate to open a new one!

Best regards,

Marc
