### ISSUE TITLE
Object not found in cache when saving to the database

### ISSUE THREAD

**Issue by gerbenm** [compomics/peptide-shaker#235]
Hi Harald, Marc,

I'm rerunning some old experiments.
Shotgun experiment using a RIBO-seq derived protein search space concatenated with SwissProt.
Searches with SearchGUI went fine.
I think "PTM scoring" throws an error after a while, see report.

I the following dropbox, you can find the SearchGUI Zip file, the spectra (zippped) and the search_DB.
https://www.dropbox.com/sh/r91egrr0c1ocbhf/AABGhKa4DujwyjyETbU32G_Na?dl=0

Is it possible to have a look at this?
Many thanks in advance,
Gerben

[report_mESC_shotgun.txt](https://github.com/compomics/peptide-shaker/files/656833/report_mESC_shotgun.txt)

**Comment by mvaudel** [comment]
Hi Gerben,

Thanks for sharing the files with us, it looks like a problem with our database back-end. I am on it and should be sorted out very soon!

Best regards,

Marc

**Comment by gerbenm** [comment]
Hi Harald, Marc,

I wish the both of you a good 2017!

Any news on this bug?

Thanks in advance,
Cheers,
Gerben

**Comment by hbarsnes** [comment]
Hi Gerben,

No fix yet, but we've just found a dataset that fairly consistently produces the same error within minutes of starting the loading in PeptideShaker. So hopefully this will make it easier to track down and solve finally the issue. We'll keep you posted.

Best regards,
Harald

**Comment by gerbenm** [comment]
Hi Harald, 
Any progress on this bug?
I would like to use the PeptideShaker tool within a proteogenomics course I'm giving with this example case, that's why...
Sorry to disturb you again on this,
Enjoy the weekend,
gerben

**Comment by mvaudel** [comment]
Hi Gerben,

Sorry for the delay. I have been trying recently to load your dataset and it was working fine with my current version of the code. I am however jugling between different datasets that all result in this error for different reasons so it can be that I am wrong. Can you try the beta version at the link below and see if it works on your side?

http://vedlegg.uib.no/?id=5a27a519beee916e84077eaa19b4c709

Best regards,

Marc

**Comment by gerbenm** [comment]
Hi Marc,

I'm sorry but it still throws an error...
See attach,

Gr.ben

PS: Let me know if you need more information.

[PeptideShaker 1.15.0-SNAPSHOT log.txt](https://github.com/compomics/peptide-shaker/files/730198/PeptideShaker.1.15.0-SNAPSHOT.log.txt)

**Comment by gerbenm** [comment]
Hi Marc,

Just to test, I tried loading/searching all of my spectrums in one big mgf file, rather than uploading/searching them separately one by one (in total 46 mgfs).

Somehow I thought that might have had an impact, but no. The same error is thrown ...

Sorry,
Gerben

[PeptideShaker 1.14.6 log.txt](https://github.com/compomics/peptide-shaker/files/742088/PeptideShaker.1.14.6.log.txt)

**Comment by hbarsnes** [comment]
Hi Gerben.

We just released PeptideShaker v1.15.0 which hopefully solves the issue. Could you give it a go and let us know?

Best regards,
Harald

**Comment by gerbenm** [comment]
Sorry but no cigar...
Did you want me to rerun the search as well, or not necessary?

Let me know if I can do something to help.
Gerben

[PeptideShaker 1.15.0 log_bugreport.txt](https://github.com/compomics/peptide-shaker/files/742303/PeptideShaker.1.15.0.log_bugreport.txt)
[report_mESC_shotgun.txt](https://github.com/compomics/peptide-shaker/files/742302/report_mESC_shotgun.txt)

**Comment by hbarsnes** [comment]
Hi Gerben,

It's not the same error as before though. Hopefully that is good news. I will look into it and get back to you.

Best regards,
Harald

**Comment by gerbenm** [comment]
Hi Harald,

I tried rerunning it on the big MGF-file search results. Peptideshaker terminates without an error.
Let me first try and rerun both cases with the latest versions of SG and PS.
I'll provide you with the outcome shortly.

Thanks in advance,
Cheers,
Gerben

**Comment by gerbenm** [comment]
Hi Harald, Marc,

Working with the latest versions of SG and PS (3.2.6 and 1.15.0) everything works fine using the split mgf files.

Thanks a ton for resolving this issue!
Gerben
