### ISSUE TITLE
Can you copy a custom Export Feature report type to a different computer

### ISSUE THREAD

**Issue by 1Moe** [compomics/peptide-shaker#238]
Hi there,

I have made a custom report to export features in PeptideShaker. I would like to know if it is possible for me to transfer this custom report from my old computer to a new work computer without having to re-create the custom report.

Cheers
Moe

**Comment by mvaudel** [comment]
Hi Moe,

Allowing saving the report has long been on our list but we never got to it, sorry about that. I will try to look into it. In the meantime, you can try to copy the _exportFactory.cus_ of the _.peptideshaker_ folder of your user folder, hopefully that should be picked-up by the tool.

Best regards,

Marc
