### ISSUE TITLE
Export annotated MSMS spectra from comand line

### ISSUE THREAD

**Issue by videlc** [compomics/peptide-shaker#240]
Hey,

I was wondering if there was a command-line to extract annotated MSMS spectra.
The idea behind is to perfrom batch-retrieve from a specific list with target peptides id (many) MSMS spectra for manual validation (with fragment ions annotation) from a server without the need of opening cpsx file/search for peptide/export to pdf/png, which can be time consuming when there are hundreds cpsx files and thousands of desired MSMS spectra.

Best regards,
Vivian

**Comment by hbarsnes** [comment]
Hi Vivian,

I'm afraid there is currently no support for this kind of feature. We may consider it in the future, but it sounds more like something that fits into a LIMS system than into PeptideShaker itself? Maybe you should look into colims (http://compomics.github.io/projects/colims.html) and request such a feature there?

Best regards,
Harald

**Comment by mvaudel** [comment]
Hi Vivian,

In addition to what Harald pointed, note that you can export the fragment ions found for every PSM as export, maybe that would help for your QC?

Best regards,

Marc

**Comment by videlc** [comment]
Hey Marc and Harald,

Thanks for your answers ! Indeed, this kind of feature would help ! Is there a command line to do it for each cpsx file we got ? I could just extract ion informations out of these files to script "rebuild" spectra as a graph on my own with R for example.

Thanks a lot !
Vivian

**Comment by mvaudel** [comment]
Hi Vivian,

Yes, you can create your own export and run it in command line on your cps files using the [ReportCLI](https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI#b---reportcli). That said it might be easier to annotate the spectra directly in R ;)

Hope this helps,

Marc
