### ISSUE TITLE
Error while re-saving Andromeda results obtained via SearchGUI

### ISSUE THREAD

**Issue by animesh** [compomics/peptide-shaker#241]
Dear Developers,

I face an error while saving, screenshot:

Inline image 1
![image](https://cloud.githubusercontent.com/assets/21457/22586857/5c797a60-e9ff-11e6-8156-b5b925aa7d14.png)

Essentially want to visualize MaxQuant search results using Peptide Shaker, so I re-ran (is it possible to directly import MaxQuant search results BTW?) using Andromeda via SearchGUI (parameter etc in autogen "Method" section below). 

The results were successfully generated and opened with Peptide Shaker, however i hit this issues while re-saving the results.

Further I see difference in number of peptides reported between direct MaxQuant search and Andromeda+SearchGUI, any ideas why that be? 

Another attempt to re-save got stuck mid-way. so probably 
[PeptideShaker 1.15.0 log.txt](https://github.com/compomics/peptide-shaker/files/750065/PeptideShaker.1.15.0.log.txt) log may not be so useful anymore? None the less, I am attaching the same.

Best regards,

Ani

Method:

Protein Identification

          Peak lists obtained from MS/MS spectra were identified using Andromeda version 1.5.3.4 [PMID 21254760].The search was conducted using SearchGUI version [add version] [PMID  21337703].
          Protein identification was conducted against a concatenated target/decoy [PMID 20013364] version of the Homo sapiens complement of the UniProtKB [PMID 14681372] (version of [add database version] , 70953 (target) sequences).The decoy sequences were created by reversing the target sequences in SearchGUI. The identification settings were as follows: Trypsin, Specific, with a maximum of 2 missed cleavages20.0 ppm as MS1 and 0.02 Da as MS2 tolerances; fixed modifications: Carbamidomethylation of C (+57.021464 Da),  variable modifications: Acetylation of protein N-term (+42.010565 Da), Deamidation of N (+0.984016 Da), Deamidation of Q (+0.984016 Da), Oxidation of M (+15.994915 Da), fixed modifications during refinement procedure: Carbamidomethylation of C (+57.021464 Da), . All algorithms specific settings are listed in the Certificate of Analysis available in the supplementary information.
          Peptides and proteins were inferred from the spectrum identification results using PeptideShaker version 1.15.0 [PMID 25574629]. Peptide Spectrum Matches (PSMs), peptides and proteins were validated at a 1.0% False Discovery Rate (FDR) estimated using the decoy hit distribution. All validation thresholds are listed in the Certificate of Analysis available in the supplementary information. Post-translational modification localizations were scored using the D-score [PMID 23307401] and the phosphoRS score [PMID 22073976] with a threshold of 95.0 as implemented in the compomics-utilities package [PMID 21385435].A phosphoRS score above was considered as a confident localization. 
          The mass spectrometry data along with the identification results have been deposited to the ProteomeXchange Consortium [PMID 24727771] via the PRIDE partner repository [PMID 16041671] with the dataset identifiers [add dataset identifiers]. During the review process, the data can be accessed with the following credentials upon login to the PRIDE website (http://www.ebi.ac.uk/pride/archive/login): Username: [add username here], Password: [add password here].

**Comment by hbarsnes** [comment]
> Copied from the PeptideShaker Google group:

Hi Animesh,

Would it be possible for you to send us the log? You can find it in the "Help" -> "Bug Report" menu. To help us keeping track of the problem, would be great if you could set up an issue in Github as well.

The main difference between your results as seen in PeptideShaker and MaxQuant is that we don't do any preprocessing, so the mass resolution is not as good as in MaxQuant. It is currently not possible to open MaxQuant results in PeptideShaker directly. It is in discussion between our two teams, though :)

Best regards from Bergen!

Marc

**Comment by hbarsnes** [comment]
Issue assume resolved in later versions of PeptideShaker when cleaning up the backend code. If this is not the case, please let us know and we'll reopen the issue.

**Comment by animesh** [comment]
Thanks for the update Harald :) Any news on supporting MaxQuant results?

Regards from Sunny Trondheim ;)

Regards,

Ani


--------------------------"The Answer Lies In The
Genome"--------------------------

**Comment by hbarsnes** [comment]
Hi Animesh,

> Any news on supporting MaxQuant results?

Not until MaxQuant starts supporting a standard output format like mzIdentML. And in any case we would need to rewrite the backend to support other spectrum types than mgf. So won't happen in the near future I think.

Best regards from Sunny Bergen. ;)
Harald
