### ISSUE TITLE
export to mzIdentML throws error

### ISSUE THREAD

**Issue by gerbenm** [compomics/peptide-shaker#242]
Hi Harald, Marc,

Sorry to disturb again...
I'm trying to export my proteogenomics project as mzIdentML (v1.1) (in order to convert to proBAM).
This throws an error at around 72% of completion:

[PeptideShaker 1.15.0 log_export_to_mzIdentML.txt](https://github.com/compomics/peptide-shaker/files/750702/PeptideShaker.1.15.0.log_export_to_mzIdentML.txt)

I placed the project ZIP file on:
https://www.dropbox.com/s/chbquoy9h2vamz5/mESC_proteoformer_swiss_shotgun_allmgf.zip?dl=0

Thanks for your input,
Cheers,
Gerben

**Comment by hbarsnes** [comment]
Hi Gerben,

Thanks for telling us about this. I have the same error on my side. Will look into it and get back to you.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Gerben,

This issue has been resolved in PeptideShaker v1.15.1.

Best regards,
Harald
