### ISSUE TITLE
Combined searching of DIA umpire mgf files

### ISSUE THREAD

**Issue by 1Moe** [compomics/peptide-shaker#243]
Hi Harald and Marc,

thanks for your continued efforts to improve SearchGui and PeptideShaker - they are both great tools and I love using them.

I have recently tried DIA-umpire to extract some pseudo MS/MS spectra from my DIA SWATH files (TripleTof 5600 wiff files). DIA umpire puts out 3 mgf files per 1 input file and the DIA umpire instructions say this: 

> Each file corresponds to a different “quality level” of precursor ions (Q1= More than two isotopic peaks detected in MS1, Q2 = only two isotopic peak detected, Q3 = detected unfragmented precursor in MS2). **These spectra are written to separate files, because they must be searched separately against a protein database as a consequence of differences in FDR estimates for these varying quality data.**

I also found some info on the MatrixScience webpage suggesting using Q1 and Q3 together for best results http://www.matrixscience.com/blog/searching-dia-data-especially-swath.html

I'm now wondering if you could let me know the best strategy (in your opinion) to analyse the DIA umpire mgf files using searchgui and PS. 

1) Do I have to search the 3 mgf files (coming from the same wiff file) separately and load together into peptideshake or can I search the 3 files together?

2) I have 50 biological samples with 3 technical replicates (3 injections per sample from the same tube). In theory I could generate 3x50x3 = 450 mgf files using DIA umpire. What would be the best combination to build a spectral library for DIA? 

3) I tried searching the 3 mgf files together, comparing X!tandem and comet. Comet was the clear winner in terms of protein IDs - 9 IDs for Xtandem vs 127 IDs for Comet. Would you know the reason for this vast difference?

I have posted this here as well https://github.com/BioContainers/specs/issues/73 to ask for the best strategy to search multiple mgf files.

Cheers
Moe

**Comment by mvaudel** [comment]
Hi Moe,

Thank you for the kind words on our work! 

1- You can search and run Q1-3 in SearchGUI+PeptideShaker. If there are enough ids, PeptideShaker will score and threshold them separately automatically. 

2- If you have different replicates, you need to make different PeptideShaker projects. I am afraid at the moment we don't have any quantification tool that would allow to compare the results between replicates. For this we use MaxQuant.

3- This is rather surprising, in our hands X!Tandem performs very well. Maybe it is a problem with the search parameters? Did you try other search engines like Myrimatch or ms-gf+? In general, when evaluating the performance of identification tools I would recommend to compare at the PSM level in order to avoid protein inference issues.

Hope this helps,

Marc

**Comment by mvaudel** [comment]
Hi again,

Something that could explain the difference between X!Tandem and Comet is the tolerance on the precursor. If I recall correctly X!Tandem assumes that you have the monoisotopic peak while Comet has a tolerance of several daltons. If DIA-umpire struggles at finding the monoisotopic peak it can be that it gets rescued by Comet and not X!Tandem. Maybe something similar could happen with the charge. The best is to look at some spectra confidently identified by only one algorithm and try to find such differences. 

Hope this helps,

Marc

**Comment by 1Moe** [comment]
Thank you all for your help and quick reply!

Please see below for my response and also related to this, do you still recommend going from wiff to mzmL via the Sciex converter and then from mzML to mzXML via msconvert?

    I'll search the 3 mgf files together

    yes, I'd like to build a DIA derived library for import into skyline - especially for retention time standards. As you said, I'm also not sure what is to be gained in terms of more IDs from running multiple samples together in 1 search.

    see link https://drive.google.com/drive/folders/0BybCLLWRgDsUX2VTc0F1ZlpCMnM containing
    a) the parameters for X!tandem and Comet for SearchGUI
    b) the certificate of analysis and report from peptideshaker
    c) the 3 mgf files from 1 wiff file (wiff - mzML - mzXML - mgf)

Regards
Moe
