### ISSUE TITLE
mvn compile errors

### ISSUE THREAD

**Issue by wolski** [compomics/peptide-shaker#244]
First:

Trying Could not find artifact com.compomics:utilities:jar:4.11.1 in genesis-maven2-repository (http://genesis.UGent.be/maven2) -> [Help 1]

Fixed by editing pom to 4.11.0 (not sure if good idea)

Next error I am running into is:
 mvn compile -U -e

...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5:compile (default-compile) on project PeptideShaker: Compilation failure: Compilation failure:
[ERROR] bootstrap class path not set in conjunction with -source 1.6
[ERROR] C:\Users\wolski\prog\peptide-shaker\src\main\java\eu\isas\peptideshaker\parameters\PeptideShakerSettings.java:[5,37] [deprecation] PSProcessingPreferences in com.compomics.util.preferences has been deprecated
...

Thank you.

**Comment by hbarsnes** [comment]
Hi,

We're in the process of deploying utilities v4.11.1, should be online later today. That should solve the problem. Reverting to v4.11.0 will probably not work as there are more likely some code changes that are not backwards compatible.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

Utilities v4.11.1 has now been deployed, so you should be able to build PeptideShaker again. Please let us know if this is not the case and we'll reopen the issue.

Best regards,
Harald
