### ISSUE TITLE
Viewing Peptide shaker mzIdentML project in Scaffold

### ISSUE THREAD

**Issue by fazeliniah** [compomics/peptide-shaker#252]
Hi ,
Is there any way to view PeptideShaker's project in Scaffold? I exported the PeptideShaker project as mzIdentML but when I tried to open the file in Scaffold, it complained that there is no decoys in the search results. How can I view/export the decoy information in the mzIdentML file?
I hardly used scaffold but one of our Proteomics Core clients insists to receive his data to be viewed using Scaffold. 
Thanks for your help. 
H

**Comment by hbarsnes** [comment]
Hi H,

If Scaffold supports mzIdentML as input you should be able to open the PeptideShaker exported mzIdentML files as well. It could be that Scaffold has to adjust their mzIdentML reader to be able to extract all the relevant parts of the file though.

As to the inclusion of decoys in the PeptdeShaker mzIdentML files, the decoys are included by default, assuming that you added decoys as part of the search carried out before processing the data in PeptideShaker. But again it could be that Scaffold requires the decoys to be annotated in a certain non-standard way.

I'd recommend contacting the Scaffold support for details about this.

You may also want to check if Scaffold requires that you included the complete protein sequences in the mzIdentML file. These are not added by default but can easily be added by selecting the "Include Protein Sequences" option towards the bottom of the mzIdentML export dialog in PeptideShaker.

> I hardly used scaffold but one of our Proteomics Core clients insists to receive his data to be viewed using Scaffold.

Have you tried sending them the zipped PeptideShaker project instead? Perhaps they will end up preferring this option instead..? ;-)

Best regards,
Harald

**Comment by fazeliniah** [comment]
You can count on me as an advocate for Peptide Shaker. Keep up the good work :)

**Comment by hbarsnes** [comment]
> You can count on me as an advocate for Peptide Shaker. Keep up the good work :)

Thanks! :)
