### ISSUE TITLE
PTMs disappearing after minor change in search settings

### ISSUE THREAD

**Issue by akwalker** [compomics/peptide-shaker#254]
I am not sure if this is a PS or a SG problem. I have a search in SearchGUI using tandem. I have 6 or 7 variable mods and one fixed on cysteine. Each of these mods has PSM matches when I view the results in PeptideShaker. I have Oxidized Met, Dioxidized Trp, deamidation on N and Q, carbamyl on peptide nterm, and a variable mod on Lys (crosslinker). 

Looking for crosslinks, I only want the peptides with that mod on Lysine so I set it to fixed instead of variable and repeat the search. When I import these results into PS, now oxidation of Met, oxidation of Trp, and deamidation of N and Q report no PSMs. 

I know from the first search that there should still be peptides (either with no lys or mod lys) with some of these PTMs. 

How does changing one PTM from variable to fixed cause me to loose all PSMs with oxidation and deamidation? I actually see this quite frequently but seemingly random. I will have a pretty good search result, then change one setting and suddenly, I have modifications with no PSMs.

**Comment by mvaudel** [comment]
When searching with a fixed modification, the search engines will try their best to match spectra to modified peptides. This has two consequences if your peptides are not all modified: (1) you will not find the non modified peptides and (2) the algorithm will still try to match spectra from non modified peptides to a modified sequence.

If not all peptides are modified, the search engines will therefore force the spectra obtained on non-modified peptides and create false positive IDs. With a higher prevalence of false positives, your identification rate at 1% FDR will therefore fall down.

It is the same as with contaminants, if you don't include contaminants to your database the spectra from contaminants will be incorrectly matched to your sequences. You will find more literature on this at the link below.
https://www.ncbi.nlm.nih.gov/pubmed/21695130

For this reason, we use fixed modifications only for modifications that appear on over 98% of the possible targets. You can find these metrics in the QC plots.

Hope this helps,

Marc
