### ISSUE TITLE
selenocysteine analysis

### ISSUE THREAD

**Issue by jflucier** [compomics/peptide-shaker#255]
Hi,

i am trying to analyse a sample using Selenocysteine as variable mods. Here is the mods string passed to IdentificationParametersCLI:

export __COMET_NUM_PTMS="5"
export __COMET_REMOVE_METH="1"
export __ENZYME_LIST="Trypsin"
export __FIXED_MODS="Carbamidomethylation of C"
export __FRAG_TOL="0.1"
export __MAX_CHARGE="5"
export __MS_AMANDA_INSTRUMENT="b, y, -H2O, -NH3"
export __MS_LOW_MEM_MODE="0"
export __MSGF_INSTRUMENT="2"
export __MSGF_NUM_PTMS="5"
export __MYRIMATCH_NUM_PTMS="5"
export __FRAG_TOL="0.1"
export __FRAG_PPM="0"
export __PREC_PPM="0"
export __PREC_TOL="0.006"
export __TIDE_NUM_PTMS="5"
export __TIDE_USE_NEUTRAL_LOSSES="1"
export __VARIABLE_MODS="Oxidation of M, FormylMet of protein N-term, Formylation of peptide N-term, Phosphorylation of S, Phosphorylation of T, Phosphorylation of Y, **Selenocysteine**"
export __XTANDEM_MIN_FRAG_MZ="50"

echo "Generating SearchGUI parameter file"
java -cp $SEARCHGUI_JAR_PATH eu.isas.searchgui.cmd.IdentificationParametersCLI \
-ms_low_mem_mode $__MS_LOW_MEM_MODE \
-max_charge $__MAX_CHARGE \
-xtandem_min_frag_mz $__XTANDEM_MIN_FRAG_MZ \
-msgf_num_ptms $__MSGF_NUM_PTMS \
-myrimatch_num_ptms $__MYRIMATCH_NUM_PTMS \
-ms_amanda_instrument "'$__MS_AMANDA_INSTRUMENT'" \
-comet_num_ptms $__COMET_NUM_PTMS \
-comet_remove_meth $__COMET_REMOVE_METH \
-tide_num_ptms $__TIDE_NUM_PTMS \
-tide_use_neutral_losses $__TIDE_USE_NEUTRAL_LOSSES \
-db $TEMPDIR/db/searchgui_db_concatenated_target_decoy.fasta \
-out $TEMPDIR/searchgui.parameters \
-enzyme "$__ENZYME_LIST" \
-fixed_mods '"'"$__FIXED_MODS"'"'  \
-variable_mods '"'"$__VARIABLE_MODS"'"' \
-frag_tol $__FRAG_TOL \
-frag_ppm $__FRAG_PPM \
-prec_tol $__PREC_TOL \
-prec_ppm $__PREC_PPM \
-protein_fdr 0.001 \
-msgf_instrument $__MSGF_INSTRUMENT > $OUTPUT_DIR/logs/IdentificationParametersCLI_run.log 2>&1

this return me the following error:

An error occurred while parsing the variable modifications:
PTM Selenocysteine not found.

Available Modifications:

Default Modifications:
18O(1) of peptide C-term        (+2.004246 targeting Peptide C-terminus)
18O(2) of peptide C-term        (+4.008493 targeting Peptide C-terminus)
4-Hydroxyproline        (+83.073499 targeting P)
Acetaldehyde +26        (+26.01565 targeting Peptide N-terminus)
Acetylation of K        (+42.010565 targeting K)
Acetylation of peptide N-term   (+42.010565 targeting Peptide N-terminus)
Acetylation of protein N-term   (+42.010565 targeting Protein N-terminus)
Amidation of the peptide C-term (-0.984016 targeting Peptide C-terminus)
Amidation of the protein C-term (-0.984016 targeting Protein C-terminus)
Arginine 13C(6) (+6.020129 targeting R)
Arginine 13C(6) 15N(4)  (+10.008269 targeting R)
Carbamidomethylation of C       (+57.021464 targeting C)
Carbamidomethylation of E       (+57.021464 targeting E)
Carbamidomethylation of K       (+57.021464 targeting K)
Carbamilation of K      (+43.005814 targeting K)
Carbamilation of protein N-term (+43.005814 targeting Protein N-terminus)
Carboxymethylation of C (+58.005479 targeting C)
Deamidation of N        (+0.984016 targeting N)
Deamidation of N 18O    (+2.988262 targeting N)
Deamidation of Q        (+0.984016 targeting Q)
Dehydration of S        (-18.010565 targeting S)
Dehydration of T        (-18.010565 targeting T)
Didehydro of T  (-2.01565 targeting T)
Diiodination of Y       (+251.793296 targeting Y)
Dimethylation of K      (+28.0313 targeting K)
Dimethylation of K 2H(6)        (+34.068961 targeting K)
Dimethylation of K 2H(6) 13C(2) (+36.07567 targeting K)
Dimethylation of R      (+28.0313 targeting R)
Dimethylation of peptide N-term (+28.0313 targeting Peptide N-terminus)
**...**
Pyrolidone from carbamidomethylated C   (-17.026549 targeting Peptide N-terminus starting with C)
SUMO-2/3 Q87R   (+471.207761 targeting K)
Sodium adduct to D      (+21.981944 targeting D)
Sodium adduct to E      (+21.981944 targeting E)
Sulfonation of S        (+79.956815 targeting S)
Sulfonation of T        (+79.956815 targeting T)
Sulfonation of Y        (+79.956815 targeting Y)
TMT 10-plex of K        (+229.162932 targeting K)
TMT 10-plex of peptide N-term   (+229.162932 targeting Peptide N-terminus)
TMT 2-plex of K (+225.155833 targeting K)
TMT 2-plex of peptide N-term    (+225.155833 targeting Peptide N-terminus)
TMT 6-plex of K (+229.162932 targeting K)
TMT 6-plex of peptide N-term    (+229.162932 targeting Peptide N-terminus)
Thioacyl of peptide N-term      (+87.998286 targeting Peptide N-terminus)
Trideuterated Methyl Ester of D (+19.05013 targeting D)
Trideuterated Methyl Ester of E (+17.03448 targeting E)
Trideuterated Methyl Ester of K (+17.03448 targeting K)
Trideuterated Methyl Ester of R (+17.03448 targeting R)
Trideuterated Methyl Ester of peptide C-term    (+17.03448 targeting Peptide N-terminus)
Trimethylation of K     (+42.04695 targeting K)
Trimethylation of R     (+42.04695 targeting R)
Trimethylation of protein N-term A      (+42.04695 targeting Protein N-terminus)
Trioxidation of C       (+47.984744 targeting C)
Ubiquitination of K     (+114.042927 targeting K)
iTRAQ 4-plex of K       (+144.102062 targeting K)
iTRAQ 4-plex of Y       (+144.102062 targeting Y)
iTRAQ 4-plex of peptide N-term  (+144.102062 targeting Peptide N-terminus)
iTRAQ 8-plex of K       (+304.199039 targeting K)
iTRAQ 8-plex of Y       (+304.199039 targeting Y)
iTRAQ 8-plex of peptide N-term  (+304.199039 targeting Peptide N-terminus)
mTRAQ of 13C(6) 15N(2)  (+148.109162 targeting K)
mTRAQ of K 13C(3) 15N   (+144.102062 targeting K)
mTRAQ of K light        (+140.094963 targeting K)
mTRAQ of peptide N-term 13C(3) 15N      (+144.102062 targeting Peptide N-terminus)
mTRAQ of peptide N-term 13C(6) 15N(2)   (+148.109162 targeting Peptide N-terminus)
mTRAQ of peptide N-term light   (+140.094963 targeting Peptide N-terminus)

Selenocysteine is not in the list of mods outputted. SearchGUI version currently in use is SearchGUI-3.1.0 and peptideshaker is 1.13.4

On the release information page, its written that selenocysteine support was added on release PeptideShaker 0.17.2

thank again for your help.

**Comment by mvaudel** [comment]
Hi JF,

Yes we added support for Selenocysteine, but as amino acid, not as modification. Would you like to have a C -> U modification as well?

Best regards,

Marc

**Comment by jflucier** [comment]
oh... that explains it. 

Is it easy for you guys to introduce this new modification C->U? I know there is a method within the compomics pipeline to create our own modifications but you will have to guide me on how to do this if that is easy and ok for you.

tks so much Marc.

JF

**Comment by mvaudel** [comment]
I must say I am not familiar with selenocysteine analyses. If it is standard to have it as modification and not in the database it makes sense to add it by default. I will look into it.

Best regards,

Marc

**Comment by jflucier** [comment]
another solution i can think of would be to add entries in my fasta where each sequence with cysteine is duplicated to included selenocysteine instead of cysteine... Do you think this would work? 

We are trying to figure out if proteins incorporated selenocysteine in a new organism we did MS on. 

I will wait for your advise before launching the analysis.

tks again Marc.

**Comment by mvaudel** [comment]
Hi again,

Yes then it makes perfect sense to add it as modification. We will need a few days to release new versions but I can send you a plugin with the modification tomorrow :)

Best regards,

Marc

**Comment by jflucier** [comment]
your awesome... will wait for that plugin.

tks so much once more Marc.

**Comment by mvaudel** [comment]
Hi again,

You will find a patch containing the modification at the link below.
http://vedlegg.uib.no/?id=68eb135a6c2318c8c07a485d44f21e0e

If you are using the tool from the GUI, please select the file as _ptm_configuration_ in the _Resources Settings_.

If you are using the tool in command line, please select the file using the _-ptm_configuration_ option.

The modification _Selenocysteine_ should be available as S -> Se exchange in C. 

It is the first time I use this patching option that I wrote several years ago, so cannot ensure that it will work at first try...

Hope this helps, we will release new versions with the modifications implemented very soon.

Best regards,

Marc

**Comment by jflucier** [comment]
Hi Marc,

tks for quick response and patch... amazing support as usual. I have some last questions. As you maybe remember, I am running SearchGUI and PeptideShaker on an HPC cluster. To test patch sent, i have copied SearchGUI and PeptideShaker install directory to a temp folder and run the following command:

[jflucier@ip32 softwares]$ java -cp SearchGUI-latest/SearchGUI-latest.jar eu.isas.searchgui.cmd.PathSettingsCLI -ptm_configuration ptmFactory-4.12.0.json
Path configuration completed.

This seem to have worked. Afterwards, when i run :

[jflucier@ip32 softwares]$ java -cp SearchGUI-latest/SearchGUI-latest.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -mods

I still get same mods output as before. So my guess is that i have to run PathSettingsCLI each time I want SearchGUI and PeptideShaker to detect selenocysteine. Is that right? Do I need to specify selenocysteine in the variable mods parameter? Probably not since it is not outputted as valid mods by IdentificationParametersCLI.... 

I am asking this to know if PathSettingsCLI alters the SearchGUI and PeptideShaker install directory by adding some files to it (json file). I need to know because the first step of my analysis pipeline is to copy the SearchGUI and PeptideShaker install directory to the compute node. So on the compute node, do i need to run PathSettingsCLI or if i already runned it on our main install directory (the directory that is copied to the compute node), the patch will be already applied when i transfert code to compute nodes.

Sorry if post not clear. Do not hesitate to ask me to elaborate more if needed.

tks again Marc for all your help.

JF

**Comment by mvaudel** [comment]
Hi again,

Yes I remember the HPC, I often show your specs to impress people!

You are correct that running the PathSettingsCLI alters the installation. Running it is however not necessary, you can use the command line argument directly in the SearchCLI command line. I don't think that the -mods command takes the path into account - I would need to look into this.

Hope this will work,

Marc

**Comment by jflucier** [comment]
perfect will try this out by passing directly to SearchCli... think its the easier and cleaner way to integrate to my pipeline. Do i need to provide a string specifying selenocysteine in the variable mods parameter? 

After this answer, i think i will be all set.

tks again Marc.

JF

**Comment by mvaudel** [comment]
Yes, just use it as a normal variable modification. The name I used is "Selenocysteine" with capital 'S'. We will release new versions soon where this will be implemented by default. But if this works you can implement virtually any modification by including it in the json file you pass to in command line :)

Thank you for your patience and the thorough testing,

Marc

**Comment by jflucier** [comment]
Hi again Marc,

I tired passing the -ptm_configuration to SearchCli and it returns Unrecognized option... see below:

[jflucier@ip32 20160723_2D_SRodrigue_ALL]$ java -Xmx27G -cp $SEARCHGUI_JAR_PATH eu.isas.searchgui.cmd.SearchCLI -spectrum_files "$TEMPDIR/${__IN_DATASET_NAME}.mgf" -output_folder $TEMPDIR/search_results/ -temp_folder $TEMPDIR/ -id_params $TEMPDIR/searchgui.parameters.par -andromeda 0 -omssa 1 -xtandem 1 -msgf 1 -ms_amanda 0 -myrimatch 1 -comet 1 -ptm_configuration /netmount/ip32_home/jflucier/analysis/mass_spec/matteau/ptmFactory-4.12.0.json -tide 0
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -ptm_configuration
	at org.apache.commons.cli.Parser.processOption(Parser.java:363)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at eu.isas.searchgui.cmd.SearchCLI.<init>(SearchCLI.java:83)
	at eu.isas.searchgui.cmd.SearchCLI.main(SearchCLI.java:401)
[jflucier@ip32 20160723_2D_SRodrigue_ALL]$ java -Xmx27G -cp $SEARCHGUI_JAR_PATH eu.isas.searchgui.cmd.SearchCLI -spectrum_files "$TEMPDIR/${__IN_DATASET_NAME}.mgf" -output_folder $TEMPDIR/search_results/ -temp_folder $TEMPDIR/ -id_params $TEMPDIR/searchgui.parameters.par -andromeda 0 -omssa 1 -xtandem 1 -msgf 1 -ms_amanda 0 -myrimatch 1 -comet 1 -ptm_configuration /netmount/ip32_home/jflucier/analysis/mass_spec/matteau/ptmFactory-4.12.0.json -tide 0
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -ptm_configuration
	at org.apache.commons.cli.Parser.processOption(Parser.java:363)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at eu.isas.searchgui.cmd.SearchCLI.<init>(SearchCLI.java:83)
	at eu.isas.searchgui.cmd.SearchCLI.main(SearchCLI.java:401)
  
I am not using the latest SearchGUI v3.2.11 but 3.1.0, could this paprameter support be added after 3.1.0? 

Thanks again Marc.

**Comment by jflucier** [comment]
ok sorry for spam... I installed v3.2.11 and passing the -ptm_configuration and -variable_mods string directly to SearchCli (not via IdentificationParametersCLI) seem to have done the trick using v3.2.11.

Will keep you informed when i get results. tks again Marc.

**Comment by mvaudel** [comment]
Hi JF,

This sounds great, let's hope it works! I will keep you posted with our progress of making new releases :)

Best regards,

Marc

**Comment by jflucier** [comment]
Hi Marc, just to mention that this patch json file work with latest version of PeptideShaker also. Doesnt work with version PeptideShaker-1.13.4, it throws an error enzyme not found. 

When i run using PeptideShaker-1.16.3, it starts running and crashes after a while. Its fail when loading identification files. Here is the log:

[jflucier@ip32 20160723_2D_SRodrigue_ALL]$ java -Xmx27G -cp /ltmp/jflucier/temp_ms/20160723_2D_SRodrigue_ALL/softwares/PeptideShaker-1.16.3/PeptideShaker-1.16.3.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -temp_folder $TEMPDIR/PeptideShaker_temp -experiment $__IN_DATASET_NAME  -sample sample -replicate 1 -id_params $TEMPDIR/searchgui.parameters.par -identification_files "$TEMPDIR/search_results/searchgui_out.zip" -spectrum_files "$TEMPDIR/${__IN_DATASET_NAME}.mgf" -ptm_configuration /netmount/ip32_home/jflucier/analysis/mass_spec/matteau/ptmFactory-4.12.0.json -out "$TEMPDIR/shaker_results/${__IN_DATASET_NAME}.cpsx" variable_mods "Oxidation of M, FormylMet of protein N-term, Formylation of peptide N-term, Phosphorylation of S, Phosphorylation of T, Phosphorylation of Y, Selenocysteine"
Path configuration completed.
Failed to write in the following configuration folders. Please use a temporary folder, the path configuration command line, or edit the configuration paths from the graphical interface.
ptm_configuration: Folder containing the supported PTMs.
Mon Mar 27 10:23:36 EDT 2017 Unzipping searchgui_out.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Mon Mar 27 10:26:02 EDT 2017 Import process for 20160723_2D_SRodrigue_ALL (Sample: sample, Replicate: 1)

Mon Mar 27 10:26:02 EDT 2017 Importing sequences from searchgui_db_concatenated_target_decoy.fasta.
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
Mon Mar 27 10:26:02 EDT 2017 An error occurred while loading the identification files:
Mon Mar 27 10:26:02 EDT 2017 Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.init(FMIndex.java:472)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:386)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1447)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1380)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:209)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:443)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:152)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:750)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:221)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:950)
Free memory: 1864700984
Mon Mar 27 10:26:02 EDT 2017 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>
[jflucier@ip32 20160723_2D_SRodrigue_ALL]$ java -Xmx27G -cp /ltmp/jflucier/temp_ms/20160723_2D_SRodrigue_ALL/softwares/PeptideShaker-1.16.3/PeptideShaker-1.16.3.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -temp_folder $TEMPDIR/PeptideShaker_temp -experiment $__IN_DATASET_NAME  -sample sample -replicate 1 -id_params $TEMPDIR/searchgui.parameters.par -identification_files "$TEMPDIR/search_results/searchgui_out.zip" -spectrum_files "$TEMPDIR/${__IN_DATASET_NAME}.mgf" -ptm_configuration /netmount/ip32_home/jflucier/analysis/mass_spec/matteau/ptmFactory-4.12.0.json -out "$TEMPDIR/shaker_results/${__IN_DATASET_NAME}.cpsx" variable_mods "Oxidation of M, FormylMet of protein N-term, Formylation of peptide N-term, Phosphorylation of S, Phosphorylation of T, Phosphorylation of Y, Selenocysteine"
Path configuration completed.
Failed to write in the following configuration folders. Please use a temporary folder, the path configuration command line, or edit the configuration paths from the graphical interface.
ptm_configuration: Folder containing the supported PTMs.
Mon Mar 27 10:23:36 EDT 2017 Unzipping searchgui_out.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Mon Mar 27 10:26:02 EDT 2017 Import process for 20160723_2D_SRodrigue_ALL (Sample: sample, Replicate: 1)

Mon Mar 27 10:26:02 EDT 2017 Importing sequences from searchgui_db_concatenated_target_decoy.fasta.
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
Mon Mar 27 10:26:02 EDT 2017 An error occurred while loading the identification files:
Mon Mar 27 10:26:02 EDT 2017 Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.init(FMIndex.java:472)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:386)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1447)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1380)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:209)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:443)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:152)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:750)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:221)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:950)
Free memory: 1864700984
Mon Mar 27 10:26:02 EDT 2017 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>

At the beginning it throws a warning saying it cant write to configuration folders the ptm_configuration folder... if i understood well. Dont think it picks up my -temp_folder argument from PeptideShaker command (-temp_folder $TEMPDIR/PeptideShaker_temp), but might be wrong. i look at  temp folder after crash and it does write inside it:

[jflucier@ip32 20160723_2D_SRodrigue_ALL]$ ll $TEMPDIR/PeptideShaker_temp/*
-rw-rw-r-- 1 jflucier xroucou 2286 Mar 27 10:43 /ltmp/jflucier/temp_ms/20160723_2D_SRodrigue_ALL/PeptideShaker_temp/utilities_userpreferences.cup
/ltmp/jflucier/temp_ms/20160723_2D_SRodrigue_ALL/PeptideShaker_temp/fasta_indexes:
total 0
/ltmp/jflucier/temp_ms/20160723_2D_SRodrigue_ALL/PeptideShaker_temp/gene_mapping:
total 3035
-rw-rw-r-- 1 jflucier xroucou      65 Mar 27 10:47 ensembl_versions
-rw-rw-r-- 1 jflucier xroucou    5401 Mar 27 10:47 go_domains
-rw-rw-r-- 1 jflucier xroucou 1932978 Mar 27 10:47 hsapiens_gene_ensembl_gene_mappings
-rw-rw-r-- 1 jflucier xroucou 9660221 Mar 27 10:47 hsapiens_gene_ensembl_go_mappings
/ltmp/jflucier/temp_ms/20160723_2D_SRodrigue_ALL/PeptideShaker_temp/identification_parameters:
total 0
/ltmp/jflucier/temp_ms/20160723_2D_SRodrigue_ALL/PeptideShaker_temp/matches:
total 0
/ltmp/jflucier/temp_ms/20160723_2D_SRodrigue_ALL/PeptideShaker_temp/pride:
total 0


tks again for your help Marc.

**Comment by jflucier** [comment]
Hi Marc,

been reading on selenocysteine and i think it cannot be treated as a modification of cysteine afterall... I missguided you with my previous post. Selenocysteine are encode by stop codon UGA in vertebrates so dont think its right afterall to check for selenocysteine as cysteine modification as they are not encoded by the same codon. 

However, the bacteria we have just sequence uses a different translation table (table 4) and its the UGA codon encodes a tryptophan instead of a stop codon, so, in that case, selenocysteine can only replace tryptophan (W->U)... You could possibly add modification that looks for that as it is valid for most Mold, Protozoan and Mycoplasma/Spiroplasma species. Dont know if its feasible to integrate selenocysteine modification for human because it replaces the stop codon. 

Anyway, wanted to warn you before you release and sorry for missguidance.

I think i have found a way to do selenocysteine discovery by modifying my fasta file iteratively. I can share my solution if your interested if it works.

tks again Marc for your help on this.

**Comment by mvaudel** [comment]
Hi again,

Ok, this makes sense, I will add W-U instead then :) If you are looking at amino acid exchanges, it might be better to run de novo and then map your data back allowing this variant. This is still a beta feature in PeptideShaker, I can send you a snapshot with variants enabled if you want to test it. Otherwise, DirecTag + TagRecon is the best I am aware of for such tasks :)

Best regards,

Marc

**Comment by jflucier** [comment]
You provide me so much help. The least i could do is test this for you in my environment. Wanted to compare outputs from peptideshaker with variant option and DirecTag + TagRecon pipeline but source dont seem to be included anymore with the proteowizard tools  (as specified by https://my.vanderbilt.edu/dtabb73/). 

I can try to run peptideshaker with variants enable and also the W->U modifications in 2 seperate run. Currently running my pipeline with usual settings so I can compared in the end these 3 peptideshakers outputs. I will send you results afterwards if interested.

tks Marc.

**Comment by hbarsnes** [comment]
Issue assume resolved in newer versions of PeptideShaker. If this is not the case, please let us know and we'll reopen the issue.
