### ISSUE TITLE
"Downloading Gene/GO Mappings. Please wait..." for past 2 hours.

### ISSUE THREAD

**Issue by JitskeK** [compomics/peptide-shaker#258]
@#Hi everyone,

This is my first time using searchGUI/peptide shaker, and everthing has been working fine, exept now when I am trying to run my first search, it's been downloading gene/GO Mappings for two hours now and is still at 1%. I'm doing this on my home PC (with quite a lot of memory), so I was just wondering if this is normal, or if I should cancel the search and change my settings.

I enclosed the reports of the processes for more insight.

Thank you for your time,

Kind regards,

Jitske

[Processing Steur_1.txt](https://github.com/compomics/peptide-shaker/files/881730/Processing.Steur_1.txt)
[SearchGUI Steur_1.txt](https://github.com/compomics/peptide-shaker/files/881729/SearchGUI.Steur_1.txt)

**Comment by hbarsnes** [comment]
Hi Jitske,

I see that you closed the issue? Does this mean that you managed to solve the problem? 

I do note that your database seems to contain a lot of species though. Any particular reason why you would include all of these species and not only the one you are studying? I would recommend checking out our tutorial for how to generate the correct FASTA file: https://compomics.com/bioinformatics-for-proteomics/identification/.

Including only the species studied will dramatically decrease the time it takes to download the gene and GO mappings.

Best regards,
Harald

**Comment by JitskeK** [comment]
Hi Harald,

Thank you for the response!

The reason I closed the topic is because the search was canceled due to an error.

I was looking online for information on the error and seems to be involved with memory, probably related to my non specified FASTA file. I will check out your tutorial!

Thank you so much for your help,

Jitske

Outlook voor Android<https://aka.ms/ghei36> downloaden


Van: Harald Barsnes
Verstuurd: donderdag 30 maart 13:42
Onderwerp: Re: [compomics/peptide-shaker] "Downloading Gene/GO Mappings. Please wait..." for past 2 hours. (#258)
Aan: compomics/peptide-shaker
Cc: JitskeK, State change

Hi Jitske,

I see that you closed the issue? Does this mean that you managed to solve the problem?

I do note that your database seems to contain a lot of species though. Any particular reason why you would include all of these species and not only the one you are studying? I would recommend checking out our tutorial for how to generate the correct FASTA file: https://compomics.com/bioinformatics-for-proteomics/identification/.

Including only the species studied will dramatically decrease the time it takes to download the gene and GO mappings.

Best regards,
Harald
