### ISSUE TITLE
Opening searchGUI zip finds wrong input_database.fasta

### ISSUE THREAD

**Issue by chambm** [compomics/peptide-shaker#261]
```
Tue Apr 25 11:37:53 CDT 2017        Import process for mo_tai (Sample: mo_tai, Replicate: 0)

Tue Apr 25 11:37:53 CDT 2017        Importing sequences from input_database.fasta.

Tue Apr 25 11:37:53 CDT 2017        Importing Data Canceled!
Tue Apr 25 11:37:53 CDT 2017        Non unique accession number found 'DECOY_generic'!
```
I created a new project from a SearchGUI zip at:
`d:\test\Mo_tai data\Mo_Tai_iTRAQ_f9-Sample_Mouse_total.whole_exp.cRAP.zip`

It asked me if I wanted to override the existing params file and I said "yes". Then it gave me the above error. When I looked at the params, I saw it was actually looking at a different FASTA:
`d:\test\input_database.fasta` (from a different project)

The correct FASTA was of course at:
`D:\test\Mo_Tai data\.PeptideShaker_unzip_temp\Mo_Tai_iTRAQ_f9-Sample_Mouse_total.whole_exp.cRAP_PeptideShaker_temp\data\input_database.fasta`
When I adjusted the params to point at that database, the import worked fine.

I tried in PS 1.15.1 and 1.16.5.

**Comment by hbarsnes** [comment]
Hi Matt,

Thanks for telling us about this. I fail to reproduce it on my side though. You sure you selected the correct option with regards to which settings file to use in the below dialog?

![identification settings](https://cloud.githubusercontent.com/assets/13151214/25439567/0f5d05b0-2a9d-11e7-98bb-cd5ea1b4576e.png)

If I use "Replace File", PeptideShaker uses the settings from the SearchGUI zip file and I have no problems with the FASTA file. However, if I instead use the "Use Existing File" option, PeptideShaker ends up using the wrong FASTA file. (Keep Both Files also works fine, but does create a second search settings file.)

So which of the three options did you select?

Best regards,
Harald

**Comment by chambm** [comment]
I have trouble reproducing it now, so I suppose I accidentally clicked "Use Existing File"! I'm not sure why this prompt is necessary though. Why isn't the parameters file always tied with the params stored in the SearchGUI zip and automatically read from there?

**Comment by hbarsnes** [comment]
The parameters are stored by name in your user home folder (or another user defined folder) for easy reuse. We therefore cannot directly overwrite the stored parameter file if the SearchGUI zip file contains a parameter file with the same name but with different settings, hence the user options above.

Note that this is only a problem if the parameter file has the same name as an already existing parameter file, but with different content. So using different names for parameter files with different settings avoids the dialog (and makes them easier to tell apart as well).
