### ISSUE TITLE
Fixed modifications from Mascot .dat file

### ISSUE THREAD

**Issue by JakobBu** [compomics/peptide-shaker#262]
Hi Harald

There seems to be a problem importing fixed modifications from the Mascot .dat file.
I have dimethyl-labelled with deuteroformaldehyde.
I have prepared a small .mgf file with three Mascot PSM's, the mascot dat file and the fasta file.
![image](https://cloud.githubusercontent.com/assets/28535686/25807425/18df4e04-3407-11e7-85ba-2d2311fd7104.png)

[Pepshaker_dimethylD4_case.zip](https://github.com/compomics/peptide-shaker/files/983666/Pepshaker_dimethylD4_case.zip)

I hope it makes sense

Thanks in advance
Jakob

**Comment by hbarsnes** [comment]
Hi Jakob,

I made a stupid mistake when adding "Dimethylation of K 2H(6)", where I added it on the K, but, due to copy-paste, only on n-terminal K. Now corrected. I will release a new version and let you know.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

The new PeptideShaker version has now been released and should fix the problem. If this is not the case, please let me know and I'll reopen the issue.

Note that you'll have to create a new settings file in PeptideShaker as the old one will still refer to the old version of "Dimethylation of K 2H(4)" with the typo.

Best regards,
Harald

**Comment by JakobBu** [comment]
Works now - many thanks

bw
Jakob

2017-05-08 17:03 GMT+02:00 Harald Barsnes <notifications@github.com>:
