### ISSUE TITLE
Peak color in spectrum annotation panel

### ISSUE THREAD

**Issue by wenbostar** [compomics/peptide-shaker#264]
Hi,
The colors of b and y ion peaks are always blue. How to make b and y peaks be plotted with different colors?

![image](https://cloud.githubusercontent.com/assets/5302110/26279147/530d0cc4-3d71-11e7-8fac-8db3434a0c95.png)

Best regards!
Bo

**Comment by hbarsnes** [comment]
Hi Bo,

I'm afraid you cannot change the color of the peaks separately for each fragment ion type. You can only do this for the annotation above the peaks. The peak color is only separated on annotated vs. not annotated, as in blue vs. gray in your example above.

However, you can always export the spectrum plot as svg and edit the colors there if you need this for a figure for a particular spectrum, e.g. for a publication.

Best regards,
Harald
