### ISSUE TITLE
Error in validation

### ISSUE THREAD

**Issue by carlauranga** [compomics/peptide-shaker#268]
Hello, please find the log for the issue I am having with peptide shaker. The validations are not coming up automatically anymore. Thank you for your help.

[Carla_Uranga_PeptideShaker 1.16.9 log.txt](https://github.com/compomics/peptide-shaker/files/1032966/Carla_Uranga_PeptideShaker.1.16.9.log.txt)

**Comment by hbarsnes** [comment]
I'm not sure I understand what the problem is? Can you explain a bit more what you mean by "the validations are not coming up automatically anymore"?

**Comment by carlauranga** [comment]
So I am searching a relatively small set of peptides from a gel, and many proteins come up with many valid peptides, but the final protein validation is tagged "doubtful".  I did try editing the validation filter but nothing worked.  I can't upload my .cpsx file but Github does not allow it. Thank you.

**Comment by hbarsnes** [comment]
Have you tried clicking the Doubtful icon for the protein(s) in question? This will bring up the Validation dialog showing you why each protein is considered Doubtful. Note that being labeled as doubtful does not mean that the protein is not validated at the selected FDR level, only that it fails the extra validation filters and should thus be treated with caution. See our [tutorials](https://compomics.com/bioinformatics-for-proteomics) for more details on the validation.

**Comment by hbarsnes** [comment]
Issue assume resolved. If this is not the case, please let us know and we'll reopen the issue.

**Comment by carlauranga** [comment]
So it's odd, but I have to go in and manually validate proteins that were
identified with many 100% validated peptides. I do have a small data set
and a human only database, so is this why?

Thanks,

Carla Uranga

**Comment by hbarsnes** [comment]
Hi Carla,

The proteins are validated separately from the peptides (and the PSMs) at one 1% FDR and using separate quality control filters. Hence you can have proteins categorized as Doubtful even though they have numerous validated peptides categorized as Confident.

You can control which proteins, peptides and PSMs that are considers as Doubtful via the Quality Control settings under Advanced Settings in the Identification Settings dialog.

However, keep in mind that proteins (and peptides and PSMs) indicated as Doubtful are still validated at 1% FDR. They simply fail to pass the extra quality control filters. It is therefore important to note that being classified as Doubtful does not mean that the protein (or peptide/PSM) is not statistically validated, simply that it should be treated with caution and inspected in more detail before being used as the basis for a major new finding.

Best regards,
Harald
