### ISSUE TITLE
Using CLI to analyse and export searchGUI results indepentently

### ISSUE THREAD

**Issue by sfghuis** [compomics/peptide-shaker#269]
Dear developers,

I am currently trying to use peptideshaker to analyse and export several database searches independently to a pepXML format. To do this using the GUI I would have to make a separate project for each file analyze and export them. Would it also be possible to use the CLI to run over a directory analyse and export the file accordingly?

In addition when running site localisation score algorithm would it be possible to calculate the A-score and PhosphoRS score at the same time?

Looking forward to your reply,

Bas

**Comment by hbarsnes** [comment]
Hi Bas,

> Would it also be possible to use the CLI to run over a directory analyse and export the file accordingly?

Yes, this should not be too difficult. It is just a matter of iterating over the files and repeating the command line with the changed input. Remember to only run one PeptideShaker instance from the same jar file at the time though.

> In addition when running site localisation score algorithm would it be possible to calculate the A-score and PhosphoRS score at the same time?

I'm afraid this is not supported, so you'll have to choose one of them.

Best regards,
Harald
