### ISSUE TITLE
GO Analysis

### ISSUE THREAD

**Issue by Bihike** [compomics/peptide-shaker#272]
Hello!

I have a problem when I click to GO Analysis:

"An error occured: Server returned HTTP response code: 403 for URL: http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007568&format=oboxml. If the problem persists, please contact the developers."

May I ask somebody to help me what should I do?
Thank you for youor kind reply.

B.

**Comment by hbarsnes** [comment]
Hi B,

The "GO Analysis" tab works fine on my end. Could it be that you were unlucky and that the gene ontology website was down for a short time just when you tried to access it? Perhaps you could you try opening the "GO Analysis" tab once more and see if you get the same error?

Best regards,
Harald

**Comment by Bihike** [comment]
Dear Harald!

Unfortunatelly, the program show the same error when I tried it again. I work with CHO fasta file, perhaps is it a problem? Thank you!

B.

**Comment by Bihike** [comment]
Actually, it is doesn't work with the example file. The same error code apeared.

**Comment by hbarsnes** [comment]
Hi B,

Seems like there is a problem with your network that stops you from accessing the GO website. Do you have any firewall other network access limitations that may explain this?

BTW, what happens if you simply click the link in your initial message? Are you able to open it in your browser or do you get the same error?

Best regards,
Harald

**Comment by Bihike** [comment]
Dear Harald!

Yes, you're right, the firewall was the key of my problem. Thank you very much for your help! :)

**Comment by hbarsnes** [comment]
Hi B,

Great! I will then close the issue, but please don't hesitate to open a new one if you come across other problems.

Best regards,
Harald
