### ISSUE TITLE
question about databases from RNASeq data

### ISSUE THREAD

**Issue by fazeliniah** [compomics/peptide-shaker#277]
Hi, 
My question is about generating protein/peptide databases from RNA-Seq data. I would like to know what tools you recommend for processing RNA-Seq data to generate fasta databases for the Searchgui.  In particular, I am interested in 6 reading frame translation for short RNA reads. 
Thanks
H

**Comment by mvaudel** [comment]
Hi,

I think customProDB is the reference tool to create databases from RNA-Seq data. I am not sure in the particular case of short reads. We don't develop such tools ourselves I am afraid. 
https://academic.oup.com/bioinformatics/article-lookup/doi/10.1093/bioinformatics/btt543

SearchGUI and PeptideShaker will accept databases in most formats, but in case you are using a custom format, you might need to reformat your fasta file. You will find a generic format in our help below.
https://github.com/compomics/searchgui/wiki/DatabaseHelp

Hope this helps,

Marc
