### ISSUE TITLE
Export table in Spectrum IDs tab using CLI

### ISSUE THREAD

**Issue by lcscs12345** [compomics/peptide-shaker#279]
Hi,

I would like to export the table exactly as the Spectrum IDs tab using CLI. I have played around with GUI using "Export > Identification Features > Add new report type" to learn the custom export options. However, I haven't been able to reproduce the Spectrum IDs table. Note that I'm aware of the "Copy to File" arrow in GUI. Thank you!

**Comment by mvaudel** [comment]
Hi,

Currently it is impossible to export exactly the same export from command line because the tables export is using some deprecated code we never cleaned-up. We are currently refactoring the tool and in the next version exports will be the same from the tables and from the command line.

Apologies for the inconvenience,

Marc

**Comment by hbarsnes** [comment]
Hi,

As far as I can see you can get all the columns (except the precursor intensity) from the main Spectrum IDs table via creating a custom report that includes elements from the Peptide Spectrum Matching Summary category.

After creating the report in the graphical user interface it will become available for [use in via the command line](https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI#b---reportcli).

The only other change, besides the missing precursor intensity, is the ordering of the columns. But I assume this can be easily dealt with when parsing the data.

Would this not cover what you need?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
