### ISSUE TITLE
Different modification results from the same file

### ISSUE THREAD

**Issue by joeyuzh** [compomics/peptide-shaker#280]
Hi,

Recently, I found that the modification results coming from the same file can be different. First, I used a search setting that includes Carbonylation of P&W together with 5 other variable modifications (decarboxylation of D&E, oxidation of K, citrullination of R, Quinone of Y), the output result showed that only 2 proteins were tagged with Carbonylation. However, the next time when I used a search setting that only includes Carbonylation of P&W, the amount of carbonylated proteins boosted up to 23.  The other settings for these two searches were kept the same. Does that mean the combination of the variable modifications in the search setting can affect the modification result?

Regards,

Joe

**Comment by mvaudel** [comment]
Hi Joe,

Yes, adding more variable modifications increases the search space and decreases the discrimination power of identification algorithms. In short, your peptides will have more candidates to compete with. We recommend searching with a minimal set of modifications that you know are in the sample. More information can be found in our tutorials: https://compomics.com/bioinformatics-for-proteomics

Hope this helps,

Marc
