### ISSUE TITLE
GO analysis

### ISSUE THREAD

**Issue by Bihike** [compomics/peptide-shaker#281]
Dear Developers!

I have a problem when I want to use the GO analysis in PeptideShaker program, however the firewall was closed. Error message: "The markup in the document preceding the root element must be well-formed"
Do you have any solution?

Thank you for your reply.

Bihike

![peptideshaker-1 16 12](https://user-images.githubusercontent.com/29485157/29606892-d65a2648-87ef-11e7-8dbe-3ba60fa4e970.jpg)

**Comment by hbarsnes** [comment]
Hi Bihike,

The GO Analysis tab requires an internet connection to download the GO terms, so if you cannot allow PeptideShaker through your firewall I'm afraid the GO Analysis tab will not work.

Are you able to allow PeptideShaker to access the internet or do you have another computer you can run the analysis on?

Best regards,
Harald

**Comment by lukauskas** [comment]
I get the same error, internet is working fine.

**Comment by hbarsnes** [comment]
> I get the same error, internet is working fine.

I can confirm that I know get the same error. I will look into it and get back to you as soon as possible.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

The problem was that there is a new version of [QuickGO](https://www.ebi.ac.uk/QuickGO/) (which is what we use to extract the category of the GO terms, i.e. biological process, cellular component or molecular function) were the syntax had changed slightly for the output. We've now corrected the error and will release a new version as soon as possible.

Best regards,
Harald

**Comment by Bihike** [comment]
Deat Harald,

All right, I will try it again with the new release. Thank you for you efforts!!

Best regards,
Bihi

**Comment by hbarsnes** [comment]
Hi,

We've now released PeptideShaker v1.16.13 which should solve the issue with the GO Analysis tab. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by Bihike** [comment]
Thank you Harald! It is perfect now!! :)

**Comment by samehmgd** [comment]
hi hbarsnes
same problem here . i made sure internet connection is ok and firewall is disabled.
it was working before but suddenly it does not even with the sample example
im using 1.16.13 version

**Comment by hbarsnes** [comment]
Hi Sameh,

We've now released PeptideShaker v1.16.14 which should solve the issue with the GO Analysis tab. Once more. (The problem was that QuickGO had changed from using http to https.)

Best regards,
Harald
