### ISSUE TITLE
PeptideShaker runs out of memory

### ISSUE THREAD

**Issue by Morder86** [compomics/peptide-shaker#282]
Hello!

I am trying to import SearchGui output files to PeptideShaker and it permanently runs out of memory on "Validating identifications as 1% FDR, quality control of matches". I use 64-bit Windows 10, 8.00 GB RAM (6GB assigned to Java), Intel(R)Core(TM) i5-6500 CPU. The .mgf files for Searchgui were obtained by MSConvert (Peak Picking was used). The database for SearchGui is Swiss-Prot human reviewed (contains 40432 sequences including decoy), only carbamidomethylation of C and oxidation of M were indicated as fixed and variable modifications, respectively.

What I am also noticed that among my 12 raw files there is one that is significantly smaller than others, and this file is the only one that is successfully processed by PeptideShaker. 

Could you please give me any suggestions where the problem can be?

**Comment by hbarsnes** [comment]
Hi,

Thanks for telling us about this.

When you write "6GB assigned to Java" does this mean that you set the memory for PeptideShaker to 6GB via the PeptideShaker Welcome dialog > Settings & Help > Settings > Java Settings? And given that you don't say anything about command lines, I assume you're using the graphical user interface to run PeptideShaker?

Can I also ask which search engines you are using? If you're using more than one, you can perhaps try loading only the results from one of the search engines as a test?

Best regards,
Harald

**Comment by Morder86** [comment]
Dear Dr. Barsnes,

Thank you very much for the response! Yes, what I mean is that I have set
the memory of 6 GB for PeptideShaker, as you said. And I use grafic user
interface, not the command prompt. In my searches I have  used X!Tandem
only.

Best regards,

Dmytro

**Comment by hbarsnes** [comment]
Hi Dmytro,

Strange, I don't see any reason why you should not be able to load your data with those settings. Can you send us your PeptideShaker log file? Maybe it will tell us a bit more about what is going on. You'll find the file via the Welcome dialog > Settings & Help > Help > Bug Report.

> What I am also noticed that among my 12 raw files there is one that is significantly smaller than others, and this file is the only one that is successfully processed by PeptideShaker.

How big are the raw files when converted to mgf?

Best regards,
Harald

**Comment by Morder86** [comment]
[PeptideShaker 1.16.12 log.txt](https://github.com/compomics/peptide-shaker/files/1256852/PeptideShaker.1.16.12.log.txt)

Hi, I have uploaded the log file. Mgf files are from 2.1 to 3.5 GB, and the only one that works is 861 MB

**Comment by hbarsnes** [comment]
Hi Dmytro,

> Mgf files are from 2.1 to 3.5 GB, and the only one that works is 861 MB

Ok, that explains why PeptideShaker is struggling. Where do these huge mgf files come from? And are you sure they only include good quality MS2 spectra or could you consider filtering them?

Perhaps you could also consider using the splitting option in SearchGUI (see Edit > Advanced Settings > Mgf File Size Check) when searching the data? This would split the large mgf files into smaller mgf files that would be searched individually and then later merged during the processing in PeptideShaker.

Best regards,
Harald

**Comment by Morder86** [comment]
Hi, thank you very much for responding again. These files came as the result of conversion of initial .raw files to mgf files. The sizes of initial files are 2.1-2.6 GB, and the one that works - 1.65 GB. I am not sure that they include only high quality MS2 spectra, I would be grateful if you could suggest me a good way of filtering them during conversion to .mgf files (I have already used Peak Picking with Vendor algorithm in MSConvert, but, obviously, it is not enough).

**Comment by hbarsnes** [comment]
Hi Dmytro,

Is there anything special with the way the raw files are created that could explain why they are so big? Which instrument are you using for example?

I don't know of any good way of filtering the data when converting to mgf, besides the peak picking already used. My best tip would therefore be to try the splitting in SearchGUI as detailed above. Try it on one of the big files first and see if that helps?

Best regards,
Harald

**Comment by Morder86** [comment]
Dear Dr. Barsnes,

The problem is that the procedure has been done by proteomic core unit of the University my current lab has recently moved from, and I didn't have direct contacts with them. And now they rarely respond to our emails. Below is the only description that I was able to find in one of the grant applications, I am not sure if this can give you an idea what is going on, but I am attaching it.

"LC-MS/MS analysis
Peptides were resuspended in 10 μL of loading buffer (0.1% formic acid, 0.03% trifluoroacetic acid, 1% acetonitrile). Peptide mixtures (2 μL) were separated on a self-packed C18 (1.9 μm Dr. Maisch, Germany) fused silica column (25 cm x 75 μM internal diameter (ID); New Objective, Woburn, MA) by a Dionex Ultimate 3000 RSLCNano and monitored on a Fusion mass spectrometer (ThermoFisher Scientific). Elution was performed over a 120-min gradient at a rate of 350 nl/min with buffer B ranging from 3% to 80% (buffer A: 0.1% formic acid in water, buffer B: 0.1% formic in acetonitrile). The mass spectrometer cycle was programmed to collect at the top speed for 3 second cycles. The MS scans (400-1600 m/z range, 200,000 AGC, 50 ms maximum ion time) were collected at a resolution of 120,000 at m/z 200 in profile mode and the HCD MS/MS spectra (0.7 m/z isolation width, 30% collision energy, 10,000 AGC target, 35 ms maximum ion time) were detected in the ion trap. Dynamic exclusion was set to exclude previous sequenced precursor ions for 20 seconds within a 10 ppm window. Precursor ions with +1, and +8 or higher charge states were excluded from sequencing."

I will try to run Searchgui in a way you told me, thank you very much for this suggestion!

Best regards,

Dmytro

**Comment by Morder86** [comment]
Unfortunately, splitting did not help too much, still runs out of memory. I will try to filter the data.

**Comment by hbarsnes** [comment]
> Unfortunately, splitting did not help too much, still runs out of memory. I will try to filter the data.

That is strange. How small were the mgf files after splitting? You may need to fiddle a bit with the splitting settings to get the size you need. And did you try with a single large file first?

**Comment by Morder86** [comment]
It made 5 files from 470MB to 885MB. The initial large file (more than 3GB) which has been split is the one that I am constantly trying to analyze , and PeptideShaker always fails when tries to upload the results for this file.

**Comment by hbarsnes** [comment]
> It made 5 files from 470MB to 885MB.

Try making the split files even smaller, as they are still pretty big.

> PeptideShaker always fails when tries to upload the results for this file.

Fails as in runs out of memory? Or are there errors?

**Comment by Morder86** [comment]
Hi! Yesterday morning I launched PeptideShaker import of Searchgui results for split mgf file in order to answer your question. But it is still running. Before that it usually ran out of memory rather than showed errors.

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
