### ISSUE TITLE
Unable to create custom reports from PeptideShakerCLI

### ISSUE THREAD

**Issue by rkg92** [compomics/peptide-shaker#284]
Hi Compomics team,

I have recently tried to export custom reports from the command line. I was unable to get it to work. I looked through the documentation and learned that I have to flag the "-peptideshaker_user_preferences" to the .peptideshaker/ directory containing the ExportFactory.cus 
file and did that. 
I am able to export custom reports using the GUI but using the CLI, I get the following error message---

<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>java.lang.IllegalArgumentException: Unrecognized report type: 10. Available reports are: 0: Certificate of Analysis, 1: Default Hierarchical Report, 2: Default PSM Phosphorylation Report, 3: Default PSM Report, 4: Default Peptide Phosphorylation Report, 5: Default Peptide Report, 6: Default Protein Phosphorylation Report, 7: Default Protein Report, 8: Extended PSM Report.
	at eu.isas.peptideshaker.export.PSExportFactory.getExportTypeFromCommandLineOption(PSExportFactory.java:423)
	at eu.isas.peptideshaker.cmd.ReportCLIInputBean.<init>(ReportCLIInputBean.java:66)
	at eu.isas.peptideshaker.cmd.ReportCLI.main(ReportCLI.java:348)

I was also wondering if it is possible to include decoy sequences in the default outputs? 
It'd be great if you could help me find a solution to this. Thank you very much!

Best,
Riddhiman

**Comment by hbarsnes** [comment]
Hi Riddhiman,

Are you running the CLI on the same machine as the one running the GUI? And from the same PeptideShaker jar file? If so, the same reports should be available to the CLI and the GUI.

Do you see your custom report when using the empty ReportCLI command line (java -cp PeptideShaker-X.Y.Z.jar eu.isas.peptideshaker.cmd.ReportCLI)? It should be listed as a valid parameter to the -reports option.

> I looked through the documentation and learned that I have to flag the "-peptideshaker_user_preferences" to the .peptideshaker/ directory containing the ExportFactory.cus

There should be no need to refer to the user preferences folder, unless this folder is different for the CLI compared to the GUI.

Could you show me the complete CLI you are trying to execute?

> I was also wondering if it is possible to include decoy sequences in the default outputs?

Which default outputs are you here referring to? The decoys sequences are there in the mzIdentML export for example.

Best regards,
Harald

**Comment by rkg92** [comment]
Hi Harald,

Thank you for getting back so promptly. 

>Are you running the CLI on the same machine as the one running the GUI? And from the same PeptideShaker jar file? If so, the same reports should be available to the CLI and the GUI.

Yes, I am running both the CLI and GUI from the same machine (which was why I was more confused as to why it wasn't seeing the custom reports)

>Do you see your custom report when using the empty ReportCLI command line (java -cp PeptideShaker-X.Y.Z.jar eu.isas.peptideshaker.cmd.ReportCLI)? It should be listed as a valid parameter to the -reports option.

I do not see the custom report (it says report option out of range and only lets me export in the list of reports formats that are preset)

> Could you show me the complete CLI you are trying to execute?

java -cp PeptideShaker-X.Y.Z.jar eu.isas.peptideshaker.cmd.ReportCLI -in sample.cpsx -out_reports /peptide_shaker/reports/path -reports "3, 5, 7, 10, 11, 12"

(I don't know if this makes a difference but I am currently using SearchGUI-3.2.20 and PeptideShaker-1.16.12)
>Which default outputs are you here referring to? The decoys sequences are there in the mzIdentML export for example. 

I was referringto the following -report options 
3: Default PSM Report
5: Default Peptide Report
7: Default Protein Report

It'd be great if I could export my decoy hits in the above mentioned reports.

Thank you for all your assistance! Appreciate it.

Best,
Riddhiman

**Comment by hbarsnes** [comment]
Hi Riddhiman,

Perhaps your use of the -peptideshaker_user_preferences option has messed up the link to the custom reports? Could you check again in the GUI that you still see your custom reports there?

> (I don't know if this makes a difference but I am currently using SearchGUI-3.2.20 and PeptideShaker-1.16.12)

Should not have an impact as there are no changes related to the reports in the latest version.

> It'd be great if I could export my decoy hits in the above mentioned reports.

You are correct that the decoys are not included in these reports, but you can easily make your own custom reports with the same columns which also includes the decoys. Simply select the "Include Decoys" option in the Settings section at the top when creating the new report.

Best regards,
Harald

**Comment by rkg92** [comment]
Hi Harald,

>Perhaps your use of the -peptideshaker_user_preferences option has messed up the link to the custom reports? Could you check again in the GUI that you still see your custom reports there?

I am able to still export it from the GUI but when I try to export from the CLI I get the following error message---

<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>java.lang.IllegalArgumentException: Unrecognized report type: 10. Available reports are: 0: Certificate of Analysis, 1: Default Hierarchical Report, 2: Default PSM Phosphorylation Report, 3: Default PSM Report, 4: Default Peptide Phosphorylation Report, 5: Default Peptide Report, 6: Default Protein Phosphorylation Report, 7: Default Protein Report, 8: Extended PSM Report.
	at eu.isas.peptideshaker.export.PSExportFactory.getExportTypeFromCommandLineOption(PSExportFactory.java:423)
	at eu.isas.peptideshaker.cmd.ReportCLIInputBean.<init>(ReportCLIInputBean.java:66)
	at eu.isas.peptideshaker.cmd.ReportCLI.main(ReportCLI.java:348)

>You are correct that the decoys are not included in these reports, but you can easily make your own custom reports with the same columns which also includes the decoys. Simply select the "Include Decoys" option in the Settings section at the top when creating the new report. 

That is what I thought would be the best option. However, I am not able to do it because of this issue. It exports perfectly fine from the GUI but I would like to serially do it for multiple files (>200 MS experiments). I hope I am not missing something. Thanks! 

Best,
Riddhiman

**Comment by hbarsnes** [comment]
Hi Riddhiman,

Strange, it seems like your custom reports are not available to the CLI. However, I just tested this on my side, and it all seems to work fine.

Could you send me your exportFactory.cus file? You'll find it in your user home folder in the ".peptideshaker" folder. I will then check if the file actually contains your custom exports.

Best regards,
Harald

**Comment by rkg92** [comment]
Hi Harald,

Github isn't letting me attach these files through this thread. I have emailed you the files. Thanks!

Best,
Riddhiman

**Comment by hbarsnes** [comment]
Hi Riddhiman,

Thanks for the files. If I go into my .peptideshaker folder and replace my exportFactory.cus file with your exportFactory_remoteserver.cus file (removing the "_remoteserver" part), I can use your custom exports via both the GUI and the CLI without any problems.

The exportFactory_localsystem.cus file on the other hand does not contain the custom reports.

From the Welcome dialog of PeptideShaker choose Settings & Help > Settings > Resource Settings, and see what is listed for "peptideshaker_exports". Does this refer to the folder containing the correct exportFactory.cus file? In other words, the one named exportFactory_remoteserver.cus in the files you sent me? If not, change the folder to the folder containing the correct exportFactory.cus file and try the CLI again.

You can also change the folder using the -peptideshaker_exports option on the command line.

Best regards,
Harald

**Comment by rkg92** [comment]
Hi Harald,

>From the Welcome dialog of PeptideShaker choose Settings & Help > Settings > Resource Settings, and see what is listed for "peptideshaker_exports". Does this refer to the folder containing the correct exportFactory.cus file? In other words, the one named exportFactory_remoteserver.cus in the files you sent me? If not, change the folder to the folder containing the correct exportFactory.cus file and try the CLI again

This fixed the problem! Also, it seems like the _localsystem.cus file had the custom reports (not the _remoteserver.cus). Sometimes the exportFactory.cus file resets to default. It may be a problem in the future. 

But it works fine now! Thanks for all your help! You have been extremely resourceful! Really appreciate it! 

Best,
Riddhiman

**Comment by Seb-Leb** [comment]
I am having a similar problem but changing the path to exportFactory in the GUI doesn't seem to fix the problem.
Harlad said

> You can also change the folder using the -peptideshaker_exports option on the command line.

But I when I add that parameter in the ReportCLI command, it doesn't recognize the option.

`java -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.ReportCLI -in "$TEMPDIR/shaker_results/b5609.cpsx.zip" -peptideshaker_exports $EXP_FACT_PATH/apps/exportFactory.cus -out_reports reports/ -reports "9"`

`<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -peptideshaker_exports`

**Comment by hbarsnes** [comment]
> But I when I add that parameter in the ReportCLI command, it doesn't recognize the option.

Thanks for letting us know. There was an oversight on our part where only the -temp_folder option (which sets all the paths) was supported when using the ReportCLI. This has now been corrected and a new PeptideShaker version (v1.16.26) has just been released.

If you still experience problems with the path settings, I recommend to open a new issue. As we tend to ignore the old closed issues. ;)
