### ISSUE TITLE
Exporting peptide list

### ISSUE THREAD

**Issue by samehmgd** [compomics/peptide-shaker#286]
Hi
a simple question that i cant find an answer for it
How can i export the full peptide info from the analysis?
thanks

**Comment by hbarsnes** [comment]
Hi,

You can export all the peptide information via the "Identification Features" option on the "Export" menu. There you can either choose the "Default Peptide Report" or set up your own custom report including only the features you need.

Best regards,
Harald

**Comment by samehmgd** [comment]
many thanks appreciating your prompt reply
