### ISSUE TITLE
Go annotation

### ISSUE THREAD

**Issue by samehmgd** [compomics/peptide-shaker#287]
I'm using peptide shaker version 1.16.13 with a Java 1.8.144 , 64 bit and 8 GB rams. my run was perfectly analyzed then suddenly, GO annotation is not shown in all runs even the sample run . the message says "an error occured, if the problem persists, please contact the developers ".
i made sure there is no firewall

I appreciate your help.

**Comment by hbarsnes** [comment]
Hi Sameh,

We've now released PeptideShaker v1.16.14 which should solve the issue with the GO Analysis tab. Once more. (The problem was that QuickGO had changed from using http to https.)

Best regards,
Harald
