### ISSUE TITLE
protein groups in mzid

### ISSUE THREAD

**Issue by chrishuges** [compomics/peptide-shaker#289]
Hi,

I posted this on the google group as well, but I will due so again here for visibility. 

I am trying to upload some mzid files from PeptideShaker to massIVE (this is a reanalysis of published data). However, I am running into an issue with the mzid that is output from PeptideShaker. Specifically, during the upload it tries to convert to mzTab and I get the error:

"mzTab do not support one protein in more than one ambiguity groups"

After speaking with the people at CCMS, it seems that a change to allow this in mzTab is potentially on the horizon, but not yet. 

Is there a way to stop PeptideShaker from including the same protein in multiple groups in the mzid output?

Thanks!
Chris

**Comment by hbarsnes** [comment]
Please see the [PeptideShaker Google Group](https://groups.google.com/forum/#!topic/peptide-shaker/dHQbuEiKr3g) for follow-up on this issue.
