### ISSUE TITLE
Memory issue with PeptideShaker 1.16.15

### ISSUE THREAD

**Issue by hcadre** [compomics/peptide-shaker#291]
Unfortunately, I did not have a look at this site until I had run through my new analysis - PeptideShaker did not import the data passed on by SearchGUI due to a "OutOfMemoryError" (see below). I am not a power user of this pipeline, so I am not aware of any recommendations regarding the settings for memory allocated to JAVA. This is phosphoproteomics project with 18 .raw files each one on average 1GB in size and the search was done using XTandem, Amanda and OMSSA. Does it make sense to start the PeptideShaker part again or should I wait until the memory issue (see issues #290, 283, 282) is solved with the next release of PeptideShaker?

Any comment is highly appreciated!

Kind regards, 

Hannes

.........
.........
Thu Nov 16 16:05:14 CET 2017        File import completed. 1158154 first hits imported (6027956 secondary) from 539264 spectra.
Thu Nov 16 16:05:14 CET 2017        [938269 first hits passed the initial filtering]
Thu Nov 16 16:05:14 CET 2017        Computing assumptions probabilities.
Thu Nov 16 16:05:15 CET 2017        Saving assumptions probabilities.
Thu Nov 16 16:41:32 CET 2017        Selecting best peptide per spectrum.
Thu Nov 16 17:19:35 CET 2017        Computing PSM probabilities.
Thu Nov 16 17:19:35 CET 2017        Scoring PTMs in PSMs (D-score and PhosphoRS)
Thu Nov 16 18:06:07 CET 2017        An error occurred: Java exception: 'GC overhead limit exceeded: java.lang.OutOfMemoryError'.
Thu Nov 16 18:06:07 CET 2017        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Thu Nov 16 18:06:07 CET 2017        Importing Data Canceled!

**Comment by hbarsnes** [comment]
Hi Hannes,

Regarding memory, the general tip is: the more the better. :) The reason being that then more data can be kept in memory (compared to writing/reading to/from the disk), which speeds up the processing.

You can try increasing the amount of memory you give to PeptideShaker to see if this solves the problem. This can be done from the Welcome Dialog > Settings & Help > Settings > Java Settings. Note that you need Java 64 bit to use more than 2 GB of memory. For more details see: http://compomics.github.io/projects/compomics-utilities/wiki/javatroubleshooting.html.

If this does not help, I'm afraid you'll have to wait for the new release which includes improved memory handling.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by nattzy94** [comment]
Hi,

I am having similar problems with memory. I am searching a relatively large database of 5 million sequences (37Gb, storage is mirrored so ~18.5Gb actual). I ran on command line with default java heap size and later increased to 8Gb heap size with java Xmx8G. However, in both cases, the job quits after about 10h while it is attempting to index my input fasta database. 

The end of the output file reads: 
`Reindexing: subcut-56h-translated-nostops.fasta.`

The log file error message is as follows:

```
Tue May 19 15:06:17 SGT 2020: SearchGUI version 3.3.20.
Memory given to the Java virtual machine: 7635730432.
Total amount of memory in the Java virtual machine: 2017984512.
Free memory: 1975873640.
Java version: 1.8.0_191.
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.matches(Unknown Source)
        at java.lang.String.matches(Unknown Source)
        at com.compomics.util.protein.Header.parseFromFASTA(Header.java:802)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.createFastaIndex(SequenceFactory.java:805)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:711)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:641)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:582)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:558)
        at eu.isas.searchgui.cmd.SearchCLI.call(SearchCLI.java:247)
        at eu.isas.searchgui.cmd.SearchCLI.<init>(SearchCLI.java:102)
        at eu.isas.searchgui.cmd.SearchCLI.main(SearchCLI.java:378)
```

Will increasing my heap size solve the memory issue? And roughly how much should I increase it to? I am testing a heap size of 16Gb at the moment.

**Comment by dominik-kopczynski** [comment]
Hi Nattzy, thank you for your message. The indexing function needs during its indexing process unfortunately about 3x the space of the original fasta file (only during construction). So if you have a fasta file of about 19GB, you will need currently a computer with about 57GB memory. Since no one was using that big databases in the past, we didn't build the index to be stored externally (e.g. hard disk), but since you are also having this big database, we will discuss this issue immediately. I will drop you a line. Cheers

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
