### ISSUE TITLE
Errors in paths 

### ISSUE THREAD

**Issue by ypriverol** [compomics/peptide-shaker#293]
@hbarsnes & @mvaudel : 

I have search my data with SearchGUI and Then converted into PeptideShacker using the following command: 

```
java -cp /Users/yperez/IdeaProjects/github-repo/pride-cluster/PRIDE-Cluster/cluster-data-generation/resources/PeptideShaker/PeptideShaker-1.16.15.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment "PRIDE Assay Reanalysis 39086" -sample "No sample name" -replicate 1 -identification_files ./searchgui_out.zip -out ./ps_output.cpsx
```
Output here: 

> Sat Dec 09 09:25:39 GMT 2017 Unzipping searchgui_out.zip.
> 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> 
> Sat Dec 09 09:25:50 GMT 2017 Import process for PRIDE Assay Reanalysis 39086 (Sample: No sample name, Replicate: 1)
> 
> Sat Dec 09 09:25:50 GMT 2017 Importing sequences from proteomes-9913-complete.fasta.
>  0%
> 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> Sat Dec 09 09:26:17 GMT 2017 FASTA file import completed.
> Sat Dec 09 09:26:17 GMT 2017 Importing gene mappings.
> Sat Dec 09 09:26:18 GMT 2017 Establishing local database connection.
> Sat Dec 09 09:26:20 GMT 2017 Reading identification files.
> Sat Dec 09 09:26:20 GMT 2017 Parsing PXD001204-39086.msgf.mzid.
> 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> Sat Dec 09 09:26:26 GMT 2017 Loading spectra for PXD001204-39086.msgf.mzid.
> Sat Dec 09 09:26:26 GMT 2017 Importing PXD001204-39086.mgf
> Sat Dec 09 09:26:27 GMT 2017 PXD001204-39086.mgf imported.
> 10% 20% 30% 40% 50% 60% 70% 80% 90%
> Sat Dec 09 09:26:27 GMT 2017 Collecting peptides to map.
> 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> Sat Dec 09 09:26:28 GMT 2017 Mapping peptides to proteins.
> 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> Sat Dec 09 09:26:30 GMT 2017 Importing PSMs from PXD001204-39086.msgf.mzid
> 10% 20% 30% 40% 50% 60% 70% 80% 90%
> ........
> Sat Dec 09 09:29:16 GMT 2017 Project successfully created.
> Sat Dec 09 09:29:16 GMT 2017 Saving results.
> 10% 20% 30% 40% 50% 60% 70% 80% 90%
> Sat Dec 09 09:30:01 GMT 2017 Results saved to /Volumes/yasset_data/ms_work/reanalysis/PXD001204/.PXD001204-39086/./ps_output.cpsx.
> 
> 
> Sat Dec 09 09:30:03 GMT 2017 PeptideShaker process completed.
> Sat Dec 09 09:30:03 GMT 2017 Processing Completed.

Now I have tried to convert the output into mzId: 

```
java -cp /Users/yperez/IdeaProjects/github-repo/pride-cluster/PRIDE-Cluster/cluster-data-generation/resources/PeptideShaker/PeptideShaker-1.16.15.jar eu.isas.peptideshaker.cmd.MzidCLI -in ./ps_output.cpsx -output_file PXD001204-39086.mzid -contact_first_name "Yasset" -contact_last_name "Perez-Riverol" -contact_email "yperez@ebi.ac.uk" -contact_address "EBI" -organization_name "EBI" -organization_email "yperez@ebi.ac.uk" -organization_address "Cambridge, UK"
```
and I god the error: 

> /Volumes/yasset_data/ms_work/reanalysis/PXD001204/PXD001204-39086/./ps_output.cpsx.
> java.io.OptionalDataException
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1373)
> 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
> 	at java.util.HashMap.readObject(HashMap.java:1394)
> 	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
> 	at java.util.HashMap.readObject(HashMap.java:1396)
> 	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
> 	at java.util.HashMap.readObject(HashMap.java:1396)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
> 	at java.util.HashMap.readObject(HashMap.java:1396)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
> 	at java.util.HashMap.readObject(HashMap.java:1396)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
> 	at java.util.HashMap.readObject(HashMap.java:1396)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
> 	at com.compomics.util.io.SerializationUtils.readObject(SerializationUtils.java:58)
> 	at com.compomics.util.experiment.io.ExperimentIO.loadExperiment(ExperimentIO.java:44)
> 	at eu.isas.peptideshaker.fileimport.CpsFileImporter.<init>(CpsFileImporter.java:57)
> 	at eu.isas.peptideshaker.utils.CpsParent.loadCpsFile(CpsParent.java:205)
> 	at eu.isas.peptideshaker.cmd.MzidCLI.call(MzidCLI.java:127)
> 	at eu.isas.peptideshaker.cmd.MzidCLI.main(MzidCLI.java:338)

I was having a look and after the creation of the resources folder is trying to read the subfolder resources/experiment and is not present. Then I got the error. What to do? Can you point me to the please where I can fix this?

**Comment by mvaudel** [comment]
Hi Yasset!

Thanks for the detailed report! Can you try to redirect the temporary folder and log? For this, just add ```-temp_folder yourFolder -log yourLog``` to your command line. It should solve the resources folder issue. 

More details can be found here:
https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI#e---pathsettingscli

Also, I would recommend zipping the PeptideShaker output to avoid problems with file dependencies, just add ```-zip yourZip.zip``` to the command.

Hope this helps,

Marc

**Comment by ypriverol** [comment]
I have zipped the the output and use the log and temp folders but still I'm getting the error. New command: 

```
java -cp /Users/yperez/IdeaProjects/github-repo/pride-cluster/PRIDE-Cluster/cluster-data-generation/resources/PeptideShaker/PeptideShaker-1.16.15.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment "PRIDE Assay Reanalysis 39086" -sample "No sample name" -replicate 1 -identification_files ./searchgui_out.zip -out ./ps_output.cpsx -temp_folder ./ -log logs -zip ./ps_output.cpsx.zip
```

If I try to open it with the desktop version the output is that the file is corrupted.

**Comment by hbarsnes** [comment]
Hi Yasset,

Please use complete paths when referring to files or folders on the command line, e.g. don't use things like "./ps_output.cpsx". This should solve the problem.

Best regards,
Harald

**Comment by ypriverol** [comment]
@hbarsnes I have used absolute paths and did't work. 

<img width="1280" alt="screen shot 2017-12-09 at 18 16 14" src="https://user-images.githubusercontent.com/52113/33798281-943f9590-dd0d-11e7-92fa-9bb0f5210b27.png">

Here the log: 

[PeptideShaker.log](https://github.com/compomics/peptide-shaker/files/1544965/PeptideShaker.log)

**Comment by hbarsnes** [comment]
@ypriverol You seem to have some very strange paths in that error message? Can you send me the complete PeptideShaker command line you are using? Also, this error is while opening the project, are you sure there were no errors when processing the data?

**Comment by ypriverol** [comment]
@mvaudel and @hbarsnes Problem solve when you add the full path to searchgui and peptide shacker.. also I used now non-hidden folders. 

Thanks for the support.
