### ISSUE TITLE
duplicate key value in a unique or primary key constraint

### ISSUE THREAD

**Issue by brickyyyy** [compomics/peptide-shaker#294]
An error occurred: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL180113184057040' defined on 'PROTEINS'.

**Comment by hbarsnes** [comment]
Hi,

I'm afraid this is a known error that have also been reported by other users. The good news is that we are in the process of refactoring our code to remove this and other related issues (plus speeding up the processing). The bad news is that I cannot at this time tell you when the new version will become available.

But I will let you know as soon as the new version is ready for beta testing.

Best regards,
Harald

**Comment by brickyyyy** [comment]
Hi Harald,

Thank you very much for your quick answer. I am looking forward to hearing from you again :)

Regards,
Valentina

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
