### ISSUE TITLE
Question: how is the replicate number internally processed?

### ISSUE THREAD

**Issue by tivdnbos** [compomics/peptide-shaker#295]
Hi,

I was wondering what happens internally with the replicate number? Is it meant for biological or technical replicates? What happens with the output in PeptideShaker if you have multiple SearchGUI zipfiles for one PeptideShaker project, but just leave (or change) the (obliged) replicate number field as 0, 1 or the number of SearchGUI files? 

Thanks,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

The replicate number is not really used at the moment. It was added as a means of annotating the samples for when PeptideShaker will support the processing of multiple distinct samples. However, we have not yet gotten to this point. It is still in our plans though. So at the moment you can just leave the number at the default value.

Best regards,
Harald

**Comment by tivdnbos** [comment]
Thanks for your quick reply. Will this be improved in the new version of PeptideShaker? Have you already a date in mind for the beta release of the new version?

Best regards, 
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

I'm afraid that the support for processing multiple samples will not be part of the upcoming beta release. It is more focused on fixing memory related issues. It does however include some changes required for the future processing multiple samples.

No date yet for the beta release I'm afraid. Hopefully won't be too long.

Best regards,
Harald
