### ISSUE TITLE
Identification file

### ISSUE THREAD

**Issue by ntayl** [compomics/peptide-shaker#307]
Hi,

I'm new to this software so sorry if this is a very basic question. I'm wondering what type of file I need to use as the 'Identification file' when starting a new project?

**Comment by hbarsnes** [comment]
Hi,

The identification files supported as input to PeptideShaker are results from the given proteomics search engines and de novo tools: X! Tandem, MS-GF+, MS Amanda, OMSSA, MyriMatch, Comet, Tide, Mascot, Andromeda, Novor and DirecTag. All of which are available via [SearchGUI](http://compomics.github.io/projects/searchgui.html) (except for Mascot, as it is commercial software).

To ensure that the identification files are compatible with PeptideShaker we strongly recommend running the searches through SearchGUI.

For more details, I'd recommend taking a look at our tutorial material: http://compomics.com/bioinformatics-for-proteomics.

Best regards,
Harald
