### ISSUE TITLE
Extracting only PSMs

### ISSUE THREAD

**Issue by tivdnbos** [compomics/peptide-shaker#308]
Dear Marc, Harald,

I was wondering if there's an option in PeptideShaker (GUI or CLI) to only extract the identified peptides & PSMs, without calculating the probability it's linked to a protein.
If working with a peptide database (peptide fasta), PeptideShaker crashes due to a memory overload during the step mentioned above.

Best, 
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

I'm afraid this not supported in the current PeptideShaker version, but I think it might be supported in the upcoming release. I could be wrong though. @mvaudel knows more about this.

As for the memory issues, these should hopefully also be solved in the upcoming release. The bad news is that we cannot say exactly when the new version will become available, but we are getting close to releasing a beta version for testing.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Tim,

This feature is now available in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If it does not work as wanted, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This feature is supported in the new release that is available now. If it does not work as wanted, please let us know by opening a new issue.
