### ISSUE TITLE
Adding IdentiPy results input

### ISSUE THREAD

**Issue by chrishuges** [compomics/peptide-shaker#309]
Has there been any discussion around incorporating the IdentiPy search engine into SearchGUI or the results into PeptideShaker?

https://pubs.acs.org/doi/10.1021/acs.jproteome.7b00640
https://bitbucket.org/levitsky/identipy/src/default/

We have done extensive testing of different combinations of search engines for different types of data with SearchCLI and PeptideShakerCLI and which ultimately give the best data. Although combining 2 or more search engines still gives a superior result, IdentiPy gives a very nice output in standalone comparisons. The output is standard pep.xml, so should be straightforward to implement I would think.

Would be very nice to have included!

Cheers,
Chris

**Comment by hbarsnes** [comment]
Hi Chris,

We generally only add search engines to SearchGUI that do not require the user to install additional software or libraries. And as far as I can see IdentiPy requires the installation of both Python?

We could however consider adding support for loading pepxml files from IdentiPy in PeptideShaker if you think that would be interesting on its own? If yes, it would be great if you could send us a pepxml file from IdentiPy (along with the mgf and FASTA file, and preferably a related settings file from SearchGUI)? I know that pepxml is considered as a standard format, but from experience pepxml is not always pepxml. Should hopefully not be too hard to update our code though.

Best regards,
Harald

**Comment by chrishuges** [comment]
Yes it does require Python. 

Happy to send all of those files. Where shall I deposit them, or send them to?

Cheers,
Chris

**Comment by hbarsnes** [comment]
Hi Chris,

> Where shall I deposit them, or send them to?

Can you upload them to Dropbox or similar and send me the link?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Chris,

Took longer than planned, but now I've finally set up an issue at the IdentiPy webpage. You can follow the progress here: https://bitbucket.org/levitsky/identipy/issues/6/loading-identipy-pepxml-files-in.

Best regards,
Harald

**Comment by chrishuges** [comment]
Hi Harald,

That is great! I have redone the search as requested with the latest commit of IdentiPy. I have put the relevant files on google drive: https://drive.google.com/open?id=1_t30rv3z5WaolTZCXNC5yBctZJDggbib.

Please let me know if you have troubles getting them. 

FYI, we are creating the mgf files (also stored in the google drive folder) using [RawQuant](https://github.com/kevinkovalchik/RawQuant) on Linux. If the header format is wrong, let me know and it can easily be changed.

Cheers,
Chris

**Comment by hbarsnes** [comment]
Hi Chris,

Thanks for the updated files. As you can see there are still some issues, but we are making good progress. :)

> FYI, we are creating the mgf files (also stored in the google drive folder) using RawQuant on Linux. If the header format is wrong, let me know and it can easily be changed.

No need to change the mgf titles. It was just me misunderstanding the pep.xml file. I still think the titles should be annotated via the spectrumNativeID attributes though, but that is up to the IdentiPy developers and not related to the format of the spectrum titles.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Chris,

Maybe you've already seen the comments on the IdentiPy issue tracker, but we can now parse the mgf-based IdentiPy pep.xml files without any issues and support for loading IdentiPy results will be included in the next major release of PeptideShaker. :)

Best regards,
Harald

**Comment by chrishuges** [comment]
Awesome! Thank you for all your work to make this happen. I look forward to trying it out in the next release.

**Comment by hbarsnes** [comment]
Hi Chris,

IdentiPy should be supported in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If this is not the case, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

And if it does work as wanted, it would also be great of you could let us know by replying to this original issue and letting us know. :)

Best regards,
Harald

**Comment by hbarsnes** [comment]
Support for loading results from IdentiPy is included in the new release that is available now. If it does not work as wanted, please let us know by opening a new issue.
