### ISSUE TITLE
Identification result file 'searchGUI_input.txt' not recognized.

### ISSUE THREAD

**Issue by antortjim** [compomics/peptide-shaker#310]
Hi there :smile: 

I am writing a bash script combining the power of SearchGUI and PeptideShaker. However, I cannot get them to work properly, as when I try to read the search result files produced by SearchGUI with PeptideShaker, I get the following error

```
Tue May 15 10:27:47 CEST 2018 Parsing searchGUI_input.txt.
Tue May 15 10:17:09 CEST 2018 Identification result file 'searchGUI_input.txt' not recognized.
Tue May 15 10:17:09 CEST 2018 PeptideShaker Processing Canceled.
```
when I run 
`java -cp $PEPTIDESHAKER_PATH eu.isas.peptideshaker.cmd.PeptideShakerCLI   -experiment $EXP_NAME   -sample $SAMPLE_NAME  -replicate $REPLICATE    -identification_files $OUT_DIR   -spectrum_files $SPECTRA   -id_params $OUT_DIR/$PARAMS_NAME.par   -out $OUT_DIR/$SAMPLE_NAME.cpsx`

while the same dataset does not return the error when running PeptideShaker with the GUI

This is the content of searchGUI_input.txt:
```
/home/antortjim/data/thp1/mgf/PD7502-GDTHP1-A_C1.mgf
/home/antortjim/data/thp1/mgf/PD7503-GDTHP1-A_C2.mgf
```
i.e the absolute path of the mgf files used in the analysis, one per line

How can I get around this?

I am using SearchGUI version 3.3.1 and PeptideShaker 1.16.23 on Ubuntu 16.04

Thanks!!

**Comment by antortjim** [comment]
I can now see that if I put searchGUI_input.txt somewhere else, the command is successful and the project (cpsx file) is created. However, when I launch it on the GUI, the path to the spectra needs to be supplied.

Moreover, if any .txt files are present in the folder storing searchGUI output, PeptideShaker tries to parse them. Therefore, the output folder of searchGUI should be empty when it gets populated.

**Comment by antortjim** [comment]
Hi Harald

Thanks for your mail!
I am trying providing the zip file produced by searchGUI (the default) and passing it to `-identification_files` in PeptideShaker. But I get a very cryptic error

```
Tue May 15 13:56:21 CEST 2018 Unzipping searchgui_out.zip.
Tue May 15 13:56:21 CEST 2018 An error occurred while creating the PeptideShaker project.
java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:569)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:938)

```
If instead, I unzip the file to an empty folder and pass the folder name as input to `-identification_files` I get the same error as before:

```
Tue May 15 14:00:51 CEST 2018 Parsing searchGUI_input.txt.
Tue May 15 14:00:51 CEST 2018 Identification result file 'searchGUI_input.txt' not recognized.
Tue May 15 14:00:52 CEST 2018 PeptideShaker Processing Canceled.
```

Best


Antonio

**Comment by hbarsnes** [comment]
Hi Antonio,

Could it be that you are using a relative path when referrng to the zip file in the PeptideShaker command line? As the error in question refers to a line trying to get the parent folder of the zip file. I think that if you change it to the complete path it should all work fine.

Best regards,
Harald

**Comment by antortjim** [comment]
Hi Harald

You are right, I needed to pass an absolute path :man_facepalming: :+1: 

Thanks for your help and have a very nice day!

Best regards,
Antonio

**Comment by antortjim** [comment]
Even though this fixes the issue, Peptide Shaker still does not know how to locate the mgf files. How can I provide that info via CLI? I tried providing the mgf files in the zip file by setting `-output_data 1` in searchGUI but still no luck.

Thank you very much for your help!! :smiley: 

Best

Antonio

**Comment by hbarsnes** [comment]
Hi Antonio,

What kind of error do you get? And have you checked that the mgf files are in the zip file?

Best regards,
Harald

**Comment by antortjim** [comment]
Hi Harald

After making sure the mgf file is inside the `data` folder in `searchgui_out` (achieved by passing `-output_data 1` to searchGUI), the message prompting to locate the mgf file manually stopped appearing. 

Thank you for your help!!

Best
Antonio
