### ISSUE TITLE
Custom PTMs

### ISSUE THREAD

**Issue by ntayl** [compomics/peptide-shaker#311]
Hi,

I am trying to create my own custom modification on search GUI. I am unsure what I need to put into the neutral ions and reporter ions sections. Also the particular modification in not on unimod so do I need to put anything in that section?

Thank you for your help,

Neil

**Comment by mvaudel** [comment]
Hi Neil,

If you are not aware of neutral losses associated to your modification, you can leave these fields blank. Same for the unimod, if the modification is not there you can just proceed.

Hope this helps,

Marc

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
