### ISSUE TITLE
Peptide summary not opening

### ISSUE THREAD

**Issue by Sbuthelezi** [compomics/peptide-shaker#312]
I have a problem opening the peptide summary for some of my runs on the validation tab. When I click on the peptide option the program freezes. The below error appears.

"Inspect the log file for details: resources/conf/startup log"

This problem is not consistent as I am able to open my other runs without a problem.

Please help.

**Comment by mvaudel** [comment]
Hi,

Currently the tool is unstable if multiple instances are running simultaneously. Please make sure that only one instance is running at a time. If the problem persists, please send us the resources/conf/startup.log file located in the folder of the jar file.

Hope this helps,

Marc

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
