### ISSUE TITLE
error Importing Data from Mascot search

### ISSUE THREAD

**Issue by temaia** [compomics/peptide-shaker#313]
Hello, 

I would like to report an error at the end of the import of a Mascot search project into a new PeptideShaker project: 
- Data import was canceled due to the impossibility of finding one scan object in cache (please see the enclosed error file)
[error_finalimport_endlines.txt](https://github.com/compomics/peptide-shaker/files/2027519/error_finalimport_endlines.txt)
[error_finalimport_endlines.txt](https://github.com/compomics/peptide-shaker/files/2027523/error_finalimport_endlines.txt)

Could you give me a hint on how to solve this? Are there any requirements about the location of the input files (in this case mgf, dat (or even the raw ones))

**Comment by hbarsnes** [comment]
Hi,

I'm afraid this is a known issue with how PeptideShaker handles the memory (you can find several other users reporting similar issues). The good news is that we are in the process of refactoring the code to remove the chance of such errors occurring. We are (hopefully) getting close to releasing a beta version with these improvements and will let you know as soon as it is available.

Best regards,
Harald

**Comment by temaia** [comment]
Dear Harald, 

Thank you for your email. 

We are looking forward to your beta version release. 

Best regards, 

Teresa

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
