### ISSUE TITLE
Custom prefix for report files

### ISSUE THREAD

**Issue by antortjim** [compomics/peptide-shaker#314]
Hi there!

I was wondering if it would be possible to add a flag to the ReportCLI utility in Peptide-Shaker so the prefix that is prepended to all reports generated from the same project (.cpsx file) can be set to a custom value. By default, it is set to `experiment_sample_replicate_`, as taken from the corresponding `-experiment`, `-sample` and `-replicate` flags used when calling `eu.isas.peptideshaker.cmd.PeptideShakerCLI`. Ideally there would be a `-prefix` flag in ReportCLI overriding this.

```
java -cp $PEPTIDESHAKER_PATH eu.isas.peptideshaker.cmd.ReportCLI \
     -in $ROOT_DIR/$EXP_NAME/$PS_OUT/$SAMPLE_NAME.cpsx \
     -out_reports $ROOT_DIR/$EXP_NAME/$PS_OUT/reports \
     -reports "0,1,2,3,4,5,6,7,8" \
     -prefix $MYPREFIX
```

This would be useful for more convenient connection to downstream tools such as https://github.com/compomics/moFF/, which requires the input files (i.e Default_PSM_Report from Peptide-Shaker) to have the same name as the raw files. This can be of course achieved by simply renaming the files, but it adds an unnecessary processing step.

Please point me out if this is already possible to do! Thanks beforehand.

Best regards

Antonio

**Comment by mvaudel** [comment]
Hi Antonio,

Sure, we can label reports the way you want. We are currently refactoring the tool, we will include this in the next major release (will be 2.0.x). If we overlook it please send us a reminder here, our todo list is quite long at the moment :)

Thanks for the suggestion,

Marc

**Comment by antortjim** [comment]
Hi Marc

Thanks, that would be great! Looking forward to it :D 

Best

Antonio

**Comment by hbarsnes** [comment]
Hi Antonio,

The requested prefix has now been added to the ReportCLI command line options and will be available in the next major release of PeptideShaker.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This feature should be included in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the feature does not work as wanted, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

And if it does work as wanted, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by antortjim** [comment]
Dear Harald,

I cannot check now but I will in the not so far future when I use PeptideShaker again. Thank you very much! I will reopen if needed.
Best regards,
Antonio
