### ISSUE TITLE
Exporting spectral index

### ISSUE THREAD

**Issue by antortjim** [compomics/peptide-shaker#315]
Hi there!

Would it be possible to add a new feature to the list of exportable features in PeptideShaker? It would be great if the tool could export the **Spectral Index (SI)** of each validated spectrum in a PS project. More details on the SI are here:
https://www.ncbi.nlm.nih.gov/pubmed/20010810 -- development of the method
https://www.ncbi.nlm.nih.gov/pubmed/29400476 -- recent implementation in the Trans Proteomic Pipeline (TPP)

Exporting the SI would enable downstream MS2 intensity-based label-free quantification in a very straightforward way. The feature would consist of the summed intensity of all the b- and y- ions that contributed to the given spectrum identification.
Currently, it is possible to compute by creating a PS custom export and post-processing it. This processing could be provided by PS, so no post-processing would be required by the user.
Provided the SI, the SIn can easily be computed following the equations in the first paper I linked.

Please don't hesitate to correct me if this is already possible or if it would not make much sense (I could be wrong). Thanks beforehand!

Cheers

Antonio

**Comment by antortjim** [comment]
The length of the proteins would also be required in order to perform the last step of the normalization. However, I can't see that feature included in the PS list of custom features. Moreover, I don't know how to define protein length when the matched protein is a protein group (i.e several sequences).

**Comment by antortjim** [comment]
Hi Harald,

Thanks for your fast answer! Of course I imagine implementing the SI is not straightforward. Thanks for looking at this.
The length is not included but the molecular weight. On the other hand, one can always fetch the length from Uniprot or from the fasta database used I guess. I reckon the thing with the proteins group is a problem yes.. :angel:
I will try to implement it on my own.

Once again, thanks for sharing your work in such an open way.

Best regards,
Antonio

**Comment by hbarsnes** [comment]
Hi Antonio,

Protein length has now been added to the list of protein features available as part of the identifications feature export and will be available in the next major release of PeptideShaker.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Antonio,

Protein length is now available in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

Best regards,
Harald

**Comment by antortjim** [comment]
Hi Harald,

Sorry for the late response. But thank you very much for looking into it. It is great news!! :)

Best regards,
Antonio
