### ISSUE TITLE
Custom report not availabile in CLI

### ISSUE THREAD

**Issue by Seb-Leb** [compomics/peptide-shaker#317]
I have created a custom report in PeptideShaker 1.16.26 GUI on my local machine and sent the resulting exportFactory.cus file to our HPC platform. (same version of PeptideShaker there)
As suggested in issue #284 I set the -temp_folder option to the folder containing exportFactory.cus (I also tried setting the -peptideshaker_exports option). However, my custom report does not show in the indexed reports when runing the folowing comand:
`java -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.ReportCLI`

here is my resources/conf/paths.txt:
```
peptideshaker_matches_directory=/home/sleblanc/BP2_ms_rerun/tmp
peptideshaker_user_preferences=/home/sleblanc/BP2_ms_rerun/tmp
peptideshaker_exports=/home/sleblanc/BP2_ms_rerun/tmp
unzip=/home/sleblanc/BP2_ms_rerun/tmp
utilities_user_preferences=/home/sleblanc/BP2_ms_rerun/tmp
ptm_configuration=/home/sleblanc/BP2_ms_rerun/tmp
enzyme_configuration=/home/sleblanc/BP2_ms_rerun/tmp
fasta_indexes=/home/sleblanc/BP2_ms_rerun/tmp/fasta_indexes
gene_mapping=/home/sleblanc/BP2_ms_rerun/tmp/gene_mapping
pride_annotation=/home/sleblanc/BP2_ms_rerun/tmp/pride
identification_parameters=/home/sleblanc/BP2_ms_rerun/tmp/identification_parameters
```

exportFactory.cus is in /home/sleblanc/BP2_ms_rerun/tmp/

[exportFactory.cus.zip](https://github.com/compomics/peptide-shaker/files/2130976/exportFactory.cus.zip)

Please advise
Thank you!

**Comment by hbarsnes** [comment]
It seems like you have yet again uncovered a bug that we were not aware of. The user-defined path settings are only read _after_ the checking of the command line options. Which means that your user-defined exportFactory file will not be used and instead it defaults to the standard options.

We'll try to come up with a fix and release a new version as soon as possible.

In the meantime you could try to putting your custom exportFactory file into the default location expected by PeptideShaker? This should be in "user.home"/.peptideshaker/exportFactory.cus. I guess this would be "/home/sleblanc/.peptideshaker/exportFactory.cus" in your case? Do you have such a folder? And does it contain an exportFactory file?

**Comment by Seb-Leb** [comment]
It works!
I didn't realize I had that directory. Is the directory cerated even when only using the CLI? I did use the GUI with X11 forwarding so it might have been created then..
Thank you very much
our lab really appreciates all your work

**Comment by hbarsnes** [comment]
> Is the directory cerated even when only using the CLI?

Should be yes. But as you may have noticed this is clearly not the most well-tested part of our code. :)
