### ISSUE TITLE
Custom modification

### ISSUE THREAD

**Issue by ntayl** [compomics/peptide-shaker#319]
Hello,

I am trying to identify a custom modification that I have added to the C-terminus of a protein. As far as I can tell on search GUI you can only account for an increase of mass due to a modification. However my modification is added via hydrolysis so is there any way I can account for both the added mass of my modification as well as the loss of the OH on the amino acid I am modifying. 

Thank you for your help.

**Comment by hbarsnes** [comment]
Hi,

When setting up a modification in SearchGUI you provide the atom composition which is then calculated into the mass shift the modification results in. You can add both positive and negative components which will be summed together. To subtract a given atom, simply choose a negative integer for the number of copies of that atom.

Best regards,
Harald

**Comment by ntayl** [comment]
Hi Harlod,

I didn't realised this was possible. Thank you for your help.
