### ISSUE TITLE
Difference between Extended and Default PSM reports

### ISSUE THREAD

**Issue by antortjim** [compomics/peptide-shaker#321]
Hi Harald and Marc

I have tried to relate the statistics from the PeptideShaker GUI to the ones I get by analyzing the PSM reports. I can see that the numbers on top of the table **Spectrum Selection** in the **Spectrum IDs** tab are (I) the sum of spectra validated or doubtful in the **Default PSM report** and (II) the total number of spectra in the mgf file

`tail -n +2 Default_PSM_Report.txt | rev | cut -f1 | rev | sort | uniq -c
`
 ```  
  4283 Confident
   142 Doubtful
```
the sum is 4425, which is the number I visualize in the GUI.
However, running the same on the Extended PSM report, I get
```
   4307 Confident
    161 Doubtful
   4146 Not Validated
```
the sum of those is < # spectra in the mgf file (8956). I guess the missing ones are those that were not assigned to anything. But why are there more both confident and doubtful identifications in the extended report than the default? I thought the only difference was that the extended includes the not validated identificatons.

Moreover, I get that there are 4531 unassigned spectra by looking at the third barplot in the bottom
![unassigned](https://user-images.githubusercontent.com/13869571/42376185-84b62fc0-811e-11e8-8c06-b331b645d551.png).

That is, the total spectra - # (spectra validated + doubtful from default report)

I have checked if creating the reports via the GUI makes a difference and it doesn't.

So what's the difference between the Extended and Default PSM reports?! :stuck_out_tongue: 

Thanks for your time and your help!

Best regards,

Antonio

**Comment by hbarsnes** [comment]
Hi Antonio,

> So what's the difference between the Extended and Default PSM reports?

The are only two differences: 1) the Default PSM Report only includes the validated PSMs while the Extended PSM Report includes all PSMs, and 2) the Default PSM Report does not include the decoys hits while the Extended PSM Report does. (The Extended PSM Report also includes one additional column indicating whether a PMS is a decoy hit or not.)

Best regards,
Harald

**Comment by antortjim** [comment]
Hi Harald

Thanks, of course! I missed the decoy column.

Thanks for your help!!!

Antonio
