### ISSUE TITLE
Peptideshaker results with openswath

### ISSUE THREAD

**Issue by srithegreat** [compomics/peptide-shaker#329]
Hi,

I really appreciate the peptide-shaker and the way it has emerged in past years. I use it for DDA searches from 3 different search engines. Now I want to create a spectral library from the results and use the same with openswath pipeline. Is is feasible with the current version? How should I proceed? Should I exporting the results as mzid?

Srikanth

**Comment by hbarsnes** [comment]
Hi Srikanth,

I'm afraid we have no experience with OpenSWATH. I'd recommend contacting the OpenSWATH developers (or read their documentation) to figure out what kind of input they require.

The available export options in PeptideShaker, of which mzIdentML is one of the supported formats, can be found on the Export menu in main PeptideShaker window after opening a project.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Srikanth,

It would perhaps be simpler to make your own custom report from PeptideShaker compared to exporting to mzIdentML and then parsing it. At least it's worth looking into.

Best regards,
Harald

**Comment by srithegreat** [comment]
Hi Herald,

I tried to export custom report format from PeptideShaker, but looks like I am not able to get the fragment intensity and other columns like fragment type, series. Do you have a way to get the same? I am interested in creating a list of similar kind (http://openswath.org/en/latest/docs/generic.html).

Regards,
Srikanth

**Comment by hbarsnes** [comment]
Hi Srikanth,

Have you turned on "Show Advanced Features" and "Show Sub Features" in the bottom right corner in the dialog where you create the custom report?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
