### ISSUE TITLE
PeptideShaker Error with Comet

### ISSUE THREAD

**Issue by chrishuges** [compomics/peptide-shaker#330]
Hi, 

I am encountering an issue with Comet in PeptideShaker (I have tried versions 1.16.23 and 1.16.29 and it occurs in both). I am processing an MGF input via the command:

```
for i in *.zip; do java -Xmx120g -cp /projects/ptx_analysis/chughes/software/PeptideShaker-1.16.29/PeptideShaker-1.16.29.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment fractions -sample $i -replicate 1 -identification_files /projects/ptx_analysis/chughes/projects-current/xxxxx/ms_data/$i -spectrum_files /projects/ptx_analysis/chughes/projects-current/xxxxx/ms_data/ -id_params /projects/ptx_analysis/chughes/parameter-files/current/ch_may2018_OT-MS1_HCD-OT-MS2_human-trypsin_StdMods.par -out /projects/ptx_analysis/chughes/projects-current/xxxxx/ms_data/$i.out.cpsx; done
```

When PeptideShaker tries to process the Comet results, the following error appears:

```
Thu Sep 20 09:06:41 PDT 2018 Unzipping ch_XXXXX.raw_searchgui_out.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Thu Sep 20 09:06:45 PDT 2018 Import process for fractions (Sample: ch_XXXXX.raw_searchgui_out.zip, Replicate: 1)

Thu Sep 20 09:06:46 PDT 2018 Importing sequences from uniprot_human-crap_sep2018_FWD_concatenated_target_decoy.fasta.
 0%
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Thu Sep 20 09:07:02 PDT 2018 FASTA file import completed.
Thu Sep 20 09:07:02 PDT 2018 Importing gene mappings.
Thu Sep 20 09:07:03 PDT 2018 Establishing local database connection.
Thu Sep 20 09:07:05 PDT 2018 Reading identification files.
Thu Sep 20 09:07:05 PDT 2018 Parsing ch_XXXXX.raw.comet.pep.xml.
Thu Sep 20 09:07:07 PDT 2018 Loading spectra for ch_XXXXX.raw.comet.pep.xml.
Thu Sep 20 09:07:07 PDT 2018 Importing ch_XXXXX.raw.mgf
Thu Sep 20 09:07:07 PDT 2018 ch_XXXXX.raw.mgf imported.
10% 20% 30% 40% 50%<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>

Thu Sep 20 09:07:07 PDT 2018 An error occurred while loading the identification files:
Thu Sep 20 09:07:07 PDT 2018 Index: 15129, Size: 15129
java.lang.IndexOutOfBoundsException: Index: 15129, Size: 15129
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at com.compomics.util.experiment.io.massspectrometry.MgfIndex.getSpectrumTitle(MgfIndex.java:239)
        at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrumTitle(SpectrumFactory.java:1114)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importSpectrum(FileImporter.java:999)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importPsms(FileImporter.java:720)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:476)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:151)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:738)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:938)
Free memory: 1766901360
Thu Sep 20 09:07:08 PDT 2018 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>
```

I am using SearchCLI with the below input command to generate these data:

```
for i in *.mgf; do java -Xmx100g -cp /projects/ptx_analysis/chughes/software/SearchGUI-3.3.1/SearchGUI-3.3.1.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files /projects/ptx_analysis/chughes/projects-current/xxxxx/ms_data/$i -output_folder /projects/ptx_analysis/chughes/projects-current/xxxxx/ms_data/ -id_params /projects/ptx_analysis/chughes/parameter-files/current/ch_may2018_OT-MS1_HCD-OT-MS2_human-trypsin_StdMods.par -output_option 1 -xtandem 1 -msgf 1 -comet 1; done
```

I generated the MGF inputs using [RawTools](https://github.com/kevinkovalchik/RawTools). The MGF header looks like:

```
BEGIN IONS
RAWFILE=ch_XXXX_1.raw
TITLE=Spectrum_19
SCAN=19
RTINSECONDS=0.137723333333333
PEPMASS=432.224365234375
CHARGE=2
```

Interestingly, I don't encounter this error with Comet if I use an MGF with the header:

```
BEGIN IONS
TITLE=ch_XXXX_1.19.19.2
RTINSECONDS=8.2634
PEPMASS=432.224365234375 8761.318359375
CHARGE=2+
```

Not sure what is going on here. I am going to roll back to SearchCLI 3.2.26 before Comet was updated and see what the result is. Will post here.

Thanks!
Chris

**Comment by chrishuges** [comment]
Gives same issue with SearchCLI 3.2.26 using the old Comet version.

**Comment by hbarsnes** [comment]
Hi Chris,

I think this error is due to how the spectrum titles are annotated in the pepxml file and how we try to map them back to the spectrum titles in the mgf file. We prefer relying on the `spectrumNativeID` tag which should include the spectrum title from the searched mgf file. But if this tag is missing we have to rely on the `index` tag and try to map the index back to the n'th spectrum in the mgf file, which is more of a guess.

Could you check to confirm that your first type of mgf header results in pepxml files that do not include the `spectrumNativeID` tag, while the second type of mgf header results in pepxml files that do contain the `spectrumNativeID` tag? If that is the case, it would explain why we have trouble parsing the first pepxml file.

As to why the pepxml is different in the first place you'd have to ask the developer of Comet, but probably due to how the mgf file is parsed?

Best regards,
Harald

**Comment by chrishuges** [comment]
Interesting, thanks Harald. This does appear to be the issue, and it seems Comet needs to have the MGF header a specific way. 

On a side note, what would an ideal MGF header include for SearchGUI and PeptideShaker look like? And in what format? For example, does anything about the first MGF header I posted above make you think it might give an issue with this mapping you mention?

Cheers,
Chris

**Comment by chrishuges** [comment]
Just to add to the above comment, I notice in the 'default_PSM_report' from Peptide Shaker that it doesn't seem able to get the actual spectrum number out for the 'Spectrum Number' column. What needs to be in the MGF header to make this mapping work properly? I can parse it out of the Spectrum Title column easily enough, but I would rather it work properly.

**Comment by hbarsnes** [comment]
Hi Chris,

> On a side note, what would an ideal MGF header include for SearchGUI and PeptideShaker look like? And in what format? For example, does anything about the first MGF header I posted above make you think it might give an issue with this mapping you mention?

Our main requirement is that the spectrum title is unique and can thus be used to uniquely identify a spectrum. (Also should not include non-standard characters etc., but I guess that is a given.) Both of the headers above should therefore be fine for both SearchGUI and PeptideShaker. Well, unless you pass the first of them through Comet that is. ;)

>  I notice in the 'default_PSM_report' from Peptide Shaker that it doesn't seem able to get the actual spectrum number out for the 'Spectrum Number' column. What needs to be in the MGF header to make this mapping work properly?

Given that the spectrum number/index is not always reliable, and given that there is no one standard format for how to annotate spectrum number/index across all the different spectrum file formats, PeptideShaker basically ignores the spectrum numbers, and instead relies on the spectrum titles. What you see in the 'Spectrum Scan Number' column in the report is simply what is included in the 'SCAN' element of the mgf header.

Best regards,
Harald

**Comment by chrishuges** [comment]
Ok thanks! This issue is solved for me.
