### ISSUE TITLE
peptide-shaker writes to HOME

### ISSUE THREAD

**Issue by bernt-matthias** [compomics/peptide-shaker#331]
Hi @hbarsnes @CarlosHorro 

the galaxy guy again :) 

I just ran with peptideshaker into a similar problem as with searchgui. The program writes some data in the home directory, which again does not work in Galaxy. 

The directory/file is `~/.peptideshaker/exportFactory.cus`

I already tested `peptide-shaker eu.isas.peptideshaker.cmd.PathSettingsCLI -temp_folder JOBFOLDER -log JOBFOLDER/peptideshaker.log` but this did not help. 

also `export HOME=JOBFOLDER` did not help. 

Maybe the PathSettingsCLI also needs an `--exec_dir` parameter? Or is there another way?

**Comment by hbarsnes** [comment]
Have you tried adding the -temp_folder option directly to the PeptideShaker command line?

**Comment by bernt-matthias** [comment]
Just rechecked. All calls use -temp_folder (there was one missing) the file is created. 

Also the calls use --exec_dir (which is undocumented). 

I also tried to add a call to PathSettingsCLI. Also did not help. 

You may have a look on the comman line here: 

https://github.com/bernt-matthias/tools-galaxyp/blob/topic/peptideshaker-homefix/tools/peptideshaker/peptide_shaker.xml

**Comment by hbarsnes** [comment]
> All calls use -temp_folder (there was one missing) the file is created.

So what kind of errors do you get? And what has been changed compared to the current working Galaxy version of PeptideShaker?

> Another problem seems to be the memory requirements. For the actual data of one of our users peptideshaker needs apparently more than 56G (I call with -Xmx 46G)

Don't see how this relates to the use of the home folder..? And what is the problem with going above 56 GB for the Xmx option? We frequently run with >60 GB on our side.

**Comment by bernt-matthias** [comment]
`So what kind of errors do you get? And what has been changed compared to the current working Galaxy version of PeptideShaker?`

```
java.io.FileNotFoundException: /home/petrusch/.peptideshaker/exportFactory.cus (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.compomics.util.io.SerializationUtils.writeObject(SerializationUtils.java:23)
	at eu.isas.peptideshaker.export.PSExportFactory.saveFactory(PSExportFactory.java:118)
	at eu.isas.peptideshaker.export.PSExportFactory.getInstance(PSExportFactory.java:97)
	at eu.isas.peptideshaker.cmd.ReportCLIParams.<clinit>(ReportCLIParams.java:15)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLIParams.createOptionsCLI(PeptideShakerCLIParams.java:76)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:919)
```

```
java.io.FileNotFoundException: /home/petrusch/.peptideshaker/exportFactory.cus (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.compomics.util.io.SerializationUtils.writeObject(SerializationUtils.java:23)
	at eu.isas.peptideshaker.export.PSExportFactory.saveFactory(PSExportFactory.java:118)
	at eu.isas.peptideshaker.export.PSExportFactory.getInstance(PSExportFactory.java:97)
	at eu.isas.peptideshaker.cmd.ReportCLIParams.<clinit>(ReportCLIParams.java:15)
	at eu.isas.peptideshaker.cmd.ReportCLI.main(ReportCLI.java:332)
```

So the main problem is that it writes/reads a file in the users home. Even if this would be successful it would be problematic in a multi user environment like Galaxy. The file is accessed by PeptideShakerCLI and ReportCLI.

I tried the following changes: 

- I added `export HOME=WORKDIR`
- For MzidCLI I added the parameter `-temp_folder \$cwd/MzidCLI` (now all peptide-shaker calls have the exec_dir and log_folder parameters)
- I also tried to add a call
```
peptide-shaker eu.isas.peptideshaker.cmd.PathSettingsCLI 
            --exec_dir="\$cwd/${bin_dir}"
	-temp_folder \$cwd/PathSettingsCLI
		-log \$cwd/peptideshaker.log
```

The full command line is 

```
mkdir output_reports; 
cwd=`pwd`; 
export HOME=$cwd;  
echo "" > peptideshaker_stderr &&  
ln -s '/gpfs1/data/galaxy_server/galaxy-dev/database/files/001/285/dataset_1285220.dat' searchgui_input.zip && 
jar xvf searchgui_input.zip SEARCHGUI_IdentificationParameters.par &&   peptide-shaker eu.isas.peptideshaker.cmd.PathSettingsCLI --exec_dir="$cwd/bin" -temp_folder $cwd/PathSettingsCLI -log $cwd/peptideshaker.log &&  
(peptide-shaker eu.isas.peptideshaker.cmd.PeptideShakerCLI --exec_dir="$cwd/bin" -temp_folder $cwd/PeptideShakerCLI -experiment 'Galaxy_Experiment_2018092121161537557391' -sample 'Sample_2018092121161537557391' -replicate 1 -identification_files $cwd/searchgui_input.zip -id_params $cwd/SEARCHGUI_IdentificationParameters.par -out $cwd/peptideshaker_output.cpsx -zip $cwd/peptideshaker_output.zip -reports 5  -threads "${GALAXY_SLOTS:-12}"  -protein_fdr "1.0" -peptide_fdr "1.0" -psm_fdr "1.0" -ptm_score "0" -ptm_alignment "1" -ptm_sequence_matching_type "1" -protein_fraction_mw_confidence "95.0"  -import_peptide_length_min "6" -import_peptide_length_max "30" -import_precurosor_mz "10.0" -import_precurosor_mz_ppm "1" -exclude_unknown_ptms "1"  2>> peptideshaker_stderr)  &&  
echo "Running Reports";   
echo "Generating mzIdentML"; 
(peptide-shaker eu.isas.peptideshaker.cmd.MzidCLI --exec_dir="$cwd/bin" -temp_folder $cwd/MzidCLI -in $cwd/peptideshaker_output.zip -output_file $cwd/output.mzid -contact_first_name "Proteomics" -contact_last_name "Galaxy" -contact_email "galaxyp@umn.edu" -contact_address "galaxyp@umn.edu" -organization_name "University of Minnesota" -organization_email "galaxyp@umn.edu" -organization_address "Minneapolis, MN 55455, Vereinigte Staaten" 2>> peptideshaker_stderr) &&   
(peptide-shaker eu.isas.peptideshaker.cmd.ReportCLI --exec_dir="$cwd/bin" -temp_folder $cwd/ReportCLI -in $cwd/peptideshaker_output.zip -out_reports $cwd/output_reports -reports 5  2>> peptideshaker_stderr)   && find $cwd/output_reports -name '*Peptide_Report*' -exec bash -c 'mv "$0" "peptides.txt"' {} \;  && 
cat peptideshaker_stderr 2>&
```

**Comment by bernt-matthias** [comment]
Sorry about mixing the unrelated memory question in. Was just wondering that a <1GB input file generates more than 50GB RAM usage.

**Comment by hbarsnes** [comment]
@bernt-matthias So are you saying that you still get the errors with the references to the home folder even _after_ adding the temp_folder option to all the command lines?

@CarlosHorro Do you see any obvious issues with the command lines above? As this all works fine on our end right?

**Comment by bernt-matthias** [comment]
Jep. I still get the file `~/.peptideshaker/exportFactory.cus` in the users home.

**Comment by bernt-matthias** [comment]
The error I reported in the first place was from the current Galaxy version.  

- The user (petrusch) has for some reason (which I don't understand yet) no permission to write/read(?) the file `~/.peptideshaker/exportFactory.cus` so he gets the exception.
- When I reproduce this with my own user I just get the file `~/.peptideshaker/exportFactory.cus` written. 

The important point is that the file should not be written at all in the home dir.  

You can see the differences of the Galaxy wrappers (which did not influence if the file was written or not -- I just tried to reproduce what I learned from the recent changed in the searchgui wrapper)

https://github.com/galaxyproteomics/tools-galaxyp/compare/master...bernt-matthias:topic/peptideshaker-homefix

**Comment by hbarsnes** [comment]
> The important point is that the file should not be written at all in the home dir.

Agreed. Which is why the temp_folder option was added in the first place.

Maybe there is an error in the PathSettingsCLI such that the new temp folder is not set correctly? Works fine when running as a standard command line outside Galaxy though. Or maybe the temp folder provided as an alternative to "user home" does not exist or cannot be written to?

**Comment by hbarsnes** [comment]
Can you check that the file path.txt inside the PeptideShaker-X.Y.Z\resources\conf folder is actually created? And that it contains the temp path you set?

**Comment by bernt-matthias** [comment]
yes its created in the folder I specify with --exec_dir, ie. "$cwd/bin/resources/conf". none of the contained variables points to the users home.

**Comment by hbarsnes** [comment]
Ok, so then at least the temp paths are set. Could you try running the PeptideShaker command line without the reports? As then I think it should complete without errors and we can focus on the creation of the reports as the source of the issue.

**Comment by bernt-matthias** [comment]
I already ran the script step by step and I can verify that the file is already created by: 
`peptide-shaker eu.isas.peptideshaker.cmd.PeptideShakerCLI`

**Comment by bernt-matthias** [comment]
I also just checked if the more recent version 1.16.29 helps .. negative (Galaxy currently uses 1.16.26)

**Comment by hbarsnes** [comment]
The problem are the calls to PSExportFactory.getInstance which has a reference to the default user home folder. And given that this is called _before_ the new temp paths are set we end up with referring to the wrong folder...

I'll try to find a way around the problem and get back to you.

**Comment by bernt-matthias** [comment]
Great. Thanks a lot.

**Comment by bernt-matthias** [comment]
What is actually the content of `exportFactory.cus`? My main question is if the content may affect the results of peptideshaker...

**Comment by hbarsnes** [comment]
It contains the content of the different reports, i.e. when you say "give me report 1 and 3", for example, it then tells PeptideShaker what to include in each report. The content is standard for the default reports, but will differ for the custom user-created reports.

**Comment by hbarsnes** [comment]
@bernt-matthias Finally got some time to look into this issue in depth and think I have come up with a solution. Basically I had to split the command line such that any arguments related to changing the temp paths are executed _before_ the command line itself is carried out. Tricky, but now seem to work. Would be great if you could do some tests before I release new versions? You can find the two snapshots here: https://www.dropbox.com/s/fxad3wo6jx8lmcs/PeptideShaker-1.16.30-SNAPSHOT.zip?dl=0 and  https://www.dropbox.com/s/05oya5hm90oh1s4/SearchGUI-3.3.5-SNAPSHOT-mac_and_linux.tar.gz?dl=0.

**Comment by bernt-matthias** [comment]
Hi @hbarsnes. Thanks for your efforts. I successfully tested two of the scripts generated by Galaxy (one for searchgui and one for peptideshaker). Was quiet tricky since I needed to mimic the additional wrapper included in the conda package. 

However, I ran SearchGUI and PeptideShaker and neither `~/.peptideshaker` nor `~/.searchgui` was created. Looks good. If you give me a ping I could update the bioconda package.

Thanks a lot.

**Comment by bernt-matthias** [comment]
I have two more questions (that are unrelated to this PR -- but related to the update to 1.16.30)

1. it seems that since 1.16.26 (the version currently used in Galaxy) and 1.16.29 the reports changed (there are now with_non-validated_matches outputs for PSM/peptide/protein  and the order of the numbers in the command line arguments changed). 
Since these were not mentioned in the change log I'm wondering if there were any other changes to the command line interface that need to be reflected in the Galaxy wrapper. 
Maybe you can make a diff of the command line options 1.16.26 and the new version?

2. Currently a typical peptide shaker script generated by Galaxy looks like this (omitting almost all options)

```
PathSettingsCLI ...
PeptideShakerCLI -reports 0,1,2,3,4,5,6,7 ...
ReportCLI -out_reports output_reports -reports 0,1,2,3,4,5,6,7 ...
```

I'm wondering if there is any reason why PeptideShakerCLI and ReportCLI both have the reports option. Galaxy only uses the reports in the directory output_reports  that are written by ReportCLI and ignores the reports of PeptideShakerCLI which are in the current working directory.

The reports seem to be identical (only the PSM reports seem to differ in order, and the certificate has once   "Selected Ions: b, y" and once    "Selected Ions: y, b"). Could it be that MzidCLI might be called between PeptideShakerCLI and ReportCLI if the user selects this?

If you also see no reason for generating the reports twice I could remove either the ReportCLI call or the -reports option from  PeptideShakerCLI.

**Comment by hbarsnes** [comment]
> I successfully tested two of the scripts generated by Galaxy (one for searchgui and one for peptideshaker).

Great! We will do some more testing tomorrow and then deploy new versions.

> it seems that since 1.16.26 (the version currently used in Galaxy) and 1.16.29 the reports changed

Yes, we needed to add reports that also included the non-validated hits without requiring the user to create custom reports.

> Since these were not mentioned in the change log

They were: https://github.com/compomics/peptide-shaker/wiki/ReleaseNotes. :)

> I'm wondering if there were any other changes to the command line interface that need to be reflected in the Galaxy wrapper.

Nope, there are no other changes.

> I'm wondering if there is any reason why PeptideShakerCLI and ReportCLI both have the reports option. 

The reason is that these have two different use cases. If generating the reports as part of processing the data I'd recommend using the reports options directly on the PeptideShakerCLI command line. This should be faster as the reports are then created when the data is already loaded in memory.

The ReportCLI is intended to be used if the PeptideShaker project has been created previously and thus requires a saved cpsx file as input, meaning that the project will have to be reopened before the reports can be created.

Generally in the Galaxy setting I'd recommend using the report options directly on the PeptideShakerCLI command line.

> Galaxy only uses the reports in the directory output_reports that are written by ReportCLI and ignores the reports of PeptideShakerCLI which are in the current working directory.

If you add the -out_reports option to the PeptideShakerCLI the reports should end up in the folder of your choice. Note also the -zip option (for PeptideShakerCLI), which affects where the reports end up.

> Could it be that MzidCLI might be called between PeptideShakerCLI and ReportCLI if the user selects this?

The order of the MzidCLI and ReportCLI should not matter. But I'd recommend running both the report options and the mzid export options directly as part of the PeptideShakerCLI and not as separate command lines. For the same reason as detailed for the ReportCLI above.

Note that including the mzid export options on the PeptideShakerCLI command line requires this new snapshot: https://www.dropbox.com/s/x7ygsolii9jicy5/PeptideShaker-1.16.30-SNAPSHOT.zip?dl=0. Thought this was already included but seems I was wrong. It is now though. :)

**Comment by bernt-matthias** [comment]
Wonderful, thanks for the detailed comments. I already incorporated the new reports so I only need to remove the MzidCLI and ReportCLI options and move their options to PeptideShakerCLI.
