### ISSUE TITLE
Peptide Shaker Bug

### ISSUE THREAD

**Issue by basak2018** [compomics/peptide-shaker#332]
I searched a raw file using the new Search GUI (Integrated within peptide shaker and then try to pull the searched data with Peptide shaker. But while importing the attached file is the error which is coming.

THanks,
Trayambak

[
[PeptideShaker 1.16.29 log.txt](https://github.com/compomics/peptide-shaker/files/2411356/PeptideShaker.1.16.29.log.txt)
](url)

**Comment by hbarsnes** [comment]
Hi Trayambak,

Seems to be a problem with the post-translational modifications. Which modifications are you using?

Best regards,
Harald

**Comment by basak2018** [comment]
HI Herald,
I have used oxidation of Proline as an additional modification apart from Methionine oxidation and Carbamidomethylation of Cys.

However I intend to use a couple of modifications on lysine too—1. Glucosylgalactosylhydroxylysine
                                                                                                                                  2. Galactosylhydroxylysine
                                                                                                                                  3. Hydroxylysine

Thanks,
Trayambak

-
Trayambak Basak, PhD
Post-Doctoral Fellow
Division of Nephrology and Hypertension
Vanderbilt Medical Center
1161 21st Avenue South
B-3124 Medical Center North
Nashville, TN 37232
Lab: (615) 343-4684
Cell: (615) 275-8692
Email:trayambak.basak@vumc.org
*Please note change in email address to vumc.org

**Comment by basak2018** [comment]
HI Herald,
I have used oxidation of Proline as an additional modification apart from Methionine oxidation and Carbamidomethylation of Cys. 

However I intend to use a couple of modifications on lysine too—1. Glucosylgalactosylhydroxylysine
                                                                                                                                  2. Galactosylhydroxylysine
                                                                                                                                  3. Hydroxylysine

Thanks,
Trayambak

**Comment by hbarsnes** [comment]
Hi Trayambak,

And which search engines are you using? Often this particular issue can be resolved by loading data from only one search engine at the time. So maybe you could try that?

Best regards,
Harald

**Comment by basak2018** [comment]
HI Herald,
I initially used MSGF-Plus, Myrimatch, Comet and OMSSA. I just tried opening only MSGF-plus output from Search-GUI with peptideshaker and it is opening.

I have two questions:
1. How do i merge/concatenate all of the searches and can we combine one result output from PeptideShaker as highlighted?

2. How do I also run X! TAndem, MS-Amanda, Andromeda and Tide?  I would like to obtain maximum IDs for one file by combining all the search outputs from different search Engine.

Thanks for your help,
Trayambak

**Comment by basak2018** [comment]
HI Herald,
I am able to load the three outputs from Myrimatch, MSGF-Plus and Comet. However, while loading OMSSA, I receive this error file attached.

Kindly suggest.

THanks,
Trayambak.
[Peptide_Shaker_Log_OMSSA_Loading.txt](https://github.com/compomics/peptide-shaker/files/2425988/Peptide_Shaker_Log_OMSSA_Loading.txt)

**Comment by hbarsnes** [comment]
Hi Trayambak,

> How do i merge/concatenate all of the searches and can we combine one result output from PeptideShaker as highlighted?
How do I also run X! TAndem, MS-Amanda, Andromeda and Tide? I would like to obtain maximum IDs for one file by combining all the search outputs from different search Engine.

I'm afraid that the best way of doing both of these is to load all the data at the same time in PeptideShaker. The issues you are seeing are most likely related to the PeptideShaker backend and the way the memory is handled. This will be fixed in the next major PeptideShaker release, but it will still take some time before this one becomes available. In the meantime the only known fix is
to increase the memory provided to the tool. This is done via the Welcome dialog > Settings & Help > Settings > Java Settings. Would this be an option for you?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
