### ISSUE TITLE
'Attempting to create duplicate peptide key' as before (#56 issue)

### ISSUE THREAD

**Issue by JihyeShin8406** [compomics/peptide-shaker#335]
Hi, Marc and Harald!

I am the writter of # 56 issue.
A few years ago, I'd carried out the identification through SearchGui (MS-GF +) and tried to validate and visualize them using a PeptideShaker,
but I had difficulty with issue of 'Attempting to create duplicate peptide key'.

I am currently working on another project in another lab and I want to use SearchGUI and PeptideShaker.
However, I have the same problem as before.
I am really sorry, when I searched for the article to solve this issue, I come to remebrance I'd raised same issue earlier.
I can not remember exactly how I solved the problem at the time.

The interesting thing is If I used  mgf files that only divided for a fraction of the time from the same raw files, the problem does not occur.
The log file and report I sent are the result of 1.16.29, but I confirmed that other computers did not resolve the problem at  #1.16.30.
It seems that some researchers including myself have still difficult due to this issue.
If necessary, I'd like to send all of the files (.mgf, .fasta, .mzid, .par) in a confidential condition.

Best regard,
J Shin.

[Attempting to create duplicate peptide key.txt](https://github.com/compomics/peptide-shaker/files/2464484/Attempting.to.create.duplicate.peptide.key.txt)
[PeptideShaker 1.16.29 log.txt](https://github.com/compomics/peptide-shaker/files/2464486/PeptideShaker.1.16.29.log.txt)

**Comment by hbarsnes** [comment]
Hi J Shin,

I'm afraid this is a rather common issue with the way the memory is handled in PeptideShaker and there is not much to do until the new major release of PeptideShaker is available. The only known fix is to increase the memory provided to PeptideShaker.

The good news is that we are hopefully getting close to fixing all the issues with the new version, but the bad news is that we have just uncovered a new related issue that we are currently struggling to solve. But we'll let you know as soon as the new version is ready for testing.

Sorry that we cannot be of more help at this point.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
