### ISSUE TITLE
Merging results

### ISSUE THREAD

**Issue by srithegreat** [compomics/peptide-shaker#336]
Hi,

I have results from different search engines from two different database searches (one for human and other for yeast). I would like to merge and create one combined result file using peptideshaker. Is it possible? What should be my reference database for the parameter file (a combination of human and yeast?). Will that affect how the FDR is calculated and applied?

**Comment by hbarsnes** [comment]
Hi Srikanth,

This is far from a trivial question and I'd recommend inspecting the recent literature on the topic of multi-species proteomics. I have no experience with such searches myself though.

As for PeptideShaker, the loading of searches from two different databases is not supported. We may look into this in the future though. And while it is possible to use a merged database when loading the data in PeptideShaker, this will not work as we always redo the peptide to protein mapping when processing the data in PeptideShaker, which will mess up your multi-species search results.

Given that this is more of a general proteomics question, and not something that will be included in PeptideShaker in the near future, I think I will now close this issue. You could instead perhaps consider contacting the developers of the search engines directly? Or send the question to a more general proteomics Google group?

Best regards,
Harald
