### ISSUE TITLE
Validation in PeptideShakerCLI

### ISSUE THREAD

**Issue by iquasere** [compomics/peptide-shaker#337]
Greetings to the proteomics team

I am using the CLI version of PeptideShaker, and have used this command to create a PeptideShaker project from a SearchCLI result
```
java -cp ~/PeptideShaker-1.16.31/P-1.16.31.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment myexperiment -sample mysample -replicate 1 -identification_files searchgui_out.zip -out ps_output.cpsx
```
and then I run the ReportCLI tool for generating several reports
```
java -cp ~/PeptideShaker-1.16.31/PeptideShaker-1.16.31.jar eu.isas.peptideshaker.cmd.ReportCLI -in ps_output.cpsx -out_reports ReportCLI/ -reports 0,1,2,3,4,5,6,7,8,9,10,11
````
after which, PeptideShaker successfully generates reports of the PSMs and identified proteins. Problem is, those are not yet validated. As I understand, such validation happens in PeptideShaker, with many options for manual validation. My question here is, what are the CLI options that you would suggest for validating peptide and protein matches, for performing ptm analysis and for automatically (if possible at the moment) perform de novo peptide identification? I guess my answers lie with the FollowUpCLI tool, but I haven't been able to relate its possible arguments with these tasks, and using it at the moment, with default settings
```
java -cp ~/PeptideShaker-1.16.31/PeptideShaker-1.16.31.jar eu.isas.peptideshaker.cmd.FollowUpCLI -in ps_output.cpsx -recalibration_folder FollowUpCLI/ -recalibration_mode 0 -spectrum_folder FollowUpCLI/ -psm_type 0 -progenesis_file FollowUpCLI/output.progenesis -progenesis_type 0 -accessions_file FollowUpCLI/output.accessions -accessions_type 0 -fasta_file FollowUpCLI/output.fasta -fasta_type 0 -inclusion_list_file output.inclusion -inclusion_list_format 0 -inclusion_list_peptide_filters 0,1,2 -inclusion_list_protein_filters 1,2,3 -inclusion_list_rt_window 5
```
returns this message
```
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Nov 05 17:04:35 WET 2018 Protein database db.fasta.
Mon Nov 05 17:04:36 WET 2018 Recalibrating Spectra. Inspecting Mass Deviations. Please Wait... (1/23)
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Nov 05 17:04:37 WET 2018 An error occurred while recalibrating the spectra.
Mon Nov 05 17:04:37 WET 2018 Exporting Spectra - Writing File. Please Wait... (1/23)
Mon Nov 05 17:04:37 WET 2018 Spectrum export completed.
Mon Nov 05 17:04:37 WET 2018 Loading Protein Information. Please Wait...
Mon Nov 05 17:04:38 WET 2018 Protein accessions export completed.
Mon Nov 05 17:04:38 WET 2018 Loading Protein Information. Please Wait...
Mon Nov 05 17:04:38 WET 2018 Protein details export completed.
```
and outputs very little, since it has stopped right at the start of running.

So, the main question here is, after getting the non-validated reports from PeptideShaker, what is the usual proceeding for validating the matches?

Thank you very much for the attention

**Comment by hbarsnes** [comment]
Hi João,

> So, the main question here is, after getting the non-validated reports from PeptideShaker, what is the usual proceeding for validating the matches?

The matches are already validated as part of the PeptideShaker processing, which is independet of running the tool via the graphical user interface or via the command line. The reports should therefore already include the validated matches.

However, in order to validate the matches using FDR you have to employ the target-decoy strategy, i.e. your FASTA file has to also contain the set of decoy sequences. From the command line this can be done using the FastaCLI (see details toward the end of the wiki: https://github.com/compomics/searchgui/wiki/SearchCLI).

Regarding the FollowUpCLI command lines, this is only used to export data from PeptideShaker in different formats for follow-up analysis in other tools, and is unrelated to the validation.

For a better understanding of how the validation works in SearchGUI/PeptideShaker I'd recommend having a look at our tutorials: http://compomics.com/bioinformatics-for-proteomics. These focus on the graphical user interface, but the underlying concepts are the same for the command lines.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.

**Comment by iquasere** [comment]
Sorry for the late response, Harald, the fact is that PeptideShaker has returned empty reports. I thought they were empty because a validation step was lacking, because the only reports to contain information were the Certificate of Analysis and the "with non validated matches" reports. All others contain only the header. For example, when issuing head command on "myexperiment_mysample_1_Default_Protein_Report.txt" I get
```
        Main Accession  Description     Gene Name       Chromosome      MW [kDa]        Possible Coverage [%]   Coverage [%]    Spectrum Counting       Confidently Localized Modification Sites        # Confidently Localized Modification Sites        Ambiguously Localized Modification Sites        #Ambiguously Localized Modification Sites       Protein Inference       Secondary Accessions    Protein Group   #Validated Peptides       #Peptides       #Unique #Validated Unique       #Unique to Group        #Validated Unique to Group      #Validated PSMs #PSMs   Confidence [%]  Validation
```
Is this a bug or an oversight on my part?

**Comment by hbarsnes** [comment]
This would indicate that you have no validated results. Please make sure that you are using a target-decoy database. Also check your search settings to makes sure that there are search results to validate in the first place.

Have you tried opening the cpsx file in the graphical user interface of PeptideShaker to look at the data? This should give you better ideas about what is going on.

**Comment by iquasere** [comment]
![pslooks](https://user-images.githubusercontent.com/16226371/48770746-4ecc9200-ecb7-11e8-89f2-2a19bad6682e.png)

Indeed no protein was validated. Coverage is 0 for every protein, as is confidence. However, there are a lot of spectra for a lot of proteins.

**Comment by iquasere** [comment]
Probaly I did something wrong when specifying how the validation should be carried, since database search is set to Target only

![validationhell](https://user-images.githubusercontent.com/16226371/48771161-7bcd7480-ecb8-11e8-9672-70aa8046c9c4.png)

**Comment by hbarsnes** [comment]
> Probaly I did something wrong when specifying how the validation should be carried, since database search is set to Target only

Yes, you need to use a target-decoy database. If using the SearchCLI command line you need to use the FastaCLI to add the decoys.

Example:

java -cp SearchGUI-X.Y.Z.jar eu.isas.searchgui.cmd.FastaCLI -in "your target fasta file" -decoy

Then use the resulting target-decoy database as input to the SearchCLI command line.

**Comment by hbarsnes** [comment]
> Just one last thing, the FASTACLI tool seems to have no option to direct output. Is this correct?

Correct. The file is created in the same folder as the original FASTA file.
