### ISSUE TITLE
Importing of data cancelled

### ISSUE THREAD

**Issue by mezjiwaji** [compomics/peptide-shaker#338]
Hi 
When i run Peptideshaker using a fasta file of the human proteins (from uniprot), after a 8h, i get an importing data cancelled error. The error reads 'GC overhead limit exceeded: java.lang.OutOfMemoryError'. I have used other smaller fasta files successfully. I have also increased the ram to 20 gb in the hope that it would address the issue. Do you have any suggestions as to how i can address this issue?
With thanks.

**Comment by hbarsnes** [comment]
Hi,

Increasing the memory should be the best option. Can you double check that the new memory settings is actually used? You can find this out via the PeptideShaker Welcome dialog > Settings & Help > Settings > Java Settings. Also check that you are using a 64 bit version of Java, as otherwise the memory usage is limited to around 1 GB.

Best regards,
Harald

**Comment by mezjiwaji** [comment]
Hi Harald. 
Thank you for your prompt reply. I am using java version 1.8.0_161, running the 64 bit version and have 24.4 gb for memory. 
Best regards, Mez.

**Comment by hbarsnes** [comment]
Hi Mez,

Strange. When you say that you have "a fasta file of the human proteins (from uniprot)", are we then talking both SwissProt and TrEMBL, i.e. both reviewed and unreviewed protein sequences? (Let me know if you are not familiar with these terms btw.) Just wondering how large your database is? How many protein sequences (excluding decoys) does it contain? And what are the rest of your search settings? Most importantly the enzyme and the PTMs used?

Best regards,
Harald

**Comment by mezjiwaji** [comment]
hi 
i have downloaded just the reviewed sequences so that is the 20411 reviewed sequences (from swiss-prot). I am using trypsin as the enzyme. Wrt the modifications, deamidation of N, deamidation of Q, oxidation of M, acetylation of the N-terminal of the proteins and Methyltio of C and all are variable. 
All these settings were used in previous runs, the only change has been the use of the new fasta file. 
best regards, mez.

**Comment by hbarsnes** [comment]
Hi Mez,

The FASTA file should not be a problem. So it's probably the combination of the amount of variable modifications and the size of your database and/or spectrum file(s). Would it be an option to change any of the variable modifications into fixed modifications?

Which search engines are you using btw? If you are using multiple, you could consider reducing the number?

If none of these options work (and you don't have access to more memory), I think the only solution is to wait for the next major PeptideShaker release, which should address such memory issues in a better way.

The thing is that the tool should never run out of memory, it should simply start relying more on the disk. But somewhere along the way this seems to have gotten messed up in one of our attempts to improve the memory usage...

Best regards,
Harald

**Comment by mezjiwaji** [comment]
Hi 
Thank you Harald for the help. I shall do as you advise- reduce the number of variable modifications and the number of search engines. 
As you can tell, i am a beginner in the field of ms data analysis and i appreciate the time and courtesy with which you have addressed my query.
Best regards, Mez.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
