### ISSUE TITLE
PeptideShaker splashscreen hangs if no response from server about updated version

### ISSUE THREAD

**Issue by emptyport** [compomics/peptide-shaker#339]
I don't have a good way to verify what exactly is going on, but I think I know what the issue is. I am trying to start PeptideShaker 1.16.25 (which I know is not the most up-to-date). This morning PeptideShaker started hanging on the splash screen. I decided to go ahead and download the most up-to-date version from the Compomics website, but the download never starts and the page is loading forever. It seems to me that the server where the zip file is located is not very responsive this morning. I'm guessing the infinitely loading splash screen of PeptideShaker is due to it waiting to hear back from the server if an updated version is available. However, there is no timeout for the call so PeptideShaker never opens because it is waiting for a reponse from a non-responsive server.

If this is indeed the issue, PeptideShaker should have a timeout built in to the updated version check so that it doesn't get stuck on the splash screen. If I disconnect my computer from the internet, I am able to open PeptideShaker, so it definitely seems like this is the issue.

**Comment by emptyport** [comment]
I gave it a few minutes before I ended the process and tried starting it without an internet connection. With no internet connection it started up about as quickly as usual.

**Comment by hbarsnes** [comment]
The server is now back online and the issue should no longer occur. I will therefore close the issue, but don't hesitate to reopen it if you manage to figure out what was special about your setup that could explain why the behavior was different on your end compared to the networks I tested.
