### ISSUE TITLE
Not able to create the PeptideShaker project

### ISSUE THREAD

**Issue by EhsanIrajizad** [compomics/peptide-shaker#346]
Hi,
I have created a project from SearchCLI and I want to analyze the data using PeptideShaker.
When I run the program in the command line I get an error about creating the PeptideShaker project.

 java -cp PeptideShaker-1.16.38.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment TQ -sample Q1 -replicate 1 -identification_files searchgui_out.zip
Thu Feb 07 17:21:50 CST 2019 Unzipping searchgui_out.zip.
Thu Feb 07 17:21:50 CST 2019 An error occurred while creating the PeptideShaker project. Please see the PeptideShaker log file: /rsrch1/ccp/hanash/Hanash_Lab_GPFS/Ehsan Irajizad/Test_PeptideShaker/resources/PeptideShaker.log

Here is the PeptideShaker.log file:

Thu Feb 07 17:21:50 CST 2019: PeptideShaker version 1.16.38.
Memory given to the Java virtual machine: 28631367680.
Total amount of memory in the Java virtual machine: 2058354688.
Free memory: 2004615056.
Java version: 1.8.0_131.
java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:579)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:181)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:957)

Could you please let me know how can I fix it?
Thanks a lot,
Ehsan

**Comment by hbarsnes** [comment]
Hi Ehsan,

The PeptideShaker command line requires that you use complete paths when referring to files or folders. Hence if you replace "searchgui_out.zip" with the complete path to the zip file the error should go away.

Best regards,
Harald

**Comment by EhsanIrajizad** [comment]
Hi Harald,

Still it can not create the project!
Here is my command line:

java -cp /home/eirajizad/MD\ anderson\ documents/Research/Frameshift/Mass\ spec_frameshif/Analysis_Ehsan/S1KT/Test_manual_S1KT/Crypto/PeptideShaker-1.16.38.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment TQ -sample Q1 -replicate 1 -identification_files /home/eirajizad/MD\ anderson\ documents/Research/Frameshift/Mass\ spec_frameshif/Analysis_Ehsan/S1KT/Test_manual_S1KT/Crypto/S1KT_MHC_MA_Frc-01_searchgui_out.zip

Fri Feb 08 16:24:32 CST 2019 Unzipping S1KT_MHC_MA_Frc-01_searchgui_out.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Fri Feb 08 16:24:32 CST 2019 An error occurred while creating the PeptideShaker project. Please see the PeptideShaker log file: /home/eirajizad/MD anderson documents/Research/Frameshift/Mass spec_frameshif/Analysis_Ehsan/S1KT/Test_manual_S1KT/Crypto/resources/PeptideShaker.log



Fri Feb 08 16:24:30 CST 2019: PeptideShaker version 1.16.38.
Memory given to the Java virtual machine: 5577900032.
Total amount of memory in the Java virtual machine: 375914496.
Free memory: 364149264.
Java version: 1.8.0_191.
java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:685)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:181)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:957)

Still the same error even if It I put the complete path to the zip file!

Thanks in advance for your help.
Best,
Ehsan

**Comment by hbarsnes** [comment]
Hi Ehsan,

Seems like there is a problem with locating your FASTA file. Maybe be due to your paths containing both forward and backward slashes, plus white space? Or are the backward slashed only there to escape the white space? In any case, it would probably be better to avoid the white space or use quotes around the paths.

Best regards,
Harald

**Comment by EhsanIrajizad** [comment]
Thanks and I am still struggling with the code! (has not been solved yet)!

Is there anyway (commands) that I can manually input the .fasta file? Right now it either reads from .zip file or from .par files (its .fa destination).
Can I use something like:
java -cp SearchGUI-X.Y.Z.jar eu.isas.searchgui.cmd.FastaCLI
but in peptideshaker?
Then I can tell where is my exact FASTA location in my peptideshaker command lines.

Thansk a lot,
Ehsan

**Comment by hbarsnes** [comment]
Hi Ehsan,

> Is there anyway (commands) that I can manually input the .fasta file?

Yes, you can use options from the [IdentificationParametersCLI](https://github.com/compomics/compomics-utilities/wiki/IdentificationParametersCLI) on your PeptideShakerCLI command line. So by adding the -db option you should be able to provide the path to your FASTA file.

Best regards,
Harald

**Comment by EhsanIrajizad** [comment]
Thanks a lot Harald,
It is working!
Thanks!



Best,
Ehsan
