### ISSUE TITLE
Commandline error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by soerendip** [compomics/peptide-shaker#347]
I am trying to run peptide-shaker on commandline. My command is

`java -cp /home/.../Software/PeptideShaker/PeptideShaker-1.16.38/PeptideShaker-1.16.38.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment "label" -sample "label" -replicate "0" -identification_files "searchgui_out.zip" -spectrum_files "/home/.../workspace/uofc/lsarp/proteomics/0002-D003_MS2-TMT/rawtools/1.4.2/S8926_A_TMT_T_MS2_181116.raw.mgf" -id_params "/home/.../searchgui-search-parameters/TMT11a.par"`

I am getting the output:

> STDOUT:
> Wed Feb 13 11:14:17 MST 2019 Unzipping searchgui_out.zip.
> Wed Feb 13 11:14:17 MST 2019 An error occurred while creating the PeptideShaker project. Please see the PeptideShaker log file: /home/.../Software/PeptideShaker/PeptideShaker-1.16.38/resources/PeptideShaker.log
> 
> STDERR:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/home/.../Software/PeptideShaker/PeptideShaker-1.16.38/lib/gson-2.4.jar) to field java.awt.Color.value
> WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

And output log shows:

> Wed Feb 13 11:14:17 MST 2019: PeptideShaker version 1.16.38.
> Memory given to the Java virtual machine: 16869490688.
> Total amount of memory in the Java virtual machine: 1056964608.
> Free memory: 1030785608.
> Java version: 11.0.1.
> java.lang.NullPointerException
> 	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:579)
> 	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:181)
> 	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:957)

`java -version
openjdk version "11.0.1" 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)`

I can open the searchgui file with the PetideShakerGUI without problems. Is there anything wrong with the command?

**Comment by hbarsnes** [comment]
> WARNING: An illegal reflective access operation has occurred

This one is due the use of OpenJDK and should go away if using Oracle's own Java version.

> I can open the searchgui file with the PetideShakerGUI without problems. Is there anything wrong with the command?

You have to provide the complete path to the identification results zip file. In other words, change "searchgui_out.zip" to the complete path and you should be able to process the data via the command line as well.

**Comment by soerendip** [comment]
The problem was not the java version. It was the missing absolute path to the searchgui_zip file. Once I passed it including the full path it worked fine.
