### ISSUE TITLE
import data got cancelled

### ISSUE THREAD

**Issue by EhsanIrajizad** [compomics/peptide-shaker#348]
Hi Harald,

I did msgf search using searchCLI and when I want to open the results with peptide shaker it says import data canceled (after 2 or 3 min). I repeated with X!Tandem and It works without any problem. I have attached the error and log file of opening msgf data using peptideshaker.
Could you please help me how to read msgf using peptide shaker and how can I fix it? 
Based on your suggestion in previous issues, I increased the java memmory to 16 GB (my computer is 16GB) but still I am getting the same error!

Fri Feb 22 09:23:21 CST 2019: PeptideShaker version 1.16.38.
Memory given to the Java virtual machine: 7635730432.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 84897176.
Java version: 1.8.0_151.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_151
os.name: Mac OS X
memory: 33.2/133.2
processors available: 8
useCommandThread: false
java.lang.NullPointerException
	at com.compomics.util.experiment.biology.Peptide.getPotentialModificationSites(Peptide.java:1067)
	at com.compomics.util.experiment.biology.PTMFactory.getExpectedPTMs(PTMFactory.java:436)
	at eu.isas.peptideshaker.fileimport.PsmImporter.importAssumptions(PsmImporter.java:526)
	at eu.isas.peptideshaker.fileimport.PsmImporter.importPsm(PsmImporter.java:331)
	at eu.isas.peptideshaker.fileimport.PsmImporter.access$000(PsmImporter.java:69)
	at eu.isas.peptideshaker.fileimport.PsmImporter$PsmImporterRunnable.run(PsmImporter.java:1415)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

# ------------------------------------------------------------------
# PeptideShaker 1.16.38 Report File
#
# Originally saved by: eirajizad @ BSTMC02W321ZHTD.local
#                  on: 22 Feb 2019, 09:29
#                  as: msgf file error.txt
# ------------------------------------------------------------------

Fri Feb 22 09:24:53 CST 2019        Import process for 1 (Sample: 1, Replicate: 0)

Fri Feb 22 09:24:54 CST 2019        Importing sequences from UNIPROT_1308_HUMAN_concatenated_target_decoy.fasta.
Fri Feb 22 09:25:54 CST 2019        FASTA file import completed.
Fri Feb 22 09:25:54 CST 2019        Importing gene mappings.
Fri Feb 22 09:25:57 CST 2019        Establishing local database connection.
Fri Feb 22 09:26:05 CST 2019        Reading identification files.
Fri Feb 22 09:26:05 CST 2019        Parsing IPAS_0303_CID_TCE_SG23to24.msgf.mzid.
Fri Feb 22 09:27:17 CST 2019        Loading spectra for IPAS_0303_CID_TCE_SG23to24.msgf.mzid.
Fri Feb 22 09:27:17 CST 2019        Importing IPAS_0303_CID_TCE_SG23to24.mgf
Fri Feb 22 09:27:18 CST 2019        IPAS_0303_CID_TCE_SG23to24.mgf imported.
Fri Feb 22 09:27:18 CST 2019        Collecting peptides to map.
Fri Feb 22 09:27:18 CST 2019        Mapping peptides to proteins.
Fri Feb 22 09:27:19 CST 2019        Importing PSMs from IPAS_0303_CID_TCE_SG23to24.msgf.mzid
Fri Feb 22 09:27:19 CST 2019        An error occurred: null
Fri Feb 22 09:27:19 CST 2019        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Fri Feb 22 09:27:19 CST 2019        Importing Data Canceled!

**Comment by hbarsnes** [comment]
Hi Ehsan,

This error is not related to the memory but rather due to the set of PTMs used. For one of the peptides from MS-GF+ PeptideShaker is not able to figure out the correct location of a PTM. Are you searching with any unusual PTMs? Or an unusual combination of PTMs?

Best regards,
Harald

**Comment by EhsanIrajizad** [comment]
Hi Harald,

Thanks for the fast response,
Yes. I am using unusual PTMs. I have added them using UNIMOD to SearchGUI and they have following properties:
 	Name	Short	Mass	Type	Residues	CV	
1	Deoxyhypusine	deoxyhypusine	71.07349929343	0	K, Q	UNIMOD:1041	
2	Hypusine	hypusine	87.06841391299	0	K	UNIMOD:379	
3	spermidine	spermidine	128.13134852272	0	Q	UNIMOD:1421	
4	spermine	spermine	185.18919775201	0	Q	UNIMOD:1420	


Does it mean that it can not read PTM? How can I fix it?

Best,
Ehsan

**Comment by hbarsnes** [comment]
Hi Ehsan,

If you really want the MS-GF+ results (as these will be pretty similar to the X! Tandem ones anyway), you can try running PeptideShaker with only one core. This will be slower, but should remove the chance of any multithreading issues occurring. You can change this via the Processing option at the bottom of the New Project dialog, or via the -threads option on the command line.

You can also try changing the PTM Localization parameters (edit the Identification parameters, then Show Advanced Settings and click on PTM Localization, or from the command line see https://github.com/compomics/compomics-utilities/wiki/IdentificationParametersCLI#ptm-localization).

If any of the PTMs can be set as fixed this could also help.

Best regards,
Harald

**Comment by EhsanIrajizad** [comment]
Thank you so much Herald,
It works now,
Best,
Ehsan
