### ISSUE TITLE
Error GO "null_go_mappings" 

### ISSUE THREAD

**Issue by monteires** [compomics/peptide-shaker#350]
An error is occurring when using GO, help.

An error occured: C:\Users\katia.conceicao\.compomics\gene_mappings\null_go_mappings  (The system can not find the file specified). If the problem persists, please contact the developers.

LOG:

Fri Feb 01 16:50:42 CET 2019: PeptideShaker version 1.16.38.
Memory given to the Java virtual machine: 3776970752.
Total amount of memory in the Java virtual machine: 255328256.
Free memory: 245966176.
Java version: 1.8.0_201.
Output folder not set. Please use -out_reports (or the more general -out option). Processing canceled.

Wed Apr 03 11:41:23 BRT 2019: PeptideShaker version 1.16.38.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 125993272.
Java version: 1.8.0_51.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_51
os.name: Windows 7
memory: 52.4/163.1
processors available: 4
useCommandThread: false
java.io.FileNotFoundException: C:\Users\katia.conceicao\.compomics\gene_mappings\null_go_mappings (O sistema não pode encontrar o arquivo especificado)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.compomics.util.experiment.biology.genes.go.GoMapping.loadMappingsFromFile(GoMapping.java:73)
	at eu.isas.peptideshaker.gui.tabpanels.GOEAPanel$4.run(GOEAPanel.java:374)

**Comment by hbarsnes** [comment]
Hi,

It seems that you have a FASTA file containing sequences where the species is not annotated, or not annotated properly. Where does your FASTA file come from? If it is not from UniProt the species cannot be extracted and there will not be any gene ontology annotation available. This should not result in the above error though, so something appears to be wrong in the parsing of your FASTA headers.

Best regards,
Harald

**Comment by monteires** [comment]
Good afternoon,

Thanks for the support. I'll check the headers.
The sequences are from Uniprot.

**Comment by hbarsnes** [comment]
> The sequences are from Uniprot.

Can you tell us which species? Maybe one of them is not mapped correctly when getting the GO terms from Ensembl.

**Comment by monteires** [comment]
Candida albicans (strain SC5314 / ATCC MYA-2876) | Streptococcus pneumoniae (strain ATCC BAA-255 / R6) | Pseudomonas aeruginosa (strain ATCC 15692 / DSM 22644 / CIP 104116 / JCM 14847 / LMG 12228 / 1C / PRS 101 / PAO1) | Staphylococcus aureus

I removed the species that were together in the Fasta code, leaving only one in each code. This corrected the error that appeared, but now the GO is blank, no information is displayed.

Do proteins / peptides need to be checked?

**Comment by hbarsnes** [comment]
I would suspect that there is no GO information for these specific species, or at least not for the most common species in your FASTA file. You can perhaps try switching to a different background species via the Edit > Species Settings menu option.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
