### ISSUE TITLE
problem opening peptideshaker

### ISSUE THREAD

**Issue by hale94** [compomics/peptide-shaker#351]
I installed peptideshaker on a new computer (64 bit windows 10, i7 8550, 8gb RAM).  It does not open and gives the following message on the log

Fri Feb 01 16:50:42 CET 2019: PeptideShaker version 1.16.38.
Memory given to the Java virtual machine: 3776970752.
Total amount of memory in the Java virtual machine: 255328256.
Free memory: 245966176.
Java version: 1.8.0_201.
Output folder not set. Please use -out_reports (or the more general -out option). Processing canceled.

Any suggestions would be appreciated.

**Comment by hbarsnes** [comment]
Can you also check the startup log file? You'll find it in PeptideShaker-X.Y.Z\resources\conf\startup.log.

**Comment by hale94** [comment]
There is no statup log in that folder. Apparently it is not making it to startup.

**Comment by hbarsnes** [comment]
Are you trying to start PeptideShaker by double clicking the jar file or via the command line?

BTW, are you sure that the above log file is from the new installation? As it shows the date "Fri Feb 01 16:50:42 CET 2019"?

**Comment by hale94** [comment]
I probably downloaded the zip file on that date.  My computer recently crashed and I am trying to install on a new computer.  I have tried both double clicking and command line.

 

C:\Users\John\Downloads\SearchGUI-3.3.13-windows (1)\SearchGUI-3.3.13\SearchGUI-3.3.13.jar

**Comment by hbarsnes** [comment]
> I probably downloaded the zip file on that date.

The log file with the time stamp is only created when running PeptideShaker and does not indicate when you downloaded the zip file. I would recommend downloading a new copy of the PeptideShaker zip file, just to ensure that this is not the problem.

To run PeptideShaker from the command line use `java -jar PeptideShaker-X.Y.X.jar`.

BTW, I assume you have confirmed that you have Java installed on your new computer? If not, please see https://github.com/compomics/compomics-utilities/wiki/JavaTroubleShooting.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
