### ISSUE TITLE
Corrupted .cpsx files

### ISSUE THREAD

**Issue by TessaGillett** [compomics/peptide-shaker#356]
Hello,

A while back I reported a problem which turned out to be due to my .cpsx files being corrupted (issue #352). The issue was closed since the problem seemed to be solved when rerunning them, but I was asked to re-open the issue if it happened again/I found how to reproduce the error. I can't actually re-open it, so that's why I this new one. Anyway:

After rerunning all corrupted files I find that again 8% of them result in this problem. After rerunning those as well, everything is OK, so my problem is solved for now, but I figured it might be good to report anyway since it would be good to find a proper solution. The third time I ran these files it did actually work, so I don't actually know how to reproduce the error, but I did save the corrupted .cpsx file, search GUI zipped results and of course the .mgf of one of these cases. If those would be useful, please let me know and I'll put them on weTransfer.

Thanks,
Tessa

**Comment by hbarsnes** [comment]
Hi Tessa,

I guess you cannot technically reopen an issue yourself. I ment more reply to the old issue and I'd reopen it. But never mind, the two issues are linked anyway. :)

As long as you now have the results you need I think we'll let this issue be for now and hope that it will be resolved in the next major update of PeptideShaker where the backend has been reimplemented to better deal with issues such as this one.

I will let you know when the new version is available for testing.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by TessaGillett** [comment]
Hi Harald, thank you for the update! I'm afraid that at the moment I'm not able to check whether the issue has been solved, sorry. I might be able to (and have to ;) ) turn back to it later though, in which case I'll make sure to let you know.

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
