### ISSUE TITLE
Problems loading data from searchGUI into peptideshaker

### ISSUE THREAD

**Issue by Matsdc** [compomics/peptide-shaker#357]
Hello,

As a little experiment for my master's dissertation next year I wanted to try and get used to searchGUI/Peptideshaker. I merged my own database based on the research article 'Metaproteomics analysis using the Galaxy framework' from Jagtap et al. I had to change some things because there were some problems (e.g. 'no unique identifier') but in the end it all worked fine. After retrieving the searchGUI_out.zip file i wanted to load this into Peptideshaker but i can't click on the 'load data!' button because there apparently is no Identification file selected (see picture). It does give me a warning saying i should use UniProt databases only because some features will be limited. I hope this problem can be resolved.

Kind regards,

Mats

![Peptideshaker problem](https://user-images.githubusercontent.com/50178228/57029261-8285ed80-6c41-11e9-9884-b17b6fa71b3f.PNG)

**Comment by hbarsnes** [comment]
Hi Mats,

Are you sure that the search completed successfully and that there are actual identification files in the selected zip file? Also, which search engines did you use? And did all of them complete their search?

Best regards,
Harald

**Comment by Matsdc** [comment]
Hi Harald,

I'm not really sure what went wrong. The progress bar did go twice from 0% to 100% though, I don't know if that is supposed to happen. I thought it was fine because I did not get any error messages which I talked about in the first message. I only used X!Tandem. The picture shows what is in the zip file. 

![searchgui](https://user-images.githubusercontent.com/50178228/57242801-c5c2d080-7034-11e9-864d-b91a7e4abd43.PNG)

Best regards,
Mats

**Comment by hbarsnes** [comment]
Hi Mats,

I'm afraid it seems like your search did not provide any search results. I would recommend going back and redoing the search and pay close attention to the output shown during the running of the search. Most likely the search did not complete successfully and this output will hopefully indicate the source of the problem.

Best regards,
Harald

**Comment by Matsdc** [comment]
Hi Harald,

Thanks for replying so fast. I will redo the search but at the moment I have other priorities. I will open another issue if I encounter any problems.

Best regards,

Mats
