### ISSUE TITLE
Biotinylation modification and xtandem

### ISSUE THREAD

**Issue by jflucier** [compomics/peptide-shaker#359]
Hi,

linked to issue #354

using SearchGUI-3.3.14-beta, when xtandem is exceuted, I get weird trace in shell not seen in previous versions. These trace are clearly linked to the new "Biotinylation of K" I introduced in the ptmFactory-4.12.14.json file.

Here is the trace of execution using two different paramters file, one with Oxidation of M and the other with the Biotinylation of K:

`
# Oxidation of M
[jflucier@ip32 QE_0817_10973]$ /home/xroucou_group/apps/compomics/clean_install/SearchGUI-latest/resources/XTandem/linux/linux_64bit/tandem /nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp/temp_ms/QE_0817_10973/softwares/SearchGUI-3.3.14-beta/resources/XTandem/linux/linux_64bit/input_searchGUI.xml

X! TANDEM Piledriver (2015.04.01.1)

Loading spectra (mgf)............. loaded.
Spectra matching criteria = 25169
Starting threads ........................ started.
Computing models:
	Spectrum-to-sequence matching process in progress | 50 ks 
	Spectrum-to-sequence matching process in progress | 100 ks 
	Spectrum-to-sequence matching process in progress | 150 ks 
	Spectrum-to-sequence matching process in progress | 200 ks 
	Spectrum-to-sequence matching process in progress | 250 ks 
	Spectrum-to-sequence matching proc	sequences modelled = 283 ks
Model refinement:
	partial cleavage ..... done.
	unanticipated cleavage ..... done.
	finishing refinement ... done.
Merging results:
	from 2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.18.19.20.21.22.23.24.

Creating report:
	initial calculations  ..... done.
	sorting  ..... done.
	finding repeats ..... done.
	evaluating results ..... done.
	calculating expectations ..... done.
	writing results ..... done.

Valid models = 23538

`
parameter file is available here: [https://drive.google.com/file/d/13K3drwffOUscQQuO3pQfWXPisUKPyQEd/view?usp=sharing](url)

`
#Biotinylation of K
[jflucier@ip32 QE_0817_10973]$ /home/xroucou_group/apps/compomics/clean_install/SearchGUI-latest/resources/XTandem/linux/linux_64bit/tandem /nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp/temp_ms/QE_0817_10973/softwares/SearchGUI-3.3.14-beta/resources/XTandem/linux/linux_64bit/input_searchGUI.xml

X! TANDEM Piledriver (2015.04.01.1)

Loading spectra (mgf)............. loaded.
Spectra matching criteria = 25185
Starting threads ........................ started.
Computing models:
G
G
G
G
G
G
G
G
G
G
G
G
G
G
..........
`
This list of G never ends. Waited a long time but exec never finishes. 

Parameter file can be downloaded here: [https://drive.google.com/file/d/1LXbz7uhhEYSOnyxtmd8mO7SOdvDLslpG/view?usp=sharing](url)

I tried xtandem version 2015.04.01.1 and 2017.2.1.4 and both have this problem with Biotinylation.

Have you seen this problem previously with xtandem analysis?

tks
JF

**Comment by hbarsnes** [comment]
Hi JF,

This is X! Tandem's odd way of complaining about the parameters. I think I've only seen this when using strange combinations of PTMs. My guess would be that this one is the one causing the issues: label="residue, potential modification motif">226.077599@</note>. I assume this one ought to be an n-terminal modification, but X! Tandem is not compatible with modifications at termini on specific amino acids.

This i usually not a problem though, as we simply filter them out when loading the results in PeptideShaker. Not really sure how to get around the issue in your case, as when we've seen this problem with the G's before it was usually due to a bug in our code in how we converted the PTMs into the X! Tandem format. Don't see any such issues with your parameter file?

Best regards,
Harald

**Comment by jflucier** [comment]
ok perfect

if this is normal xtandem behaviour. I will try to let xtandem run until it finishes. If I run xtandem without this modif it runs in couple of minutes. When I try using this modif after many hours it did not end and I killed the analysis.

Maybe if it takes to long, we will just drop xtandem and use other tools instead like comet, omssa, msgf.... 

Thank so much again for your help Harald

**Comment by hbarsnes** [comment]
Hi JF,

> if this is normal xtandem behaviour. I will try to let xtandem run until it finishes. If I run xtandem without this modif it runs in couple of minutes. When I try using this modif after many hours it did not end and I killed the analysis.

I'm not sure if it ever will finish. As every time we've seen this error we've stopped X! Tandem and corrected errors in the X! Tandem PTM tags before restarting the search. Which is not an option in your case. But I guess having to add the biotinylation on all possible residues may take a very long time.

You could perhaps consider adding the biotinylation as a refinement PTM in X! Tandem? But this could leave too few proteins for X! Tandem's second pass search. Not sure.

Best regards,
Harald

**Comment by jflucier** [comment]
> You could perhaps consider adding the biotinylation as a refinement PTM in X! Tandem? But this could leave too few proteins for X! Tandem's second pass search. Not sure.

thanks, I will take a look and see if this could work and can be easily implemented in my SearchGUI / PeptideShaker wrapper.

Xtandem should adapt the software to better support these kind of PTM in my opinion.

thank again for your suggestion and help Harald

**Comment by jflucier** [comment]
Hi Harald,

been digging into this and found the bug. 

I perfromed a test using Acetylation of peptide N-term and looked at Searchgui output and do not see the list of G in xtandem output. 

If I look into the generated parameters_searchGUI.xml, we see:

`
<note type="input" label="residue, modification mass">57.021464@C</note>

                <note>Carbamidomethylation of C</note>

        <note type="input" label="residue, potential modification **mass**">42.010565@**[**</note>

                <note>Acetylation of peptide N-term</note>

        <note type="input" label="residue, potential modification motif"></note>

                <note>The format of this parameter is similar to residue, modification mass,

                with the addition of a modified PROSITE notation sequence motif specification.

                For example, a value of 80@[ST!]PX[KR] indicates a modification

                of either S or T when followed by P, and residue and the a K or an R.

                A value of 204@N!{P}[ST]{P} indicates a modification of N by 204, if it

                is NOT followed by a P, then either an S or a T, NOT followed by a P.

                Positive and negative values are allowed.

                </note>
`
When I set modification as Biotinylation of N-termini,  parameters_searchGUI.xml looks like this:

`
<note type="input" label="residue, potential modification mass">226.077599@K</note>

                <note>Biotinylation of K</note>

        <note type="input" label="residue, potential modification **motif**">226.077599@</note>

                <note>The format of this parameter is similar to residue, modification mass,

                with the addition of a modified PROSITE notation sequence motif specification.

                For example, a value of 80@[ST!]PX[KR] indicates a modification

                of either S or T when followed by P, and residue and the a K or an R.

                A value of 204@N!{P}[ST]{P} indicates a modification of N by 204, if it

                is NOT followed by a P, then either an S or a T, NOT followed by a P.

                Positive and negative values are allowed.

                </note>

 
`

This parameter file genrates the list of G output by xtandem. If I change the parameter file to :+1: 

`
<note type="input" label="residue, potential modification mass">226.077599@[</note>
                <note>Biotinylation of N-termini</note>

`

This remove the xtandem error and it all executes normally. 

I then took this searchgui output and run peptideshaker and reportcli and biotin ptm are detected. So I think the bug is in the generation of the parameters_searchGUI.xml. The input label should be set at "residue, potential modification mass" and a terminal [ char should be added after the @ in value.

Do you think it would be easy and possible for you guys to patch the SearchGUI code to take this into account?

This issue was previously raised here [https://github.com/compomics/searchgui/issues/72](url)

Thank you again for you help
JF

**Comment by hbarsnes** [comment]
Hi JF,

How is your "biotinylation of n-term" user PTM defined in SearchGUI/PeptideShaker?

Because if I set up my own biotinylation PTMs, one on the K and one on the peptide n-term, I get the following X! Tandem parameters:

```
<note type="input" label="residue, potential modification mass">226.077599@K,226.077599@[</note>
		<note>Biotinylation of K,Biotinylation of N-term</note>
```

and I have no problems with X! Tandem when running the search.

Hence it's a bit difficult to make the correction you suggest above. ;)

Best regards,
Harald

**Comment by jflucier** [comment]
Hi Harald,

can you send me your ptmFactory-4.12.14.json file so i can make a diff with mine.

My ptmFactory-4.12.14.json file: [https://drive.google.com/file/d/1cZMfdtCJC0SwRidhBkU7MsYQq_REnRir/view?usp=sharing(url)

Generated parameters_searchGUI.xml: [https://drive.google.com/file/d/1WYy7FiPyGiogq4iZtqhMG7QMlgxy9dCq/view?usp=sharing](url)

I would like to make a diff between your file and mine and try executing SearchGUI using your mods file.

Thanks again for your help
JF

**Comment by hbarsnes** [comment]
Hi JF,

The only difference between our PTM factories is that your biotinylation of n-term is set to protein n-term while mine is set to peptide n-term.

But the actual issue issue seems rather to be one of backwards compatibility with your user PTMs, where the code does not pick up that the n-terminal PTM can be processed as a normal PTM (we changed how we annotate empty targets for the PTMs along the way), and therefore is processed as a motif instead.

Perhaps you can try the following: 1) delete your ptm factory and your SearchGUI parameter file, 2) re-add the two biotinylation modifications, and 3) recreate your SearchGUI parameter file and redo the search.

Hopefully this will take care of the backwards compatibility issue. If not, I will look into adding a workaround in the code.

Best regards,
Harald

**Comment by jflucier** [comment]
Hi again Harald,

I regenerated the ptmFactory-4.12.14.json on my linux laptop using SearchGUI-3.3.14-beta

the generated json file : [https://drive.google.com/file/d/1OopZqwyp-1lQsNdiG2cegwnYkdltl5dO/view?usp=sharing](url)

This time, I set the biotin ptm to peptide n-term. 

I then copy the software (fresh extract) on server running centos, call pathsettingcli to point to this newly generated json file and still get the biotin n-term ptm translated to the following in the parameters_searchGUI.xml : 

`
<note>residue modification parameters</note>
        <note type="input" label="residue, modification mass">57.021464@C</note>
                <note>Carbamidomethylation of C</note>
        <note type="input" label="residue, potential modification mass">226.077599@K</note>
                <note>Biotinylation of K</note>
        <note type="input" label="residue, potential modification motif">226.077599@</note>
                <note>The format of this parameter is similar to residue, modification mass,
                with the addition of a modified PROSITE notation sequence motif specification.
                For example, a value of 80@[ST!]PX[KR] indicates a modification
                of either S or T when followed by P, and residue and the a K or an R.
                A value of 204@N!{P}[ST]{P} indicates a modification of N by 204, if it
                is NOT followed by a P, then either an S or a T, NOT followed by a P.
                Positive and negative values are allowed.
                </note>


`

Really dont understand how this could be different between our system.

Thanks again for your help,
JF

**Comment by hbarsnes** [comment]
Hi JF,

I think I found and solved the problem. As expected it was due to the way we store the pattern for the terminal ptms without a specifc amino acid target.

I've released new versions of all of our tools which should solve the problem. You'll still have to delete your ptm factory and recreate your search parameters (I recommend deleting all the old ones) before retesting, as otherwise the old bug may still occur.

Best regards,
Harald

**Comment by jflucier** [comment]
Hi Harald,

were can I download these new versions?

on http://compomics.github.io/projects/searchgui.html its version v3.3.14

tks

JF

**Comment by hbarsnes** [comment]
Hi JF,

The html pages are only automatically updated once per day, but if you click the Source option in the upper right corner you'll get to the GitHub page where you can find the same download buttons with the updated links.

Or you can just replace all the 3.3.14 with 3.3.15 in the link on the html page. ;)

Best regards,
Harald

**Comment by jflucier** [comment]
thanks alot.

will try this and get back to you
JF

**Comment by jflucier** [comment]
searchgui version 3.3.15 worked perfectly without the xtandem error

generated parameters_searchGUI.xml now is:
&lt;note type="input" label="residue, potential modification mass"&gt;226.077599@K,226.077599@[&lt;/note&gt;
                &lt;note&gt;Biotinylation of K,Biotinylation N-term&lt;/note&gt;

thanks alot for your great support.
JF
