### ISSUE TITLE
[Feature Request] Decoy tag as prefix instead of suffix

### ISSUE THREAD

**Issue by tivdnbos** [compomics/peptide-shaker#360]
Hi,

I was wondering if it's possible to add in PeptideShaker proteins with a decoy prefix instead of suffix? As far I understood, this was not possible... therefore I have a feature request :)
e.g.:  >prot_REVERSED --> >XXX_prot

Best wishes,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

You are correct in that only decoy suffixes are supported. This will however be changed in the next major release of PeptideShaker. I will let you know when it is available for testing.

Best regards,
Harald

**Comment by tivdnbos** [comment]
Thanks!
