### ISSUE TITLE
Exporting Data with PTM's 

### ISSUE THREAD

**Issue by jnic19** [compomics/peptide-shaker#364]
Hi, 

I have been trying to export a peptide identification summary that includes PTM's in the modified sequence.  The only way that I have been able to export data showing PTM's is by using an extended PSM report.  Are there any certain features I could use in creating my own report type that would create an excel document showing the PTM's in the modified sequence in a peptide identification summary? 

Thanks so much!

**Comment by hbarsnes** [comment]
Hi,

Have you had a look at the Default Peptide Report? It also contains a column called "Modified Sequence" that should contain what you want?

If you create a custom report the feature I think you are looking for is called "Modified Sequence" and is found under the "Peptide Identification Summary" section.

Best regards,
Harald

**Comment by jkrebs25** [comment]
Hi Harald, 

Yes, that gives the data summary that I need. Thank you so much!
