### ISSUE TITLE
Memory issue with Peptide Shaker 1.16.42

### ISSUE THREAD

**Issue by arminsl** [compomics/peptide-shaker#367]
Hi,
I'm analyzing the searchGUI output with PeptideShaker on a Linux server, and the size of the output file is 3.6G.
Peptide Shaker throws an out of memory error after 30-40% of "Match Validation and Quality Control" step. I've read all of the related topics, and there was no answer to this problem.
Maximum available RAM for java to run Peptide Shaker is 500G and also 64 cores of CPU is available for this run.

> #PBS -l mem=500gb 
> #PBS -l vmem=500gb
> java -Xms1G -Xmx500G -cp PeptideShaker-1.16.42.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI ...

Could you please help me?
Thanks

**Comment by hbarsnes** [comment]
Hi,

I'm afraid this is a bug in the way the memory is handled in PeptideShaker. Sadly there is no known workaround except increasing the memory provided, which does not really seem like an option here.

The good news is that we are in the process of finishing a complete rewrite of the PeptideShaker backend which should solve this and other related issues. It should be available for beta testing soon. I will keep you posted.

Best regards,
Harald

**Comment by arminsl** [comment]
Thanks for your kind reply.
I was wondering if there is any estimation about the release time of this new version?

**Comment by hbarsnes** [comment]
> I was wondering if there is any estimation about the release time of this new version?

The hope was to get the beta release out before the summer holidays, but late August/early September now seems more likely. It all depends on how long it takes to sort out the final issues though, so I cannot give any guarantees.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
