### ISSUE TITLE
Andromeda Error

### ISSUE THREAD

**Issue by jnic19** [compomics/peptide-shaker#368]
Hi,

I cannot get an Andromeda search to run.  The error I receive and the bug report are shown below. 

![AndromedaError](https://user-images.githubusercontent.com/52720729/61652717-38c80480-ac7e-11e9-9e78-53b4d7d04377.PNG)

andromeda command: 
C:\Users\Sweedler Group\Downloads\searchGUI\SearchGUI-3.3.16\resources\Andromeda\windows\AndromedaCmd.exe -i C:\Users\Sweedler Group\Downloads\searchGUI\SearchGUI-3.3.16\resources\temp\peak_lists\Abd_1_0712.apl -p C:\Users\Sweedler Group\Downloads\searchGUI\SearchGUI-3.3.16\resources\Andromeda\windows\temp\Test Run Settings.apar -f C:\Users\Sweedler Group\Downloads\searchGUI\SearchGUI-3.3.16\resources\Andromeda\windows\temp -n 8 -s FALSE

**Comment by hbarsnes** [comment]
Hi,

I'm afraid the Andromeda error messages are rather cryptic. The only suggestion I can give is that you play around with your search parameters (for example, remove some of the variable modifications, change the enzyme, change the database etc.) to see if you can pinpoint the source of the error. Then contact the Andromeda developers directly at https://groups.google.com/forum/#!forum/andromeda-list.

Best regards,
Harald
