### ISSUE TITLE
export report in GUI

### ISSUE THREAD

**Issue by fazeliniah** [compomics/peptide-shaker#371]
Hi,
I would like to know if it is possible to export pivot report from peptide shaker GUI. Ideally, I wish to obtain a table with columns for the individual raw files where I can export to Perseus for downstream analysis.  
Hope this makes sense. 
Thanks
Hossein

**Comment by hbarsnes** [comment]
Hi Hossein,

You can export pretty much all of the data in PeptideShaker as tab separated values, either via the standard report types or via your own custom reports. Please see our tutorial material (https://compomics.com/bioinformatics-for-proteomics) where the export options are detailed at the end of Chapter 1.4: "Browsing Identification Results".

Best regards,
Harald

**Comment by fazeliniah** [comment]
Thank you Harald for your reply. 
I had read the tutorial material and unfortunately I am still struggling with this issue. In brief, I am searching 4 spectrum files and I would like to generate a single peptide report that have different columns for different spectrum files (e.g.  MaxQuant's peptides.txt). The "Default peptide report" or any custom-made report seem to not produce such a file. Is there anyway to generate such a file? or should I generate 4 different reports for 4 raw files?
Thanks again for your help. 
Hossein

**Comment by hbarsnes** [comment]
Hi Hossein,

PeptideShaker processes the search results from all the spectrum files as one common project. Hence it is only possible to get the type of export that you want by processing each spectrum file separately in PeptideShaker, then make individual project reports, and finally merge the reports in the end. The merging will probably not be straightforward though.

Note that PeptideShaker is focused on peptide and protein identification, not quantification. The latter is probably what you want if studying the data in Perseus? If so, I'd recommend rather using tools focused on quantification, such as MaxQuant.

Best regards,
Harald
