### ISSUE TITLE
mzid output issue in version 1.16.42

### ISSUE THREAD

**Issue by arminsl** [compomics/peptide-shaker#374]
Hi dear Harald,
I tried to parse the mzid file produced by PeptideShaker v.1.16.42 from my .cpsx file with the R package "mzID" but it reports some failure that are caused by the non-standard structure of the mzid file. The log is: 

> reading 13.mzid...Entity 'alpha' not defined
> Entity 'alpha' not defined
> Entity 'alpha' not defined
> Entity 'alpha' not defined
> Unescaped '<' not allowed in attributes values
> attributes construct error
> Couldn't find end of Start Tag DBSequence line 8628
> Opening and ending tag mismatch: SequenceCollection line 47 and DBSequence
> Unescaped '<' not allowed in attributes values
> attributes construct error
> Couldn't find end of Start Tag DBSequence line 8631
> 
Could you please help me?
Thanks.

**Comment by hbarsnes** [comment]
Hi Armin,

From what I can tell there seems to be an issue with the accession numbers of some of your protein sequences. Please make sure that these do not contain any special characters, especially '>' and '<'.

What does line 8628 in the mzid file look like?

Best regards,
Harald

**Comment by arminsl** [comment]
Thanks for your quick answer.
Line 8628 is:

> ` <DBSequence id="Os01t0267900-01 Calmodulin, Ca<sup>2+</sup> sensor, Ca<sup>2+</sup> signalling" accession="Os01t0267900-01 Calmodulin, Ca<sup>2+</sup> sensor, Ca<sup>2+</sup> signalling" searchDatabase_ref="SearchDB_1" >`

Yes. There are some unescaped special characters in this protein description. 
But I don't know what "Entity 'alpha'" is. How should I resolve this?

**Comment by hbarsnes** [comment]
> But I don't know what "Entity 'alpha'" is. How should I resolve this?

I'm not sure either. The only link to "alpha" I find in the mzIdentML specification document is the following:

`<userParam name="cross-link_chain" unitName="xsd:string" values="alpha"/>`

But this is not a mandatory element and mzid files from PeptideShaker do not contain crosslinking data anyway.

Perhaps you can try fixing the protein accession issue first and see if that also solves the alpha-issue? Or perhaps the alpha issue is simply a warning and can be ignored?

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
