### ISSUE TITLE
Mascot search vs. PeptideShaker: significant differences on the same Uniprot entry

### ISSUE THREAD

**Issue by Dernolimit** [compomics/peptide-shaker#375]
Good afternoon,
Sorry if I disturb you with some primitive issue. I have got an mgf file, from which Mascot search results in different peptide assignments than PeptideShaker, with the very same settings and very same fasta file (I mean, .fasta was generated from the Uniprot entry that is taken automatically by Mascot search).
What am I doing wrong? The peptides missing from the PeptideShaker results are easily seen in the MS/MS file, Mascot identifies it perfectly, but PeptideShaker fails.
Yours,
Dernolimit
[PeptideShaker 1.16.42 log.txt](https://github.com/compomics/peptide-shaker/files/3690521/PeptideShaker.1.16.42.log.txt)

**Comment by hbarsnes** [comment]
Hi Dernolimit,

I assume you've had a look at our Mascot help: https://github.com/compomics/peptide-shaker#mascot-support?

Other than that you have to double check that all of the search parameters are indeed identical. Perhaps you can send me screenshots of the search parameters used in the Mascot search and of the search parameters used in (presumably) SearchGUI?

Best regards,
Harald

**Comment by Dernolimit** [comment]
Dear Harald,
Thank you for your support.
1/ Yes, I had, I had consulted the Mascot help, but this actual feature is
not discussed there.
2/ In order to explain the situation, I attached a pptx file with
printscreens to explain the problem.
Thank you very much in advance for your help.
Yours,
Mihaly Dernovics

PS: As asked for, I cited SearchGUI and PeptideShaker correctly in my last
publication dealing with proteomic issues (
http://www.ftb.com.hr/164-volume-55-issue-no-3/1491-production-of-hypoallergenic-antibacterial-peptides-from-defatted-soybean-meal-in-membrane-bioreactor-a-bioprocess-engineering-study-with-comprehensive-product-characterization).
This is just to indicate how highly I appreciate the
SearchGUI-PeptideShaker :-)


Harald Barsnes <notifications@github.com> ezt írta (időpont: 2019. okt. 4.,
P, 14:48):

**Comment by hbarsnes** [comment]
Hi Mihaly,

I'm afraid it is not possible to attach files when replying to issues via email. Attachments have to be uploaded via the issue tracker web page. In other words, I did not receive the pptx file and this cannot comment on your settings.

Thank you for citing our tools! BTW, for you next publication note that we now have a [new SearchGUI publication](https://www.ncbi.nlm.nih.gov/pubmed/29774740) that we'd be very happy if you cite instead of the old one. :)

Best regards,
Harald

**Comment by Dernolimit** [comment]
Dear Harald,
Do you mean I should use the tracker web page? Indeed, when you wrote me "
Perhaps you can send me screenshots" I thought you meant the general e-mail
way.
So, please just indicate if I should continue with the tracker method.
Yours,
Mihaly Dernovics

Harald Barsnes <notifications@github.com> ezt írta (időpont: 2019. okt. 5.,
Szo, 18:10):

**Comment by hbarsnes** [comment]
Hi Mihaly,

Sorry for the confusion. Yes, I meant via the issue tracker. That way the other developers can see the screenshots as well and help if necessary.

Best regards,
Harald

**Comment by Dernolimit** [comment]
[Mascot_SearchGUI.pptx](https://github.com/compomics/peptide-shaker/files/3696184/Mascot_SearchGUI.pptx)

Dear Harald,
Can you see it now?

**Comment by hbarsnes** [comment]
Hi Mihaly,

Thanks for the file. I would recommend looking at the same spectrum (or spectra) Mascot identifies as the peptide in question (I guess my clicking the the Query link in Mascot) and then look up the same spectrum (or spectra) in the Spectrum IDs tab in PeptideShaker. This should tell you what the search engines in SearchGUI did differently for the given spectrum/spectra.

Best regards,
Harald

PS: There is no need to reply both via email and via the issue tracker, as both end up in the issue tracker anyway. :)

**Comment by Dernolimit** [comment]
Dear Harald,
Is it possible to look at a spectrum of a peptide in PeptideShaker that was
not  identified ?

Harald Barsnes <notifications@github.com> ezt írta (időpont: 2019. okt. 7.,
H, 14:15):

**Comment by hbarsnes** [comment]
Hi Mihaly,

> Is it possible to look at a spectrum of a peptide in PeptideShaker that was
not  identified?

Yes, all of the spectra from the mgf file are listed in the Spectrum IDs tab.

Best regards,
Harald

**Comment by Dernolimit** [comment]
OK, thank you, I will check and I will get back to you asap.

Harald Barsnes <notifications@github.com> ezt írta (időpont: 2019. okt. 7.,
H, 14:55):

**Comment by Dernolimit** [comment]
[Peptide_m_z462_75.pptx](https://github.com/compomics/peptide-shaker/files/3723356/Peptide_m_z462_75.pptx)
Dear Harald,
Please find it attached. The mass spectrum is of good quality, but no results at all. Can you please advise?

**Comment by hbarsnes** [comment]
Hi Mihaly,

> The mass spectrum is of good quality, but no results at all. Can you please advise?

Hard to know why the two search engines were not able identify the given spectrum, as I agree that the spectrum itself looks pretty good. Either the spectrum is not searched due to failing to pass the search engine prefilters, e.g. the precursor mass deviation could be too big?, or the matching sequence is not in the database (or in the database but for some reason not used).

Perhaps you can try researching this particular mgf file with the other search engines in SearchGUI as well to see if any of them are able to pick up the given peptide sequence?

Can you show me what the spectrum annotation is like for this given spectrum in Mascot?

Best regards,
Harald

**Comment by Dernolimit** [comment]
[Peptide_m_z462_75.pptx](https://github.com/compomics/peptide-shaker/files/3724368/Peptide_m_z462_75.pptx)
Dear Harald,
1/ I have added the mascot result on the missing peptide, it finds it perfectly.
2/ After adding all search engines, no hits were for this required spectrum.
Can you please advise?

**Comment by hbarsnes** [comment]
Hi Mihaly,

I think I finally figured it out. When importing peptide-spectrum-matches PeptideShaker has a couple of import filters (see Identification Settings > Advanced Settings > Import Filters). Among these is a peptide length filter where peptides shorter than 8 and longer than 30 amino acids are removed before processing in PeptideShaker. The reason for the lower limit is that peptides shorter than 8 amino acids are in many cases not unique when mapped to the possible protein sequences.

But if you alter the peptide length filter you will hopefully see the wanted peptide.

Best regards,
Harald

**Comment by Dernolimit** [comment]
Dear Harald,
You were right, this was the key for the correct assignment. As I am
working with custom peptides, I need to know small peptides (<8 aa) too, so
this is an important setting for me (maybe to others too, so you might
consider to lift up this setting to a more obvious level, e.g., into the
window of "Spectrum Matching", as it is not mentioned/highlighted in the
general manual - but this thing does not absolve me from not being careful
enough).
Therefore, I highly acknowledge your support - thank you very much.
Yours,
Mihaly Dernovics

Harald Barsnes <notifications@github.com> ezt írta (időpont: 2019. okt.
14., H, 14:34):
