### ISSUE TITLE
Memory issue with Peptideshaker

### ISSUE THREAD

**Issue by srithegreat** [compomics/peptide-shaker#376]
Hi Harald,

I have a large result set from three different search engines (~700 files) from a search of 200 MGF files against Uniprot. I am trying to combine the results and apply FDR using PeptideShaker. The process utilizes around 500 GB memory and fails after running for a Week, stuck at the PTM step. Have you tested Peptideshaker to handle such huge number of files? What would the memory requirements for such a task? 

Srikanth

**Comment by hbarsnes** [comment]
Hi Srikanth,

I'm afraid we don't have any experience with using PeptideShaker on datasets that big. We are working on a new version that should handle the memory better, but it is not yet available for testing. In the meantime perhaps you can try only loading the results from one of the search engines? And if you are not particularly interested on the PTM localization scores, you may consider changing the PTM Probabilistic Score type to None in the advanced identification settings. This should speed up that specific step of the processing.

Best regards,
Harald

**Comment by srithegreat** [comment]
Hi Harald,

Thanks for the response. I am only interested in the common modification like oxidation and Carbamidomethylation. If i disable PTM scoring, will that be affected or its only applicable for phospho kind of PTMs?
Also, I would be happy to test the beta version once its ready.

Regards,
Srikanth

**Comment by hbarsnes** [comment]
Hi Srikanth,

> I am only interested in the common modification like oxidation and Carbamidomethylation. If i disable PTM scoring, will that be affected or its only applicable for phospho kind of PTMs?

Correct. The localization score is mainly relevant when it is important specifically where a given PTM is located on a peptide, e.g. for phosphorylation or similar.

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
