### ISSUE TITLE
PRECURSOR INTENSITY OUTPUT

### ISSUE THREAD

**Issue by hazbeck** [compomics/peptide-shaker#378]
Hi,
I am trying to design my own template to export ID features and one of the parameters I am particularly interested in is INtensity of the Precursor Ion. I can see that this value is present in the spectrum ID tab (spectrum selection section), however this info is absent in the overview Peptide section. 
I was exploring possibility to export this value in the customised export table and just could not find the way to output it. As this value is present in the Spectrum ID tab, may be it is called differently or may be this issue was not flagged before. You advise on how to deal with this issue will be appreciated.
[INTENSITY.pdf](https://github.com/compomics/peptide-shaker/files/3844681/INTENSITY.pdf)

**Comment by hbarsnes** [comment]
Hi,

You are correct in that the precursor intensity is not currently included in the custom exports. This has however been added in the upcoming new release of PeptideShaker. I will let you know when it is available for downloading.

Best regards,
Harald

**Comment by hazbeck** [comment]
Thanks Harald, that would be quite handy. As you know LFQ is used more and more these days for a variety of purposes, and Intensity of the precursor, or even better AUC , for future developments, will enhance already quite formidable arrays of options available with PeptideShaker.

**Comment by hbarsnes** [comment]
For LFQ quantification via PeptideShaker you may also want to check out moFF (https://github.com/compomics/moFF). There is also a dedicated export to Progenisis under Export > Follow Up Analysis. Finally, you can also export as mzIdentML and import the results into Skyline.

**Comment by hbarsnes** [comment]
The precursor intensity can now be exported in the new beta release of PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the export does not work as wanted, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the export does work as wanted, it would also be great of you could let us know by replying to this original issue. :)

**Comment by hbarsnes** [comment]
This issue should be fixed in the new release that is available now. If not, please let us know by opening a new issue.

**Comment by hazbeck** [comment]
Thanks Harald,
I will take a look at it. But it is definitely good that results could be
exported to Skyline that I totally agree presents much better environment
to deal with such issues. Though sometimes simple readout in PeptideShaker
is also sufficient for evaluation purposes. Keep up with good work guys.
Cheers
Victor
