### ISSUE TITLE
Peptide Shaker open search results core usage

### ISSUE THREAD

**Issue by im281** [compomics/peptide-shaker#379]
It shows that you can select the number of cores you want to use but I don't see it using them all when I set it:

**Comment by hbarsnes** [comment]
Not all of the individual sub processes in PeptideShaker are multithreaded and thus not all of them are able to take advantage of the multiple cores. You'd therefore have to monitor the whole process of loading data into PeptideShaker to be sure to spot times when multiple cores are being used.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
