### ISSUE TITLE
ROC curve question

### ISSUE THREAD

**Issue by mavino** [compomics/peptide-shaker#380]
Is it possible to get out of PeptideShaker analysis the classical ROC curve with true positive rate (sensitivity) against the false positive rate (1 – specificity)?

**Comment by mvaudel** [comment]
Hi,

Although plot and axes are labeled differently, this is what you will find on the third plot of the "Validation" tab.

Hope it helps,

Marc

![roc](https://user-images.githubusercontent.com/11632644/69551042-5561a980-0f9c-11ea-9623-ddb8e96fa18f.png)
