### ISSUE TITLE
Go Issue

### ISSUE THREAD

**Issue by rromoli** [compomics/peptide-shaker#381]
Hi, I'm new to peptide-shaker. I run the latest version on a fully upgraded Debian 10 system. I get a recurring error that do not allow me to go further. The error occur during the GO Annotation because I get "GO Annotation for XXX not available". 
[PeptideShaker.log](https://github.com/compomics/peptide-shaker/files/3891568/PeptideShaker.log)

In attachment you will find the log file

Hope this help

**Comment by hbarsnes** [comment]
It seems like the Ensembl Biomarts used to extract the gene and GO annotations are very slow at the moment, with the servers even having connection issues: "Server returned HTTP response code: 500".

I'd recommend waiting and trying again later.

In the meantime you may consider turning off the gene and GO annotations, see: https://github.com/compomics/compomics-utilities/wiki/IdentificationParametersCLI#gene-annotation.

**Comment by rromoli** [comment]
Now seems work. I close the issue.

thanks!
