### ISSUE TITLE
need help with this

### ISSUE THREAD

**Issue by Pokemonshield** [compomics/peptide-shaker#383]
Hi,
I have 0 exp in proteomic analysis and I feel very hard with how to properly search. I tried to run the programme following the instruction but I got this log

Mon Dec 09 00:52:33 GMT 2019        Unzipping searchgui_out.zip.
Mon Dec 09 00:52:33 GMT 2019        Import process for a (Sample: a, Replicate: 0)

Mon Dec 09 00:52:33 GMT 2019        Importing sequences from hsp90_concatenated_target_decoy.fasta.
Mon Dec 09 00:52:34 GMT 2019        FASTA file import completed.
Mon Dec 09 00:52:34 GMT 2019        Importing gene mappings.
Mon Dec 09 00:52:35 GMT 2019        Establishing local database connection.
Mon Dec 09 00:52:36 GMT 2019        Reading identification files.
Mon Dec 09 00:52:36 GMT 2019        Parsing 230919_Sample_1.comet.pep.xml.
Mon Dec 09 00:52:36 GMT 2019        Loading spectra for 230919_Sample_1.comet.pep.xml.
Mon Dec 09 00:52:36 GMT 2019        Importing 230919_Sample_1.mgf
Mon Dec 09 00:52:36 GMT 2019        230919_Sample_1.mgf imported.
Mon Dec 09 00:52:36 GMT 2019        Importing PSMs from 230919_Sample_1.comet.pep.xml
Mon Dec 09 00:52:36 GMT 2019        An error occurred: null
Mon Dec 09 00:52:36 GMT 2019        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Mon Dec 09 00:52:36 GMT 2019        Importing Data Canceled!
could someone help me with this issue? How should I do with it?

**Comment by hbarsnes** [comment]
Hi,

There seems to be an error when loading your Comet search results. Could you please share the PeptideShaker log file? You'll find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report.

It should hopefully tell us more about why the data cannot be loaded.

Best regards,
Harald

**Comment by Pokemonshield** [comment]
[SearchGUI 3.3.17 log.txt](https://github.com/compomics/peptide-shaker/files/3970308/SearchGUI.3.3.17.log.txt)
here is it. I think it somehow cant access to certain part of directory.

**Comment by hbarsnes** [comment]
Thanks for the log file. However, this is the log file from SearchGUI, while I would need to see the log file from PeptideShaker as that is where the error occurs.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
