### ISSUE TITLE
problems with searchgui 3.3.17 and peptideshaker 1.16.42

### ISSUE THREAD

**Issue by hale94** [compomics/peptide-shaker#387]
When I start either program, I get the following error message
"an error occurred while loading the gene mappings"

Searches do no complete and searchGUI will not link to peptideshaker.

I recently loaded python onto my computer.  Could that interfere with Java?

**Comment by hbarsnes** [comment]
Hi,

Given that this issue is linked to https://github.com/compomics/searchgui/issues/224, I will close the PeptideShaker issue and continue the follow-up under the SearchGUI issue.

Best regards,
Harald
