### ISSUE TITLE
custom PTM unavailable

### ISSUE THREAD

**Issue by Seb-Leb** [compomics/peptide-shaker#389]
This is related to issue #354 and #359 posted by my colleague.
I seem to have a similar issue where I use the exact same ptmFactory file and the PathSettingsCLI class to set the path but the modification still wont appear:

`java -cp /home/xroucou_group/tools/compomics/SearchGUI-3.3.17/SearchGUI-3.3.17.jar eu.isas.searchgui.cmd.PathSettingsCLI -ptm_configuration /home/sleblanc/mac-tag/analysis/bioid/searchgui_tmp/ptm`
and then to see if the Biotinylation of K mod is available:
`java -cp /home/xroucou_group/tools/compomics/SearchGUI-3.3.17/SearchGUI-3.3.17.jar eu.isas.searchgui.cmd.IdentificationParametersCLI --mods | grep -e Biotinylation`
returns nothing.

Reading the past issues I saw that there was a new version published to take into account the path changes in the IdentificationParametersCLI class, SearchGUI-3.3.17 should include this fix right? Or am I doing anything else wrong?
thank you!

**Comment by hbarsnes** [comment]
Did you try both of the below tricks detailed in one of the previous issues?

>I think the problem is that you are mixing PeptideShakerCLI and SearchCLI command lines. As changing the ptm_configuration path for PeptideShaker does not change it for SearchGUI, and the other way around. So you need to set the path separately for both, or include the -ptm_configuration option directly in the SearchCLI and PeptideShakerCLI command lines. (The perhaps more general solution would be to use the -temp_folder option (and the -log option) instead of only the more specific -ptm_configuration option.)

I think the easiest would be to include the ptm_configuration option directly in the SearchCLI and PeptideShakerCLI command lines?

>Reading the past issues I saw that there was a new version published to take into account the path changes in the IdentificationParametersCLI class, SearchGUI-3.3.17 should include this fix right?

Well, these issues should have been solved in 3.3.14. And I'm pretty sure we did not make any changes to this part of the code after that.

**Comment by Seb-Leb** [comment]
yes, well right now I'm only trying to run SearchGUI so I only run searchcli
If I combine everything in one, this command should return something right?:
`java -cp SearchGUI-3.3.17/SearchGUI-3.3.17.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -ptm_configuration mods/ --mods | grep -e Biotinylation`
given that `mods/` contains the json from ptmFactory.
Does the ptmFactory file have to be version matched or something?
Thanks!

**Comment by hbarsnes** [comment]
> If I combine everything in one, this command should return something right?:
java -cp SearchGUI-3.3.17/SearchGUI-3.3.17.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -ptm_configuration mods/ --mods | grep -e Biotinylation
given that mods/ contains the json from ptmFactory.

This should work, but only if you replace "mods/" with the complete path I think.

> Does the ptmFactory file have to be version matched or something?

Yes, that is very much recommended.

**Comment by Seb-Leb** [comment]
Alright, I re-generated a new json with the searchgui version I am using and it works. I think the only difference is the name of the ptmFactrory file.
Thank you!
