### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by kerenb28** [compomics/peptide-shaker#390]
I am trying to use PeptideShaker-1.16.44, but when I click the jar file I get the following error massage:
Failed to start PeptideShaker:
D:\PeptideShaker\resources\conf\startup.log(Access is denied)

**Comment by hbarsnes** [comment]
It seems like you may have installed PeptideShaker in a location where you do not have read and/or write access? Trying unzipping a the PeptideShaker zip file in a different location, for example in your user home folder or on your desktop, to see it that solves the problem.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
