### ISSUE TITLE
Scaffold and PeptideShaker

### ISSUE THREAD

**Issue by MJanech** [compomics/peptide-shaker#391]
In older versions of SearchGui I could export .mzid results directly into Scaffold for visualization. In later versions, any attempt to important .mzid from SearchGui -> Peptide Shaker -> Scaffold results in numerous specification violations. The file will not upload to Scaffold. Scaffold developers tell me that the number of violations requires a fix on the side of SearchGui. Is there any plan to fix or consider an export function in Peptide Shaker that works with Scaffold?

Thank you

**Comment by hbarsnes** [comment]
Duplicate of https://github.com/compomics/searchgui/issues/227. Please see that issue for follow-ups.
