### ISSUE TITLE
Overlap of different search methods

### ISSUE THREAD

**Issue by srithegreat** [compomics/peptide-shaker#393]
I have merged results from Mascot, X!Tandem and MSGF+ using PeptideShaker which is cool. I was wondering if there is some direct way of looking at overlap of PSMs, Peptides and Proteins from the three methods, to see what we gained by merging them in PeptideShaker?

Srikanth

**Comment by hbarsnes** [comment]
Hi Srikanth,

This is not supported in the graphical user interface, but you can get an overview of the number of unique PSMs per search engine at the bottom of the Spectrum IDs tab. For further comparisons you have to make your own custom PSM export via Export > Identification Features and then post-process the data outside of PeptideShaker. To include the search engine specific data, please see the export section called Identification Algorithm Results.

Best regards,
Harald

**Comment by srithegreat** [comment]
Thanks thats a great help. Appreciated.
