### ISSUE TITLE
down/up- stream amino acids

### ISSUE THREAD

**Issue by fazeliniah** [compomics/peptide-shaker#394]
Hi, 
I am using PeptideShaker for identification of HLA class 1 peptides. The results are very impressive so far, especially when we combined the results of three search engines (comet/MSGF+/Xtandem). 
One way of doing the comparison between different conditions is the analysis of upstream and downstream amino acids (please see attached figure). In particular, I am interested to study 3 up- and 3 down-stream amino acids for the detected peptides. Is it possible to include this information for the report?
Thanks
![image001](https://user-images.githubusercontent.com/19155957/75812888-feb6f900-5d5c-11ea-82fe-152feadf45e4.png)

**Comment by hbarsnes** [comment]
Hi,

As a default the two amino acids before and after the identified peptides are included in the Default Peptide Report (Export > Identification Features) in the columns named "AAs Before" and "AAs After".

To increase the number of amino acids listed go to Edit > Project Preferences > Display, and change the number of surrounding amino acids, and then redo the export.

I hope this provides you the information you need?

Best regards,
Harald

**Comment by fazeliniah** [comment]
Sounds wonderful. Thanks for your quick response.
