### ISSUE TITLE
Error while running PeptideShakerGUI

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/peptide-shaker#397]
Hi would you mind helping me with this error running PeptideShaker, please? Thanks!

Best,
Carla

<img width="900" alt="Screen Shot 2020-04-12 at 7 55 13 AM" src="https://user-images.githubusercontent.com/22406027/79071966-5b2e0200-7c93-11ea-9f6d-d124542e2c88.png">

**Comment by hbarsnes** [comment]
Hi Carla,

I'm afraid this is a known issue. It should however be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

The PeptideShaker beta release has another issue though, related to reopening saved projects (https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues/47).

So it is up to you whether you still want to try the beta release, or wait until it is it officially released.

Best regards,
Harald

**Comment by CarlaCristinaUranga** [comment]
Hi thank you so much for responding so quickly. I am downloading it now and
am looking forward to the final version. Take care! By the way, IT from my
institute is probably going to contact you regarding installation on a
server (from the J. Craig Venter Institute). This is regarding running
SearchGUI and PeptideShaker from a Singularity container. Do you know if it
is possible to do this by chance or if there is a way?

Best wishes,
Carla

**Comment by hbarsnes** [comment]
Hi Carla,

> By the way, IT from my institute is probably going to contact you regarding installation on a
server (from the J. Craig Venter Institute). This is regarding running SearchGUI and PeptideShaker from a Singularity container. Do you know if it is possible to do this by chance or if there is a way?

I am not familiar with Singularity myself, but I think it should be possible via either Bioconda or Docker. Tell them to have a look at:
- https://github.com/compomics/peptide-shaker#bioconda
- https://github.com/compomics/peptide-shaker#docker
- https://github.com/compomics/searchgui#bioconda
- https://github.com/compomics/searchgui#docker

Best regards,
Harald

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
