### ISSUE TITLE
A plot showing individual search engine results

### ISSUE THREAD

**Issue by Hansenlab1** [compomics/peptide-shaker#400]
Hello Shaker Team, 
What is the procedure to show search results from the individual search engines in Peptide Shaker? Is it possible to plot the #IDs (y-axis) at various FDR (x-axis)?
Thanks!

**Comment by hbarsnes** [comment]
Hi,

The only search engine comparison currently supported in PeptideShaker is what you can find in the Spectrum IDs tab, which mainly focuses on the number of PSMs per search engine and on comparing the results for a given spectrum.

The FDR threshold used for the PSMs can be changed in the Validation tab.

I'm not sure if this is what you were looking for though or if you had something else in mind?

Note that this type of comparison is only possible at the PSM level in PeptideShaker, given that at the peptide and protein levels the PSMs from the individual search engines are merged into a single combined result.

Best regards,
Harald

**Comment by Hansenlab1** [comment]
Hello Herald,
Thanks for your quick reply.
Your description makes sense.

I was thinking of a figure like this:

[cid:07de289c-c775-4feb-b2d6-29f476950ea8]
That comes from a tutorial from your group I believe
https://gtpb.github.io/PDA19/assets/martens_proteomics_bioinformatics_20190401.pdf

Or an export option that lets you show which unique peptides came from a given Search Engine.

Thanks and keep up the great work!
Kirk
________________________________

**Comment by hbarsnes** [comment]
Hi Kirk,

> I was thinking of a figure like this: [cid:07de289c-c775-4feb-b2d6-29f476950ea8]

I think you need to tell me which of the 50 slides you are referring to? As the image is not shown in the issue tracker. :)

> Or an export option that lets you show which unique peptides came from a given Search Engine.

You can set up your own custom export via Export > Identification Features > Add new report type. The section containing the search engine information would be the Identification Algorithm Results.

Best regards,
Harald

**Comment by tokeru** [comment]
I had as well the itnerest in comparing search engines. We are normally using andromeda and the graph of peptide shaker tells me, comet found 300 unique PSMs, only comet found. 
Now its trivial that one wants to know, which PSM/peptides/proteins are only found with comet, how confidental they are and maybe find a reason theyre not found in andromeda for example.

with 

> You can set up your own custom export via Export > Identification Features > Add new report type. The section containing the search engine information would be the Identification Algorithm Results.

I couldnt find an option which gives me a column with the algorithm that identificated it.

Also how can it be, that peptide shaker found 2 Unique PSMs which none of the search engines found?

**Comment by hbarsnes** [comment]
> I couldnt find an option which gives me a column with the algorithm that identificated it.

In the Identification Algorithm Results export there will be one row per identification. If you include the columns called Algorithm Score and Algorithm Confidence (and probably good to also add Validation) you will get something like this:


  | Rank | Sequence | Spectrum Title | Algorithm Score | Algorithm   Confidence [%] | Validation
-- | -- | -- | -- | -- | -- | --
1 | 1 | QGGYSQSNYNSPGSG | controllerType=0 controllerNumber=1 scan=5270 | X!Tandem (18.0) | 48.7922705 | Not Validated
2 | 1 | GILAADESTGSIAKR | controllerType=0 controllerNumber=1 scan=5271 | OMSSA (1.54711950609786E-12) | 100 | Confident
3 | 2 | AVIASICVVSSMAQKVTQAQTEISVVEK | controllerType=0 controllerNumber=1 scan=5271 | OMSSA (4.63779815166792) | 14.5800317 | Not Validated
  | … |   |   |   |   |  
14 | 1 | GILAADESTGSIAKR | controllerType=0 controllerNumber=1 scan=5271 | X!Tandem (9.8E-11) | 100 | Confident
  | … |   |   |   |   |  

This indicates that the spectrum with titled "controllerType=0   controllerNumber=1 scan=5270" was only identified by X! Tandem (but not validated), while the spectrum titled "controllerType=0 controllerNumber=1 scan=5271" was identified by both OMSSA and X! Tandem (both validated).

The layout of the export may not be the optimal, but the information is all there. We are working on making this type of information more easily accessible in the graphical user interface.

> Also how can it be, that peptide shaker found 2 Unique PSMs which none of the search engines found?

The plot in question only includes the validated PSMs, and given that a PeptideShaker PSM is a combination of the search engine PSMs for the same spectrum it can end up having enough evidence to validate a PSM that was not validated by any of the search engines on their own.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
