### ISSUE TITLE
How to find total number of peptide spectra matches (PSMs)?

### ISSUE THREAD

**Issue by nattzy94** [compomics/peptide-shaker#401]
Hi,

This is more a question than an error. I would like to find out some basic statistics about my mass spec data specifically,

1. total number of spectra,
2. number of spectra that match to a database,
3. number of unique peptides that correspond to the matched spectra,
4. number of proteins that the unique peptides can be grouped into.

I have generated the default PSM and peptide reports but there doesn't seem to be a straightforward reporting of these statistics. How do I go about getting them?

**Comment by hbarsnes** [comment]
I would recommend first having a look at the Spectrum IDs tab in PeptideShaker. There you get an overview of how many spectra that was in the spectrum file(s) and how many of them were identified. This should give you the first two numbers.

With regards to the two last numbers, you should be able to find these numbers by filtering the peptide and protein reports. It will require that you pay special attention to shared peptides and protein inference in general though. I do not think we have a straightforward way of exporting these numbers directly.

Can I ask what you need these particular numbers for?

**Comment by nattzy94** [comment]
Thanks for the reply. I was just trying to get an idea of the numbers as a check to see if I was doing something wrong. 
I am trying to find novel proteins in my MS data and I'm trying to replicate this paper: https://www.biorxiv.org/content/10.1101/2020.03.21.001883v1.

> In order to evade the increase in false-positive rates, MS data is first mapped to known proteins in UniProt database, and then the unmatched spectra are mapped to the custom proteogenomic database as done by us previously in Prabakaran et al

I have so far done the first step which is to search my mgf files against the Uniprot annotated protein database. However, I am having trouble extracting the unmatched spectra. Is there a way to do this?

**Comment by hbarsnes** [comment]
Yes, you can export the unmatched spectra via Export > Follow Up Analysis, and then choose the wanted Export Spectra option at the top. This will generate an mgf file consisting only of the spectra in the wanted category, e.g. only the spectra of non-validated PSMs.

**Comment by nattzy94** [comment]
Okay, thanks very much. This is really helpful!

**Comment by hbarsnes** [comment]
Great! I will then close this issue. But don't hesitate to open a new one if you have more questions.
