### ISSUE TITLE
How to export MS2 quantification on CLI?

### ISSUE THREAD

**Issue by nattzy94** [compomics/peptide-shaker#402]
Hi,

I am trying to do protein quantification and I can see that there is a MS2 quant. column when visualising my project in PS. However, the visualisation software is taking some time to load the project on my Mac and I would prefer to do this over the command line. 

Is there a way to get MS2 quantification from the command line? I've tried generating the default protein and peptide reports but I don't see any data for MS2 quantification.

**Comment by nattzy94** [comment]
I realised that the MS2 quantification is "spectrum_counting" in the default proteins report. However, I am getting a NaN result for my proteins. Could this be because I'm searching my spectra against a database of small proteins (sorfs.org)? 

Have attached the protein report for reference. 
[sorf-search_1_0_Default_Protein_Report.txt](https://github.com/compomics/peptide-shaker/files/4584779/sorf-search_1_0_Default_Protein_Report.txt)

**Comment by hbarsnes** [comment]
The spectrum counting only uses the validated peptides/spectra, and (I assume mainly given your small database) you have no validated peptides/spectra for your proteins.

In any case, I'd recommend not relying on the spectrum counting but rather look into MS1-based quantification. PeptideShaker is compatible with both [FlashLFQ](https://github.com/smith-chem-wisc/FlashLFQ) and [moFF](https://github.com/compomics/moFF).

**Comment by nattzy94** [comment]
Yes, I do not get any validated peptides. My database is quite large (2.6M proteins) but because they are small proteins, I guess the FP rate is very high. 

Thanks! I will try MS1 quantification.

**Comment by nattzy94** [comment]
I'm new to MS so would like to make sure that I understand all this. What I understand is that the mgf files that I input into SearchGUI are MS2 spectra. This is then searched against my database. Although there are peptides that match to the proteins in the database, they do not pass a certain level of significance (or there are too many matches to the decoy db) and so are not classified as 'validated peptides'.

So because of that there is no MS quantification. But using MS1 quantification is possible because this is before the fragmentation to generate MS2 data. This reduced fragmentation supposedly will make quantification possible?

Thank you!

**Comment by hbarsnes** [comment]
> I'm new to MS so would like to make sure that I understand all this. What I understand is that the mgf files that I input into SearchGUI are MS2 spectra. This is then searched against my database. Although there are peptides that match to the proteins in the database, they do not pass a certain level of significance (or there are too many matches to the decoy db) and so are not classified as 'validated peptides'.

All correct. :)

> So because of that there is no MS quantification. But using MS1 quantification is possible because this is before the fragmentation to generate MS2 data. This reduced fragmentation supposedly will make quantification possible?

More or less. I would recommend taking a look at some of our tutorial material. You'll find an introduction to quantification in proteomics here: https://www.compomics.com/bioinformatics-for-proteomics/quantification. And here you can find more details on the statistical analysis: https://gtpb.github.io/PDA19.

**Comment by nattzy94** [comment]
Okay, thanks so much!
