### ISSUE TITLE
Peptide Shaker first use

### ISSUE THREAD

**Issue by matty83** [compomics/peptide-shaker#406]
Hi I just downloaded the program, you have to insert a series of peptides to analyze, the spectra are in raw format, you can help me set up the first use

**Comment by hbarsnes** [comment]
Hi,

I would highly recommend that you have a look at our tutorial material: http://compomics.com/bioinformatics-for-proteomics.

It should enable you to get started and teach you how to use our tools to analyze your own data.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
