### ISSUE TITLE
understanding the output of Peptideshaker, command line version

### ISSUE THREAD

**Issue by VladimirRoudko** [compomics/peptide-shaker#407]
Hello,

Upon processing the search results, peptide shaker gives some bulk statistics of each identification results. For example, for one file it gives the following STDOUT:

Mon Jun 22 11:52:27 EDT 2020 Importing sequences from human.proteome.10_concatenated_target_decoy.fasta.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:41 EDT 2020 FASTA file import completed.
Mon Jun 22 11:53:41 EDT 2020 Importing gene mappings.
Mon Jun 22 11:53:44 EDT 2020 Establishing local database connection.
Mon Jun 22 11:53:45 EDT 2020 Reading identification files.
Mon Jun 22 11:53:45 EDT 2020 Parsing 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.comet.pep.xml.
Mon Jun 22 11:53:48 EDT 2020 Loading spectra for 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.comet.pep.xml.
Mon Jun 22 11:53:48 EDT 2020 Importing 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.mgf
Mon Jun 22 11:53:48 EDT 2020 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.mgf imported.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Jun 22 11:53:48 EDT 2020 Collecting peptides to map.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:49 EDT 2020 Mapping peptides to proteins.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:49 EDT 2020 Importing PSMs from 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.comet.pep.xml
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Jun 22 11:53:50 EDT 2020 588 identified spectra (2.3%) did not present a valid peptide.
**Mon Jun 22 11:53:50 EDT 2020 52673 of the best scoring peptides were excluded by the import filters:
Mon Jun 22 11:53:50 EDT 2020     - 54.8% peptide length less than 8 or greater than 30.
Mon Jun 22 11:53:50 EDT 2020     - 45.2% peptide presenting high mass or isotopic deviation.**
Mon Jun 22 11:53:50 EDT 2020 Parsing 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.myrimatch.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:57 EDT 2020 Loading spectra for 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.myrimatch.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:57 EDT 2020 Collecting peptides to map.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:57 EDT 2020 Mapping peptides to proteins.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:57 EDT 2020 Importing PSMs from 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.myrimatch.mzid
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Jun 22 11:53:57 EDT 2020 86 identified spectra (0.4%) did not present a valid peptide.
**Mon Jun 22 11:53:57 EDT 2020 1145 of the best scoring peptides were excluded by the import filters:
Mon Jun 22 11:53:57 EDT 2020     - 5.2% peptide mapping to both target and decoy.
Mon Jun 22 11:53:57 EDT 2020     - 94.8% peptide presenting high mass or isotopic deviation**.
Mon Jun 22 11:53:57 EDT 2020 Parsing 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.novor.csv.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:58 EDT 2020 Loading spectra for 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.novor.csv.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:58 EDT 2020 Collecting peptides to map.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:58 EDT 2020 Mapping peptides to proteins.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:53:58 EDT 2020 Importing PSMs from 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.novor.csv
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Jun 22 11:53:58 EDT 2020 20099 identified spectra (77.5%) did not present a valid peptide.
**Mon Jun 22 11:53:58 EDT 2020 24323 of the best scoring peptides were excluded by the import filters:
Mon Jun 22 11:53:58 EDT 2020     - 86.8% peptide not matching to the database.
Mon Jun 22 11:53:58 EDT 2020     - 13.2% peptide length less than 8 or greater than 30.**
**Mon Jun 22 11:53:58 EDT 2020 Warning: More than 75% of the PSMs did not pass the import filters.**
 PeptideShaker did not manage to map most peptides to the database. Please verify your database.
 Please verify that your peptide selection criteria are not too restrictive.

Mon Jun 22 11:53:58 EDT 2020 Parsing 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.t.xml.
Mon Jun 22 11:54:09 EDT 2020 Loading spectra for 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.t.xml.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:54:09 EDT 2020 Collecting peptides to map.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:54:09 EDT 2020 Mapping peptides to proteins.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:54:09 EDT 2020 Importing PSMs from 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.t.xml
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Jun 22 11:54:09 EDT 2020 178 identified spectra (0.8%) did not present a valid peptide.
**Mon Jun 22 11:54:09 EDT 2020 3136 of the best scoring peptides were excluded by the import filters:
Mon Jun 22 11:54:09 EDT 2020     - 94.3% peptide length less than 8 or greater than 30.
Mon Jun 22 11:54:09 EDT 2020     - 4.8% unrecognized modifications.**
Mon Jun 22 11:54:09 EDT 2020 Parsing 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.tide-search.target.txt.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:54:11 EDT 2020 Loading spectra for 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.tide-search.target.txt.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:54:11 EDT 2020 Collecting peptides to map.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:54:11 EDT 2020 Mapping peptides to proteins.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Jun 22 11:54:12 EDT 2020 Importing PSMs from 04CPTAC_COprospective_W_VU_20150915_05CO006_f01.tide-search.target.txt
10% 20% 30% 40% 50% 60% 70% 80% 90% 90%
Mon Jun 22 11:54:13 EDT 2020 793 identified spectra (0.9%) did not present a valid peptide.
**Mon Jun 22 11:54:13 EDT 2020 26278 of the best scoring peptides were excluded by the import filters:
Mon Jun 22 11:54:13 EDT 2020     - 94.9% peptide length less than 8 or greater than 30.
Mon Jun 22 11:54:13 EDT 2020     - 4.7% peptide presenting high mass or isotopic deviation.**

I have a few questions concerning this output. What exactly the number of best scoring peptides were excluded due to import filters mean? When and how these peptides (in this case, < 8 or > 30 aa) get scored? Also, why is the variation of this number so high among different pipelines? Is there any reason to put 8/30 as threshold or these numbers can be decreased/increased, is there any scientific reason to pick these numbers?

Thank you! 
Vladimir

**Comment by VladimirRoudko** [comment]
Just FYI: total number of analyses spectra is ~26000 (on average per each each search algorithm)

**Comment by hbarsnes** [comment]
Hi Vladimir,

> What exactly the number of best scoring peptides were excluded due to import filters mean? 

PeptideShaker has various import filters that you can control via the Identification Settings > Show Advanced Settings > Import Filters. (And of course also via the CLI: https://github.com/compomics/compomics-utilities/wiki/IdentificationParametersCLI#import-filters.) 

> When and how these peptides (in this case, < 8 or > 30 aa) get scored? 

All of the peptide-spectrum-matches are scored as usual by the search engines, but the ones not passing the filters are removed before the FDR-calculation.

> Also, why is the variation of this number so high among different pipelines? 

These numbers very much depend on how well the search engine parameters align with the overall search parameters. For example, some search engines do not allow us to control all of the parameters as closely as we'd like to, and there is therefore no choice but to use a bigger search space and then filter out the matches not within the parameters afterwards.

> Is there any reason to put 8/30 as threshold or these numbers can be decreased/increased, is there any scientific reason to pick these numbers?

It is generally assumed, at least when using tryptic peptides, that peptides smaller than 8 amino acids in length will most often not be unique to a given protein sequence. Peptides longer than 30 amino acids are also rather uncommon, again at least for tryptic digestion as there will most ofte be enough tryptic cleavage sites to not result in peptides that are that long. Furthermore, peptides outside of this range tend to not work as well in the mass spectrometer.

Generally, this limitation will results in a smaller search space (and thus speed up the search) while not resulting in any noticeable drop in the number of identification. But you may of course alter the settings if you think this makes more sense for your dataset.

Best regards,
Harald

**Comment by VladimirRoudko** [comment]
Thank you! IT explains all, closing the issue then.
Best,
Vladimir
