### ISSUE TITLE
Peptide-shaker does not process DirectTag output

### ISSUE THREAD

**Issue by VladimirRoudko** [compomics/peptide-shaker#409]
Hello Harald,

I attempted to run the pipeline combining multiple search engines together and noticed that DirectTag output consistently returns error upon processing by peptide-shaker. 
Upon performing first SearchGUI step, DirectTag functions correctly, and produces following STDOUT:

directag command: 
/nfs/scratch/vova/compomics/pipeline/coad_w_vu/compomics_result/01CPTAC_COprospective_W_VU_20150901_01CO006/SearchGUI-3.3.20/resources/DirecTag/linux/linux_64bit/directag /nfs/scratch/vova/compomics/pipeline/coad_w_vu/compomics_result/01CPTAC_COprospective_W_VU_20150901_01CO006/mgf_input/01CPTAC_COprospective_W_VU_20150901_01CO006_f01.mgf -cpus 15 -StaticMods C 57.021464 -DynamicMods M 0 15.994915 -FragmentMzTolerance 0.5 -PrecursorMzTolerance 0.01 -TagLength 4 -MaxTagCount 10 -MaxPeakCount 100 -NumIntensityClasses 3 -TicCutoffPercentage 1.0 -AdjustPrecursorMass false -MinPrecursorAdjustment -0.5 -MaxPrecursorAdjustment 1.5 -PrecursorAdjustmentStep 0.1 -NumChargeStates 3 -UseChargeStateFromMS true -DuplicateSpectra true -DeisotopingMode 0 -IsotopeMzTolerance 0.25 -IsotopeMzTolerance 0.1 -MaxDynamicMods 2 -IntensityScoreWeight 1.0 -MzFidelityScoreWeight 1.0 -ComplementScoreWeight 1.0 -workdir /nfs/scratch/vova/compomics/pipeline/coad_w_vu/compomics_result/01CPTAC_COprospective_W_VU_20150901_01CO006/search_output/.SearchGUI_temp 

Wed Jun 24 14:22:05 EDT 2020 Processing 01CPTAC_COprospective_W_VU_20150901_01CO006_f01.mgf with DirecTag.

DirecTag 1.4.66 (2012-11-30)
FreiCore 1.6.210 (2012-11-30)
ProteoWizard MSData 3.0.4140 (2012-11-22)
ProteoWizard Proteome 3.0.4080 (2012-11-7)
Vanderbilt University (c) 2012, D.Tabb/M.Chambers/S.Dasari
Licensed under the Apache License, Version 2.0

Could not find the default configuration file (hard-coded defaults in use).
Reading intensity ranksum bins cache file.
Calculating uncached ranksum bins (this could take a while).
Writing intensity ranksum bins cache file.
Found 1 file for sequence tagging.
Reading spectra from file "/nfs/scratch/vova/compomics/pipeline/coad_w_vu/compomics_result/01CPTAC_COprospective_W_VU_20150901_01CO006/mgf_input/01CPTAC_COprospective_W_VU_20150901_01CO006_f01.mgf"
Read 33476 spectra with 9231634 peaks; 9.35065 seconds elapsed.
Trimming spectra with less than 10 peaks.
Trimmed 4 spectra for being too small before peak filtering.
Determining spectrum charge states from 33472 spectra.
Finished determining spectrum charge states; 0.00146294 seconds elapsed.
Filtering peaks in 33472 spectra.
Sequence tagging 33472 spectra.
Sequence tagged 9048 of 33472 spectra; 1808 per second, 00:00:05 elapsed, 00:00:14 remaining.
Sequence tagged 17848 of 33472 spectra; 1784 per second, 00:00:10 elapsed, 00:00:09 remaining.
Sequence tagged 26661 of 33472 spectra; 1777 per second, 00:00:15 elapsed, 00:00:04 remaining.
Finished sequence tagging spectra; 18.9037 seconds elapsed.
Mean original (filtered) peak count: 275.795 (93.1958)
Min/Max original (filtered) peak count: 10/1098 (10/100)
Filtered out 66.2073% of peaks before tagging.
Overall stats: 33472 spectra; 10723365 tag graph edges; 62789587 tags generated; 312809 tags retained
Writing tags to "01CPTAC_COprospective_W_VU_20150901_01CO006_f01.tags".
Finished file "/nfs/scratch/vova/compomics/pipeline/coad_w_vu/compomics_result/01CPTAC_COprospective_W_VU_20150901_01CO006/mgf_input/01CPTAC_COprospective_W_VU_20150901_01CO006_f01.mgf"; 30.1457 seconds elapsed.
Finished tagging 1 files; 30.1457 seconds elapsed.

Wed Jun 24 14:22:38 EDT 2020 DirecTag finished for 01CPTAC_COprospective_W_VU_20150901_01CO006_f01.mgf (33.1 seconds).

..... (same for other fractions).

While upon processing with Peptide-shaker, it returns an error message to STDOUT:

Wed Jun 24 16:19:20 EDT 2020 FASTA file import completed.
Wed Jun 24 16:19:20 EDT 2020 Importing gene mappings.
Wed Jun 24 16:19:30 EDT 2020 Establishing local database connection.
Wed Jun 24 16:19:32 EDT 2020 Reading identification files.
**Wed Jun 24 16:19:32 EDT 2020 Parsing 01CPTAC_COprospective_W_VU_20150901_01CO006_f01.tags.
Wed Jun 24 16:19:32 EDT 2020 An error occurred while loading spectrum matches from '01CPTAC_COprospective_W_VU_20150901_01CO006_f01.tags'. This file will be ignored. Error: java.lang.IllegalArgumentException: No amino acid or modification could be mapped to tag component "0" in tag "KYK0".** See resources/PeptideShaker.log for details.

In the PeptideShaker.log I see exactly the same message.  What would be a suggestion to fix it?

Thank you,
Vladimir

**Comment by hbarsnes** [comment]
Hi Vladimir,

The DirecTag modification mapping is added to the search parameter file when running SearchGUI. To load DirecTag data in PeptideShaker you therefore have to use the -output_data option when running SearchGUI. This ensures that the extended search parameter file is made available to PeptideShaker, which again means that we can interpret the DirecTag modification annotation correctly.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.

**Comment by veitveit** [comment]
@hbarsnes Which parameter file do you mean? The standard searchgui one? 

I am running the newest version of searchgui and peptideshaker, the former with the -output_data option, but still getting the same error as above.

**Comment by hbarsnes** [comment]
@veitveit The important part is that the search parameter file is updated with the DirecTag PTM mappings when running SearchGUI. It is therefore important that this new parameter file (which should be in the output folder or zip file from SearchGUI) is the one used as input to PeptideShaker, and not the original parameter file used as input to SearchGUI.

**Comment by veitveit** [comment]
@hbarsnes Got it and it worked, thanks! I was importing the original parameter file into peptideshaker.
