### ISSUE TITLE
sporadic error with saving/reading peptide-shaker results upon trying to export the reports.

### ISSUE THREAD

**Issue by VladimirRoudko** [compomics/peptide-shaker#410]
Hello Harald,

sorry for posting 2d issue in a row - I just thought it make sense to split them on two different posts, as the issues are not related. 
Upon running SearchCLI-PeptideShakerCLI in parallel (setup: Ubuntu, SGE-job control, 15 threads, 40Gb per run, independent installations of the software per each job, independent copy of the reference proteome, 7 jobs at a time) I noticed that at least one pipe produces error in either writing or reading *.cpsx file upon trying to export reports. Here is the very end of the STDOUT with the error:

"....
Wed Jun 24 16:35:29 EDT 2020 Project successfully created.
Wed Jun 24 16:35:29 EDT 2020 Saving results.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Wed Jun 24 16:47:48 EDT 2020 Results saved to /nfs/scratch/vova/compomics/pipeline/coad_w_vu/compomics_result/04CPTAC_COprospective_W_VU_20150915_05CO006/peptideshaker_output/04CPTAC_COprospective_W_VU_20150915_05CO006.cpsx.

Wed Jun 24 16:47:52 EDT 2020 PeptideShaker process completed.
Wed Jun 24 16:47:52 EDT 2020 Processing Completed.
10% 30% 40% 50% 70% 80% 90%
Wed Jun 24 16:48:34 EDT 2020 An error occurred while reading: /nfs/scratch/vova/compomics/pipeline/coad_w_vu/compomics_result/04CPTAC_COprospective_W_VU_20150915_05CO006/peptideshaker_output/04CPTAC_COprospective_W_VU_20150915_05CO006.cpsx.
10% 30% 40% 50% 70% 80% 90%
Wed Jun 24 16:49:08 EDT 2020 An error occurred while reading: /nfs/scratch/vova/compomics/pipeline/coad_w_vu/compomics_result/04CPTAC_COprospective_W_VU_20150915_05CO006/peptideshaker_output/04CPTAC_COprospective_W_VU_20150915_05CO006.cpsx.
"

The  applied code is the following:

mkdir -p "peptideshaker_output"
java $JAVA_OPTS -cp $peptideshaker eu.isas.peptideshaker.cmd.PeptideShakerCLI \
	-experiment myExperiment \
	-sample "${fn}" \
	-replicate 1 \
	-identification_files "search_output/searchgui_out.zip" \
	-spectrum_files "mgf_input" \
	-id_params "identification.par" \
	-out "peptideshaker_output/"${fn}".cpsx" \
	-threads ${THREADS}

mkdir "report_output"
java $JAVA_OPTS -cp $peptideshaker eu.isas.peptideshaker.cmd.ReportCLI \
	-in "peptideshaker_output/"${fn}".cpsx" \
	-out_reports "report_output" \
	-reports "0, 3, 6, 9" \
	-documentation "0, 3, 6, 9"

The confusing part is that every other parallel job (6 out of 7 for example) does finish the pipeline successfully. Also, the error is not reproducible per file: each time the issue happens with different file. So it rules out the file issues. 

Thank you for help,
Vladimir

**Comment by hbarsnes** [comment]
Hi Vladimir,

First, I would recommend merging the two command lines, as there is no need to first save the project and then reopen it to export the reports. You can simply add the -out_reports and -reports options to the PeptideShakerCLI command line.

As to why the error occurs, you would have to check the PeptideShaker log file. You can find it under PeptideShaker-X.Y.Z\resources\PeptideShaker.log.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue if it still does not work in the most recent release.
