### ISSUE TITLE
Unhandled exception in SearchGUI-4.0.0-beta

### ISSUE THREAD

**Issue by VladimirRoudko** [compomics/peptide-shaker#411]
Hello,

I was running into issue with MS Amanda search within SearchGUI-4.0.0-beta pipeline. The search result in STDOUT the following error:

Unhandled Exception:
System.TypeLoadException: Could not load type 'MSAmanda.CommandLine.MSAmandaSearch' from assembly 'MSAmanda, Version=2.0.0.14665, Culture=neutral, PublicKeyToken=null'.

Eventually, no output file is produced. My machine configurations are:
Ubuntu
Java openjdk 11.0.7 2020-04-14
Xmx40G
Threads 15

Thank you!
Vladimir

**Comment by VladimirRoudko** [comment]
According to what I've been able to find out, the error is happening upon commandline trying to load MSAmanda.exe file with mono:

"mono /path/to/SearchGUI-4.0.0-beta/resources/MS Amanda/MSAmanda.exe -s ..."

Apparently, similar commandline was working using SearchGUI-3.3.20 version (with MS Amanda Stand-Alone version 2.0.0.9706). Is it possible, that update to version 2.0.0.14665 has affected the ways how mono operates? 

Thank you,
Vladimir

**Comment by hbarsnes** [comment]
Hi Vladimir,

As far as I know there are no changes in how mono operates for the different MS Amanda versions. Do you get the same error if running the MS Amanda mono command line directly, i.e. not via SearchGUI? If so, I'd recommend contacting the MS Amanda developers directly at https://groups.google.com/forum/#!forum/msamanda.

Best regards,
Harald

**Comment by VladimirRoudko** [comment]
Hi Harald,

yes, indeed I get the same error directly running mono with MSAmanda.exe. I will post the error on the forum - thank you for the link!

Vladimir

**Comment by VladimirRoudko** [comment]
Turned out to be mono-compatibility issue on Linux platform. The error is fixed by changing mono runtime to mono complete, explanation is here:

https://groups.google.com/forum/#!msg/msamanda/XRKS2yYA2Jw/R9rFPEFOBAAJ

Again, thanks for help!
