### ISSUE TITLE
new warning message

### ISSUE THREAD

**Issue by fazeliniah** [compomics/peptide-shaker#412]
Hello Peptideshaker team, 
I have encountered a new warning message and subsequent search cancellation. I have attached the report for your review. I'd greatly appreciate any help to fix this. 
Thanks
[report.txt](https://github.com/compomics/peptide-shaker/files/5008898/report.txt)

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/C:/PeptideShaker/PeptideShaker-1.16.45/PeptideShaker-1.16.45/lib/gson-2.4.jar) to field java.awt.Color.value
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by hbarsnes** [comment]
The "illegal reflective access" messages are just internal Java warnings and can be ignored. However, it does seem like PeptideShaker is having issues opening the search results. Can you also share the PeptideShaker log file?

**Comment by fazeliniah** [comment]
Thank you very much for your help. I attached the peptideshkaer bug report.
[PeptideShaker 1.16.45 log.txt](https://github.com/compomics/peptide-shaker/files/5016120/PeptideShaker.1.16.45.log.txt)

**Comment by hbarsnes** [comment]
This looks like an issue with the use of multiple threads that we have for some time been trying to fix by redesigning this part of our code. An updated beta version should soon be available for testing. I will keep you posted.

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
