### ISSUE TITLE
Different validation status for identical PSM in two samples

### ISSUE THREAD

**Issue by VladimirRoudko** [compomics/peptide-shaker#413]
Hello Harald,

quick question concerning the PSM interpretation of PeptideShaker. I have identified one PSM which has "validated" status in one sample. However, identical PSM (based on visual exploration of fragmentation pattern and intensities) is present in another sample with the status "not validated". Does it mean that this PSM - most likely false positive? How could it happen that same PSM will have different statistical outcomes assuming that the search was performed using exactly same peptide-decoy database and same search parameters?

thank you,
Vladimir

**Comment by hbarsnes** [comment]
Hi Vladimir,

> Does it mean that this PSM - most likely false positive?

It could be, but there is no way of telling a false positive from a true positive based on the validation value alone. In fact, it is very hard in general.

> How could it happen that same PSM will have different statistical outcomes assuming that the search was performed using exactly same peptide-decoy database and same search parameters?

If the PSMs are in fact identical, i.e. scored identically by the search engine(s), the validation status ought to be the same. However, it could take nothing more than a single fragment ion being different to alter the search engine score and thus in extreme cases make one of the PSMs validated and the other not.

Best regards,
Harald

**Comment by VladimirRoudko** [comment]
Thank you, I understand it better now. Yes, indeed some spectra are nearly identical and certain fragment ion intensities are different between these two cases.  Also, I noticed, that in such doubtful situations the next predicted peptide sequence to the validated one has quiet high score as well ( as ruled by examining Spectrum IDs tab and just checking single program identifications).

Also similar question to this: I have a lot of small proteins in my target database (lets say 1-200 residues on average): around 40.000 unique ones. Majority of times peptideshaker identify one "validated + high confidence" peptide per protein. This one validated peptide has only one validated PSM as well. Close examination of this PSM shows that its quiet a good hit: validated hit has 100 score, while the next ranked PSM prediction with different peptide prediction has score of only 25 . So we can rule , that this PSM and Peptide are statistically good hits. But when I look into protein tab, the original protein is termed as statistically not valid with 51% confidence.  The full protein sequence is 30 aa, the validated peptide and PSM is 8 aa.  

with this example, could you please help me with interpretation of observed result? Should I actually bother with protein tab (taking into account that they are very short and statistically I can not expect multiple different PSMs to be mapped to them), or I can just rely on peptide/PSM tabs mostly to draw conclusions, whether proteins are in the sample or not?

Thank you,
Vladimir

**Comment by hbarsnes** [comment]
Hi Vladimir,

> The full protein sequence is 30 aa, the validated peptide and PSM is 8 aa.

In such cases the protein validation will probably not make much sense, and you would indeed be better off paying closer attention to the peptide/PSM validation. However, you should also take protein inference into account as some of your high-scoring peptides may not always be unique to one protein. Which is something you will miss if exclusively focusing on the peptide level. 

Best regards,
Harald
