### ISSUE TITLE
Gene annotation menu freezes when loading fasta with multiple species

### ISSUE THREAD

**Issue by dominik-kopczynski** [compomics/peptide-shaker#414]
When loading a fasta file with multiple species, e.g., [ecoli.zip](https://github.com/compomics/peptide-shaker/files/5028314/ecoli.zip), the options menu freezes when opening the gene annotation menu.

Cheers

**Comment by hbarsnes** [comment]
Does not seem to have anything to do with the FASTA file containing multiple species as far as I can tell. At least not according to the stack trace:

```
java.io.IOException: Server returned HTTP response code: 400 for URL: https://www.uniprot.org/taxonomy/?sort=score&desc=&compress=no&query=Escherichia%20coli%20O6:K15:H31%20(strain%20536%20/%20UPEC)&format=tab&columns=id
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at com.compomics.util.experiment.biology.taxonomy.mappings.UniprotTaxonomy.downloadMapping(UniprotTaxonomy.java:123)
...
```

Do you get the same issue in the beta version as well? As I was not able to reproduce it there.

**Comment by hbarsnes** [comment]
This error can be ignored though. And just indicates that the mappings do not exist for that species. I'm not able to reproduce the freeze though. But you may have to be a bit patient as you have quite a lot of difference species in your FASTA file. :)

**Comment by dominik-kopczynski** [comment]
Thank you Harald, I just forwarded this bug from a colleague of mine, didn't check the bug on my own. Will do now.
