### ISSUE TITLE
Peptides that match both target and decoy / PEP calculation for spectrum with multiple candidates

### ISSUE THREAD

**Issue by CHIA-HENG** [compomics/peptide-shaker#415]
Hi! Team compomics,

I have two questions regarding the algorithms of peptide-shaker.

**#1 How does peptide-shaker handle best scoring peptides that match to both target and decoy?**
During the import of database search results, peptide-shaker reported a respond similar to the one below:
"""
XXX of the best scoring peptides were excluded by the import filters:
 XX.X% peptide mapping to both target and decoy.
 XX.X% peptide length less than 8 or greater than 30.
"""
I looked through the "spectrum IDs" tab and noticed that "peptides out of length range" were excluded, but "peptides that match to target and decoy" were kept.  Am I understanding this correctly? If the latter are kept by the software, are the peptides counted as targets or decoys? 

**#2 How does peptide-shaker calculate the PEP for database search engines with multiple candidates**
I have read both the supplementary note of your 2015 paper and the online tutorial.
However, for search engines that generate multiple peptide candidates, such as COMET, does peptide-shaker take all of the candidates for FDR calculation or only the Rank 1 peptides of each spectrum?

Thank you!

**Comment by hbarsnes** [comment]
Hi,

> How does peptide-shaker handle best scoring peptides that match to both target and decoy?

The way it is currently implemented these are filtered out. We are considering changing this in future releases though.

> How does peptide-shaker calculate the PEP for database search engines with multiple candidates?

We use all of them when calculating the probabilities and estimating the scores, but use only the best ranked when calculating the FDR.

Best regards,
Harald

**Comment by CHIA-HENG** [comment]
Hi! Harald,

Thank you very much for your reply and help.
Regarding the second issue, so is it possible for a second ranked peptide, for example in comet, be chosen as the final PSM after combining the search results with other search engines? 

> > How does peptide-shaker calculate the PEP for database search engines with multiple candidates?
 
> We use all of them when calculating the probabilities and estimating the scores, but use only the best ranked when calculating the FDR.

Best regards,
Chia-Heng

**Comment by hbarsnes** [comment]
Hi Chia-Heng,

> Regarding the second issue, so is it possible for a second ranked peptide, for example in comet, be chosen as the final PSM after combining the search results with other search engines?

Yes, this can happen. It all comes down to the combined evidence and picking the most likely PSM for the given spectrum.

Best regards,
Harald

**Comment by CHIA-HENG** [comment]
Hi! Harald

Thank you for your explanation!

Best regards,
Chia-Heng
