### ISSUE TITLE
GO analysis empty

### ISSUE THREAD

**Issue by drosinis** [compomics/peptide-shaker#416]
Hi, 
I have been working with SearchGUI/Peptide shaker on&off for about 3 months
I was able to run several searches (mainly with X!tandem) and customize it to search for some tag modifications. 
One thing i didn't get was that the GO analysis was always empty. Do i need to download any files/tables (e.g. uniprot) and import them into something like a bin to work? Or could it be a problem with the way the fasta file is set up?
I am using PeptideShaker 1.16.45 on a windows10 
I appreciate any help!

**Comment by hbarsnes** [comment]
Hi,

The GO analysis only works if your FASTA file uses UniProt accession numbers, as this is how we map them to the GO terms in Ensembl. There are also some limitations with regards to which species that are annotated with the required information in Ensembl.

Best regards,
Harald

**Comment by drosinis** [comment]
Thank you!
I downloaded the FASTA from UniProt which contains the uniprot identifier (e.g. >sp|Q60476|ADA2C_CAVPO Alpha-2C adrenergic receptor OS=Cavia porcellus OX=10141 GN=ADRA2C PE=3 SV=1) , however after the search is complete it looks like the accession that is extracted links to NCBI Refseq. Any suggestions how to extract the UniProt identifier instead?

**Comment by hbarsnes** [comment]
> I downloaded the FASTA from UniProt which contains the uniprot identifier (e.g. >sp|Q60476|ADA2C_CAVPO Alpha-2C adrenergic receptor OS=Cavia porcellus OX=10141 GN=ADRA2C PE=3 SV=1)

In that case it should be possible to map to the GO terms. Depending on whether the species is annotated with GO terms in Endsembl. You should see a warning about this early on when loading the data in PeptideShaker if the species is not mapped.

> however after the search is complete it looks like the accession that is extracted links to NCBI Refseq.

Where do you see the NCBI Refseq links? As the UniProt header in the example above looks like a standard UniProt header to me. In the Overview tab in PeptideShaker the accession number links should therefore send you to UniProt. Are you saying that this is not the case?

**Comment by drosinis** [comment]
Yes, when i click on the accession number (blue underlined)  at the overview tab it sends me to NCBI not UniProt


![Capture_3_090920](https://user-images.githubusercontent.com/70050529/92669270-0ee8fb80-f2df-11ea-9d8d-5f4379edf6e2.JPG)

**Comment by hbarsnes** [comment]
That's very odd. Are you sure you are using a FASTA file with only UniProt accession numbers? As I don't see how the example protein accession number line you showed above can result in a mapping to NCBI like the one in the screenshot?

Can you try the following and send me a screenshot of the resulting dialog? After opening the PeptideShaker project go to File > Project Settings > Spectrum Matching, then click the View option after the Database field. This should give you an overview of the FASTA file content.

**Comment by ulrich-eckhard** [comment]
not sure if replying to the email notification actually works,

but I had a similar behavior once when I hadn't updated the "protein
databases" used for "protein inference". so I accidentally had searched
against database 1 (search settings in SearchGUI), but inferred the
proteins from database 2 during the import of the results into
PeptideShaker.

could that be the reason?

**Comment by ulrich-eckhard** [comment]
so i hadn't updated the fasta file here (let's see if pasting screenshots
also works):
[image: image.png]

**Comment by ulrich-eckhard** [comment]
ok ... that didn't work ...  let's try again ...
![Clipboard02](https://user-images.githubusercontent.com/13509447/92701159-efd68200-f34f-11ea-8e97-13297d0d2dd5.png)

**Comment by drosinis** [comment]
Thank you for your replies!
I looked for the Database settings as Harald suggested and it shows both the NCBI and  UniProt (see snapshot below)
![Capture_4_091020](https://user-images.githubusercontent.com/70050529/92784599-b5331080-f374-11ea-9a42-33c07e386acb.JPG)
Then i went to UniProt and downloaded a fresh fasta file and checked to find that the settings only contain the UniProt but not NCBI and repeated the search. After the search, i'm getting links to UniProt (second snapshot). However when i check the database settings again it looks like it reverts back to the initial database and the GO tab is still empty.
![Capture_5_091020](https://user-images.githubusercontent.com/70050529/92788773-3a6bf480-f378-11ea-937d-6c944317e927.JPG)
How can i update the fasta settings in the 'protein inference' that Ulrich is suggesting?

**Comment by hbarsnes** [comment]
> How can i update the fasta settings in the 'protein inference' that Ulrich is suggesting?

This is something you have to set before loading the search results in PeptideShaker. Click the Edit button after the Identification field under Project Settings in the New Project dialog. Then click on Show Advanced Settings and select the Protein Inference option. After setting the FASTA file be sure to click Yes when getting the question to save the settings.

However, if you do have UniProt links in the Overview tab and the GO tab is still empty that probably means that your species is/are not mapped to GO terms in Ensembl. There should be a mentioning of this when loading the data. You can check this later by going to File > Project Properties and scroll down to the Report section. There you should see a line like this:

`Thu Jul 04 15:38:00 CEST 2019        Importing gene mappings.`

Followed by either lines for downloading the gene and GO mappings (however only if they have not already been downloaded) or by lines stating that mappings for the following species are not available.

**Comment by drosinis** [comment]
Thank you, 
I finally managed to get the GO to show up (see snapshot below). I had to move my raw files to a new folder, do a fresh SearchGUI search,  and make sure the fasta displayed in at the Protein Inference tab was the one with UniProt as you suggested. The only tricky part was that PeptideShaker kept going to an earlier database that had both NCBI and UniProt identifiers. 
I have a couple more questions about the quantitative capabilities of PeptideShaker, concerning e.g. MS2 Quant, LFQ, and possible export to Perseus and/or MQuant? Should i create another thread?
Best regards!

![Capture_8_091020](https://user-images.githubusercontent.com/70050529/92951583-985a1400-f42c-11ea-82a6-b0ced5ddc3ba.JPG)

**Comment by hbarsnes** [comment]
> I finally managed to get the GO to show up (see snapshot below).

Great! And thanks to @ulrich-eckhard for his tips as well! :)

> I have a couple more questions about the quantitative capabilities of PeptideShaker, concerning e.g. MS2 Quant, LFQ, and possible export to Perseus and/or MQuant? Should i create another thread?

Yes, it would be best to do this under a new issue. I will therefore close this one.
