### ISSUE TITLE
LFQ

### ISSUE THREAD

**Issue by vipulbatra1985** [compomics/peptide-shaker#419]
is it possible to quantify 2 experimental groups ran in triplicates, 8 fractions each on searchGUI?

**Comment by hbarsnes** [comment]
I'm afraid that neither SearchGUI nor PeptideShaker supports label free quantification. I would recommend having a look at other tools designed for this purpose, such as MaxQuant (https://www.maxquant.org).

**Comment by vipulbatra1985** [comment]
Okay. Please let me know where can I set the experimental design e.g. sample with eight fraction run in triplicates.

**Comment by hbarsnes** [comment]
> Please let me know where can I set the experimental design e.g. sample with eight fraction run in triplicates.

SearchGUI/PeptideShaker only supports two options in terms of experimental design. Either you can process all the fractions together as one experiment or you'll have to process each fraction separately. For the former you can to some extent compare the results in the Fractions tab in PeptideShaker, while for the latter you'll have to export the results separately and compare them outside PeptideShaker.

If you want to compare the triplicates you could consider loading all the fractions of each replicate together, export the results and then compare them outside PeptideShaker. But again, our tools are not really made for these types of setups and you will probably be better off trying other tools that will be more adapted to what you want to achieve.

**Comment by vipulbatra1985** [comment]
No, its the only tool that is so intuitive and self-explanatory. I will not be better trying other tools, which by the way I have already tried: TPP and MQ (+Perseus). I understand that this tool cant handle quantification, however, I am talking about protein identification. One ought to run technical replicates. Shall I process each replicate separately? Will it be okay?

**Comment by hbarsnes** [comment]
> Shall I process each replicate separately? Will it be okay?

Yes, you can process each replicate separately, i.e. load all of the fractions for one replicate in PeptideShaker at the same time. PeptideShaker will then merge all of the fractions into one overview (with the mentioned option to inspect the individual fractions via the Fractions tab).

The thing PeptideShaker currently does not support is the comparison of projects. Which means that you will not be able to compare the different replicates directly in PeptideShaker. You will therefore have to export the results and compare them outside of PeptideShaker.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
