### ISSUE TITLE
Possible to export species?

### ISSUE THREAD

**Issue by jcanderan** [compomics/peptide-shaker#422]
Is there a way to export the species (i.e. OS/OX from Uniprot headers) with the protein matches?

Thanks!

**Comment by hbarsnes** [comment]
At the moment this is not supported, but should not be too difficult to add. I will try to include it in the next release.

**Comment by hbarsnes** [comment]
Issue resolved with the release of the new version. If this is not the case, please let us know and we'll reopen the issue.
