### ISSUE TITLE
Issues exporting sequence coverage?

### ISSUE THREAD

**Issue by jcanderan** [compomics/peptide-shaker#423]
Here is an example of what the proteins look like inside Peptideshaker GUI:
![image](https://user-images.githubusercontent.com/23535425/97097223-892dcf00-1644-11eb-81f1-d85dd46d5b5f.png)

(2.18 and 5.02 are the coverages)

Here is what the entry for 411 looks like exported using the default non-validated protein report:
11684	A0A3D9IV67	Ribosomal RNA small subunit methyltransferase E (A0A3D9IV67_9BACL)	DFP95_101192		28.209448336520985	100.0	0.0

(100.0 being possible coverage and 0.0 coverage respectively)

Here is protein 412 just as another example:
13255	A0A0G2Z5U9	Alanine--tRNA ligase (A0A0G2Z5U9_9BACT)	alaS		99.10235342696127	96.1	0.0

(96.1 and 0.0 being the coverages)

Is what is being exported different than what is displayed within the GUI or is there another issue? The number in the GUI is actually what the coverage of the identified peptides vs. the full protein sequence should be so I'm not sure what the numbers in the report are representing.

Thanks!

**Comment by hbarsnes** [comment]
Hi. The coverage values in exports only includes the validated peptides. And in both of the examples at the top there are no validated peptides (hence the red color in the plot). The exception is the possible coverage, which is independent of the peptides detected.

**Comment by jcanderan** [comment]
I guess I'm not following what possible coverage represents. I'm exporting the report with non-validated matches. I understand that coverage will included validated-peptides. What does possible coverage include then?

In the case of the non-validated report, wouldn't it make sense for coverage to include non-validated peptides plus validated peptides versus validated peptides only?

**Comment by hbarsnes** [comment]
> I understand that coverage will included validated-peptides. What does possible coverage include then?

The possible coverage is the theoretical coverage given the protease cleavage rules combined with the max number of missed cleavages and the min and max allowed peptide lengths.

> In the case of the non-validated report, wouldn't it make sense for coverage to include non-validated peptides plus validated peptides versus validated peptides only?

Maybe, but given that the whole point of the validation is to figure out which identifications we should trust and which we should not, I would also argue that including the ones we should not trust in the exports can be interpreted incorrectly as well?

**Comment by jcanderan** [comment]
Thank you for the clarification about possible coverage.

Perhaps the solution would be to include both coverage with validated only and coverage with both validated/non-validated as is the case with some other things.

I'll consider the issue closed. Thanks again!
