### ISSUE TITLE
Feature request: Export coverage % including non-validated

### ISSUE THREAD

**Issue by jcanderan** [compomics/peptide-shaker#424]
This was first brought up in my other issue but wanted to explicitly request it:

Could we please get a feature to export coverage % including non-validated peptides? (as we can with PSMs, etc).

Thank you for your efforts!

**Comment by hbarsnes** [comment]
Thanks for raising it as a separate request so that we do not forget about it! We'll look into adding it as soon as possible.

**Comment by hbarsnes** [comment]
The requested feature has now been implemented and will be included in the next major release.

**Comment by hbarsnes** [comment]
Issue resolved with the release of the new version. If this is not the case, please let us know and we'll reopen the issue.
