### ISSUE TITLE
Peptide shaker error

### ISSUE THREAD

**Issue by vipulbatra1985** [compomics/peptide-shaker#426]
Sometimes the outputting is successful and other times it gives the error (PFA). There are 8 fractions i.e. 8 .raw files from QEaxcative were used for identification. 
[SearchGUI 3.3.21 log.txt](https://github.com/compomics/peptide-shaker/files/5456544/SearchGUI.3.3.21.log.txt)

Please help.

**Comment by hbarsnes** [comment]
We are about to release new major updates of both SearchGUI and PeptideShaker that will hopefully solve this problem. I will let you know as soon the new releases are available for download.

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
