### ISSUE TITLE
Processing issue with new version

### ISSUE THREAD

**Issue by fazeliniah** [compomics/peptide-shaker#429]
Hello, 
I have updated to the new version of PeptideShaker (on Windows 10). Unfortunately, I get the following message in the log file when I tried to open the default example. Not sure what I can do to fix this since I am not able to run and process any thing. I didn't have this problem with the previous versions. 
Thanks

Wed Nov 11 12:15:25 EST 2020: PeptideShaker version 2.0.0.
Memory given to the Java virtual machine: 29826220032.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86587896.
Java version: 1.8.0_271.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_271
os.name: Windows 10
memory: 59.2/163.1
processors available: 16
useCommandThread: false
Exception in thread "ImportThread" java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
	at com.compomics.util.db.object.ObjectsDB.loadFromDB(ObjectsDB.java:341)
	at com.compomics.util.db.object.ObjectsDB.retrieveObject(ObjectsDB.java:464)
	at eu.isas.peptideshaker.utils.PsdbParent.loadPsdbFile(PsdbParent.java:232)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI$104.run(PeptideShakerGUI.java:6612)

**Comment by hbarsnes** [comment]
As mentioned in the release notes Java 9 or newer is now required to run PeptideShaker. So if you update your Java version the processing issues should hopefully be fixed.

**Comment by fazeliniah** [comment]
Thanks. I updated the Java but unfortunately got a different error when I tried to open the example file. The error log is attached for your review. 
[PeptideShaker_error.txt](https://github.com/compomics/peptide-shaker/files/5526440/PeptideShaker_error.txt)

**Comment by hbarsnes** [comment]
Thanks for letting me know about the issues with opening the example dataset. I think I know what the problem is. I will try to fix it and release a new version tomorrow. The other features should work fine though, i.e. you should be able to load your own datasets etc.

**Comment by hbarsnes** [comment]
I just released PeptideShaker v2.0.2 which should allow you to also open the example dataset. If this is not the case, or you experience other problems, please let me know and I'll reopen the issue.
