### ISSUE TITLE
Reporter Error while reading the file

### ISSUE THREAD

**Issue by InduKhatri** [compomics/peptide-shaker#430]
Hey,

I am using reporter on iTRAQ4 processed samples for quantification

java -cp Reporter-0.7.20.jar eu.isas.reporter.cli.ReporterCLI -id PATH/TO/INPUT/CPSX/FILE -out PATH/TO/OUTPUT/QUANT/FILE

However, I am getting an error

**An error occurred while reading:
FILE.cpsx.

Please verify that the Reporter version used to create
the file is compatible with your version of Reporter.**

**Comment by hbarsnes** [comment]
I'm afraid that Reporter has not been updated to work with the latest releases of PeptideShaker and at the moment it is unclear whether this will be prioritized. To use Reporter you therefore have to rely on the older PeptideShaker releases. I think PeptideShaker v1.16.45 should be ok.

**Comment by InduKhatri** [comment]
Thank you for your quick response.

**Comment by hbarsnes** [comment]
We finally got around to updating Reporter to work with the latest releases of PeptideShaker, please see https://github.com/compomics/reporter/wiki/ReleaseNotes.

Reporter is still very much in a beta state though, so please do not hesitate to tell us (via the [Reporter issue tracker](https://github.com/compomics/reporter/issues)) if you come across any other issues.

BTW, note that the PeptideShaker files are now called psdb (and not cpsx).
