### ISSUE TITLE
No identification results 

### ISSUE THREAD

**Issue by umutcakir** [compomics/peptide-shaker#431]
In old version (1.16.45) I could use same identification file (mgf) and fasta file and create output successfully. However, there seem to be no searchgui related problem (at least it does not give any error), but peptide shaker gives following error. I am using them from the command line on Ubuntu 20. 

Reading identification files.
Fri Nov 13 22:46:58 UTC 2020 No identification results.
Fri Nov 13 22:46:58 UTC 2020 PeptideShaker Processing Canceled.
CompomicsError PeptideShaker processing canceled. Please see the PeptideShaker log file: /home/ubuntu/MS/PeptideShaker-2.0.2/resources/PeptideShaker.log CompomicsError 

Log file: 

Fri Nov 13 22:46:01 UTC 2020: PeptideShaker version 2.0.2.
Memory given to the Java virtual machine: 2075918336.
Total amount of memory in the Java virtual machine: 16252928.
Free memory: 11757272.
Java version: 11.0.9.

Thank you for your help.

**Comment by hbarsnes** [comment]
I would recommend having a closer look at your search parameters to make sure that they are not too strict? If you do not see any obvious issues you can always share your parameter file here and I can have a look as well.

**Comment by umutcakir** [comment]
Thank you for your prompt reply. Here is my search parameters. Almost all are in default settings. If needed, I can share identification and fasta files privately. 

 {
  "marshallableParameterType": "identification_parameters",
  "version": "5.0.1",
  "name": "generalsearchparams",
  "description": "",
  "defaultDescription": true,
  "searchParameters": {
    "version": "5.0.1",
    "precursorAccuracyType": "PPM",
    "fragmentAccuracyType": "PPM",
    "precursorTolerance": 10.0,
    "fragmentIonMZTolerance": 10.0,
    "modificationParameters": {
      "fixedModifications": [],
      "variableModifications": [],
      "refinementVariableModifications": [],
      "refinementFixedModifications": [],
      "colors": {},
      "backUp": {},
      "id": 0
    },
    "digestionParameters": {
      "cleavageParameter": "enzyme",
      "enzymes": [
        {
          "name": "Trypsin",
          "aminoAcidBefore": [
            "R",
            "K"
          ],
          "aminoAcidAfter": [],
          "restrictionBefore": [],
          "restrictionAfter": [
            "P"
          ],
          "cvTerm": {
            "ontology": "PSI-MS",
            "accession": "MS:1001251",
            "name": "Trypsin",
            "id": 0
          },
          "id": 0
        }
      ],
      "nMissedCleavages": {
        "Trypsin": 2
      },
      "specificity": {
        "Trypsin": "specific"
      },
      "id": 0
    },
    "forwardIons": [
      1
    ],
    "rewindIons": [
      4
    ],
    "minChargeSearched": 2,
    "maxChargeSearched": 4,
    "minIsotopicCorrection": 0,
    "maxIsotopicCorrection": 1,
    "refMass": 2000.0,
    "algorithmParameters": {
      "1": {
        "type": "com.compomics.util.parameters.identification.tool_specific.OmssaParameters",
        "data": {
          "maxEValue": 100.0,
          "hitListLength": 10,
          "minimalChargeForMultipleChargedFragments": 3,
          "minPeptideLength": 8,
          "maxPeptideLength": 30,
          "removePrecursor": false,
          "scalePrecursor": true,
          "estimateCharge": true,
          "selectedOutput": "OMX",
          "memoryMappedSequenceLibraries": false,
          "neutronThreshold": 1446.94,
          "lowIntensityCutOff": 0.0,
          "highIntensityCutOff": 0.2,
          "intensityCutOffIncrement": 5.0E-4,
          "singleChargeWindow": 27,
          "doubleChargeWindow": 14,
          "nPeaksInSingleChargeWindow": 2,
          "nPeaksIndoubleChargeWindow": 2,
          "maxHitsPerSpectrumPerCharge": 30,
          "nAnnotatedMostIntensePeaks": 6,
          "minAnnotatedPeaks": 2,
          "minPeaks": 4,
          "cleaveNtermMethionine": true,
          "maxMzLadders": 128,
          "maxFragmentCharge": 2,
          "fractionOfPeaksForChargeEstimation": 0.95,
          "determineChargePlusOneAlgorithmically": true,
          "searchPositiveIons": true,
          "minPrecPerSpectrum": 1,
          "searchForwardFragmentFirst": false,
          "searchRewindFragments": true,
          "maxFragmentPerSeries": 100,
          "useCorrelationCorrectionScore": true,
          "consecutiveIonProbability": 0.5,
          "iterativeSequenceEvalue": 0.0,
          "iterativeReplaceEvalue": 0.0,
          "iterativeSpectrumEvalue": 0.01,
          "noProlineRuleSeries": [],
          "ptmIndexes": {},
          "id": 0
        }
      },
      "33": {
        "type": "com.compomics.util.parameters.identification.tool_specific.MetaMorpheusParameters",
        "data": {
          "minPeptideLength": 8,
          "maxPeptideLength": 30,
          "searchType": "Classic",
          "totalPartitions": 1,
          "dissociationType": "HCD",
          "maxModsForPeptide": 2,
          "initiatorMethionineBehavior": "Variable",
          "scoreCutoff": 5.0,
          "useDeltaScore": false,
          "fragmentationTerminus": "Both",
          "maxFragmentSize": 30000.0,
          "massDiffAcceptorType": "OneMM",
          "writeMzId": true,
          "writePepXml": false,
          "useProvidedPrecursorInfo": true,
          "doPrecursorDeconvolution": true,
          "deconvolutionIntensityRatio": 3.0,
          "deconvolutionMassTolerance": 4.0,
          "deconvolutionMassToleranceType": "PPM",
          "trimMs1Peaks": false,
          "trimMsMsPeaks": true,
          "numberOfPeaksToKeepPerWindow": 200,
          "minAllowedIntensityRatioToBasePeak": 0.01,
          "normalizePeaksAcrossAllWindows": false,
          "modPeptidesAreDifferent": false,
          "noOneHitWonders": false,
          "searchTarget": true,
          "decoyType": "None",
          "maxModificationIsoforms": 1024,
          "minVariantDepth": 1,
          "maxHeterozygousVariants": 4,
          "runGptm": false,
          "gPtmCategories": [
            "Common_Biological",
            "Common_Artifact",
            "Metal"
          ],
          "id": 0
        }
      },
      "2": {
        "type": "com.compomics.util.parameters.identification.tool_specific.XtandemParameters",
        "data": {
          "maxEValue": 0.01,
          "outputResults": "all",
          "dynamicRange": 100.0,
          "nPeaks": 50,
          "minPrecursorMass": 500.0,
          "minFragmentMz": 200.0,
          "minPeaksPerSpectrum": 5,
          "proteinQuickAcetyl": true,
          "quickPyrolidone": true,
          "refine": true,
          "refineSemi": false,
          "refinePointMutations": false,
          "refineSpectrumSynthesis": true,
          "refineUnanticipatedCleavages": true,
          "refineSnaps": true,
          "maximumExpectationValueRefinement": 0.01,
          "potentialModificationsForFullRefinment": false,
          "skylinePath": "",
          "outputProteins": true,
          "outputSequences": false,
          "outputSpectra": true,
          "outputHistograms": false,
          "stpBias": false,
          "useNoiseSuppression": false,
          "proteinPtmComplexity": 6.0,
          "parentMonoisotopicMassIsotopeError": true,
          "id": 0
        }
      },
      "3": {
        "type": "com.compomics.util.parameters.identification.tool_specific.PepnovoParameters",
        "data": {
          "hitListLength": 10,
          "estimateCharge": true,
          "correctPrecursorMass": false,
          "discardLowQualitySpectra": true,
          "fragmentationModel": "CID_IT_TRYP",
          "generateQuery": false,
          "id": 0
        }
      },
      "4": {
        "type": "com.compomics.util.parameters.identification.tool_specific.AndromedaParameters",
        "data": {
          "maxPeptideMass": 4600.0,
          "maxCombinations": 250,
          "topPeaks": 8,
          "topPeaksWindow": 100,
          "includeWater": true,
          "includeAmmonia": true,
          "dependentLosses": true,
          "fragmentAll": false,
          "empiricalCorrection": true,
          "higherCharge": true,
          "fragmentationMethod": "CID",
          "maxNumberOfModifications": 5,
          "minPeptideLengthNoEnzyme": 8,
          "maxPeptideLengthNoEnzyme": 30,
          "equalIL": false,
          "numberOfCandidates": 10,
          "ptmIndexes": {},
          "decoyMode": "none",
          "id": 0
        }
      },
      "5": {
        "type": "com.compomics.util.parameters.identification.tool_specific.MsAmandaParameters",
        "data": {
          "generateDecoy": false,
          "reportBothBestHitsForTD": true,
          "instrumentID": "b, y",
          "maxRank": 10,
          "monoisotopic": true,
          "lowMemoryMode": true,
          "performDeisotoping": true,
          "maxModifications": 3,
          "maxVariableModifications": 4,
          "maxModificationSites": 6,
          "maxNeutralLosses": 1,
          "maxNeutralLossesPerModification": 2,
          "minPeptideLength": 8,
          "maxPeptideLength": 30,
          "maxLoadedProteins": 100000,
          "maxLoadedSpectra": 2000,
          "outputFormat": "csv",
          "id": 0
        }
      },
      "7": {
        "type": "com.compomics.util.parameters.identification.tool_specific.MsgfParameters",
        "data": {
          "searchDecoyDatabase": false,
          "instrumentID": 3,
          "fragmentationType": 3,
          "protocol": 0,
          "minPeptideLength": 8,
          "maxPeptideLength": 30,
          "numberOfSpectrumMarches": 10,
          "additionalOutput": false,
          "numberTolerableTermini": 2,
          "numberOfModificationsPerPeptide": 2,
          "id": 0
        }
      },
      "8": {
        "type": "com.compomics.util.parameters.identification.tool_specific.DirecTagParameters",
        "data": {
          "ticCutoffPercentage": 100.0,
          "maxPeakCount": 100,
          "numIntensityClasses": 3,
          "adjustPrecursorMass": false,
          "minPrecursorAdjustment": -0.5,
          "maxPrecursorAdjustment": 1.5,
          "precursorAdjustmentStep": 0.1,
          "numChargeStates": 3,
          "outputSuffix": "",
          "useChargeStateFromMS": true,
          "duplicateSpectra": true,
          "deisotopingMode": 0,
          "isotopeMzTolerance": 0.25,
          "complementMzTolerance": 0.1,
          "tagLength": 4,
          "maxDynamicMods": 2,
          "maxTagCount": 10,
          "intensityScoreWeight": 1.0,
          "mzFidelityScoreWeight": 1.0,
          "complementScoreWeight": 1.0,
          "variableModifications": [],
          "id": 0
        }
      },
      "10": {
        "type": "com.compomics.util.parameters.identification.tool_specific.CometParameters",
        "data": {
          "numberOfSpectrumMatches": 10,
          "maxVariableMods": 10,
          "requireVariableMods": false,
          "minPeaks": 10,
          "minPeakIntensity": 0.0,
          "removePrecursor": 0,
          "removePrecursorTolerance": 1.5,
          "lowerClearMzRange": 0.0,
          "upperClearMzRange": 0.0,
          "enzymeType": 2,
          "isotopeCorrection": 1,
          "minPrecursorMass": 600.0,
          "maxPrecursorMass": 5000.0,
          "maxFragmentCharge": 3,
          "removeMethionine": false,
          "batchSize": 0,
          "theoreticalFragmentIonsSumOnly": false,
          "fragmentBinOffset": 0.01,
          "useSparseMatrix": true,
          "selectedOutputFormat": "PepXML",
          "printExpectScore": true,
          "minPeptideLength": 8,
          "maxPeptideLength": 30,
          "id": 0
        }
      },
      "13": {
        "type": "com.compomics.util.parameters.identification.tool_specific.MyriMatchParameters",
        "data": {
          "minPeptideLength": 8,
          "maxPeptideLength": 30,
          "numberOfSpectrumMatches": 10,
          "ticCutoffPercentage": 0.98,
          "maxDynamicMods": 2,
          "minTerminiCleavages": 2,
          "minPrecursorMass": 600.0,
          "maxPrecursorMass": 5000.0,
          "useSmartPlusThreeModel": false,
          "computeXCorr": false,
          "numIntensityClasses": 3,
          "classSizeMultiplier": 2,
          "numberOfBatches": 50,
          "lowerIsotopeCorrection": -1,
          "upperIsotopeCorrection": 2,
          "fragmentationRule": "CID",
          "maxPeakCount": 300,
          "outputFormat": "mzIdentML",
          "id": 0
        }
      },
      "27": {
        "type": "com.compomics.util.parameters.identification.tool_specific.PNovoParameters",
        "data": {
          "numberOfPeptides": 10,
          "lowerPrecursorMass": 300,
          "upperPrecursorMass": 5000,
          "acticationType": "HCD",
          "id": 0
        }
      },
      "28": {
        "type": "com.compomics.util.parameters.identification.tool_specific.TideParameters",
        "data": {
          "fastIndexFolderName": "fasta-index",
          "maxVariableModificationsPerPeptide": 255,
          "maxVariableModificationsPerTypePerPeptide": 2,
          "minPeptideLength": 6,
          "maxPeptideLength": 30,
          "minPrecursorMass": 200.0,
          "maxPrecursorMass": 7200.0,
          "decoyFormat": "none",
          "keepTerminalAminoAcids": "NC",
          "decoySeed": 1,
          "outputFolderName": "crux-output",
          "printPeptides": false,
          "verbosity": 30,
          "monoisotopicPrecursor": true,
          "clipNtermMethionine": false,
          "digestionType": "full-digest",
          "computeSpScore": false,
          "numberOfSpectrumMatches": 10,
          "computeExactPValues": false,
          "minSpectrumMz": 0.0,
          "minSpectrumPeaks": 20,
          "spectrumCharges": "all",
          "removePrecursor": false,
          "removePrecursorTolerance": 1.5,
          "printProgressIndicatorSize": 1000,
          "useFlankingPeaks": false,
          "useNeutralLossPeaks": false,
          "mzBinWidth": 0.02,
          "mzBinOffset": 0.0,
          "concatenateTargetDecoy": false,
          "textOutput": true,
          "sqtOutput": false,
          "pepXmlOutput": false,
          "mzidOutput": false,
          "pinOutput": false,
          "removeTempFolders": true,
          "id": 0
        }
      },
      "29": {
        "type": "com.compomics.util.parameters.identification.tool_specific.NovorParameters",
        "data": {
          "fragmentationMethod": "HCD",
          "massAnalyzer": "FT",
          "id": 0
        }
      }
    },
    "flanking": false,
    "id": 0
  },
  "annotationParameters": {
    "yAxisZoomExcludesBackgroundPeaks": true,
    "showAllPeaks": false,
    "intensityThresholdType": "percentile",
    "intensityLimit": 0.75,
    "automaticAnnotation": true,
    "selectedIonsMap": {
      "RELATED_ION": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18
      ],
      "TAG_FRAGMENT_ION": [
        1,
        4
      ],
      "IMMONIUM_ION": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20
      ],
      "PRECURSOR_ION": [
        0
      ],
      "REPORTER_ION": [],
      "PEPTIDE_FRAGMENT_ION": [
        1,
        4
      ]
    },
    "neutralLossesList": [
      {
        "composition": {
          "atomChain": [
            {
              "atomSymbol": "H",
              "isotope": 0,
              "id": 0
            },
            {
              "atomSymbol": "H",
              "isotope": 0,
              "id": 0
            },
            {
              "atomSymbol": "O",
              "isotope": 0,
              "id": 0
            }
          ],
          "mass": -1.0,
          "id": 0
        },
        "name": "H2O",
        "fixed": false,
        "aminoAcids": [
          "D",
          "E",
          "S",
          "T"
        ],
        "id": 0
      },
      {
        "composition": {
          "atomChain": [
            {
              "atomSymbol": "N",
              "isotope": 0,
              "id": 0
            },
            {
              "atomSymbol": "H",
              "isotope": 0,
              "id": 0
            },
            {
              "atomSymbol": "H",
              "isotope": 0,
              "id": 0
            },
            {
              "atomSymbol": "H",
              "isotope": 0,
              "id": 0
            }
          ],
          "mass": -1.0,
          "id": 0
        },
        "name": "NH3",
        "fixed": false,
        "aminoAcids": [
          "K",
          "N",
          "Q",
          "R"
        ],
        "id": 0
      }
    ],
    "neutralLossesAuto": true,
    "reporterIons": true,
    "relatedIons": true,
    "fragmentIonAccuracy": 10.0,
    "fragmentIonPpm": true,
    "showForwardIonDeNovoTags": false,
    "showRewindIonDeNovoTags": false,
    "deNovoCharge": 1,
    "tiesResolution": "mostAccurateMz",
    "id": 0
  },
  "sequenceMatchingParameters": {
    "sequenceMatchingType": "indistiguishableAminoAcids",
    "limitX": 0.25,
    "enzymaticTagsOnly": false,
    "maxPtmsPerTagPeptide": 3,
    "minAminoAcidScore": 30,
    "minTagLength": 3,
    "id": 0
  },
  "peptideVariantsParameters": {
    "variantType": "NO_VARIANT",
    "nVariants": 0,
    "nAaDeletions": 0,
    "nAaInsertions": 0,
    "nAaSubstitutions": 0,
    "nAaSwap": 0,
    "aaSubstitutionMatrix": {
      "name": "No Substitution",
      "description": "No substitution",
      "substitutions": {},
      "reverseMap": {},
      "id": 0
    },
    "fixedVariants": {},
    "id": 0
  },
  "geneParameters": {
    "autoUpdate": true,
    "useGeneMapping": true,
    "id": 0
  },
  "psmScoringParameters": {
    "spectrumMatchingScores": {
      "3": [
        1
      ],
      "8": [
        1
      ],
      "27": [
        1
      ]
    },
    "defaultScores": [
      -1
    ],
    "minDecoysInBin": 10,
    "id": 0
  },
  "peptideAssumptionFilter": {
    "minPepLength": 8,
    "maxPepLength": 30,
    "maxMassDeviation": 10.0,
    "isPpm": true,
    "unknownModification": true,
    "minIsotopes": 0,
    "maxIsotopes": 1,
    "id": 0
  },
  "modificationLocalizationParameters": {
    "probabilisticScoreCalculation": true,
    "selectedProbabilisticScore": "PhosphoRS",
    "dScoreThreshold": 95.0,
    "probabilisticScoreThreshold": 95.0,
    "probabilisticScoreNeutralLosses": false,
    "sequenceMatchingParameters": {
      "sequenceMatchingType": "aminoAcid",
      "limitX": 0.25,
      "enzymaticTagsOnly": false,
      "maxPtmsPerTagPeptide": 3,
      "minAminoAcidScore": 30,
      "minTagLength": 3,
      "id": 0
    },
    "alignNonConfidentModifications": true,
    "id": 0
  },
  "proteinInferenceParameters": {
    "modificationRefinement": true,
    "simplifyProteinGroups": true,
    "simplifyGroupsEvidence": true,
    "simplifyGroupsConfidence": true,
    "simplifyGroupsEnzymaticity": true,
    "simplifyGroupsVariants": true,
    "confidenceThreshold": 0.05,
    "id": 0
  },
  "idValidationParameters": {
    "defaultProteinFDR": 1.0,
    "defaultPeptideFDR": 1.0,
    "defaultPsmFDR": 1.0,
    "validationQCPreferences": {
      "dbSize": false,
      "firstDecoy": true,
      "confidenceMargin": 1.0,
      "id": 0
    },
    "id": 0
  },
  "fractionParameters": {
    "proteinConfidenceMwPlots": 95.0,
    "fractionMolecularWeightRanges": {},
    "id": 0
  },
  "fastaParameters": {
    "targetDecoy": true,
    "decoyFlag": "_REVERSED",
    "decoySuffix": true,
    "targetDecoyFileNameTag": "_concatenated_target_decoy",
    "id": 0
  },
  "id": 0
}
[mysearchparameters.zip](https://github.com/compomics/peptide-shaker/files/5541270/mysearchparameters.zip)

**Comment by hbarsnes** [comment]
I would recommend having a look at the fragment tolerance value, as 10 ppm may be too restrictive. In the old version the default was 0.5 Da. If this does not make a difference you can always share the spectrum and FASTA files with me at harald.barsnes@gmail.com.

**Comment by umutcakir** [comment]
Yes, it works now. Thank you for your reply.
