### ISSUE TITLE
custom export

### ISSUE THREAD

**Issue by hale94** [compomics/peptide-shaker#435]
when I try to create a custom export protocol on v 2.0.7 I get the following error message and the protocol is not saved

An error occurred: C:\Users\John\peptideshaker\exportFactory.cus (Access is denied)
If the problem persists please contact the developers.

Any help would be appreciated.

**Comment by hbarsnes** [comment]
You need to have write access to the C:\Users\John\peptideshaker folder. If this is not the case, and it cannot be changed, you can change the temp folders via the PeptideShaker Welcome dialog > Settings & Help > Settings > Resource Settings.

**Comment by hale94** [comment]
I have write privileges to that folder. The new version (2.0.8) does not save custom exports either.

**Comment by hbarsnes** [comment]
> I have write privileges to that folder. The new version (2.0.8) does not save custom exports either.

Creating custom exports work fine on my side. Could it be that you have more than one PeptideShaker instance running at the same time?

And did you try redirecting the export folder just to see if that made a difference?

**Comment by hbarsnes** [comment]
We just released PeptideShaker v2.0.15 that restores the saving of the custom exports. I hope you were also able to solve the access denied issue? If not, please let us know and we'll open the issue.
