### ISSUE TITLE
Can filtered results be loaded into PeptideShaker?

### ISSUE THREAD

**Issue by danielgeiszler** [compomics/peptide-shaker#441]
Hi,

I already have filtered and validated PSM lists and I was hoping to take advantage of some of your visualization tools. Is there any way to load fully processed PSM lists into PeptideShaker? And if not, is this something you’re planning on supporting in the future?

**Comment by hbarsnes** [comment]
I'm afraid this is not supported at the moment as all of the loaded results have to be processed and unified before being displayed.

May I ask where the data you want to load comes from? Would it be an option to redo the filtering in PeptideShaker?

And are there any visualization options in PeptideShaker that you are particular interested in?

**Comment by danielgeiszler** [comment]
This is from FragPipe. Unfortunately, we need to use the Prophets for the filtering here.

There wasn't anything in particular, I was just poking around to see what was available and convenient, and it looked like there was a lot of functionality here.

Thanks for your time and the fast response! Cheers.
