### ISSUE TITLE
Error ocurred: null

### ISSUE THREAD

**Issue by jackframar** [compomics/peptide-shaker#442]
I am running into this issue every time I try to import data into the peptideshaker 2.0.11

Thu Feb 18 23:55:56 EST 2021        File import completed. 855177 first hits imported (8440976 total) from 1986661 spectra.
Thu Feb 18 23:55:56 EST 2021        [844417 first hits passed the initial filtering]
Thu Feb 18 23:56:00 EST 2021        Computing assumptions probabilities.
Thu Feb 18 23:56:04 EST 2021        Saving assumptions probabilities, selecting best match, scoring modification localization.
Thu Feb 18 23:56:07 EST 2021        Importing Data Canceled!
Thu Feb 18 23:56:08 EST 2021        An error occurred: null
Thu Feb 18 23:56:08 EST 2021        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Can you please help me fixing this? Thank you

**Comment by hbarsnes** [comment]
Can you take a look at the PeptideShaker error log? You'll find it via the Welcome dialog > Settings & Help > Help > Bug Report. It should hopefully provide us with more information about the source of the issue.

**Comment by jackframar** [comment]
Hi Harald,

I have zero experience in java so looking at the log doesn't tell me
anything but it certainly will to you. I copied here the most recent error
string. Thank you so much for your help!

Jackeline

 PeptideShaker.log
<https://drive.google.com/file/d/1ScHxk912BsQunCy08ZFCM-mrQjPAB3DY/view?usp=drive_web>

**Comment by hbarsnes** [comment]
Thanks for sharing the log file! I'm afraid this is a known error with the database backend that we are currently struggling to fix. The only known workaround at the moment is to increase the amount of memory given to PeptideShaker. This can be done via the Welcome dialog > Settings & Help > Settings >Java Settings.

I will let you know when we managed to solve the issue and a new version is available.

**Comment by jackframar** [comment]
Thanks for letting me know. I do have a stupid question about increasing
the memory as i am not sure what I am supposed to do or what number to
change. I have a 16 GB Ram. Could you give detailed instructions?
Sorry for the extra work. This is not my area of expertise at all.
Thanks!!

Jackeline

**Comment by jackframar** [comment]
Nevermind. I found where I needed to change it! Thanks!
