### ISSUE TITLE
MzidCLI error Generating the mzID file

### ISSUE THREAD

**Issue by KunathBJ** [compomics/peptide-shaker#443]
Hello,

I've run SearchGUI-3.3.20 and PeptideShaker-1.16.45 successfully on a centos server.
I used Xtandem, MSGF+ and comet as search engine and could generate the reports without any problem.

I've recently tried to run the MzidCLI but I have an error message with not much information in there.
Could you adivse me what I might have done wrong here please?

The command and error message are:

```
java -Xmx${MEM}G -cp $PS_DIR/PeptideShaker-1.16.45.jar eu.isas.peptideshaker.cmd.MzidCLI \
>     -in "$OUT_DIR/${PREFIX}.cpsx.zip" \
>     -output_file "$OUT_DIR./${PREFIX}.cpsz.mzid " \
>     -contact_first_name Test \
>     -contact_last_name Test \
>     -contact_email Test \
>     -contact_address Test \
>     -organization_name Test \
>     -organization_email Test \
>     -organization_address Test
>
> done
```

```
Wed Feb 24 13:58:03 CET 2021 Unzipping sample.1228_9.cpsx.zip. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
10% 20% 30% 40% 90%
Wed Feb 24 13:58:27 CET 2021 Protein database 1228_9_concatenated_target_decoy.fasta.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Wed Feb 24 13:58:32 CET 2021 An error occurred while generating the mzid file.
```

Thanks a lot for your help!!
Take care,

Ben

**Comment by hbarsnes** [comment]
Hi Ben,

There should be more information in the PeptideShaker log file. You'll find it in the PeptideShaker-X.Y.Z\resources folder. The file is called PeptideShaker.log. Hopefully it will shed some more light on the root of the problem.

Best regards,
Harald

**Comment by KunathBJ** [comment]
Hi Harald,

I had to rerun it couple of times to try to find something. There was nothing in the resources folder for that step, but if I add the command -log , I have a log /sample.
So here is what I have in there:

```
Thu Feb 25 08:26:52 CET 2021: PeptideShaker version 1.16.45.
Memory given to the Java virtual machine: 61084270592.
Total amount of memory in the Java virtual machine: 2024275968.
Free memory: 2003136632.
Java version: 1.8.0_162.
Reindexing: 20191203_NJ_PW_DKK082_68.mgf. (changes in the file detected)
java.io.FileNotFoundException: /mnt/isilon/projects/ecosystem_biology/MiBiPa/metaP/1228_9/1228_9.out./sample.1228_9.cpsz.mzid  (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at eu.isas.peptideshaker.export.MzIdentMLExport.<init>(MzIdentMLExport.java:278)
        at eu.isas.peptideshaker.export.MzIdentMLExport.<init>(MzIdentMLExport.java:224)
        at eu.isas.peptideshaker.cmd.CLIExportMethods.exportMzId(CLIExportMethods.java:365)
        at eu.isas.peptideshaker.cmd.MzidCLI.call(MzidCLI.java:178)
        at eu.isas.peptideshaker.cmd.MzidCLI.main(MzidCLI.java:296)
```

Thanks a lot again,
Ben

**Comment by KunathBJ** [comment]
Additionally, I have an intermediate question regarding mzid in PeptideShaker:
Will the .mzid output file be different if the search has been done with for example, 2 search engines or 3 search engines?
Will the way the score is written/ the format of the output file different?

Thanks a lot,
Ben

**Comment by hbarsnes** [comment]
> FileNotFoundException: /mnt/isilon/projects/ecosystem_biology/MiBiPa/metaP/1228_9/1228_9.out./sample.1228_9.cpsz.mzid  (No such file or directory)

And does that folder exist? I note that there is a rather strange folder name in there, i.e. "1228_9.out."? Please check that the folder where you're writing the mzid file to exists, as it will not be created as part of the export itself.

> Will the .mzid output file be different if the search has been done with for example, 2 search engines or 3 search engines?
Will the way the score is written/ the format of the output file different?

PeptideShaker combines the search results from the individual search engines, generally picking the best result across the search engines for each peptide to spectrum match (PSM). Thus, using different search engines, or different combinations of search engines, can impact what is considered as the best PSM.

The way the scores are written and the format of the output file will however not be affected as this is always based on the combined score which is of the same type and format. You will however also get the individual search engine scores as additional information for each PSM, and this list will of course vary depending on the search engines used.

**Comment by KunathBJ** [comment]
Hello Harald,

Thanks a lot for the additional information. That's perfect !!

For the issue, there was indeed an issue with the folder name. Sorry about that.
It all works just fine now.

Thanks again a lot for your help.
Take care,

Ben
