### ISSUE TITLE
OX as part of taxonomy

### ISSUE THREAD

**Issue by jcanderan** [compomics/peptide-shaker#444]
Is there any chance to include OX (from uniprot header) as part of the taxonomy or else as its own column in the output reports? For example: Bacteroides fragilis str. 3988T(B)14 (OX=1339315) or whatever would be most appropriate.

Thanks!

**Comment by hbarsnes** [comment]
Just released PeptideShaker v2.0.16 which includes the organism identifier, i.e. content of the OX tag in UniProt headers, as a separate columns in the protein exports. Please let me know if it does not work as wanted, and I'll reopen the issue.
