### ISSUE TITLE
PeptideShaker Protein Grouping

### ISSUE THREAD

**Issue by KunathBJ** [compomics/peptide-shaker#446]
Hello,

Not really an issue but more a question about something I never really noticed before since I collapse my identified proteins into functional groups.
But when I look at the Default Protein Report from PeptideShaker, my Main Accession column contains multiple time the same protein ID. 
How is this possible? The protein group column doesn't contain the exact same list of protein but there is a certain overlap. Aren't those different lines supposed to be only one bigger protein group with only one main accession?

I couldn't find the explication on the grouping method in PeptideShaker. That's why I ask here. Hope I'm not too much on the wrong place.

Sorry for the basic question and thanks in advance for your help,

Ben

**Comment by hbarsnes** [comment]
Hi Ben,

The same protein accession number can occur more than once in the main accession column when it is part of more than one protein group. This can for example happen if the protein has a set of peptides that it shares with other proteins (thus creating one protein group), while it also has at least one peptide that is unique to the given protein (creating a second protein group).

For the latter group there will of course only be one main accession, as there is only one protein, but for the second group a group representative has to be selected. There are no clear "rules" for how to select this representative. One could for example pick the one with the most protein evidence in UniProt or the one with the most peptides mapping to it etc. But no matter the approach there is no guarantee that the protein it not already selected as the group representative for another group.

Note also that there is no guarantee that members of the same protein group are similar (beyond sharing sharing one or more peptides). Hence, one cannot assume that all of the proteins in the same group have the same function or are linked to the same biological processes. This has to be evaluated for each group, although the PI (protein inference) column is at least trying to help you with this, as it tries to give clues with regards to how similar the proteins in the group are. Note that this kind of categorizing should be taken with a grain of salt though. And in any case, relying on only the group representatives in the follow-up analysis will always be problematic with regards to the interpretation.

You can find more information in our tutorial material (https://www.compomics.com/bioinformatics-for-proteomics). See the section about "Protein Inference" on page 24 in the chapter called "1.4 Browsing Identification Results". 

Best regards,
Harald
