### ISSUE TITLE
An error occurred: Cannot invoke "com.compomics.util.experiment.identification.matches.SpectrumMatch.getPeptideAssumptionsMap()" because "spectrumMatch" is null

### ISSUE THREAD

**Issue by Jacky11** [compomics/peptide-shaker#450]
Hello,

I tried to use peptideshaker from 3 replicates in 2 biological conditions to identify proteins of helicobacter pylori

I tried before with MaxQuant, but had very little protein identified, so I wanted to see with SearchGUI and PeptideShaker if I can find more protein using non-specific enzyme search.

SearchGUI seems to have worked, but PeptideShaker did not automatically launch following SearchGUI. As I was able to get a number of results so I used PeptideShaker from those results. Unfortunately, it doesn't work out and so I don't have any results. But it seems SearchGUI provided many results... Could you help me find the solution? I am a little lost.

Please find here the reports:
[peptideshaker_report.txt](https://github.com/compomics/peptide-shaker/files/6231890/peptideshaker_report.txt)
[searchgui_report.txt](https://github.com/compomics/peptide-shaker/files/6231891/searchgui_report.txt)

Many thanks in advance !

**Comment by hbarsnes** [comment]
Could you please also share the PeptideShaker log file? You'll find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report. It will hopefully make it easier to locate the root of the problem.

**Comment by Jacky11** [comment]
Hello,

Here is the log file:
[PeptideShaker 2.0.18 log.txt](https://github.com/compomics/peptide-shaker/files/6234689/PeptideShaker.2.0.18.log.txt)

Thanks !

**Comment by Jacky11** [comment]
Interestingly, when I used only the novor results (i.e. files .novor.csv.gz), PeptideShaker works.

**Comment by hbarsnes** [comment]
I'm afraid you've come across a known (but yet unsolved) issue with the PeptideShaker backend. The only known fix at the moment is to increase the amount of memory given to PeptideShaker. This you can do via the Welcome dialog > Settings & Help > Settings > Java Settings.

The reason why it works if only loading the Novor results is that this requires less memory, thus avoiding the issue.

**Comment by Jacky11** [comment]
Thank you so much Harald ! It works for Comet outputs after I change 4GB to 16GB and it is pretty nice ! I am testing to merge all outputs (finger cross).
