### ISSUE TITLE
cms file not found error

### ISSUE THREAD

**Issue by bernt-matthias** [compomics/peptide-shaker#454]
Hi @hbarsnes 

Just tested the latest PS release (https://github.com/bioconda/bioconda-recipes/pull/28155) with Galaxy and got 

```
java.io.FileNotFoundException: /tmp/tmpti3s3okg/job_working_directory/000/2/working/PeptideShakerCLI/.PeptideShaker_unzip_temp/searchgui_input_PeptideShaker_temp/data/searchgui_tinyspectra1.cms (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileReader.<init>(CmsFileReader.java:91)
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileIterator.<init>(CmsFileIterator.java:43)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileIterator.getMsFileIterator(MsFileIterator.java:74)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.writeCmsFile(MsFileHandler.java:211)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.register(MsFileHandler.java:148)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:1038)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:243)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1389)
```

in addition to https://github.com/compomics/peptide-shaker/issues/448

The directory `.PeptideShaker_unzip_temp` does not extist.

command line is:

```
mkdir output_reports && 
cwd=`pwd` && 
export HOME=$cwd &&  
ln -s '/tmp/tmpti3s3okg/files/1/f/4/dataset_1f4cc036-a677-4525-b78f-7b3675d4939f.dat' searchgui_input.zip &&  
jar xvf searchgui_input.zip SEARCHGUI_IdentificationParameters.par &&   
peptide-shaker -Djava.awt.headless=true eu.isas.peptideshaker.cmd.PeptideShakerCLI -gui 0 -temp_folder $cwd/PeptideShakerCLI -use_log_folder 0 -reference 'Galaxy_Experiment_2021042310471619167647' -identification_files $cwd/searchgui_input.zip -id_params $cwd/SEARCHGUI_IdentificationParameters.par  -out $cwd/peptideshaker_output.psdb  -threads "${GALAXY_SLOTS:-12}"   -output_file $cwd/output.mzid -include_sequences 0 -contact_first_name "Proteomics" -contact_last_name "Galaxy" -contact_email "galaxyp@umn.edu" -contact_address "galaxyp@umn.edu" -organization_name "University of Minnesota" -organization_email "galaxyp@umn.edu" -organization_address "Minneapolis, MN 55455, Vereinigte Staaten"
```

**Comment by hbarsnes** [comment]
If .PeptideShaker_unzip_temp does not exist, then were is searchgui_input.zip unzipped? Does the PeptideShakerCLI folder exist?

**Comment by hbarsnes** [comment]
The following command line works fine for me (outside of Galaxy):

`java -cp PeptideShaker-2.0.20.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -gui 0 -temp_folder C:\Users\Harald\Desktop\temp1 -use_log_folder 0 -reference Galaxy_Experiment_2021042310471619167647 -identification_files C:\Users\Harald\Desktop\temp2\searchgui_out.zip -out C:\Users\Harald\Desktop\temp1\out\peptideshaker_output.psdb`

**Comment by bernt-matthias** [comment]
> If .PeptideShaker_unzip_temp does not exist, then where is searchgui_input.zip unzipped? 

I do not know. After PS exits I can not find any unzipped files (in particular not the missing one). 

But the output indicates that its unzipped: 

```
Fri Apr 23 10:47:29 CEST 2021 Unzipping searchgui_input.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
```

> Does the PeptideShakerCLI folder exist?

Yes.

**Comment by hbarsnes** [comment]
Strange. Hopefully @CarlosHorro can take a look at it next week.

**Comment by CarlosHorro** [comment]
Hi @bernt-matthias ,

I have been able to reproduce it, and, although I have to do some more tests with simpler datasets, it seems to happen when PS uses files generated by SG Galaxy tool instead of the desktop app.

I will tell more in some days.

Greetings,
Carlos

**Comment by hbarsnes** [comment]
@bernt-matthias I've just released new versions of both SearchGUI and PeptideShaker that should solve the problem. (You should only need to update PeptideShaker though.) The problem was that the cms file was outdated and had to be recreated with the new faster compression, but in the process we ended up deleting the old cms file and then trying to refer to again it a couple lines further down. Safety measures have now been out into place so that this cannot happen again.
