### ISSUE TITLE
Getting PDB data stalls for hours and uses high GPU? 

### ISSUE THREAD

**Issue by orsburn** [compomics/peptide-shaker#457]
Howdy CompOmics!
I'm having trouble generating a 3D image of any proteins in PeptideShaker 2.0.25 and I also tried 2.0.6. just to see if it was a version issue. My 1080TI GPU went to "very high power usage" according to Windows 10 Pro (64-bit) and appeared to stay there for about 6 hours but it never generated an image. I also pulled the demo data and tried to make a 3D model of one of the HeLa proteins to no avail. I'm not sure where it's getting stuck, trying to pull down PDB data or actually modeling it. I'm allowing 32GB of RAM in Java 1.8 64-bit. Any ideas would be appreciated!

**Comment by orsburn** [comment]
Thanks for checking it out! I was able to install the PDB that I needed locally, but it doesn't have quite the same power. I'll watch out for the fix.

**Comment by hbarsnes** [comment]
We've just released PeptideShaker v2.0.27 which should restore the PDB connection (by changing the web service used). Please let us know if this is not the case, and we'll reopen the issue.

If you experience other issues with the peptide to PDB mapping, please do not hesitate to open a new issue.
