### ISSUE TITLE
individual report

### ISSUE THREAD

**Issue by fazeliniah** [compomics/peptide-shaker#458]
Dear peptide-shaker team, 
Is there any way with the peptide-shaker GUI version to process MS files individually? For example, I would like to process 20 different raw files to generate 20 different reports. I know this may not be a very common use and appreciate any help. 
Thanks

**Comment by hbarsnes** [comment]
I'm afraid this is not supported in the GUI. But these types of setups is kind of what the command line has been created for. For more details please see https://github.com/compomics/peptide-shaker/issues/449#issuecomment-815684151.
