### ISSUE TITLE
TMTPro Overlabelling and Custom Modifications

### ISSUE THREAD

**Issue by emhumphries** [compomics/peptide-shaker#459]
Hi,
I am new to SearchGUI/PeptideShaker and I am really liking it, so thanks! 
I'm trying to investigate over-labelling of S, T, Y, and H using TMTpro16plex. When I search for labelling efficiency using the below parameters in SearchGUI 4.0.33, I get expected results in PeptideShaker 2.0.25.
- ThermoRawFileParser
- X!Tandem Search Engine
- Fixed mod - carbamidomethylation of C, TMTpro of K, TMTpro of peptide N-term
- Variable mod - Phosphophorylation of S
- Default settings for protease and fragmentation

However, when I add a user modification for TMTpro of phosphorylated S as a variable modification, I lose all my phosphorylation modifications and identify a small number of TMTpro-Phos-S mods. I'm assuming this is an issue with X!Tandem handling the custom modification however I've tried MS Amanda, MS-GF+ and Novor but they crash. Any suggestions on how to get around this? 
![TMTpro of Phos-S](https://user-images.githubusercontent.com/74599273/118783540-83deed00-b8d2-11eb-9c32-0b60e63457b0.png)

**Comment by hbarsnes** [comment]
Can you try simplifying the pattern for the custom TMTpro-Phos-S modification to just "S"?

**Comment by emhumphries** [comment]
I noticed that the default TMTPro of K has the modification pattern set to just "K" so I initially set the modification to just "S" for TMTpro-Phos-S and clicked okay as shown below. When I reopened the user modification, the pattern automatically reverted to the complex pattern. 
![TMTpro of Phos-S v2](https://user-images.githubusercontent.com/74599273/118895795-31411780-b94a-11eb-9c36-48cd7a01d913.png)

**Comment by hbarsnes** [comment]
Strange... I do not see this behavior myself. Can you share your modificationFactory-5.0.0.json file after adding the custom modification? You will find it in the .compomics folder in your user home folder.

**Comment by emhumphries** [comment]
Here it is as a txt as json aren't supported here. I haven't finished setting up TMTpro of Phos-H/T/Y as I wanted to test TMTpro of Phos-S. [modificationFactory-5.0.0.txt](https://github.com/compomics/peptide-shaker/files/6515046/modificationFactory-5.0.0.txt)

**Comment by hbarsnes** [comment]
I think I might understand what is happening. Could it be that you are editing the Pattern text field directly and not via the Modification Pattern dialog (i.e. the one that pops up if clicking in the Pattern text field)? If so, try to rather remove the second constraint via the Modification Pattern dialog and then click the OK button. As the patterns is not updated otherwise. I will try to make this more clear in the next release.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
