### ISSUE TITLE
New peptide shaker version doesn't open the example

### ISSUE THREAD

**Issue by deeptijk** [compomics/peptide-shaker#461]
<img width="723" alt="Screenshot 2021-05-27 at 14 56 15" src="https://user-images.githubusercontent.com/38948179/119838921-b359af00-befb-11eb-9b60-7ae1cb8e9a98.png">

How to resolve this issue. I am using the peptide shaker for the training material for PRIDE.

**Comment by hbarsnes** [comment]
I'm not able to reproduce the issue on my end. Can you please also share the PeptideShaker log file? You'll find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report.

**Comment by deeptijk** [comment]
[PeptideShaker 2.0.27 log.txt](https://github.com/compomics/peptide-shaker/files/6555466/PeptideShaker.2.0.27.log.txt)

Thank you for your reply. Here is log file.

**Comment by hbarsnes** [comment]
Can you please check your download of PeptideShaker to unsure that it contains the folder PeptideShaker-2.0.27\resources\example_dataset\data and that this folder contains the FASTA file called uniprot-human-reviewed-trypsin-november-2020_concatenated_target_decoy.fasta?

Can you also confirm that you are unzipping the PeptideShaker zip file before running the tool?

**Comment by deeptijk** [comment]
<img width="1011" alt="Screenshot 2021-05-28 at 05 07 07" src="https://user-images.githubusercontent.com/38948179/119928007-93b19d80-bf72-11eb-8cdb-51d115e8fbae.png">
Yes, it does have the file you have mentioned. 

And I have unzipped it before launching the tool. Although I couldn't launch it by clicking the jar file, I did it with the command line java -jar PeptideShaker-2.0.27.jar

**Comment by hbarsnes** [comment]
I've just released a new version of PeptideShaker solving some other issues with opening the example dataset. Can you give it a go and see if it also solves the problem on your side? (I have not been able to reproduce that particular issue though...)

**Comment by deeptijk** [comment]
I just updated the latest version, it's the same issue. I really don't understand the problem here.

**Comment by hbarsnes** [comment]
> I really don't understand the problem here.

Me neither I'm afraid. I've asked some of the other developers to have a look. Hopefully we can figure it out in the end. Maybe it's a specific issue for OS X.

**Comment by deeptijk** [comment]
Just for your information, I am using macOS Big Sur.

**Comment by hbarsnes** [comment]
The problem should now finally be fixed and we have released a new version of PeptideShaker. Please let us know if you still cannot open the example dataset, and we'll reopen the issue.

**Comment by deeptijk** [comment]
The problem is still there, it's just one step ahead, it says loading, and I left it for hours but nothing loaded.

**Comment by hbarsnes** [comment]
Can you send me the updated log file?

**Comment by hbarsnes** [comment]
Can you try deleting the file PeptideShaker-2.0.29\resources\example_dataset\data\qExactive01819.cms and then try to open the example dataset again?

**Comment by hbarsnes** [comment]
I've also just released yet another version of PeptideShaker updating the cms file. Would be great if you could try that one as well? Hopefully you will not have to delete the cms file in that one.

**Comment by deeptijk** [comment]
Ok, I have tried with and without deleting the qExactive01819.cms file and still, it is not working. 
[PeptideShaker.log](https://github.com/compomics/peptide-shaker/files/6583929/PeptideShaker.log)

**Comment by hbarsnes** [comment]
The error log you shared is for the 2.0.29 version. Did you also try the 2.0.30 version?

**Comment by deeptijk** [comment]
Yes, with both the versions. Here are two log files with/without qExactive01819.cms file.

With qExactive01819.cms - 
[PeptideShaker-1.log](https://github.com/compomics/peptide-shaker/files/6584080/PeptideShaker-1.log)

Without qExactive01819.cms -
[PeptideShaker.log](https://github.com/compomics/peptide-shaker/files/6584081/PeptideShaker.log)

**Comment by hbarsnes** [comment]
I think we've figured out that the problem is due to Java 16. Do you have older Java versions you can try instead?

**Comment by hbarsnes** [comment]
Older Java versions can be downloaded here: https://adoptopenjdk.net/releases.html

**Comment by hbarsnes** [comment]
I can confirm that the issue is indeed Java 16 (or rather a compression library we use has issues when using Java 16). At least I can now finally reproduce the issue with Java 16, but not with Java 15 and older. We'll keep searching for a proper fix, but for now, please downgrade to Java 15 or older.

**Comment by deeptijk** [comment]
Yes, finally it worked when I downgraded my java. I opened
<img width="1427" alt="Screenshot 2021-06-02 at 15 42 38" src="https://user-images.githubusercontent.com/38948179/120501179-522d5200-c3b9-11eb-8bec-27f8baf9ee08.png">
 the latest version and it worked.

**Comment by hbarsnes** [comment]
With the new releases of PeptideShaker and SearchGUI Java 16 is now also supported.

**Comment by deeptijk** [comment]
Thank you for letting me know.
