### ISSUE TITLE
target/decoy results not validated

### ISSUE THREAD

**Issue by Proteomicslab57357** [compomics/peptide-shaker#467]
\hi
while searching a sample with peptide shaker. although no significant mass shift, validation status of target/decoy results did not pass 1% . as a result 0 proteins out of 2167 were retained.

How could this problem been solved?
please see attachment screen shot
[Doc1.docx](https://github.com/compomics/peptide-shaker/files/7135401/Doc1.docx)

**Comment by hbarsnes** [comment]
I cannot really see any obvious issues from the provided screenshots, however I do see that you are using a pretty old version of PeptideShaker. I would therefore recommend that you update to the latest version and see if that solves the problem?

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
