### ISSUE TITLE
MS file exceeds memory mapped reader max buffer size.

### ISSUE THREAD

**Issue by brvpuyve** [compomics/peptide-shaker#468]
Hi,

I am trying to process large .mgf files (approximately 10Gb), but unfortunately SearhGUI crashes.
The memory assigned to Java was already increased to 250 Gb, but no luck.
Any suggestions on how to resolve this?

Best,
[SearchGUI 4.1.1 log.txt](https://github.com/compomics/peptide-shaker/files/7180197/SearchGUI.4.1.1.log.txt)
Bart

**Comment by mvaudel** [comment]
Hi Bart,

If nothing is suspicious about these mgf files (acquisition and peak-picking are ok), the low hanging fruit is to split your mgf files. I can fix our handling of the spectra to accommodate larger MS files, but I don't expect to have the time to look into it before October.

Apologies for the inconvenience,

Marc

**Comment by kbarylyuk** [comment]
Hi Marc and the team,
I am running in the same error with a roughly 5.5 Gb mzML file, and I am wondering if there has been any development going on to enable handling larger files. I am not sure if a workflow with converting the data to MGF files and then splitting them is going to be optimal in my setting, but I am happy to give it a try if you could kindly provide a bit more detailed guidance on how to do it. Thank you!
Konstantin

**Comment by mvaudel** [comment]
Hi Konstantin,

Time is flying! Apologies, I have not been able to prioritize this and am not sure when I can finally refactor this code. In the meantime splitting the file would be the way to go.

Sorry that I cannot help more at this stage,

Marc

**Comment by hbarsnes** [comment]
I've just released SearchGUI version 4.3.8 that should take care of the problem with the buffer size. If this is not the case, please let me know and I'll reopen the issue.
