### ISSUE TITLE
<CompomicsError>PeptideShaker processing canceled

### ISSUE THREAD

**Issue by quark-spec** [compomics/peptide-shaker#469]
Dear developers,

I am using PeptideShakerCLI and getting this error. I couldn't find out what is wrong from the terminal output or PeptideShaker.log. May I know what is wrong here? Thank you.

[PeptideShaker terminal log.txt](https://github.com/compomics/peptide-shaker/files/7233065/PeptideShaker.terminal.log.txt)
[PeptideShaker.log](https://github.com/compomics/peptide-shaker/files/7233066/PeptideShaker.log)

**Comment by quark-spec** [comment]
I used the GUI version and still got a similar error. It has an additional line saying `An error occurred: Index 13541452 out of bounds for length 13129569`. What exactly is this error pointing to? Thanks again.

[PeptideShaker GUI log.txt](https://github.com/compomics/peptide-shaker/files/7233103/PeptideShaker.GUI.log.txt)

**Comment by hbarsnes** [comment]
Would it be possible for you to share the data you are trying to load in PeptideShaker? If you do not want to share a link here, you can send it directly to me at harald.barsnes@gmail.com.
