### ISSUE TITLE
Gene ontology download runs for several minutes reporting errors on each file

### ISSUE THREAD

**Issue by orsburn** [compomics/peptide-shaker#471]
Hi CompOmics!
Every file I open in PeptideShaker opens up with a long string of downloads from Ensembl that it can not complete. 
![image](https://user-images.githubusercontent.com/39571544/139358170-e313813d-0722-4194-a903-38a1bbf77c9f.png)
Is it possible to deactivate it's search for these GO databases?
Thanks!
-ben

**Comment by orsburn** [comment]
Hmmm....I don't see that listed as an option in either Peptide Shaker or SearchGUI under the advanced settings on the Windows GUI. I'll keep digging for it.  Thanks for getting back to me!

**Comment by hbarsnes** [comment]
Unless you are using very old versions of SearchGUI and PeptideShaker you should have these settings available as described above. I'm attaching a screenshot of where to locate them. You will find the parameters from the dialog in which you set the search parameters.

![Identification Settings](https://user-images.githubusercontent.com/13151214/139538613-ad3e5d85-2272-43d6-835e-a77e586fa5f3.png)

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
