### ISSUE TITLE
Unable to load data

### ISSUE THREAD

**Issue by MNTsnowman** [compomics/peptide-shaker#473]
Hi

First time trying to use this, and it gives me an error telling me to make a post here... So here we are, what did I do?

Just out of curiosity, can this tool be used for exporting intensities of PTMs and the total or non-modified intensity of that same AA? That's what i need, so.

Kind Regards
Martin
[Report.txt](https://github.com/compomics/peptide-shaker/files/7565528/Report.txt)

**Comment by hbarsnes** [comment]
Hi Martin,

It seems like your pep.xml files are not supported by our software. Can I ask which search engine that was used to create these files? Maybe we can make some minor adjustments to support them. Would it be possible for you to share one of the pep.xml files?

> Just out of curiosity, can this tool be used for exporting intensities of PTMs and the total or non-modified intensity of that same AA?

No, I'm afraid this is not something we support at the moment.

Best regards,
Harald

**Comment by MNTsnowman** [comment]
Hi Harald

That explains a lot. :) It is generated by Fragpipe. Fragpipe generated multiply different pepXML files, maybe i took the wrong one?

Orriginally i was looking for a tool to perform statistical analysis of PTMs, and this came up in a search. As you can see i never got the chance to try. However, if it cannot do this, i will find another alternative. Thanks for the fast reply though. :)

Best
Martin

**Comment by hbarsnes** [comment]
Hi Martin,

> It is generated by Fragpipe. Fragpipe generated multiply different pepXML files, maybe i took the wrong one?

Could be. But pep.xml files do not always contain the same information, so it may be that we would have to change our code slightly to also support Fragpipe pep.xml files.

In any case, if our tools cannot do what you need, I will go ahead and close the issue.

Good luck on your search for alternative tools.

Best regards,
Harald
