### ISSUE TITLE
Download link is not functional

### ISSUE THREAD

**Issue by kromer-m** [compomics/peptide-shaker#474]
The download button does not work, the server is not available. Is there any other possibility how to download the program? Thanks!

**Comment by hbarsnes** [comment]
I'm afraid the server containing the downloads went down on Friday. It should hopefully be back up on Monday and the downloads should then be available again. I will keep you posted.

**Comment by hbarsnes** [comment]
I’m afraid that it is taking longer than we hoped for to get the server back online.

In the meantime you can download the latest version of PeptideShaker here:  https://iomics.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/2.2.2/PeptideShaker-2.2.2.zip

**Comment by kromer-m** [comment]
Thank you very much for a swift solution !

**Comment by hbarsnes** [comment]
The server is now finally back online and the normal links are working again.
