### ISSUE TITLE
Question: replicates, LFQ, PTM, fractions

### ISSUE THREAD

**Issue by r0620660** [compomics/peptide-shaker#475]
Hi,

I'm a starting researcher, and was recently introduced to the world of proteomics and peptide-shaker. After going through the tutorials of the comp omics pipeline, I wanted to re-analyze an ms dataset (PXD008662 on proteomXchange) in order to get quantitative on protein acetylation.  During my attempt at this analysis, I ran into certain problems for which I didn't find an answer in the tutorial. My questions are:

1) How do you analyze a dataset with multiple replicates per condition? Do you analyze these replicates all separately, or can I just perform the peptide search with all the MGF files at once?

2) How do fractions work in peptide-shaker? If I understand correctly, this is used when two runs come from the same sample, or is this meant for replicates from the same condition?
 
3) Is it possible to do an LFQ for acetylated peptides in Peptideshaker? (my goal here would be to get a list of 'confident valid' proteins with sites that are differentially acetylated)

Any help with these questions would be greatly appreciated!
 
Kind regards,
Nand

**Comment by hbarsnes** [comment]
Hi Nand,

> How do you analyze a dataset with multiple replicates per condition? Do you analyze these replicates all separately, or can I just perform the peptide search with all the MGF files at once?

This depends on whether you want to compare the results from each replicate or whether you just want a combined result. If you want to compare the results across the replicates you have to process each MGF file separately in PeptideShaker, as when loading the search results from multiple MGF files we merge the results.

> How do fractions work in peptide-shaker? If I understand correctly, this is used when two runs come from the same sample, or is this meant for replicates from the same condition?

Yes, the fraction tab in PeptideShaker is mainly intended to compare separate fractions of the same sample and is not really meant for replicates. Note also that PeptideShaker does not support the comparison of samples (potentially with multiple replicates) directly. You will have to process the results for each sample separately, export the results, and then do the comparison outside of PeptideShaker.

> Is it possible to do an LFQ for acetylated peptides in Peptideshaker? (my goal here would be to get a list of 'confident valid' proteins with sites that are differentially acetylated)

PeptideShaker focuses on identification. If you want to do LFQ you have to either combine PeptideShaker with other tools such as [moFF](https://github.com/compomics/moFF) or [FlashLFQ](https://github.com/smith-chem-wisc/FlashLFQ), or use a different tool altogether, such as [MaxQuant](https://www.maxquant.org).

Best regards,
Harald

**Comment by r0620660** [comment]
Hi Herald,

Thank you for the quick response! I do have a follow-up question for question 1 and 2.

**Comment by hbarsnes** [comment]
Hi Nand,

> So if I understand correctly, it would be allright for me to combine all the replicates of one condition, assuming I just wanted to identify the peptides in that condition, or am I wrong?

Yes, I think that should be ok. Just note that you will however lose the possibility to compare the different replicates.

> If a sample is enriched for a certain PTM using affinity chromatography (let's call it processed sample 1), and afterwards the eluent of this process is enriched for another PTM (processed sample 2), are these processed samples considered fractions?

I guess that is a matter of definition. As long as its the same sample split into multiple subsamples I think you would be correct in referring to the results as fractions.

Best regards,
Harald

**Comment by r0620660** [comment]
Hi Herald,
Thank you for all the help!
Best regards,
Nand
