### ISSUE TITLE
Error opening previous output files - "compatible versions" required

### ISSUE THREAD

**Issue by MNTNguyen** [compomics/peptide-shaker#476]
Dear all, 
I'd appreciate some help here with opening previous output files. The error is:
**"An error occuring while opening ... Please verify that the verison used to create the file is compatible with your version of Peptide Shaker."**
Sounds like the latest version of Peptide shaker cannot open those created from previous version.
I, obviously, updated Peptide Shaker over this year multiple times (as many as I was asked) and curently work with the latest version. I could not imagine that one should keep all previous versions of Peptide shaker just to open its corresponding previous output files. 
Is there any way to solve this more systematically?
Thanks a lot in advance!
Best regards,

**Comment by hbarsnes** [comment]
As far as possible we try to maintain compatibility between versions. However, sometimes this is not possible or would require a lot of work as we would have to to maintain both the old and the new code. Usually, the update of the major version number, i.e. from v1.x.x to v2.x.x signals a break in compatibility, but there may also be some exceptions where a change in the second number in the version number, i.e. from v2.0.x to v2.1.x, can also result in issues with compatibility.

In any case, there is no need for you to store all of the old versions of PeptideShaker locally, as these are all available here: https://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/. Simply choose the version you think was used to generate the given PeptideShaker project and download the file corresponding PeptideShaker-X.Y.Z.zip file.

There is of course also the option of reprocessing the input data in the most recent version of PeptideShaker, but I understand that this is often not a preferred solution.

**Comment by MNTNguyen** [comment]
hi Harald,
thanks for the quick reply.
it's at least clear that it's not on our computer settings or similar.
Anyway, it's gonna be a major problem because I don#t keep track of which
version for which output file. And I have thousands of them, too...
Best regards,
Minh

**Comment by hbarsnes** [comment]
Hi Minh,

Note that we do not break the backwards compatibility often and that you do not have to find the exact version of PeptideShaker used to create the project. If it's a project from before November last year, trying the latest version before we moved to 2.x should be enough, i.e. version 1.16.45. If it's a more recent project, you can try PeptideShaker 2.0.32. Hopefully one of these should allow you to open your old projects.

And if you still have the html report created when processing the data for the first time (it should be in the same folder as the psdb file), it will also have a section about the PeptideShaker version used. Example:

```
...

Report:
# ------------------------------------------------------------------
# PeptideShaker 2.0.30 Report File
#
# Originally saved by: Harald @ LAPTOP-92114JEJ
#                  on: 14 Jun 2021, 16:10
# ------------------------------------------------------------------

...
```

Best regards,
Harald
