### ISSUE TITLE
Installation issue of peptide shaker with Java

### ISSUE THREAD

**Issue by EmilieCarneiro** [compomics/peptide-shaker#489]
Hello, 
I am trying to install searchGui and peptide shaker on my computer (windows 11 home). However, after unzipping both folders, when I click the .jar files I get an error message saying "Java is not installed. Do you want to download the latest version of java?"
If I click yes I am redirected to download 64-bit Java for Windows Version 8 Update 341. I installed it but the error message remains. I also installed Java JDK 19 and still the error message. Any idea how I can solve this problem? Thank you for your help.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/107934660/192107475-bb26c27a-8a10-4bf1-8336-72970041884a.png">

**Comment by hbarsnes** [comment]
Please see https://github.com/compomics/searchgui/issues/329 for the follow-up of this issue.
