### ISSUE TITLE
Default Protein Reports exits with a fatal error

### ISSUE THREAD

**Issue by iquasere** [compomics/peptide-shaker#490]
Running ```java -cp PeptideShaker-2.2.12/PeptideShaker-2.2.12.jar -Xmx51200M eu.isas.peptideshaker.cmd.ReportCLI -in path/to/ps_output.psdb -out_reports path/to/out_dir -reports 9``` returns
```
Thu Sep 29 14:44:15 UTC 2022 Exporting. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd3291ad6a3, pid=29208, tid=29209
#
# JRE version: OpenJDK Runtime Environment (17.0.3) (build 17.0.3-internal+0-adhoc..src)
# Java VM: OpenJDK 64-Bit Server VM (17.0.3-internal+0-adhoc..src, mixed mode, sharing, tiered, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [sqlite-3.36.0.3-7c636d52-4f25-423e-864a-8c4c42bc83b9-libsqlitejdbc.so+0x116a3]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to //core.29208)
#
# An error report file with more information is saved as:
# //hs_err_pid29208.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```
The report is written, apparently just fine. This also happens with the ```10``` report. All other reports seem to work fine, so it seems to be related to "Default_Protein_Report"s.

**Comment by hbarsnes** [comment]
Can you try updating to a more recent Java version and see if that solves the problem?

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.

**Comment by iquasere** [comment]
Sorry, Harald, for not following up on this. I ended up just ignoring the error, as the most recent versions of peptide-shaker in Bioconda still threw this exception, while the report was generated just fine. This happened with reports 9 and 10.

**Comment by hbarsnes** [comment]
Ok, thanks for the update. I will just keep the issue closed then and maybe reopen it in the future if the problem is reported by more users.

**Comment by hbarsnes** [comment]
@esraaelmligy Can you try updating to a newer Java version and see if that solves the problem?

**Comment by esraaelmligy** [comment]
I updated to the latest java version but i still face the same error, and now when i try to rerun the old jobs again they also result in the same error.

Thu Apr 04 10:34:27 EET 2024 Exporting reports.
Thu Apr 04 10:34:27 EET 2024 Exporting Certificate of Analysis.
Thu Apr 04 10:34:27 EET 2024 Exporting Default PSM Report.
Thu Apr 04 10:34:28 EET 2024 Exporting. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3982d1fe17, pid=49677, tid=49678
#
# JRE version: OpenJDK Runtime Environment (21.0.2+13) (build 21.0.2+13-Ubuntu-120.04.1)
# Java VM: OpenJDK 64-Bit Server VM (21.0.2+13-Ubuntu-120.04.1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [sqlite-3.40.0.0-60f1b6cf-47a1-4a1d-a128-f985c150c02d-libsqlitejdbc.so+0x11e17]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/esraa/core.49677)
#
# An error report file with more information is saved as:
# /home/esraa/hs_err_pid49677.log
[2827.665s][warning][os] Loading hsdis library failed
#
# If you would like to submit a bug report, please visit:
#   Unknown
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)

**Comment by esraaelmligy** [comment]
[hs_err_pid49677.log](https://github.com/compomics/peptide-shaker/files/14864516/hs_err_pid49677.log)

This attached file is the log file generated by the error, it is to note that this is an external file and not the peptideshaker's log file
