### ISSUE TITLE
Modifications view: mirrored spectrum

### ISSUE THREAD

**Issue by szabzola** [compomics/peptide-shaker#491]
Hi, thanks for great software!
In the modifications view for a number releases, the mirrored spectrum (selecting modified and related peptide) shows really mirrored spectrum (the same spectrum on top/bottom) just labels are different.
Regards,

**Comment by hbarsnes** [comment]
Do you have an example screenshot that you can share here? Please note that these peptide-spectrum-matches can be very similar and thus look almost the same.

**Comment by szabzola** [comment]
Hi, at the moment I found only this.
In mirrored spectra beacuse of label on y2 (even if y labels ar off) all other peaks look small, I have found no way to change scaling (feature request?).
But I have chosen a different charge state for related PSM (unmodified peptide), which is completely different. Also, if I change selection in related PSM list, mirrored spectrum is not changed (peak labels may change).
Mirrored MS/MS spectra:
![image](https://user-images.githubusercontent.com/61981001/194021241-7605fba5-2dcf-4a06-b2bc-90483a6280ef.png)
Modified peptide MS/MS (+2)
![image](https://user-images.githubusercontent.com/61981001/194021418-a7cc6083-99cb-4ca6-bd36-a5b607fb9b7f.png)
Unmodified peptide MS/MS (+2)
![image](https://user-images.githubusercontent.com/61981001/194021580-a5df9a2e-bdff-4aa3-87f7-c19ea172b20e.png)

**Comment by hbarsnes** [comment]
You are correct. There was indeed a bug that resulted in the mirrored spectrum not always updating correctly. I've just released a new version (v2.2.14) which should solve the problem. Please give it a go and let me know.

As to the scaling, you can always zoom in on a wanted area by using the mouse. Simply click and drag to the right for the given area you want to zoom in on. Right-clicking will reset the zoom to the entire spectrum.

**Comment by szabzola** [comment]
Thanks, a lot, I will try it.
About zooming: in mirrored view if I zoom in on th m/z axis (which is the only zoom option) the intensity scale remains the same (unlike in singe spectrum view, when it autoscales).

**Comment by hbarsnes** [comment]
> About zooming: in mirrored view if I zoom in on the m/z axis (which is the only zoom option) the intensity scale remains the same (unlike in singe spectrum view, when it autoscales).

I think it is due to the rescaling required to make spectra comparable even if the max intensity levels are very different, as otherwise one would risk one of the spectra not being visible at all. I will look into making the scaling an option that can be turned off, as there are clearly also cases were seeing the actual intensities are preferred.

**Comment by szabzola** [comment]
Everything is just perfect, including scaling in 2.2.15.
Thank you for the really quick solutions.
