### ISSUE TITLE
Failed to put two fixed modifications

### ISSUE THREAD

**Issue by KKKKK-tech** [compomics/peptide-shaker#498]
When I using SearchGUI, I added the TMT10plex to the fixed modification. But when I run out.zip with PeptideShaker, following error occurred. How can I solve this problem?

![O@A5WONV%ERBPR)DKJ4F73Y](https://user-images.githubusercontent.com/74421386/202834513-ff5fa0c5-7af4-44af-8067-c23af1c40d6a.png)

**Comment by hbarsnes** [comment]
Thanks for letting us know. A fix is in progress, but I cannot at the moment tell you when it will be included in an official new release as it requires a lot more testing first. Perhaps @mvaudel could provide you with a beta version to test?

**Comment by KKKKK-tech** [comment]
Thanks for your reply. Looking forward to the new release! : )

**Comment by mvaudel** [comment]
Hi,
Sorry for the delay. Would you have more information on how the search parameters were designed? It seems that you are using two fixed modifications targeting lysine which is not allowed. You can add only one modification per amino acid.
When using TMT please use one modification for all tags, and add the different reporter ions in the modification details. For TMT 10-plex I would recommend using the modification definition available in SearchGUI.
Hope it helps,
Marc

**Comment by KKKKK-tech** [comment]
Hi,
It's my problem and I've solved it after following your advice, thanks!
> When using TMT please use one modification for all tags, and add the different reporter ions in the modification details

BTW, I encountered the same problem with #450, and it does not seem to work even though I increased the memory to 128G. My database is concatenated target-decoy human protein, which is about 26M, and the search_output.zip of comet is about 300M. Could you give me some suggestions to solve this problem avoid increasing memory? Thank you!

**Comment by hbarsnes** [comment]
> It's my problem and I've solved it after following your advice, thanks!

Great! I will then close this issue. But do not hesitate to open a new one if you come across other problems.

> BTW, I encountered the same problem with https://github.com/compomics/peptide-shaker/issues/450, and it does not seem to work even though I increased the memory to 128G. My database is concatenated target-decoy human protein, which is about 26M, and the search_output.zip of comet is about 300M. Could you give me some suggestions to solve this problem avoid increasing memory?

The only other option is to try turning off the parallel processing. You can do this from the New Project dialog by setting the Processing option at the bottom to only use 1 core. Note however that this will make the processing significantly slower.
