### ISSUE TITLE
"No PeptideShaker project was found in the zip file"

### ISSUE THREAD

**Issue by alexander-stolz-fh** [compomics/peptide-shaker#499]
After sucessfully running search GUI (in the log files I can see that several 1000 peptides were identified) I am not able to open the .zip output file in PeptideShaker. I always get the same error: "No PeptideShaker project was found in the zip file". I tried with several MS files and search engine but I am running in the same problems all the time.
Does anyone know this problem? 
I am using SearchGUI V4.1.24 and PeptideShaker V2.2.17.

Thanks in advance!

**Comment by hbarsnes** [comment]
Would I be correct in guessing that you are using the "Open Project" option and not the "New Project" option from the PeptideShaker Welcome dialog? The "Open Project" option is only for opening saved PeptideShaker projects, while the "New Project" option is the one to use when processing the zipped output from SearchGUI.

**Comment by alexander-stolz-fh** [comment]
Hey hbarsnes!
Thank you so much. This might be one of these really stupid threads that, however, help a lot of people.
You're right I was using "open" instead of "new". Now everything works fine. Thank you for this fast reply :)

**Comment by hbarsnes** [comment]
You're welcome! Always nice having some issues that are easy to fix as well. ;)
