### ISSUE TITLE
Error exporting custom PTMs

### ISSUE THREAD

**Issue by juank1892** [compomics/peptide-shaker#500]
Hi Peptide-Shaker team,

I am getting the following error:

Cannot invoke "com.compomics.util.pride.CvTerm.getOntology()" because "cvTerm" is null.`

I recently got back to this tool and I am really happy to see its exports working on Skyline. However, I performed a search with some custom PTMs that are not in Unimod and I am wondering if there is a way to export a mzIdentML for follow-up work on Skyline?

Sincerely,
Juan C.

**Comment by hbarsnes** [comment]
Hi Juan,

Thanks for letting us know about this one! Here is a beta version that should solve the problem: https://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/2.2.18-beta/PeptideShaker-2.2.18-beta.zip

Hopefully this version will allow you to generate a valid mzIdentML file even when having custom PTMs without Unimod mapping.

Best regards,
Harald

**Comment by hbarsnes** [comment]
The issue has been resolved in PeptideShaker 2.2.18 which has now been officially released.
