### ISSUE TITLE
error in processing of msgf.mzid files

### ISSUE THREAD

**Issue by Bakhtiyarlp** [compomics/peptide-shaker#503]
Hello,

I ran GUI on my desktop (Windows), using MS-GF+ and got mzid files. When I try using peptideshaker (desktop, windows) I get an error. Here is the bug report. Any help is appreciated. Thanks!
[save_report.txt](https://github.com/compomics/peptide-shaker/files/10564483/save_report.txt)

**Comment by hbarsnes** [comment]
It seems like there may be an issue with the connection to the underlying database. Are all the required files stored locally? Or are any of them on network drives or shared folderes? If the latter, I would recommend moving all the files to a local drive and trying to load the data once more.

It would also be great if you could share the PeptideShaker log file? You can find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report.

**Comment by Bakhtiyarlp** [comment]
Thank you. Apparently that was the problem, the files were on onedrive folder. I used local drive and it worked.

Thanks again!

**Comment by Bakhtiyarlp** [comment]
Is there any manual that I can follow when using peptideshaker? I want to know whether I should be processing technical replicates or biological replicates together or not?

**Comment by hbarsnes** [comment]
> Is there any manual that I can follow when using peptideshaker?

Please have a look at our tutorial material here: https://www.compomics.com/bioinformatics-for-proteomics

> I want to know whether I should be processing technical replicates or biological replicates together or not?

This question is not really covered in the tutorials, but generally we recommend processing technical replicates and biological replicates separately. The reason being that the results from the different replicates are merged into one common result in PeptideShaker, hence if processing biological replicates together you will not be able to compare the identifications from the individual replicates.

Note that as the initial problem has been solved, I will now close this issue, but please do not hesitate to open a new one if you have more questions later.
