### ISSUE TITLE
Peptideshaker Error 203

### ISSUE THREAD

**Issue by TPawla** [compomics/peptide-shaker#504]
Hi,
I am trying to analyze peptides with variable custom modification. My PeptideShaker version is 4.1.7

Basically, after trying several search engines, I always get an error 203. The search completes (GUI 4.1.7), but when I try to launch the results, the results fail to load after a second (in the PeptideShaker log it says an error occurred, 203).

This does not happen when the modification is fixed - only variable.

Thank you in advance for your help!

**Comment by hbarsnes** [comment]
Seems like there is an issue with deciding the location of the variable PTM. It would be great if you could share the PeptideShaker log file? You can find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report. It should be able to tell us a bit more about the error.

**Comment by TPawla** [comment]
There you  go.
Thank you for  the quick reply.
Best regards.


[Error 203.txt](https://github.com/compomics/peptide-shaker/files/10579339/Error.203.txt)

**Comment by hbarsnes** [comment]
Thanks for sharing the log file. It seems like you are using a rather old PeptideShaker version though (v2.2.5). I would therefore recommend that you first update to the most recent version (v2.2.19) to see if that solves the problem. If not, please share the new log file and we'll take it from there.

**Comment by TPawla** [comment]
Thank you, I'll update the software and try again.

**Comment by TPawla** [comment]
Unfortunately, updating to version 2.2.19 did not help. Here is the log file.
Thank you in advance.
[PeptideShaker 2.2.19 log.txt](https://github.com/compomics/peptide-shaker/files/10581256/PeptideShaker.2.2.19.log.txt)

**Comment by hbarsnes** [comment]
There are no error message in this new log file. Can you say a bit more about what issues you experienced when trying the latest release?

One thing I do see however is that you are using a rather old Java version. I would recommend updating to a more recent version here: https://adoptium.net/temurin/releases. After updating you can make sure that the new Java version is used via the Welcome dialog > Settings & Help > Settings > Java Settings.

**Comment by TPawla** [comment]
Hi again, 
I've updated Java and again, the software doesn't finish a search, when variable modifications are added.


[SearchGUI 4.1.7 log.txt](https://github.com/compomics/peptide-shaker/files/10608728/SearchGUI.4.1.7.log.txt)

**Comment by hbarsnes** [comment]
I would again recommend that you make an update. This time to SearchGUI, where the current release is v4.2.1.

Let me know if this makes any difference and if not, please share the new log file(s).

And when you say that the search does not finish, are you referring to a specific search engine in SearchGUI or the general loading of the data in PeptideShaker? If the latter, please share the PeptideShaker log as well.

**Comment by TPawla** [comment]
Hi again,
I have now PeptideShaker 2.2.19., SearchGUI 4.2.1., and Java 19 installed.
[SearchGUI 4.2.1 log.txt](https://github.com/compomics/peptide-shaker/files/10612020/SearchGUI.4.2.1.log.txt)
Basically, the issue has now expanded: software first froze up (happened last time, before updating Java), now after making sure everything is updated, it crashes when searching variable modifications, and no modifications at all

**Comment by TPawla** [comment]
Initially, the issue happened only when variable modifications were looked for, and it happened as the GUI search was finishing up, as the file was being zipped. 
Once I updated both PeptideShaker and SearchGUI, but not Java, software froze quite quickly (after ~40% search done on search GUI side).
Now, SearchGUI crashes after around 30% of one search engine only (regardless of variable mods or no mods required).

**Comment by TPawla** [comment]
Here is the PeptideShaker log:
[PeptideShaker - Copy.log](https://github.com/compomics/peptide-shaker/files/10612042/PeptideShaker.-.Copy.log)
Here is the SearchGUI log:
[SearchGUI 4.2.1 log.txt](https://github.com/compomics/peptide-shaker/files/10612043/SearchGUI.4.2.1.log.txt)

**Comment by hbarsnes** [comment]
> Once I updated both PeptideShaker and SearchGUI, but not Java, software froze quite quickly (after ~40% search done on search GUI side).

This is expected, as it will only work if you update both tools and Java at the same time.

> Now, SearchGUI crashes after around 30% of one search engine only (regardless of variable mods or no mods required).

A problem I see in your log file is that you are using comma in your folder name, i.e. "TM 1 file, new software var mod". This confuses our tools as it is assumed that comma separates multiple files in a list. Try removing or replacing the comma and see if that helps.

This still does not seem to solve the underlying problem with your custom variable modification though. Can you share the details of your custom modification?

**Comment by TPawla** [comment]
Hi,
So the SearchGUI finished, but now we are back to PeptideShaker crashing.
[PeptideShaker.log](https://github.com/compomics/peptide-shaker/files/10613876/PeptideShaker.log)
Here is the report from failed analysis:

[Report from failed analysis.txt](https://github.com/compomics/peptide-shaker/files/10613879/Report.from.failed.analysis.txt)

And here is SearchGUI bug report:
[SearchGUI 4.2.1 log.txt](https://github.com/compomics/peptide-shaker/files/10613883/SearchGUI.4.2.1.log.txt)


Regarding the variable modification - no variable modifications work.
I have tried variable modifications for amino acid substitutions, and only fixed ones work. 

My variable mod is not any different than a substitution, with an extra few atoms.
All the best.

**Comment by TPawla** [comment]
So now thankfully the regular analysis without any variable modifications works, but not for variable mods.
Thanks

**Comment by TPawla** [comment]
Hi again - I think all was solved thanks to your suggestions! Thank you for your assistance :)
