### ISSUE TITLE
how to perform significance test on experimental versus control spectral count files from peptideshaker?

### ISSUE THREAD

**Issue by Bakhtiyarlp** [compomics/peptide-shaker#505]
Hello,

This is probably out of scope of this tool, but I do not know where to ask this question.

I know that peptideshaker output can be channeled to SAINTexpress for analysis of significance protein hits in experimental versus control, however my problem with this is that my data do not have the bait spectral counts. The way that I set up my experiment, excludes the bait proteins before samples are run on mass spec. My question is how can I perform significance analysis between two peptide shaker files without the need to have spectral count data of the bait protein?

**Comment by mvaudel** [comment]
Hi,

This is indeed outside the scope of the issue tracker of the tool.

In general, if you want to evaluate the significance between different conditions, you need to process your samples separately (e.g. ten control and ten experiments) and then compare the estimated abundance between conditions among replicates in your favorite statistical analysis software. For example, MSstats should contain all the methods that you need https://www.bioconductor.org/packages/release/bioc/html/MSstats.html

Sorry that we cannot help you more at this stage,

Marc
