### ISSUE TITLE
saint express bait name from peptide shaker

### ISSUE THREAD

**Issue by Bakhtiyarlp** [compomics/peptide-shaker#506]
Hello, I am trying to using saint express pre-processing on apostl to create bait and prey files. I am using protein report text file from peptide shaker as the input. What raw in the peptideshaker text file is the bait name? Is it the gene name, accession number or protein description?

**Comment by mvaudel** [comment]
Hi,
Apologies, I must confess not being familiar with these tools, but in general we refer to proteins by their accession numbers.
Hope it helps,
Marc
