### ISSUE TITLE
PeptideShaker output in tabular format

### ISSUE THREAD

**Issue by trishorts** [compomics/peptide-shaker#507]
We have a FlashLFQ user that wants to know how to export peptide shaker output in tabular format so they can import the results into our software. Do you have a manual or wiki entry that might help them out?

https://github.com/smith-chem-wisc/FlashLFQ/issues/125

**Comment by hbarsnes** [comment]
There is a section in [our tutorial material](https://www.compomics.com/bioinformatics-for-proteomics) on how to export data from PeptideShaker in different formats. Please check out [pages 35 to 39 of Chapter 1.4  - Browsing Identification Results](https://drive.google.com/file/d/0B4sW8rLWPbRyUm5tdFRObTJSaEE/view?usp=sharing&resourcekey=0-NgNbCuD5h8MAoJy79cJk7w).

**Comment by trishorts** [comment]
Thanks. I will pass the message onto our user and see if it resolves the issue.

**Comment by hbarsnes** [comment]
Great! The exports are also available via the command line: https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI#b---reportcli

**Comment by justmpm** [comment]
Hi,
I wasn't able to find a way to export a .tabular file from PeptideShaker, but I did find that both the Default PSM Report and the Extended PSM Report are compatible with FlashLFQ.

Cheers
Mike

**Comment by hbarsnes** [comment]
Hi Mike,

Great that you were able to find a solution. All the text-based exports from PeptideShaker are indeed by default tab separated, and should therefore already be in the wanted format. Hence it is just a matter of including the columns you need.

Best regards,
Harald
