### ISSUE TITLE
export algorithm score

### ISSUE THREAD

**Issue by danyunghsu** [compomics/peptide-shaker#508]
Hi all,
I want to export each phosphorylated site and the respective algorithm score. I didn't find any instructions for the term algorithm score and algorithm raw score both on the website and in the paper. I did notice that Harold mentioned algorithm raw score is the unchanged score by the search engine. How does peptideshaker process the algorithm raw score into algorithm score actually?
Besides, i find one phospho site corresponding to more than one score in the output txt file. Why does this happen? Can you help me?
![issuepeptideshaker](https://user-images.githubusercontent.com/126338073/225657876-bf2a496d-b523-48a0-a8e5-a9643670ac56.png)

**Comment by danyunghsu** [comment]
Hi Marc,
Thank you for your answer. What I want is the original score of each phosphorylated peptide given by amanda, not PEP. I found amanda score in the searchgui_output.zip, but i'm not sure which score it relates to when i export my results from peptide shaker. What score should i choose?
Thanks
Danyung

**Comment by danyunghsu** [comment]
Hi Marc,
Thank you for your answer. What I want is the original score of each phosphorylated peptide given by amanda, not PEP. I found amanda score in the searchgui_output.zip, but i'm not sure which score it relates to when i export my results from peptide shaker. What score should i choose?
Thanks
Danyung
![amandascore](https://user-images.githubusercontent.com/126338073/225932848-7f248514-08ab-48f8-a0b1-bdb0a147823a.png)

**Comment by hbarsnes** [comment]
Hi Danyung,

To get the original search engine scores you can make your own custom export which includes the "Identification Algorithm Results":

![image](https://user-images.githubusercontent.com/13151214/227517524-9bc4e5de-376a-4c8e-a4fd-50ba9c8d21a7.png)

You'll find this option via the Export > Identification Features menu option, and then choose "Add new report type" at the bottom left.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
