### ISSUE TITLE
Peptideshaker issue with the identification result file 'searchGUI_input.txt' not being recognized.

### ISSUE THREAD

**Issue by JuneCoco** [compomics/peptide-shaker#510]
I use the command line to run Peptideshaker, but I've encountered an issue with the identification result file 'searchGUI_input.txt' not being recognized. I'm not sure what the problem is. Could you help me figure it out? Thanks.

This is the command I'm using:
java -cp ./PeptideShaker-2.2.23/PeptideShaker-2.2.23.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference test_CT26 -fasta_file ./CT26_4__CT26PP98_id_142_concatenated_target_decoy.fasta -identification_files ./SG_res1 -spectrum_files ./mzml_index -id_params ./SearchGUI_params.par

There is no error in the Peptideshaker.log
Mon Apr 17 16:53:59 CST 2023: PeptideShaker version 2.2.23.
Memory given to the Java virtual machine: 31675383808.
Total amount of memory in the Java virtual machine: 2181038080.
Free memory: 2141527528.
Java version: 18.0.2.1.

This is the process information displayed on the screen.

Mon Apr 17 16:54:02 CST 2023 Unzipping searchgui_out.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Mon Apr 17 16:54:08 CST 2023 Import process for test_CT26

Mon Apr 17 16:54:11 CST 2023 Importing sequences from CT26_4__CT26PP98_id_142_concatenated_target_decoy.fasta.
Mon Apr 17 16:54:38 CST 2023 Importing gene mappings.
Mon Apr 17 17:01:27 CST 2023 Establishing local database connection.
Mon Apr 17 17:01:27 CST 2023 Reading identification files.
Mon Apr 17 17:01:27 CST 2023 Parsing MHC_Celine_170516_1.ms-amanda.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Apr 17 17:01:34 CST 2023 Checking spectra for MHC_Celine_170516_1.ms-amanda.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Apr 17 17:01:34 CST 2023 Importing PSMs from MHC_Celine_170516_1.ms-amanda.mzid
 50% 60% 70% 80% 90% 100% 110% 120% 130% 140%
Mon Apr 17 17:02:04 CST 2023 32 identified spectra (0.1%) did not present a valid peptide.
Mon Apr 17 17:02:04 CST 2023 676 of the best scoring peptides were excluded by the import filters:
Mon Apr 17 17:02:04 CST 2023     - 100.0% peptide mapping to both target and decoy.
Mon Apr 17 17:02:04 CST 2023 Parsing MHC_Celine_170516_1.ms-amanda.mzid.gz.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Apr 17 17:02:15 CST 2023 Checking spectra for MHC_Celine_170516_1.ms-amanda.mzid.gz.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Apr 17 17:02:15 CST 2023 Importing PSMs from MHC_Celine_170516_1.ms-amanda.mzid.gz
 50% 60% 70% 80% 90% 100% 110% 120% 130% 140%
Mon Apr 17 17:02:21 CST 2023 32 identified spectra (0.1%) did not present a valid peptide.
Mon Apr 17 17:02:21 CST 2023 676 of the best scoring peptides were excluded by the import filters:
Mon Apr 17 17:02:21 CST 2023     - 100.0% peptide mapping to both target and decoy.
Mon Apr 17 17:02:21 CST 2023 Parsing MHC_Celine_170516_2.ms-amanda.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Apr 17 17:02:29 CST 2023 Checking spectra for MHC_Celine_170516_2.ms-amanda.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Apr 17 17:02:29 CST 2023 Importing PSMs from MHC_Celine_170516_2.ms-amanda.mzid
 50% 60% 70% 80% 90% 100% 110% 120% 130% 140%
Mon Apr 17 17:02:59 CST 2023 20 identified spectra (0.0%) did not present a valid peptide.
Mon Apr 17 17:02:59 CST 2023 552 of the best scoring peptides were excluded by the import filters:
Mon Apr 17 17:02:59 CST 2023     - 100.0% peptide mapping to both target and decoy.
Mon Apr 17 17:02:59 CST 2023 Parsing MHC_Celine_170516_2.ms-amanda.mzid.gz.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Apr 17 17:03:08 CST 2023 Checking spectra for MHC_Celine_170516_2.ms-amanda.mzid.gz.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Apr 17 17:03:08 CST 2023 Importing PSMs from MHC_Celine_170516_2.ms-amanda.mzid.gz
 50% 60% 70% 80% 90% 100% 110% 120% 130% 140%
Mon Apr 17 17:03:14 CST 2023 20 identified spectra (0.0%) did not present a valid peptide.
Mon Apr 17 17:03:14 CST 2023 552 of the best scoring peptides were excluded by the import filters:
Mon Apr 17 17:03:14 CST 2023     - 100.0% peptide mapping to both target and decoy.
Mon Apr 17 17:03:14 CST 2023 Parsing MHC_Celine_170516_3.ms-amanda.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Apr 17 17:03:22 CST 2023 Checking spectra for MHC_Celine_170516_3.ms-amanda.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Apr 17 17:03:22 CST 2023 Importing PSMs from MHC_Celine_170516_3.ms-amanda.mzid
 50% 60% 70% 80% 90% 100% 110% 120% 130% 140%
Mon Apr 17 17:03:46 CST 2023 32 identified spectra (0.1%) did not present a valid peptide.
Mon Apr 17 17:03:46 CST 2023 610 of the best scoring peptides were excluded by the import filters:
Mon Apr 17 17:03:46 CST 2023     - 99.7% peptide mapping to both target and decoy.
Mon Apr 17 17:03:46 CST 2023 Parsing MHC_Celine_170516_3.ms-amanda.mzid.gz.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Apr 17 17:03:53 CST 2023 Checking spectra for MHC_Celine_170516_3.ms-amanda.mzid.gz.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Apr 17 17:03:54 CST 2023 Importing PSMs from MHC_Celine_170516_3.ms-amanda.mzid.gz
 50% 60% 70% 80% 90% 100% 110% 120% 130% 140%
Mon Apr 17 17:03:57 CST 2023 32 identified spectra (0.1%) did not present a valid peptide.
Mon Apr 17 17:03:57 CST 2023 610 of the best scoring peptides were excluded by the import filters:
Mon Apr 17 17:03:57 CST 2023     - 99.7% peptide mapping to both target and decoy.
Mon Apr 17 17:03:57 CST 2023 Parsing searchGUI_input.txt.
Mon Apr 17 17:03:57 CST 2023 Identification result file 'searchGUI_input.txt' not recognized.
Mon Apr 17 17:03:57 CST 2023 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. Please see the PeptideShaker log file: ./PeptideShaker-2.2.23/resources/PeptideShaker.log</CompomicsError>

**Comment by hbarsnes** [comment]
Please make sure that the content of the ./SG_res1 folder only includes the SearchGUI results, as otherwise all of the files in the folder will be assumed to be search result files.

In your case it seems like you may also have a copy of the searchGUI_input.txt file in this folder. Please delete this one, only keeping the SearchGUI zip file, and then try again.

If this does not work you can try linking to the zip file directly in your command line, i.e. ./SG_res1/searchgui_out.zip, instead of the folder.

**Comment by hbarsnes** [comment]
All of this is controlled via the identification parameters. These you can set via IdentificationParametersCLI: https://github.com/compomics/compomics-utilities/wiki/IdentificationParametersCLI

In particular the FDR thresholds are set here: https://github.com/compomics/compomics-utilities/wiki/IdentificationParametersCLI#validation-levels
