### ISSUE TITLE
An error occurred while loading the spectrum file(s)

### ISSUE THREAD

**Issue by esraaelmligy** [compomics/peptide-shaker#511]
Urgent matter:

I am using the ReportsCLI and have a SearchGUI zipped file as an input but it gives me this error upon execution 

code used: java -cp PeptideShaker-2.2.23.jar eu.isas.peptideshaker.cmd.ReportCLI -in  "/home/user/path/to/search_gui_run/searchgui_out.zip" -out_reports "/home/user/path/to/pep_shaker_run" -reports "0, 3"

Log:

Memory given to the Java virtual machine: 995426304.
Total amount of memory in the Java virtual machine: 62849024.
Free memory: 50604880.
Java version: 11.0.18.
java.lang.NullPointerException
	at eu.isas.peptideshaker.utils.PsdbParent.loadSpectrumFiles(PsdbParent.java:435)
	at eu.isas.peptideshaker.utils.PsdbParent.loadSpectrumFiles(PsdbParent.java:411)
	at eu.isas.peptideshaker.cmd.ReportCLI.call(ReportCLI.java:152)
	at eu.isas.peptideshaker.cmd.ReportCLI.main(ReportCLI.java:508)

**Comment by esraaelmligy** [comment]
Thank you so much for the fast answer, can you please refer me to the exact code where i can process the SearchGUI results with peptideshaker to be ready for generating the reports?

**Comment by hbarsnes** [comment]
You can find all the details about the command lines here: https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI

And here is the specific command line for processing SearchGUI results: https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI#a---peptideshakercli
