### ISSUE TITLE
No identification results generated from peptideshaker

### ISSUE THREAD

**Issue by esraaelmligy** [compomics/peptide-shaker#514]
**Hello, i am trying to simulate the galaxy protegenomics database search using searchGUI and peptideshaker but when i try to run peptide shaker it gives me the following error:**

Tue May 23 13:51:40 EET 2023 Unzipping searchgui_out.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

10%
Tue May 23 13:51:42 EET 2023 Import process for mm10

Tue May 23 13:51:42 EET 2023 Importing sequences from Final_database.fasta.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tue May 23 13:51:42 EET 2023 Importing gene mappings.
Tue May 23 13:51:42 EET 2023 Establishing local database connection.
Tue May 23 13:51:42 EET 2023 Reading identification files.
Tue May 23 13:51:42 EET 2023 Parsing Mo_Tai_Trimmed_mgfs__Mo_Tai_iTRAQ_f4.t.xml.gz.
10%
Tue May 23 13:51:42 EET 2023 No PSM found in Mo_Tai_Trimmed_mgfs__Mo_Tai_iTRAQ_f4.t.xml.gz.
Tue May 23 13:51:42 EET 2023 Parsing Mo_Tai_Trimmed_mgfs__Mo_Tai_iTRAQ_f5.t.xml.gz.
10%
Tue May 23 13:51:42 EET 2023 No PSM found in Mo_Tai_Trimmed_mgfs__Mo_Tai_iTRAQ_f5.t.xml.gz.
Tue May 23 13:51:42 EET 2023 Parsing Mo_Tai_Trimmed_mgfs__Mo_Tai_iTRAQ_f8.t.xml.gz.
10%
Tue May 23 13:51:42 EET 2023 No PSM found in Mo_Tai_Trimmed_mgfs__Mo_Tai_iTRAQ_f8.t.xml.gz.
Tue May 23 13:51:42 EET 2023 Parsing Mo_Tai_Trimmed_mgfs__Mo_Tai_iTRAQ_f9.t.xml.gz.
10%
Tue May 23 13:51:42 EET 2023 No PSM found in Mo_Tai_Trimmed_mgfs__Mo_Tai_iTRAQ_f9.t.xml.gz.
Tue May 23 13:51:42 EET 2023 No identification results.
Tue May 23 13:51:42 EET 2023 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. Please see the PeptideShaker log file: /home/esraaa/PeptideShaker-2.2.25/resources/PeptideShaker.log</CompomicsError>

**I have tried looking at the log file but i really can't see a problem explained in there, it gives me the following:**

Tue May 23 13:51:40 EET 2023: PeptideShaker version 2.2.25.
Memory given to the Java virtual machine: 4162846720.
Total amount of memory in the Java virtual machine: 264241152.
Free memory: 251682192.
Java version: 11.0.19. 

**So i don't really know what is the problem with my job, keeping in mind that i am providing the same exact files and parameters executed in the galaxy tutorial "https://training.galaxyproject.org/training-material/topics/proteomics/tutorials/proteogenomics-dbsearch/tutorial.html" so if you could please help me know how to solve this issue.**

**Comment by esraaelmligy** [comment]
**This is the command i am running the program with:**

java -cp /path/to/PeptideShaker-2.2.25.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -reference mm10 -identification_files /path/to/searchgui_out.zip -out /path/to/output.psdb -out_reports /path/to/directory -reports "0, 3"

**These are also the spectrum files and the SearchGUI compressed results i am running with:**

https://drive.google.com/drive/folders/1GZzEtqreFkViqgjBsaLIjiYUlVWI4-Pk?usp=share_link

**Comment by hbarsnes** [comment]
Hi! As far as I can tell PeptideShaker is correct, i.e. there are no PSMs in your X! Tandem search results files. In fact they only contain the search parameters and nothing else. The tiny size of only 2 kb each is a good clue of this.

You therefore have to go one step further back in your pipeline and try to figure out what went wrong with the search in SearchGUI. My guess is that you made a mistake when setting the search parameters.

Actually, a quick look at your id.params.par file reveals a fragment ion tolerance of only 0.05 ppm, pretty sure this should be 0.05 Da?

Try redoing the search with a fragment ion tolerance of 0.05 Da and you should get results looking more like what you expected.

**Comment by esraaelmligy** [comment]
Hello!  i actually didn't realize that the fragment ion tolerance wasn't in Da and upon fixing it the results came out just as expected.

Thank you so much for helping and taking the time to check the parameters file, i will be closing the issue now.
