### ISSUE TITLE
PeptideShaker won't open file

### ISSUE THREAD

**Issue by HarryTaylor1296** [compomics/peptide-shaker#516]
Hi, 

I have performed some DDA analysis for a colleague and processed the data. I would like them to be able to open the file themselves to scroll through the data. 

I performed the analysis via searchGUI, and performed post-processing using PeptideShaker v2.2.25.

They have downloaded the same version of PeptideShaker (v.2.2.25), but they get the following error when they open the file:

"An error occured while reading: FILE_LOCATION>NAME.psdb

Please verify that the version used to create this file is compatible with your version of PeptideShaker."

The only option is to click OK. Which then closes the software. How do I resolve this for them?

Thanks,
Harry

**Comment by hbarsnes** [comment]
Hi Harry,

May I ask how you shared the PeptideShaker results with your colleague? The recommended option is to open the data in PeptideShaker on your end and then use the Export > PeptideShaker Project As > Zip File option. This ensures that they have all the required data and all they have to do is unzip the zip file and use the Open Project option in the PeptideShaker Welcome Dialog.

Best regards,
Harald

**Comment by HarryTaylor1296** [comment]
Hi Harald, 

Thanks for getting back to me so quickly. I have just sent this to my colleague but they still cannot open the file when I export the file in this manner. The same error message remains. 

Please let me know what else I can try to solve the issue

Thanks, 
Harry

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
