### ISSUE TITLE
Java update warning message even after Java updated

### ISSUE THREAD

**Issue by MNTNguyen** [compomics/peptide-shaker#518]
Dear SearchGUI developers, 
I used SearchGUI for a while and recently when I opened the programm, a warning message popped up:
"Running with Java version 1.8.0_372-b07, SearchGUI works best with Java >=11.
See Java Troubleshotting for more details." (photo attached)
<img width="281" alt="SGUI_Java warning message" src="https://github.com/compomics/peptide-shaker/assets/83227918/57d12149-1d41-4146-968c-e0f0edc4e631">
I updated Java to 11 and even carefully checked in the Java settings in SearchGUI to make sure it configures correctly. (photo atached)
<img width="713" alt="SGUI_Java settings" src="https://github.com/compomics/peptide-shaker/assets/83227918/4de9c3dd-cbe1-41c1-be57-4a4b164e6278">

But I still got this message everytime I opened SearchGUI (other than that it works fine).
Do you have any idea why the warning message keeps appearing? 
Not a big issue but kinda weird only...
Thank you in advance.

Best, 
Minh

**Comment by hbarsnes** [comment]
Hi Minh,

If you do not need the older Java version you can perhaps consider removing it? (This is recommended for safety reasons anyway.) Hopefully that should get rid of the warning.

Best regards,
Harald

**Comment by MNTNguyen** [comment]
oh thanks Harald for the quick reply, i'll ask our IT person again about it. 
We installed the new version together so I assumed the old version is replaced. but it may not be the case.

Best, 
Minh
