### ISSUE TITLE
Failed to open SearchGUI

### ISSUE THREAD

**Issue by JesusCastano01** [compomics/peptide-shaker#520]
Hi,
I've been using SearchGUI for the past week, and today, suddenly, it stopped working for no reason. I'm a little bit confuse. Every time I tried to open it, an error message pops up, saying "Cannot invoke "com.compomics.util.parameters.UtilitiesUserParameters.getMemoryParameter()" because "this.userParameters" is null.

Any advice on how to fix this? As I said it suddenly stopped working, so I'm very confused about what could have happened.
Thanks,

![image](https://github.com/compomics/peptide-shaker/assets/139022774/b842d0d7-d55a-4099-98a2-4d20301429b5)

**Comment by hbarsnes** [comment]
Please see the follow-up to this issue here: https://github.com/compomics/searchgui/issues/355
