### ISSUE TITLE
Canceled import from search gui

### ISSUE THREAD

**Issue by Parniyan-M** [compomics/peptide-shaker#521]
Hi, 

I have an issue with importing searchgui output data and I am not sure what is the issue! here is the log!

Thu Aug 17 12:54:51 CEST 2023        Import process for tian-xenograft-HuO2

Thu Aug 17 12:54:51 CEST 2023        Importing sequences from database_HUMAN_MOUSE_uniprotkb_cRAP_Tripsin_lysc_COL6A3domains_2023_08_16_concatenated_target_decoy.fasta.
Thu Aug 17 12:55:17 CEST 2023        Importing gene mappings.
Thu Aug 17 12:55:18 CEST 2023            No taxonomy found for Lysobacter enzymogenes.
Thu Aug 17 12:55:18 CEST 2023            Downloading GO and gene mappings for species Mus musculus.
Thu Aug 17 12:55:50 CEST 2023            GO mappings downloaded.
Thu Aug 17 12:55:52 CEST 2023            Gene mappings downloaded.
Thu Aug 17 12:55:55 CEST 2023        Establishing local database connection.
Thu Aug 17 12:55:55 CEST 2023        Reading identification files.
Thu Aug 17 12:55:55 CEST 2023        Parsing H20151213_HOL2_34_rafktra_10pp.t.xml.gz.
Thu Aug 17 12:55:56 CEST 2023        Checking spectra for H20151213_HOL2_34_rafktra_10pp.t.xml.gz.
Thu Aug 17 12:55:56 CEST 2023        Importing PSMs from H20151213_HOL2_34_rafktra_10pp.t.xml.gz
Thu Aug 17 12:55:58 CEST 2023        3707 identified spectra (9.1%) did not present a valid peptide.
Thu Aug 17 12:55:58 CEST 2023        19742 of the best scoring peptides were excluded by the import filters:
Thu Aug 17 12:55:58 CEST 2023            - 21.9% peptide length less than 8 or greater than 30.
Thu Aug 17 12:55:58 CEST 2023            - 18.8% peptide presenting high mass or isotopic deviation.
Thu Aug 17 12:55:58 CEST 2023            - 59.2% unrecognized modifications.
Thu Aug 17 12:55:58 CEST 2023        Parsing H20151214_HOL2_05_rafktra_10pp.t.xml.gz.
Thu Aug 17 12:55:59 CEST 2023        Checking spectra for H20151214_HOL2_05_rafktra_10pp.t.xml.gz.
Thu Aug 17 12:55:59 CEST 2023        Importing PSMs from H20151214_HOL2_05_rafktra_10pp.t.xml.gz
Thu Aug 17 12:56:00 CEST 2023        3836 identified spectra (9.4%) did not present a valid peptide.
Thu Aug 17 12:56:00 CEST 2023        20165 of the best scoring peptides were excluded by the import filters:
Thu Aug 17 12:56:00 CEST 2023            - 22.4% peptide length less than 8 or greater than 30.
Thu Aug 17 12:56:00 CEST 2023            - 19.1% peptide presenting high mass or isotopic deviation.
Thu Aug 17 12:56:00 CEST 2023            - 58.5% unrecognized modifications.
Thu Aug 17 12:56:00 CEST 2023        File import completed. 81398 first hits imported (82627 total) from 90594 spectra.
Thu Aug 17 12:56:00 CEST 2023        [42310 first hits passed the initial filtering]
Thu Aug 17 12:56:01 CEST 2023        Computing assumptions probabilities.
Thu Aug 17 12:56:01 CEST 2023        Saving assumptions probabilities, selecting best match, scoring modification localization.

Thu Aug 17 12:56:12 CEST 2023        Importing Data Canceled!
Thu Aug 17 12:56:12 CEST 2023        An error occurred: Cannot invoke "com.compomics.util.experiment.identification.matches.SpectrumMatch.getPeptideAssumptionsMap()" because "spectrumMatch" is null
Thu Aug 17 12:56:12 CEST 2023        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

**Comment by hbarsnes** [comment]
A beta version that may fix this issue is available for testing here: https://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/3.0.0-beta/PeptideShaker-3.0.0-beta.zip

Note that you will have to reprocess the data in PeptideShaker, i.e. you cannot open old PeptideShaker projects directly.

Please let us know if this beta version solves the issue?

**Comment by Parniyan-M** [comment]
Thank you for the response.
unfortunately, No! it gave the same error!

**Comment by hbarsnes** [comment]
Then I'm afraid the only known solution at the moment is to increase the amount of memory provided to PeptideShaker. You can do this via the PeptideShaker Welcome Dialog > Settings & Help > Settings > Java Settings > Memory. Can you try increasing the memory and see if that solves the problem?

**Comment by Parniyan-M** [comment]
great!thanks! yes, it is resolved! :)
