### ISSUE TITLE
Mascot compatibility documentation not up-to-date

### ISSUE THREAD

**Issue by elrubio** [compomics/peptide-shaker#523]
The [Mascot Support section](https://compomics.github.io/projects/peptide-shaker.html#mascot-support) of the Peptide Shaker *Readme* contains the following sentence:

> Mascot’s [Automatic Decoy Search](http://www.matrixscience.com/help/decoy_help.html#AUTO) is *not* compatible with PeptideShaker. The reason for this is that Mascot uses a random decoy approach and not a reverse decoy approach.

To my understanding, this was changed already back in 2012, when Mascot v2.4 changed the default decoy creation method from *random* to *reverse*, at least for fully and semi-specific enzymes.

The Mascot documentation (as linked above) actually states:

> **Method 1**: reversed protein sequences
>     The default for MS/MS searches with a fully specific or semi-specific enzymes
>
> **Method 3**: randomised protein sequences
>     The default for MS/MS searches with enzyme None and all PMF searches. This was the default method in Mascot 2.3 and earlier. If the target database is nucleic acid, it is the original sequence that is randomised, not the translation. The average amino acid composition of the decoy sequences is the same as the average composition of the target database. 

Also, standard Mascot result reports contain a section *Sensitivity and FDR (**reversed** protein sequences)*.

Even if this doesn't mean that Mascot results (with auto decoy search enabled) can be directly used in PeptideShaker, I'd suggest to update the documentation accordingly.

**Comment by hbarsnes** [comment]
Thanks for the tip! I guess it just shows how long our tools have been around... ;)

I've had an attempt at updating the documentation. Please take a look at let me know what you think?

(Note however that the Mascot support has not really been tested or updated for many years and we would rather recommend instead using the search engines supported in SearchGUI when loading data into PeptideShaker.)

**Comment by elrubio** [comment]
Thanks, the update looks good to me. 👍🏼 

It's a minor point but it was puzzling me and it might save other people's time.
