### ISSUE TITLE
Writing mzidentML files

### ISSUE THREAD

**Issue by prao123** [compomics/peptide-shaker#528]
Hello!
What does peptide shaker require to write mzidentML files? Is it possible to import pepXML files from other search engines outside of SearchGUI - such as Fragpipe and ouput an mzidentML file? 
I am running a proteogenomics workflow in Galaxy (use.Galaxy.eu) and our workplace uses Fragpipe. However, the mzidentML generated through other methods such as idconvert (https://proteowizard.sourceforge.io/tools/idconvert.html) or from Crux psm-convert (https://crux.ms/commands/psm-convert.html) seems to be smaller and bit different than the one generated by Peptide shaker and result in errors on Galaxy. The workaround I am trying is whether I can import the Fragpipe search result files in to PeptideShaker and output an mzid file.

Thank you

**Comment by hbarsnes** [comment]
PeptideShaker only writes mzIdentML files after first processing a set of search results files. Ideally these would come from SearchGUI. Other data sources may be possible, but in that case we cannot guarantee that the files will be supported and there may be errors.

With regards to using FragPipe output as input to PeptideShaker, I do not think this is something we have tried. We do support the reading of pepXML files from Comet though, but as pepXML is not really a standard format there are often minor differences that has to be accounted for when reading pepXML from different sources. But you can always try loading your FragPipe pepXML files into PeptideShaker (together with the FASTA and spectrum files) and see what happens?

Note however that PeptideShaker will always reprocess the input data and thus the result will not be identical to the FragPipe results. Hence, if you want a pure data file converter, PeptideShaker will not be the recommended software to use. It would therefore be preferable to either fix the issue by producing a supported output file in the first place or by improving the downstream tools to support the specific output format.

**Comment by prao123** [comment]
I will try importing the pepXML file by including the additional fasta and spectrum files. But, I guess, the downstream processing steps may need to be addressed to make it reproducible. 
Thank you for your thoughts and potential workaround solutions.

**Comment by hbarsnes** [comment]
No worries. Good luck in searching for a possible workaround.

I will close this issue, but do not hesitate to open a new one if you come up with more questions later.
