### ISSUE TITLE
pep.xml file parsing error

### ISSUE THREAD

**Issue by marinacd** [compomics/peptide-shaker#529]
Hi! I seem to have a problem with reading my spectrum matches from Search Gui, I have to run them separatly due to Java class path issues but Search Gui seems to work fine.
When I run PEptide Shaker I get this issue and the log shows no errors:
![Error](https://github.com/compomics/peptide-shaker/assets/50925521/facbe985-697a-48f6-828e-d5bdc7a74680)

Thank you

**Comment by hbarsnes** [comment]
I will look into the issue with the gene mappings for Baker's yeast and see if I can find a solution.

However, this is not the real problem. Rather it is your Comet output file. It is either empty or has somehow been corrupted. Have you checked that the Comet search completed correctly and without any errors and that the file is not empty?

**Comment by hbarsnes** [comment]
I just released a new PeptideShaker version (v3.0.3) that solves the Baker's yeast gene mapping issue. So if you update to the latest version that particular error message should disappear.

BTW, regarding the Java path issues, I would recommend removing all but the latest Java version. Although I'm not 100% sure what you mean by "Java class path issues"?

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
