### ISSUE TITLE
Peptide Shaker processing stops. 

### ISSUE THREAD

**Issue by marylouisedc** [compomics/peptide-shaker#530]
Hi, i was doing a standard search using Search GUI and Peptide shaker, i tried including the post processing while using the Search GUI and also tried using Search GUI first and manually uploading the files in Peptide Shaker. The process just stops at this specific point. 

![Screenshot 2023-12-02 152522](https://github.com/compomics/peptide-shaker/assets/149193371/8493da2c-e98c-4e50-a366-57c6046fd0dd)

**Comment by hbarsnes** [comment]
Please have a look in the PeptideShaker log file for more details. You can find the log file here: PeptideShaker-X.Y.Z\resources\PeptideShaker.log.

Hopefully the content in this file will tell you/us more about the source of the problem.

If you are using an old version of Java it may also help to update to a more recent version (and remove the old version(s)). You can update your Java version here: https://adoptium.net/temurin/releases.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
