### ISSUE TITLE
Protein filter Validation = Confident error

### ISSUE THREAD

**Issue by kbarylyuk** [compomics/peptide-shaker#531]
Hi,

I am getting an error whenever I try to add a protein filter for the validation level = Confident
![image](https://github.com/compomics/peptide-shaker/assets/13316340/31787e31-d0d2-4623-9ba9-1ba84cbb4a1d)
![image](https://github.com/compomics/peptide-shaker/assets/13316340/301ecd73-1a3c-4dd8-a1cf-a13c370c1e67)
![image](https://github.com/compomics/peptide-shaker/assets/13316340/b978c3bb-0da2-41c1-bd8a-7530dad1376f)

Log file attached.

If I clear the filter list and add it again there is no error message, but PeptideShaker is then stuck with the progress bar window at 0%.
[PeptideShaker 3.0.4 log.txt](https://github.com/compomics/peptide-shaker/files/13717693/PeptideShaker.3.0.4.log.txt)

Thank you!

**Comment by hbarsnes** [comment]
Thanks for letting us know! There indeed seems to be a bug in this particular filter. There does not seem to be an easy fix though and given that it is a non-essential beta feature I cannot promise that will have the time to dig deeper into it at the moment. However, we will keep the issue open as a reminder and will let you know if we manage to come up with a solution.

**Comment by kbarylyuk** [comment]
Thank you, Harald!
I appreciate that it is a beta feature, but I think the possibility to flexibly filter the results is quite a useful one that is also widely available in many analogous software suits. It would be great to see it fully implemented in PeptideShaker at some point in the future.
I can add that I tried the negative filter, too - with the same outcome (first an error message, then frozen progress bar and PeptideShaker becoming non-responsive).

**Comment by hbarsnes** [comment]
Turned out to be easier to fix than I thought. I've just released a new version (v3.0.5) that should solve the problem. If this is not the case, or if you experience other problems with the filters, please let me know and I'll reopen the issue.
