### ISSUE TITLE
Peptide Shaker only imports rank-1 PSMs and ignores the rest?

### ISSUE THREAD

**Issue by ChrissiKalk97** [compomics/peptide-shaker#533]
Hello,

I am running a Comet search with SearchGUI on a file containing 100 spectra and use Peptide Shaker (tried different version 3.0.1, 3.0.5 and 2.2.25) in order to visualize the results and obtain information about rank, score, mass etc in a txt format. I am trying to obtain 100 PSMs per spectrum in  Peptide Shaker (so 100*100 PSMs in total, which comet also seems to find): 
To me it seems like PS only imports the rank1 PSMs:
Thu Jan 18 08:51:35 CET 2024        File import completed. 100 first hits imported (10000 total) from 100 spectra.
Thu Jan 18 08:51:35 CET 2024        [100 first hits passed the initial filtering]
Thu Jan 18 08:51:35 CET 2024        Computing assumptions probabilities.
...
And skips the rest? When I export it is always exactly 100 results, one per spectrum. When clicking on the Spectrum ID tab I can see 100 identification resutls for each PSM from Comet, but Peptide Shaker seems to select only one. The other 99 are not validated, but I of course also tried to export wihtout the check on "validated only", but that does not change the output. I have also made the search settings very allowive and played around with this, while this changes the results displayed in the overview tab very slightly, there are never more than 100 PSMs exported...
<img width="620" alt="Screenshot _PS" src="https://github.com/compomics/peptide-shaker/assets/134528906/e2f4a9be-2736-4314-a401-a01b94ec4ead">

Some help on this would be greatly appraciated :)

**Comment by hbarsnes** [comment]
PeptideShaker imports all of the PSM, but only uses and shows the best scoring one for each spectrum. Except for in the Spectrum IDs tab where as you noticed all of the PSMs are displayed.

If you want to export all of the PSMs, I would recommend having a look at the export options in PeptideShaker. You'll find them via the Export menu > Identification Features. To create your own custom export click the "Add new report type" at the bottom left. The data you are interested should be in the "Identification Algorithm Results" section. Note however that this will more or less be the same as the raw search results from Comet, hence you could just as well skip PeptideShaker and work directly with the Comet result file.
