### ISSUE TITLE
 Search GUI Memory Issues

### ISSUE THREAD

**Issue by EthanHasenoehrl** [compomics/peptide-shaker#536]
I'm utilizing SearchGUI to perform a search on a set of mzML files. I keep on getting the following error found in the log file: 

Mon Jun 17 13:00:28 MDT 2024: PeptideShaker version 3.0.8.
Memory given to the Java virtual machine: 4194304000.
Total amount of memory in the Java virtual machine: 134217728.
Free memory: 124138904.
Java version: 11.0.22.

I have tried a variety of settings with memory and CPU usage and nothing seems to fix the issue. I am running a M3 Pro with 18gb of RAM running Mac OS 14.5 if that helps.

Any input is greatly appreciated.

**Comment by hbarsnes** [comment]
That message is not really an error as such, just an indication of the amount of memory used. Are you seeing any more specific error messages?

In any case, I would recommend updating to a more recent Java version: https://adoptium.net/temurin/releases.

Increasing the amount of memory given to SearchGUI and PeptideShaker may also help. In PeptideShaker this is done via the Welcome dialog > Settings & Help > Settings > Java Settings > Memory, while in SearchGUI you do this via the Java Settings on the Edit menu in the main dialog.

Finally, if you're starting PeptideShaker from directly SearchGUI it may also help to perform the execute the two tools separately, i.e. first search the data in SearchGUI and then open them in PeptideShaker afterwards.

**Comment by EthanHasenoehrl** [comment]
Hello,

Thank you very much for your fast response. I updated Java and allocated 10 gb of RAM and that seemed to fix one of the issues. I ran a prior experiment with a .mgf file and the SearchGUI and PeptideShaker worked perfectly.

I am running a mzML file converted Waters .raw file using the protocol as described in this post : https://ccms-ucsd.github.io/GNPSDocumentation/fileconversion_waters/. There is a bug in the software that necessitates running a custom script as described in that post.

I attached two output files from SearchGUI that I got when trying to these converted mzML files. Have you seen anything similar to this before when using this program? It could very well be an issue with the file itself, however I am not tech savvy enough to know exactly. 

[X!Tandem.txt](https://github.com/user-attachments/files/15890251/X.Tandem.txt)
[Comet.txt](https://github.com/user-attachments/files/15890252/Comet.txt)

Thank you again, and I look forward to your response.

**Comment by hbarsnes** [comment]
Seems like there is an issue with the mzML files and that neither X! Tandem nor Comet finds any usable spectra in there. And given that the problem occurs both with the mzML files directly and with the internally converted mgf files I'm afraid there is not much we can do on our end to address the issue.

I would recommend that you take a closer look at the mzML files and see whether they contain the expected content. Or you could convert one of them to mgf and inspect the simpler mgf format instead. Hopefully you will be able to spot the problem that way.
