### ISSUE TITLE
  Error in starting peptideshaker tool 

### ISSUE THREAD

**Issue by bmzee1** [compomics/peptide-shaker#91]
Hi, when I try opening PeptideShaker-1.0.0, I get startup error, where the startup.log file reads:

Memory settings read from the user preferences: 3072
args:
original java.home: C:\Program Files\Java\jre1.8.0_60\bin\
new java.home: C:\Program Files\Java\jre1.8.0_60\bin\

Command line:
"C:\Program Files\Java\jre1.8.0_60\bin\java" -splash:resources\conf\peptide-shaker-splash.png -Xms128M -Xmx3072M -cp "C:\PeptideShaker-0.37.3\PeptideShaker-1.0.0\PeptideShaker-1.0.0.jar" eu.isas.peptideshaker.gui.PeptideShakerGUI
Process exitValue: 1

I updated java JRE to version 8, update 60.

How can I solve this issue? Thanks.

**Comment by hbarsnes** [comment]
Make sure that you installed the 64 bit version of Java if you have a 64 bit operating system or the 32 bit Java version if you have a 32 bit operating system. It is also recommended to uninstall all older Java versions.

**Comment by bmzee1** [comment]
Hi Harald,

I'm using Windows 7 (32bit) and I've uninstalled my previous Java app and
reinstalled the latest Java 32it but still getting an error.

Memory settings read from the user preferences: 3072
args:
original java.home: C:\Program Files\Java\jre1.8.0_60\bin\
new java.home: C:\Program Files\Java\jre1.8.0_60\bin\

Command line:
"C:\Program Files\Java\jre1.8.0_60\bin\java"
-splash:resources\conf\peptide-shaker-splash.png -Xms128M -Xmx3072M -cp
"C:\PeptideShaker-0.37.3\PeptideShaker-1.0.0\PeptideShaker-1.0.0.jar"
eu.isas.peptideshaker.gui.PeptideShakerGUI
Process exitValue: 1

I only noticed this problem recently when I updated to the new
PeptideShaker and Java yesterday.

Thank for your help,
Barry

**Comment by hbarsnes** [comment]
Seems like they changed the error message for setting the memory limit too high on Java 32 bit in the latest Java release. We'll update our code and release a new version as soon as possible.

**Comment by bmzee1** [comment]
Hi Harald,

I think I got around the problem by changing the JavaOptions.txt file to
-xmx1280M on the second line. It seems to work for now.

Thanks,
Barry

**Comment by hbarsnes** [comment]
Yes, that is also an option. But it should be handled automatically by the tool itself. Will be fixed in the next release.

**Comment by hbarsnes** [comment]
We've just released PeptideShaker v1.0.1 which should fix this issue without having to manually edit the JavaOptions file. Please let me know if that is not the case and I'll reopen the issue.
