### ISSUE TITLE
OMSSA modification indexes not set in the search parameters

### ISSUE THREAD

**Issue by cdlawless** [compomics/peptide-shaker#92]
I'm having difficulty runnning the latest version (1.0.1) with OMSSA output files generated from SearchGUI (v2.0.4). All on the commandline. I get the above error when importing the omx files. The full error is:
java.lang.IllegalArgumentException: OMSSA modification indexes not set in the search parameters.
	at eu.isas.peptideshaker.fileimport.PsmImporter.importAssumptions(PsmImporter.java:531)
	at eu.isas.peptideshaker.fileimport.PsmImporter.importPsm(PsmImporter.java:402)
	at eu.isas.peptideshaker.fileimport.PsmImporter.access$000(PsmImporter.java:65)
	at eu.isas.peptideshaker.fileimport.PsmImporter$PsmImporterRunnable.run(PsmImporter.java:1339)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)

The command I use is: 
java -Xms1024m -Xmx131072m -cp /mnt/lustre/scratch/mjfidcl2/PeptideShaker/PeptideShaker-1.0.1/PeptideShaker-1.0.1.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment kadmon_6600_Hydra_5_engines -s
ample kadmon_embryo_fraction_6600_5 -replicate 1 -identification_files "/mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/6600_microflow/output" -out "./kadmon_embryo_fraction_6600_5.cps" -spectrum_file
s "/mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/6600_microflow/mgfs" -id_params "/mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/6600_microflow/params/GUI-2.0.4_6600.par"

the paramater file was generated using: 
java -Xms1024M -Xmx4096M -cp /mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.0.4/SearchGUI-2.0.4.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -db /mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/fasta/Fly_BDGP5_24_Wolbachia_short_concatenated_target_decoy.fasta -out params/GUI-2.0.4_Qex -frag_tol 0.5 -prec_tol 10 -mc 2 -enzyme Trypsin -fixed_mods "Carbamidomethylation of C" -variable_mods "Oxidation of M, Phosphorylation of S, Phosphorylation of T, Phosphorylation of Y, Acetylation of protein N-term"

I have tried ParameterCLI through PeptideShaker (v1.0.1) but I get the same error at the same point.

Regards

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

The OMSSA indexes are added to the parameter file when the search is started. So if you create the parameter file and then make a copy that you give to SearchGUI, and after finishing the search you use the original parameter file (and not the one used in SearchGUI) when loading the search results in PeptideShaker, you will see the error above. Are you doing something like this?

In workflows like this we'd highly recommend using the zip output option in SearchGUI (-output_option 0), preferably combined with (-output_data 1). This results in a single zip file output from SearchGUI which can directly be used as input to PeptideShaker (without the need for the -id_params and -spectrum_files options). This is the solution we implemented for running our tools in command line workflows, for example in Galaxy.

Let me know if this option works for you.

Best regards,
Harald

**Comment by cdlawless** [comment]
Hi Harald

Thanks for you reply. I effectively use the same .par file as the one I 
provide to SearchGUI. Are you saying that SearchGUI creates an "updated" 
.par file that it then uses when searching? (the one that I see in the 
SearchGUI output folder?). I have been running SearchGUI + PeptideShaker 
for months this way up until the recent version releases and have not 
had this error with the OMSSA searches.

The workflow that I use utilises out HPC cluster. So a single SearchGUI 
single search engine is carried per job/task on the cluster similar to 
the following command:

java -Xms1024M -Xmx8192M -cp 
/mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.0.4/SearchGUI-2.0.4.jar 
eu.isas.searchgui.cmd.SearchCLI
-spectrum_files 
"/mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/Qexactive/msgf_QEBF22122014_ON_Embryos_B1_temp/QEBF22122014_ON_Embryos_B1.mgf"
  -output_folder 
/mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/Qexactive/output/ 
-id_params 
/mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/Qexactive/msgf_QEBF22122014_ON_Embryos_B1_temp/GUI-2.0.4_Qex_noPhosph.par 

  -output_option 3
-mgf_splitting 2000
-temp_folder 
/mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/Qexactive/msgf_QEBF22122014_ON_Embryos_B1_temp 

-xtandem 0 -msgf 1 -omssa 0 -myrimatch 0 -comet 0 -tide 0 -ms_amanda 0 
-andromeda 0
-msgf_folder 
/mnt/lustre/scratch/mjfidcl2/DDIP/Embryo_fractions/Qexactive/msgf_QEBF22122014_ON_Embryos_B1_temp

The only parameters that change are the search engine flags, temp folder 
and the mgf files.

The identification files for each search engine all end up in the same 
place. I then submit the outputs to PeptideShaker (again on the our HPC 
cluster) directing it to the location of the parameter file, mgfs and 
identification files.

I don't suppose this would be causing the "duplicate peptide key" error 
I am seeing in my PeptideShaker CLI? Although I get the same error with 
the GUI versions too.

Kind Regards

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

"Are you saying that SearchGUI creates an "updated" .par file that it then uses when searching?" Yes. The OMSSA PTM indexes are added to the parameter file when the search is started. The same is true for Andromeda if I remember correctly (Marc will have more details on this). This was handled differently in previous versions, but we had to make some changes to the PTM handling when adding support for Andromeda. So this may explain why you haven't seen the OMSSA issue before.

For setups like yours I'd strongly recommend using the single zip option and incluce the FASTA and mgf files, as this ensures that issues like this one cannot happen. An alternative would be to make sure that the updated parameter file created when the search start is the one provided to PeptideShaker. But I think this would make the setup more complicated to maintain?

"I don't suppose this would be causing the "duplicate peptide key" error I am seeing in my PeptideShaker CLI?" No, this is a separate unrelated issue. We're still working on this one, but it only seems to occur either with large/many input files or on special setups, so it's a bit difficult to track down.

Best regards,
Harald

**Comment by cdlawless** [comment]
Hi Harald

The advice for outputting everything to a zip file when running 
SearchGUI works. Though this has increased the amount of time that it 
takes to run a search, as they are run in serial rather than in parallel 
as separate jobs on the cluster. If that is the only way to get it to 
work, then I'm sure I'll manage.

However, I'm constantly stumbling into the duplicate peptide error with 
my datasets now and have no way of progressing them through this 
pipeline. Have you managed to find reasons why this is happening? I can 
provide our data to assist if that helps? I have been trying to get this 
working for months now.

Kind Regards

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

Good to hear that the zipping option works. I don't understand why this means that you cannot run the jobs in parallel though?

The duplicate peptide error, we are still working on this one, so it would be great if you could provide us with your data. Especially if you can reproduce this on a dataset that is not too big?

Best regards,
Harald
