### ISSUE TITLE
.compomics and .peptideshaker folder generation

### ISSUE THREAD

**Issue by jflucier** [compomics/peptide-shaker#93]
Hello again,

I have gotten further with running searchgui and peptideshaker in an HPC cluster. Now, I am facing a problem with peptideshaker.

I finally opted for the proposed solution by marc wich is to copy clean soft in temp folder on each comput node prior to execution. The problem comes from  peptideshaker that generate a .compomics and .peptideshaker folder in my $HOME folder. These foolder seems to contain sensitive information for each dataset analysed. I get errors when multiple compute node access these folders. The only run without error is the first one started since it is the one that generates tehse folders.

Is there a way to specifiy a path to generate these folders in peptideshaker options? 

For now I will try to reset $HOME to the temp folder at run time... but this is really bad as alot of things depend iont his variable.

thanks again for all your help,

JF

**Comment by mvaudel** [comment]
Hi JF,

Good to hear that you are going forward on this! You have the answer to
your question in your previous implementation ;) You can set all path
preferences using the PathSettingsCLI, or by using a temp folder. Then, all
the necessary information will be written in the given temp folder :) You
might also want to use the -data option which packs the fasta and mgf files
in the SearchGUI and PeptideShaker files. This way you don't have to
maintain links to these!

Hope that helps, please shout if I misunderstood your question or answered
it incorrectly.

Best regards,

Marc

2015-10-06 16:19 GMT+02:00 jflucier <notifications@github.com>:

**Comment by jflucier** [comment]
Hey Marc,

sorry, I forgot all about this PathSettingsCLI options

tks,

JF

**Comment by mvaudel** [comment]
Keep me posted if it solves the issue!

Marc

2015-10-06 17:07 GMT+02:00 jflucier <notifications@github.com>:

**Comment by jflucier** [comment]
Hello again Marc,

I ran PathSettingsCLI and the content of paths.txt now point to temp directory of compute node, here is content:
peptideshaker_matches_directory=/ltmp/jflucier/temp_ms/test
peptideshaker_user_preferences=/ltmp/jflucier/temp_ms/test
peptideshaker_exports=/ltmp/jflucier/temp_ms/test
unzip=/ltmp/jflucier/temp_ms/test
utilities_user_preferences=/ltmp/jflucier/temp_ms/test
ptm_configuration=/ltmp/jflucier/temp_ms/test
fasta_indexes=/ltmp/jflucier/temp_ms/test/fasta_indexes
gene_mapping=/ltmp/jflucier/temp_ms/test/gene_mapping
pride_annotation=/ltmp/jflucier/temp_ms/test/pride


Still, if I look in my $HOME directory, there is still a .peptideshaker directory created with a single file in it:

[jflucier@cp3620-mp2 ~]$ ls -a ~/.peptideshaker
.  ..  exportFactory.cus

My PathSettingsCLI command is:

java -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.PathSettingsCLI -temp_folder $TEMPDIR/ 

thank again

JF

**Comment by mvaudel** [comment]
Hi again,

Strange, the export seems to be correctly set to the temp folder. I will
clean this up.

If you want to put everything in a single folder, the simplest is to append
the -temp option to your PeptideShaker command line, then you don't have to
run PathSettingsCLI :) If some objects still get instantiated in the home
folder, they can be ignored, but it is great if you can tell me which one
so that I clean the code.

Best regards and many thanks for this thorough testing,

Marc

2015-10-06 17:31 GMT+02:00 jflucier <notifications@github.com>:

**Comment by jflucier** [comment]
I tried your suggestion with -temp option and it doesn't seemed recongnised by peptideshaker. Here is the log:

<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -temp
        at org.apache.commons.cli.Parser.processOption(Parser.java:363)
        at org.apache.commons.cli.Parser.parse(Parser.java:199)
        at org.apache.commons.cli.Parser.parse(Parser.java:85)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1010)

**Comment by mvaudel** [comment]
Yes, the exact option is "-temp_folder", sorry about this, will blame the
jet lag on that one :) I see that our documentation is not necessarily
clear that this option is to be used in PeptideShaker command lines
directly. I will correct this.

2015-10-06 19:45 GMT+02:00 jflucier <notifications@github.com>:

**Comment by hbarsnes** [comment]
Hi JF,

PeptideShaker v1.1.0 has just been released which should fix this issue. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by jflucier** [comment]
Hello Harald,

there is a problem with this new release of peptideshaker. When I execute I
ge tthis error:

[jflucier@ip32 guot]$ java -Xmx30G -cp
/home/xroucou_group/apps/softwares/PeptideShaker-1.0.10-beta/PeptideShaker-1.0.10-beta.jar
eu.isas.peptideshaker.cmd.PeptideShakerCLI
Error: Could not find or load main class
eu.isas.peptideshaker.cmd.PeptideShakerCLI


thanks,

JF

IMPORTANT: Veuillez penser à l'environnement avant d'imprimer ce courriel

Jean-Francois Lucier
Bioinformatic Research Agent
Département de Biologie / Dept of Biology
Centre de calcul scientifique / Center for Scientific Computing
Université de Sherbrooke
2500, boulevard de l'Université
Sherbrooke (Québec) J1K 2R1
CANADA

**Comment by jflucier** [comment]
Hello again,

forget previous message. I just saw there is problem with my peptideshaker
path.

sorry for spam.

JF

IMPORTANT: Veuillez penser à l'environnement avant d'imprimer ce courriel

Jean-Francois Lucier
Bioinformatic Research Agent
Département de Biologie / Dept of Biology
Centre de calcul scientifique / Center for Scientific Computing
Université de Sherbrooke
2500, boulevard de l'Université
Sherbrooke (Québec) J1K 2R1
CANADA
