### ISSUE TITLE
Error when opening exported peptide shaker data

### ISSUE THREAD

**Issue by lparsons42** [compomics/peptide-shaker#96]
Hello

I used Export -> Peptide Shaker Project As -> Zip file in Peptide Shaker 1.1.1 to export my project.  I 
then sent the zip file to my colleague who tried to open it and he ended up with the error:

"It looks like another instance of Peptide Shaker is still connected to the file. Please close all instances of Peptide Shaker and try again." 

We can't seem to get past this.  He initially tried opening it in 1.1.2, then found a copy of 1.1.1 and the same error happened in both versions.  Is there something I need to do on my end before sending the file?  

thank you
Lee

**Comment by mvaudel** [comment]
Hi Lee,

Nothing looks wrong to me in what you describe. Something which can create such issues is having multiple PeptideShaker instances running when saving - then the database we use in the back-end is locked and there is not much we can do about it. If this was the case re-exporting as zip should do the trick. Would it be possible for you to make the file available to me so that I can give it a go?

Best regards,

Marc

**Comment by lparsons42** [comment]
Marc

Thank you for the reply.  Let me check with my collaborator, as it is his data and I don't want to be sending it out without his consent.  

It is worth mentioning that the system we are exporting from is running only one instance of PeptideShaker, and the one we are trying to open it on is two time zones away and trying to open it in the only running instance of PeptideShaker.  I have also tried doing this all in our lab, copying the exported file from one system in our lab to another and I get the same error.

Is there a different method I should use if I start a PeptideShaker project on one PC and want to open it on another?  This particular project took ~36 hours to open the SearchGUI results (on a system with 12 cores and 60GB of ram) so I'm a bit scared to close PeptideShaker on it until I know I have a project that can be opened on another system.

**Comment by mvaudel** [comment]
Hi Lee,

I understand, please feel free to mention that the data will be kept
confidential on our side and permanently deleted after testing.

The zip export was designed to be sent from one lab to the other so you did
the right thing as far as I can tell. Can you try to copy only the cpsx
file generated upon saving, and open it on another computer? It will then
ask you to locate the fasta file and the folder containing the mgf files
manually. If this works you have a clean project file which you can keep as
safety back-up :)

It sounds like a very big project, was there anything peculiar making it so
slow to import?

Best regards,

Marc

2015-10-22 16:35 GMT+02:00 lparsons42 <notifications@github.com>:

**Comment by lparsons42** [comment]
Marc

I have tried opening up the cpsx file on another computer, and the same error comes from that (after I point peptideshaker to the fasta and mgf files manually).  

As for what is slowing down opening the files, I suspect it might relate to the variable mods that I included in the searchGUI setup.  We only have 5 mgf files in this set (converted from thermo orbitrap raw) but when peptideshaker reaches the point of "Scoring PTMs in PSMs (D-score and PhosphoRS)" it sits for many hours before it finishes opening.  For what it's worth, this step seems to be running as only a single thread in java, I don't know if there is a good way to split that into multiple threads or not...

Once I hear from my collaborator I will send the zip and/or cpsx file from peptide shaker.  

thank you
Lee

**Comment by lparsons42** [comment]
Marc

I just posted the files for you via google drive.  If there is a different way you would prefer I send you the files - the zip is 406mb and the cpsx file alone is 101mb -  let me know.

thank you
Lee

**Comment by mvaudel** [comment]
Hi again,

Many thanks for this, the files arrived safely in Norway. The scoring of
PTM localization is already multi threaded so it seems that one thread is
hanging. There is nothing obvious to me on why we cannot open these files.
I will look into it and keep you posted.

Best regards and apologizes for the inconvenience,

Marc

2015-10-22 17:16 GMT+02:00 lparsons42 <notifications@github.com>:

**Comment by lparsons42** [comment]
As a follow-up, I have another example of the same behavior that came from another search I ran (I had started the two searches on two similar systems around the same time, the second finished some time later as it was more spectra against a larger db).  I unfortunately accidentally quit the instance of peptide shaker that had the results open, and now I cannot reopen that project as it gives me that error when trying to open it on the same system - even with both peptideshaker and searchgui closed.  

If there is any additional information I can provide you, or anything you would like me to try, please let me know.  This second search was read in to peptide shaker 1.1.2 in windows (windows server 2008r2 64bit, if it makes a difference).

thank you
Lee

**Comment by mvaudel** [comment]
Hi Lee,

Many thanks for this additional information. From what I can see in your
files, it seems that the tool stopped writing the file before the end of
the saving, and I don't have much clue on why. Do I remember correctly that
you are running PeptideShaker from SearchGUI?

Could you open SearchGUI, go to the "Help" -> "Bug Report" menu, and send
me the log of the tool? Also, which search engines did you use for the
first dataset? Hopefully with this information I will be able to reproduce
the error on our side.

Thank you and all apologizes again for this problem,

Best regards,

Marc

2015-10-26 2:43 GMT+01:00 lparsons42 <notifications@github.com>:

**Comment by lparsons42** [comment]
Marc

I did bring up peptide shaker by way of searchgui, however I don't have searchgui open at this point.  I tried to reopen it and it seems to have made a bug report that is not particularly interesting - it just says pathnames and executable locations.  I can send it if you would like to see it regardless.  

Is there any other way to get a bug report out?  One system I have not restarted searchgui yet, if that would help...

thank you
Lee

**Comment by mvaudel** [comment]
Hi Lee,

The command lines executed is exactly what I need to reproduce the
processing on my side :) So this report should contain all the information
I need. If you could also just tell me which search engines were run that
would be great.

Best regards,

Marc

2015-10-26 18:51 GMT+01:00 lparsons42 <notifications@github.com>:

**Comment by lparsons42** [comment]
Marc

The searches that created these problems used the same set of algorithms, basically every one that was listed *except* for OMSSA, Tide, and Andromeda.  If it makes a difference, the spectra were converted beforehand to mgf using the msconvert tool from TPP.  

thank you!
Lee

**Comment by mvaudel** [comment]
Hi Lee,

Great to know. Can you send me the log of SearchGUI as well?

Thank you,

Marc

2015-10-27 15:30 GMT+01:00 lparsons42 <notifications@github.com>:

**Comment by lparsons42** [comment]
Marc

I just sent the log as an attachment on an email, directly to you.  Please let me know if there is anything else I can get you.

thank you
Lee

**Comment by mvaudel** [comment]
Hi again,

Great, looking at it right now, thanks!

Marc

2015-10-27 16:01 GMT+01:00 lparsons42 <notifications@github.com>:

**Comment by mvaudel** [comment]
Dear Lee,

As far as I remember from this exchange, you were able to run the tools on one system but not another. Is there any update or something I am missing? Shall I close the issue?

Best regards,

Marc

**Comment by mvaudel** [comment]
Dear Lee,

Hopefully the error is not occurring with the new versions of the tools. If you still have problems please tell us and we will reopen the issue.

Best regards,

Marc
