### ISSUE TITLE
Examine the output of Percolator

### ISSUE THREAD

**Issue by wyu** [compomics/peptide-shaker#97]
Hi, Team

I have a particular need that may not have been directly addressed in the current version of PeptideShaker, but well within some minor tweak I think. 

What we'd like to do is to inspect the output of the Percolator, together with the source mzML and FASTA file. It's quite similar to what can already been done for a number of input format such as mzid, etc. Perhaps, I need to add the Percolator as another import format?

Thanks!
Wen

The format of the tabular output from Percolator:

PSMId   score   q-value posterior_error_prob    peptide proteinIds
x-20130510_EXQ1_IgPa_QC_UPS1_01-4681-GAAGGHTATHHASAAPARPQPVE    0.504611        0       6.71046e-06     K.GAAGGHTATHHASAAPARPQPVE.-     253773892
x-20130510_EXQ1_IgPa_QC_UPS1_01-4670-GAAGGHTATHHASAAPARPQPVE    0.480098        0       1.09985e-05     K.GAAGGHTATHHASAAPARPQPVE.-     253773892
x-20130510_EXQ1_IgPa_QC_UPS1_01-51671-DEGPILFIHTGGAPALFAYHPHV   0.474161        0       1.23967e-05     K.DEGPILFIHTGGAPALFAYHPHV.-     253773128

**Comment by mvaudel** [comment]
Dear Wen,

Thank you for your message. Indeed it seems that you would need the support of another input format. Is it not possible to export results in a standard format like mzIdentML?

If there is no alternative we could think about implementing a parser for this format. The typical issues then are the support of posttranslational modifications. Do you know how they are annotated in this export?

Best regards,

Marc

**Comment by hbarsnes** [comment]
How do you generate the Percolator output? Would it be an option to use Crux (https://noble.gs.washington.edu/proj/crux/percolator.html)?

The reason I'm asking is that it supports an output format (percolator.psms.txt: a tab-delimited file containing the PSMs) that is very similar to the output format we already support for Tide. Which should make it much easier to get the Percolator output into PeptideShaker. (I have not done any tests though.)

Note also that we currently only support mgf as the spectrum file format. So in any case you'd have to convert your mzML into mgf for your data to be compatible with our pipeline.

Best regards,
Harald

**Comment by wyu** [comment]
Great idea! I'm using the percolator outside of crux pipeline. Though it would doable to format my results in crux format. 

Eventually I would like to use the peptideshaker as the GUI to inspect the results from our own pipeline. therefore, I'm hoping for a way where I can create a project file in my java app and let my users to load the project directly. Maybe you can give me some suggestion on where I should start working on your codebase.

Thanks
Wen

**Comment by hbarsnes** [comment]
Hi Wen,

I'm not completely sure what you mean by "inspect the results from our own pipeline"? Keep in mind that PeptideShaker reprocesses it's input (recalculates the PTM scoring and location, redoes the peptide to protein mappings, etc.), so it would not directly show the output of your pipeline.

So it depends on what you want to achieve. If reprocessing is ok, then PeptideShaker can be an option, but if you want a viewer that simply shows the results of your pipeline, then PeptideShaker is probably not the right way to go.

And on a final note, if you have control over the output format from Percolator I'd definitely recommend going for mzIdentML. The Crux format was just a suggestion if you were stuck with the output format above.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
