### ISSUE TITLE
How can we compare different PeptideShaker projects?

### ISSUE THREAD

**Issue by lparsons42** [compomics/peptide-shaker#98]
This is something I often do by writing perl scripts to parse the output of the search engines I use, but it would be great to be able to do this in peptideshaker.  For example, if files A and B are replicates, I might be interested in knowing which peptides (or proteins) are shared between them.  Conversely, if A and B are different, I am interested in knowing which peptides (or proteins) are unique to each of them.  When my set of files gets larger, I then might want to know what was common between A1, A2, A3, but not found in the combined (or shared) set of B1, B2, B3.  

Is there a way to do this?  I know I can use the spectrum IDs tab to see only peptides from specific files, but I can't find a way to trim the list to show me only ones that are either shared or unique relative to other files.  

thank you
Lee

**Comment by hbarsnes** [comment]
As this is not really an issue, but rather a request for an already planned tool for comparing PeptideShaker projects, we decided to close the issue in order to make it easier to keep track of the other "real" issues.
